### ISSUE TITLE
What do we do if NPM disappears overnight?

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1008]
With all the internal wrangling going on at npm, I wanted to talk about fallbacks should everything there go south.

1. We don't worry about it, and let the community sort something out; which given the importance of the package registry to the web, it'll probably do in a matter of days.
1. We set up something like [verdaccio](http://verdaccio.org), point our registry url configs towards that, and use it as a package cache
1. If and when it happens, we tweak our deployment process: instead of building the base image from a fresh slate, we pull the existing one, copy over the new code, rebuild the libraries and push it back up. The app images carry on as normal. (kudos to @adammcmaster for this one)

**Comment by srallen** [comment]
Microsoft bought it. Hooray.
