### ISSUE TITLE
Docker setup for local development

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1012]
@camallen did a first pass at this in #445, but we need to take another stab. I know @eatyourgreens has some requests...

- ability to run workspace commands like `dev`, `test` etc
- automatic rebuilding of libraries in the background

**Comment by eatyourgreens** [comment]
For PFE, we just pass commands to Docker so `docker-compose run dev npm test` etc. https://github.com/zooniverse/Panoptes-Front-End/blob/master/README.md#with-docker

**Comment by rogerhutchings** [comment]
This is going to be a bit more involved, since we have libraries to compile as well, but we can probably keep the interface the same

**Comment by camallen** [comment]
Library builds should just be a required setup task that you need to run before having a working docker setup. Similar to the API to install libs / setup the database, etc. https://github.com/zooniverse/Panoptes#usage

We can look at using build / cache volumes is a way to have stored state outside of the underlying docker image. 

E.g. in panoptes API we store the installed libs in a separate volume via https://github.com/zooniverse/Panoptes/blob/5da1aba86c9f49774631f7aa66188fb06ae74509/docker-compose.yml#L41

And then tell the package manager to look in the correct location, https://github.com/zooniverse/Panoptes/blob/5da1aba86c9f49774631f7aa66188fb06ae74509/docker-compose.yml#L49

**Comment by rogerhutchings** [comment]
Fixed by #1026
