### ISSUE TITLE
Test enhancements for subject queue

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1036]
**Package** lib-classifier

**Feature or Issue Description**

- [ ] Split the async request for the queue and the appending of the queue in the store into two separate actions
- [ ] Error if the API returns a successful 200 request with an empty array for the queue

**Comment by eatyourgreens** [comment]
The subjects store will call `/subjects/queued` each time the queue advances, once the queue is less than 3 subjects. `populateQueue` should check the loading state to see if there's already a request in progress. Right now, the code assumes that the time to load new subjects is less than the time to classify a subject. On a fast workflow (eg. Yes/No questions), new subjects could be requested more than once, leading to duplication in the incoming queue.
