### ISSUE TITLE
Drawing tasks - potential design issues

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#1052]
Drawing tools preview on staging: https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify?env=staging

This issue is a placeholder for formal documentation and discussion, please edit this initial comment however see fit.

**Package**
lib-classifier

**Feature or Issue Description**
drawing tasks, including task inputs, markings, anything related

**Potential Issues**
- drawing tool input icon background has poor contrast in light theme, see [these related comments](https://github.com/zooniverse/front-end-monorepo/pull/913#pullrequestreview-265687164)
- review each tool stroke width, design
- review marking's delete button
- color options

**Comment by beckyrother** [comment]
[Here's what](https://projects.invisionapp.com/d/main#/console/12923997/376615153/build) I was thinking for the button background. Click the first "Line" button to see what it would look like selected. 

All of the colors in the [DSM](https://projects.invisionapp.com/dsm/zooniverse/primary-brand/folder/colors/5c68fab7fb26bb001855f29) aside from the royal blue have accessibility ratings of AA or higher, so we can leave that one out if it's not needed. 

Thoughts?

**Comment by srallen** [comment]
The cursor icons currently used by PFE:
`crosshair` cursor when a drawing tool is selected and hovering over the interactive layer
`pointer` cursor on hover of the delete button
`grab` cursor on hover of the mark
`move` cursor on hover of the drag handle
`grabbing` cursor while dragging the mark
`not-allowed` cursor for the whole area if the max number of marks is already drawn.

**Comment by eatyourgreens** [comment]
Tool choices are disabled when you hit the maximum number of marks for a given tool, but there's no visible styling for disabled tools in the task area. Try it here on master: http://localhost:8080/?project=908&workflow=3370. The subject shows the `not-allowed` cursor so this might not be a big deal.

**Comment by eatyourgreens** [comment]
There should be an animation of some sort when a mark is deleted.

**Comment by beckyrother** [comment]
Yes. Using Penguin Watch as an example, the mark should quickly fade down and shrink in size as shown there, but not move down to the right.

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/front-end-monorepo/issues/1400

**Comment by mcbouslog** [comment]
> The cursor icons currently used by PFE:
> `crosshair` cursor when a drawing tool is selected and hovering over the interactive layer
> `pointer` cursor on hover of the delete button
> `grab` cursor on hover of the mark
> `move` cursor on hover of the drag handle
> `grabbing` cursor while dragging the mark
> `not-allowed` cursor for the whole area if the max number of marks is already drawn.

The cursors all look good to me after a quick test on http://localhost:8080/?project=908&workflow=3370. Just confirming I'm not missing anything?

**Comment by beckyrother** [comment]
current Penguin Watch action: 
![penguin watch](https://user-images.githubusercontent.com/1392130/73023532-558df200-3df1-11ea-889b-83535f06fcfe.gif)

**Comment by srallen** [comment]
@seanmiller26 there may be some actionable items from this discussion. I know @ErikOstlund is working on some enhancements for the freehand drawing tools, however, there may be some general improvements that can be made eventually.
