### ISSUE TITLE
Is a per-project notifications link useful?

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1063]
## Context

I'm currently mapping out the scope of work for completing the project app, which should handle `/project/:owner:/:name` and all child routes.

## Question

Is there really a need for a per-projects notifications page in addition to the standard notifications page?

1. The notifications link appears as part of of the site-wide navigation in the top header bar, not the project header. 
1. On PFE, the notifications link takes you to `/project/:owner:/:name/notifications` when you're in a project, and `/notifications` everywhere else. These pages _appear_ to be identical, just that the former also shows the project bar, and automatically opens the panel for that project.

## Proposed solutions

- If we don't need that page, it's a straightforward redirect to `/notifications`; we could add in a small feature to redirect with a query param of `slug`, and have that one auto-open.
- If we do need the page, I'll add it to the long list of things that need building.

## Gut feeling

Let's drop it and redirect.

**Comment by eatyourgreens** [comment]
Project moderators are probably the best people to ask. I would guess they want a link that shows them new messages for the project.

**Comment by goplayoutside3** [comment]
This will be relevant when the Notifications page is designed and ready to be built in FEM. I agree we should redirect to `https://www.zooniverse.org/notifications`.
