### ISSUE TITLE
Footer admin button label is black in dark theme

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#107]
**Package**

` lib-react-components`, `lib-grommet-theme`

**Feature or Issue Description**

<img width="272" alt="screenshot 2018-08-07 13 36 59" src="https://user-images.githubusercontent.com/2725841/43776198-fcb7b494-9a46-11e8-806b-c454d8d22253.png">

Following on from #104

**Comment by srallen** [comment]
I think I left a comment inline, but this is a Grommet bug: https://github.com/grommet/grommet/issues/2140

Hopefully fixed in the next beta release since they're going to be improving the theming support for light/dark variants.

**Comment by srallen** [comment]
I think this is fixed in the latest grommet. The story for the checkbox itself doesn't appear correctly and I'm not sure why that is, but in context of the footer when the background is set, it has the correct font color.
