### ISSUE TITLE
Unnecessary requests happening in the project app 🤦‍♂️

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1072]
While working on #1071, I found the cause of the annoying flickering in the browser chrome (project header etc). It looks like we're requesting the project from Panoptes on the server, rendering the html, then when `_app.js` loads on the client it requests it _again_, causing flickering and such. I tested this by navigating around within a project, and watching the number of project requests go up each time; it shouldn't need to request anything other than the bundle for the next page.

**Comment by eatyourgreens** [comment]
I think this has been fixed since Next 9.3.
