### ISSUE TITLE
In Windows Edge 18, subject images do not fill the entire subject viewer space.

### ISSUE THREAD

**Issue by simensta** [zooniverse/front-end-monorepo#1094]
**Package**: lib-classifier

**Feature or Issue Description**
In Windows Edge 18, subject images do not fill the entire subject viewer space.
![bs_win10_Edge_18 0-1](https://user-images.githubusercontent.com/7684729/63470365-19b1c380-c432-11e9-80c9-c384e83614ec.jpg)

**To Dos**

**Comment by srallen** [comment]
I think we may see the same issue with other image subject viewers if we continue to use svg `image` for them. This issue is visible in other browsers. It's just more pronounced in Edge.

**Comment by eatyourgreens** [comment]
Does PFE do this with SVG images too?

**Comment by srallen** [comment]
PFE uses an SVG image _and_ an HTML image with each responsible for different parts of the display functionality. If I had to guess why, it's likely because of the poor support for SVG that React had at the beginning. 

Another factor in play here is that the layout is using CSS grid, so I'm guessing the issue here is likely with CSS grid configuration rather than the SVG necessarily. But I could be wrong about that. PFE is only using flex.

**Comment by eatyourgreens** [comment]
>PFE uses an SVG image and an HTML image with each responsible for different parts of the display functionality. If I had to guess why, it's likely because of the poor support for SVG that React had at the beginning.

SVG images don't fire a `load` event, so the HTML image tells us when the subject has fully loaded and is ready to classify. Other than that, the HTML image is used if there's no drawing task and no zooming. SVG has been in PFE since well before React supported SVG, in order to handle drawing tasks.

**Comment by srallen** [comment]
@eatyourgreens is this ok to be on deck for you to take a look at next? Thanks!

**Comment by eatyourgreens** [comment]
Sure.

**Comment by eatyourgreens** [comment]
I'm not able to reproduce this. Here's Galaxy Zoo in Edge 18.
![Screenshot of Galaxy Zoo in Edge 18, showing the subject image at the correct size.](https://user-images.githubusercontent.com/59547/66840498-10d7fc80-ef60-11e9-8d15-62cf4c475347.png)

**Comment by srallen** [comment]
It's visible there. The image should take the full area and be right up against the image pan/zoom toolbar on the right. How this issue appears varies on the aspect ratio of the subject image I think.

**Comment by eatyourgreens** [comment]
That's not possible without cropping the Galaxy Zoo image, which is square.

**Comment by eatyourgreens** [comment]
http://localhost.zooniverse.org:3000/projects/asimenstad/andrea-practice/classify?env=production dies with an error, so I can't check the project from the original screenshot.

**Comment by eatyourgreens** [comment]
That Galaxy Zoo image is as large as it can get without cropping the top and bottom off.

**Comment by eatyourgreens** [comment]
This is more promising. Maybe it's triggered by file type?
https://frontend.preview.zooniverse.org/projects/stephenserjeant/what-is-beauty/classify?env=staging
![Screenshot of What is Beauty? on staging in Edge 18, showing the subject image way too small.](https://user-images.githubusercontent.com/59547/66842279-dfacfb80-ef62-11e9-8b62-faf7aba5b5e0.png)

**Comment by eatyourgreens** [comment]
Oh, I'm an idiot. You can see in that screenshot, and the original, that the subject hasn't finished loading. The task buttons are all disabled. The subject doesn't resize, and the task isn't enabled, until the load event fires. That's most likely where the problem is.

**Comment by eatyourgreens** [comment]
I can reproduce this consistently with What Is Beauty? on staging. The subject never finishes loading in Edge.

**Comment by eatyourgreens** [comment]
>SVG images don't fire a load event

That's the problem. The code attaches `onLoad` to an SVG element.

**Comment by eatyourgreens** [comment]
I'm going to take `good first issue` off this because it's not a bug for a beginner to tackle.

I don't have Edge for testing locally, so this might have to wait until I've got that set up. One solution would be to set up a HTML `img` element as a preloader and call `props.onLoad` when that loads.

**Comment by eatyourgreens** [comment]
Safari doesn't fire the `load` event for SVG images either.

**Comment by srallen** [comment]
@simensta noted in the related PR that there are still some variability in what is loaded and shown in certain browsers: https://github.com/zooniverse/front-end-monorepo/pull/1236#issuecomment-544698552

**Comment by srallen** [comment]
There are still some rendering issues, but I'll open separate issues for them.
