### ISSUE TITLE
Drawing task - save markings to annotation

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#1103]
**Package**
lib-classifier

**Feature or Issue Description**
On workflow step advance (Next) or Done (or Done & Talk) save markings from drawing/interaction state to annotation

see [ADR 15](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-15.md)

**To Dos**
...placeholder for project management, details TBD...

**Comment by simensta** [comment]
Using the [createViewModel()](https://github.com/mobxjs/mobx-utils#createviewmodel) functionality might be useful for this feature.

**Comment by eatyourgreens** [comment]
Closed by #1339.
