### ISSUE TITLE
Possible additional bugs with feedback on TESS

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1112]
**Package** lib-classifier

**Feature or Issue Description**
 One user reported recently getting a sim but not getting the feedback message: https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk/2110/1111008

We also still have an issue where `isActive` in the feedback state is remaining or initializing as true for real subjects:

![Screen Shot 2019-09-09 at 9 26 25 AM](https://user-images.githubusercontent.com/5016731/64539386-02a11b80-d2e4-11e9-8615-91dcd05e4309.png)

When the feedback state is in this incorrect state, we still get inaccurate metadata sent with the classification:

![Screen Shot 2019-09-09 at 9 28 55 AM](https://user-images.githubusercontent.com/5016731/64539558-501d8880-d2e4-11e9-983e-3b1c1e0b2bfa.png)

Which will cause unnecessary caesar extractions.

It is unclear if these are related.

**Comment by srallen** [comment]
I saw `[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[FeedbackStore Subject Observer autorun]' TypeError: Cannot read property 'toString' of null` on the branch with the mobx upgrade, which prevented the feedback from displaying and did not add the classification metadata correctly. I'm not sure if this is happenig on master yet, but this might be the bug we're looking for.

**Comment by eatyourgreens** [comment]
That might be thrown by `generateRules` if feedback is active for a subject that doesn't have feedback.

**Comment by srallen** [comment]
Yes, I'm going to spend a bit of time testing this on master to confirm the issues are there and not on the mobx upgrade branch (which I happen to be testing for final review).

**Comment by srallen** [comment]
There is a subject metadata value that is sometimes `null` and the `metadata-to-rules` calls `toString` on the metadata values. `null.toString()` will throw too, so that needs to be checked for too.

**Comment by srallen** [comment]
I've confirmed that's where the above MST error is coming from, but I'm going to write checks for both.
