### ISSUE TITLE
ZooFooter import is broken

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#112]
**Package** 

`lib-react-components`

**Feature or Issue Description**

I've just tried to fire up `app-project` and ZooFooter is breaking the build. 

```
Error in ./ZooFooter
Module not found: Error: Can't resolve './locales/en' in '/Users/rogerhutchings/Code/zooniverse/front-end-monorepo/packages/lib-react-components/lib/components/layout/ZooFooter'
```

The file appears to be there, and I've tried rebuilding the library. Just off the top of my head, but I think Next.js doesn't compile anything imported from the `node_modules` folder, so if it's not included in the `react-components` library build, then it's trying to import a JSON file and can't.

**Comment by srallen** [comment]
This was fixed in #106
