### ISSUE TITLE
Prompt the user to log in / sign up after N classifications

### ISSUE THREAD

**Issue by camallen** [zooniverse/front-end-monorepo#1129]
A non-logged in user visits the site, chooses a project say Planet Hunters - Tess and and starts classifying. After say N classifications, the system should prompt the user to log in or signup. 

The user's decision from the prompt should be recorded in a client side session store (cookie?) so we respect their wishes for the session. This should not impact other users on a shared computer. 

If the user then signs up / logs in they will receive a more tailored rate of training data long term and this recording of the user will help us determine their task skill (for training data projects, PH Tess, SpaceWarps, Gravity Spy, etc).

Linked to https://github.com/zooniverse/designator/pull/88

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/Panoptes-Front-End/issues/2049 describes why we removed this feature.

**Comment by rogerhutchings** [comment]
But it doesn't say whether we got a definitive answer on whether people do actually drop out or not. Did Alex not do the analysis, or did he do the analysis and we just didn't add it to the issue?

**Comment by srallen** [comment]
For Gravity Spy, we did this:

<img width="1431" alt="Screen Shot 2019-09-17 at 10 18 12 AM" src="https://user-images.githubusercontent.com/5016731/65055310-8e462800-d934-11e9-9748-e5efd9233a2e.png">

Inspired by how PH2 did it.

Note the GS specific message here, so this would need some work to make generalizable (something we can roll into the work to make workflow levels generalized). We could ask the GS team if they have any data. 

Related: https://github.com/zooniverse/Panoptes-Front-End/pull/2519

**Comment by srallen** [comment]
@trouille do you recall if Gravity Spy did any research into user behavior with the banner encouraging sign in?

**Comment by trouille** [comment]
I don't remember, but have emailed the team to ask.

**Comment by trouille** [comment]
Anecdotal response from team (not based on set experiment or data gathered) is that as users they found it helpful/good idea to make clear why users should sign in on this type of project (as opposed to others where signing in doesn't open up new opportunities).

**Comment by eatyourgreens** [comment]
The new classify page has this component at the moment, if you aren't signed in. The banner is much nicer and less invasive.
![Screenshot showing the Your Stats box blocked by a 'You need to sign in' message.](https://user-images.githubusercontent.com/59547/65163535-fd09ab00-da32-11e9-9a8b-4ce7086212d7.png)

**Comment by srallen** [comment]
Linked to zooniverse/panoptes#3589
