### ISSUE TITLE
Add project about pages - team

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1135]
`/projects/:owner:/:project/about/team`

<img width="1459" alt="Screenshot 2019-09-19 13 10 06" src="https://user-images.githubusercontent.com/2725841/65242916-241db680-dadf-11e9-9b16-1c28a11a6a60.png">

See #50 for more information

**Comment by beckyrother** [comment]
![screenshot](https://user-images.githubusercontent.com/1392130/72172430-bef61580-339a-11ea-8477-f3491c68eabf.png)

InVision link: https://projects.invisionapp.com/d/main#/console/12924056/399772763/preview

Similar to #1136 but adds a third column on the right for the team list. 

Additionally, modifies individual badges: 
![user badge](https://user-images.githubusercontent.com/1392130/72172772-a63a2f80-339b-11ea-8a3a-61687e461110.png)
- link on the username, not the full name
- modified typography
- role badges have colors to more clearly differentiate them. this is a global change and could be its own issue

**Comment by goplayoutside3** [comment]
Closed by PR's #2041, #2056, #2116.
