### ISSUE TITLE
Add project about pages - education

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1136]
`/projects/:owner:/:project/about/education`

<img width="1459" alt="Screenshot 2019-09-19 13 10 16" src="https://user-images.githubusercontent.com/2725841/65243058-7a8af500-dadf-11e9-9edf-8dbab295c141.png">

See #50 for more information

**Comment by beckyrother** [comment]
![screenshot](https://user-images.githubusercontent.com/1392130/72172269-5eff6f00-339a-11ea-8925-68996d9bc42b.png)

InVision link: https://projects.invisionapp.com/d/main#/console/12924056/399772762/preview

Includes new text styles for markdown H1-6, uses image alt text for a caption.

**Comment by beckyrother** [comment]
Organization about pages: https://projects.invisionapp.com/d/main#/console/12924056/400270764/preview

**Comment by eatyourgreens** [comment]
Looks good but alt text should not be used as an image caption unless
- it actually describes the content of the image.
- the alt text of the image itself is empty.

Otherwise, the alt text will be repeated twice on the page: once to describe the image and once for the caption.

**Comment by beckyrother** [comment]
@eatyourgreens  Is there another way to add captions without adding a lot of extra effort? Otherwise I'll remove this element.

**Comment by srallen** [comment]
I recommend we add separate custom markdown syntax to use to render a caption element. We already have precedent for custom markdown (it's used on talk to link to subjects for instance and custom syntax for adding attributes to links to open in a new tab). I think people will quickly pick up anything new we add.

**Comment by eatyourgreens** [comment]
Sounds good to me. Are you thinking of using [the figure element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure)?

**Comment by eatyourgreens** [comment]
For whoever picks up this issue, the content for these pages should be retrieved from the `translations` endpoint.

**Comment by beckyrother** [comment]
Great! We can do a blog/Talk post about these changes when they're implemented and be sure to point that new function out for current project owners

**Comment by srallen** [comment]
> Sounds good to me. Are you thinking of using the figure element?

Yep, we can change the rendered output from the image syntax to wrap the image in figure and add some custom syntax for the caption.

**Comment by goplayoutside3** [comment]
Closed by PR's #2041, #2056, #2116.
