### ISSUE TITLE
Add project about pages - FAQ

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1137]
`/projects/:owner:/:project/about/faq`

<img width="1459" alt="Screenshot 2019-09-19 13 10 22" src="https://user-images.githubusercontent.com/2725841/65243143-ab6b2a00-dadf-11e9-833c-91e4759f4fb0.png">

See #50 for more information

**Comment by beckyrother** [comment]
See #1136

**Comment by goplayoutside3** [comment]
Closed by PR's #2041, #2056, #2116.
