### ISSUE TITLE
Add project about pages - results

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1138]
`/projects/:owner:/:project/about/results`

<img width="1459" alt="Screenshot 2019-09-19 13 10 14" src="https://user-images.githubusercontent.com/2725841/65243210-d05f9d00-dadf-11e9-8ab6-160e856cc7d3.png">

See #50 for more information

**Comment by beckyrother** [comment]
@rogerhutchings what's the timeline for these pages?

**Comment by beckyrother** [comment]
See #1136

**Comment by goplayoutside3** [comment]
Closed by PR's #2041, #2056, #2116.
