### ISSUE TITLE
Pages Filmstrip viewer aka multi-image subject viewer

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1142]
**Package** lib-classifier

**Feature or Issue Description**
Design:

Filmstrip viewer: https://projects.invisionapp.com/d/main/#/console/12923997/387261738/preview and collapsed: https://projects.invisionapp.com/d/main/#/console/12923997/387261737/preview.

I've also updated the invision links doc with this info: https://docs.google.com/document/d/131LXuIlBGMaaPW7bd7SvFRReeLsczXfMtCUNCnOucpI/edit

**Comment by srallen** [comment]
The upper area is basically the single image viewer, though, #1094 needs to be resolved for it. The enhancement here is the preview of the other frames and selecting which one to view.

**Comment by srallen** [comment]
@beckyrother I'm curious if you want this Pages subject viewer to have a collapsible option into the pagination bullets like the text editor app version?

**Comment by beckyrother** [comment]
Yes, that would be great. This is on my to-do list for this week, can I share an InVision design tomorrow?

**Comment by srallen** [comment]
Yes, thank you!

**Comment by beckyrother** [comment]
Filmstrip viewer: https://projects.invisionapp.com/d/main/#/console/12923997/387261738/preview and collapsed: https://projects.invisionapp.com/d/main/#/console/12923997/387261737/preview.

I've also updated the invision links doc with this info: https://docs.google.com/document/d/131LXuIlBGMaaPW7bd7SvFRReeLsczXfMtCUNCnOucpI/edit

**Comment by srallen** [comment]
@simensta do you have any updates on this?

**Comment by srallen** [comment]
Closing in favor of more specific issues for what is remaining.
