### ISSUE TITLE
Layout bugs on homepage on iPhone SE

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1148]
On the iPhone SE (320 x 568px), there are some elements on the homepage that break out of the layout:

<img width="355" alt="Screenshot 2019-09-20 10 56 58" src="https://user-images.githubusercontent.com/2725841/65318348-60abe980-db95-11e9-8e07-887dc1f42c6c.png">

- Recent subjects
- Project statistics
- Researcher message
- About project
- Connect with project

**Comment by beckyrother** [comment]
The Classify button gets squished on mobile 
![IMG_0079](https://user-images.githubusercontent.com/1392130/66766210-291e1d80-ee73-11e9-8651-3a12f6a9a5d8.PNG)

**Comment by rogerhutchings** [comment]
These have been largely fixed by using Fresnel for the layout (although there are some minor padding issues - nothing that leaves it unusable), and adding the new classify buttons in #1204
