### ISSUE TITLE
Add completeness bar to workflow selection buttons

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1151]
The design for the workflow select button in the Hero widget includes a completeness bar which needs to be added:

<img width="383" alt="Screenshot 2019-09-20 13 56 54" src="https://user-images.githubusercontent.com/2725841/65328568-85608b00-dbae-11e9-939e-30d8551667c3.png">

Related: #1077 

And https://zooniverse.slack.com/archives/C0Z7YNTSL/p1554151344033200

**Comment by beckyrother** [comment]
(Working on this now)

**Comment by beckyrother** [comment]
Think I was trying to be too clever the first time. How does this feel? 
![workflow-button-3 2](https://user-images.githubusercontent.com/1392130/66015798-9e641880-e499-11e9-9e8a-4f5085a2a0b9.gif)

For reference, here's the first one we were thinking about (pretend the button text is black like it should be):
![workflow-button 1](https://user-images.githubusercontent.com/1392130/66015819-b045bb80-e499-11e9-8eba-b86b2eed799c.gif)

**Comment by eatyourgreens** [comment]
Lose the blue tooltip, and I think this is much better (and something we can implement.)

**Comment by eatyourgreens** [comment]
#1204 adds a basic background gradient, which is muted somewhat on hover/focus. Each link is announced in VoiceOver as something like 'Link: Workflow name 60% complete'.

**Comment by beckyrother** [comment]
If we need to remove the blue tooltip, let's add a secondary line to the button to indicate the percent complete and give a reason that the button is a progress bar. Design tk.
