### ISSUE TITLE
3 TESS subjects with non-sense annotations

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1169]
**Package** lib-classifier

**Feature or Issue Description**
See https://zooniverse.slack.com/archives/CANKLB50E/p1569436429281900 for the list of classifications and types of issues. These annotations are causing downstream issues in Caesar and aggregation.

We're considering the logic in [the code here](https://github.com/zooniverse/front-end-monorepo/blob/698585ff974edbad9a4e0b59b713dbe7dc555088/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js#L202-L216)

For classifications that have `0` values for the center x point and the width, it's possible that `minX` and `maxX` are null because in javascript: `(null + null) / 2` and `null - null` evaluate to `0`.

To circumvent this, we have added a check for null in the filter in https://github.com/zooniverse/front-end-monorepo/pull/1168

Additionally, it never makes sense for width to ever be negative, so we've added a math function call to make the width its absolute value.

Follow up questions and to dos:
- Under what conditions can these [d3 transformations](https://github.com/zooniverse/front-end-monorepo/blob/af82b39d155a653f4c2f05437c1e72485c69fe27/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js#L298-L302) result in null values for `minX` and `maxX`?
- We should add a conditional check to make sure the `minX` and `maxX` are not out of the bounds of the actual original data's extent.
- Should we have a minimum width for the annotation? 
- We should investigate the timeline of the non-sense annotations and see if it correlates to when the project was finished with Sector 13. Is #932 having an impact here? Are users accidentally making annotations, cannot delete them because of the banner being in the way, and then submitting the classification to try to clear it away?

**Comment by srallen** [comment]
Example of an annotation that has a negative x center point when it doesn't make sense for the data:

<img width="921" alt="Screen Shot 2019-09-25 at 6 16 23 PM" src="https://user-images.githubusercontent.com/5016731/65646712-93a11380-dfc1-11e9-8746-1e366de1941a.png">

![Screen Shot 2019-09-25 at 6 16 31 PM](https://user-images.githubusercontent.com/5016731/65646718-9ac82180-dfc1-11e9-92fe-326375253303.png)

Resolving this will be more complicated since there's two parts to this:
- We should not let users draw a brush that does not make sense for the data
- We should not add annotations to the classification that does not make sense for the data

**Comment by srallen** [comment]
@shaunanoordin do you have any insight into this question from my first post (see link above for the code in question)?

> Under what conditions can these d3 transformations result in null values for minX and maxX?

**Comment by srallen** [comment]
> Should we have a minimum width for the annotation?

Having a minimum width is a bit more complicated since we're dealing with actual data. The width could be very small and still have it make sense for the data. Any minimum we set would be arbitrary, but the width should likely _never_ be zero from actual math calculation (where `minX` and `maxX` equal each other). It would be very hard for a user to create this from actual browser interactions too... should we put in the effort to make it impossible?

**Comment by eatyourgreens** [comment]
PFE deletes invalid marks as soon as they are created, by validating the annotation. The new classifier could do this by adding validation to the annotation models. I don't know if MobX State Tree has validation built in, but it wouldn't be difficult to add a derived view to each model that validates the current state.

**Comment by shaunanoordin** [comment]
> Under what conditions can these d3 transformations result in null values for minX and maxX?

That's a puzzler. Right, so there's always one _default D3 Brush_ (that listens for input) hanging around invisibly, but that has minX: undefined, maxX: undefined so it should be removed by that `.filter()` that checks for minX/maxX === undefined.

So as you pointed out Sarah, the problem is likely coming from [this...](https://github.com/zooniverse/front-end-monorepo/blob/af82b39d155a653f4c2f05437c1e72485c69fe27/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js#L298-L302)
```
// LightCurveViewer.js, onAnnotationBrushEnd()

const brushSelection = d3.event.selection // Returns [xMin, xMax] or null, where x is relative to the SVG (not the data)

...

let dataMinX = brushSelection && brushSelection[0]
let dataMaxX = brushSelection && brushSelection[1]
annotationBrush.minX = dataMinX && currentTransform.rescaleX(this.xScale).invert((dataMinX))
annotationBrush.maxX = dataMaxX && currentTransform.rescaleX(this.xScale).invert((dataMaxX))
``` 

The first thing I'd check here is, is `d3.event.selection` null? If so, how and why? If there's any way that `null` values are coming into the annotations, it's likely from here. The only way I imagine this could be null is if... some other d3 event overwrote the selection event, but I'm not sure how I'd replicate that. Yet. 🤔 

Also, if the `d3.event.selection` IS coming out `null` for whatever reason, I'd modify this line...

```
// If the user attempted to make a selection, BUT the current task isn't
// a valid task, cancel that brush.
if (!this.isCurrentTaskValidForAnnotation()) {
  ...
}
```

...to...

```
if (!this.isCurrentTaskValidForAnnotation() || !brushSelection) {
  ...
}
```

**Comment by shaunanoordin** [comment]
> PFE deletes invalid marks as soon as they are created, by validating the annotation. 

If we implement this, we also need to delete marks that are originally valid, but modified to be invalid (e.g. dragged to the far left of the chart where the minX, maxX now becomes negative)

Query: are we actually getting _negative widths,_ or are we just guarding against the possibility? (I'm all in favour for extra guards, but if we're actually getting negative widths there's an experiment I want to perform.)

**Comment by srallen** [comment]
> are we actually getting negative widths, or are we just guarding against the possibility? (I'm all in favour for extra guards, but if we're actually getting negative widths there's an experiment I want to perform.)

We were getting negative widths in some cases (see: https://zooniverse.slack.com/archives/CANKLB50E/p1569435542277800), if someone drew a narrow annotation on the far left side beyond zero (basically where the left axis is). Since the calculation is a difference between max X and min X, it was possible. Taking the absolute value ensures that the width is always positive, which is what's happening now. To replicate, you'll have to check out the commit before #1168. A case of negative x center and width was the only case I was able to reliable replicate manually. I still don't know how users were able to submit nulls or zeros other than deducing that somehow the d3 transformations were null. 

As I said in a previous comment, whether or not a negative center x is invalid depends on the original data, unlike drawings on images where negative values will always be invalid. This is why I'm hesitant to add a validation to a MST store. We could do this, but then we'll also have to know what the data extent is. I'm more in favor of adding validation in the LCV code where all the d3 code exists for it now (it already knows the data extent) and add store validations for the general scatter plot I'm building in #1074 if and when it has a data annotation layer built for it (the variable star LCV does not have this requirement).

I'm also unsure about a minimum width other than just greater than zero, but also as I pointed out, making this impossible might not be a good use of our time because it would be extremely difficult for a user to create mathematical width of zero to result (min x and max x would equal). I think a best use of our focus would be to try to understand why the d3 transforms might end up null and fix that if that is indeed the bug. At the very least, we are preventing them from becoming classification annotations now.

**Comment by srallen** [comment]
I've put together a spreadsheet to try to gain a bit more insight about the classifications: https://docs.google.com/spreadsheets/d/1ekps2cZW8cT8jeky76GsTG6z-2aSH85cP7rLlysDRn4/edit#gid=0

There isn't much consistency in type of device, browser, or OS. They come from a variety. However, almost all of them are made after sector 13 finished, so my theory the already seen banner causing some UX issues might be on the right track.
