### ISSUE TITLE
Change alignment of social media icons in footer

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1191]
via #1189

> Is it possible to align the bottoms of the logo and the social icons? If no, can they all be left-aligned? It's awkward spacing right now. <br>
![Screenshot_10_1_19__10_04_AM](https://user-images.githubusercontent.com/1392130/65974729-0d5a5680-e433-11e9-99d3-0b99f318c03e.png)

- At small screen sizes, logo and icons should be in a left-aligned column
- Once there's enough horizontal space for both, they should be aligned to the bottom of their container

**Comment by beckyrother** [comment]
Sorry why is this assigned to me?

**Comment by srallen** [comment]
I didn't realize the original comment was from you! Sorry I'll remove the assignment.
