### ISSUE TITLE
Move `FavouritesButton` to shared react components library

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1192]
**Package** lib-classifier, app-project, lib-react-components

**Is your feature request related to a problem? Please describe.**

The `FavouritesButton` and its icon are nearly identical code between the classifier library and the project app:

https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/FavouritesButton.js

https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/src/shared/components/SubjectPreview/components/FavouritesButton/FavouritesButton.js

The only difference I see is the project app version has an additional language registered with counterpart and a class name passed as a prop to the icon.

**Describe the solution you'd like**

Move the `FavouritesButton` to the react component library and remove the duplication between the two locations. Update them to use the shared version.

**Describe alternatives you've considered**

**Additional context**

**Comment by eatyourgreens** [comment]
One version uses hooks, but that’s a minor difference.

**Comment by srallen** [comment]
Sorry, which line uses hooks? I'm talking about the view components which I've linked to.

**Comment by eatyourgreens** [comment]
My bad. There’s supposed to be a state hook that tracks whether the checkbox is checked. I’ll fix that.
