### ISSUE TITLE
Project announcement banner should be full width

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1197]
**Package** app-project

**Describe the bug**

Project announcement banner does not take full width: https://frontend.preview.zooniverse.org/projects/srallen086/srallen-testing?env=staging

**To Reproduce**

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by beckyrother** [comment]
Changed the color of the green banner background to #06B165 to improve contrast and meet AAA a11y. 'SEE RESULTS' on the green is the text link style; it should underline on hover. https://projects.invisionapp.com/d/main#/console/12924056/344288110/preview
