### ISSUE TITLE
Dark theme gold button hover text color

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1198]
**Package** lib-classify, app-project

**Describe the bug**

The hover state of the gold button on dark theme is hard to read:

<img width="381" alt="Screen Shot 2019-10-01 at 1 59 11 PM" src="https://user-images.githubusercontent.com/5016731/65993959-e7937880-e457-11e9-885b-df06bc951f90.png">

This was feedback we received from the initial implementation of the button using dark theme from PFE

**To Reproduce**

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:

**Expected behavior**

Text color should be black like currently PFE:

<img width="390" alt="Screen Shot 2019-10-01 at 1 56 40 PM" src="https://user-images.githubusercontent.com/5016731/65994012-0265ed00-e458-11e9-8667-cd4cb4735f60.png">

@beckyrother will be updating the Invision styles.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by srallen** [comment]
Note: the current invision styles for the buttons show a background color gradient, but I confirmed with @beckyrother that we will not be implementing gradients at this time.

**Comment by beckyrother** [comment]
Updated InVision – no gradients on gold buttons, black text instead of white.

**Comment by eatyourgreens** [comment]
The background colour of the Next button on the dark theme is a dark grey (dark-3), not gold. That might need to be changed too, otherwise this text colour won’t be visible.

**Comment by srallen** [comment]
This issue is about the button label text color on hover, so the color won't have to be updated for that.
