### ISSUE TITLE
Image subject viewer zoom and pan

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1208]
**Package** lib-classifier

**Describe the solution you'd like**
The image subject viewers need to be zoomable and pan-able. We could consider using d3 or vx to implement zoom if the image itself is an svg `image`. #1094 needs resolving first.

d3 zoom: https://github.com/d3/d3-zoom

vx (d3-like zoom plus declarative react components): 
https://github.com/hshoff/vx/tree/master/packages/vx-zoom
https://vx-demo.now.sh/zoom-i

**Describe alternatives you've considered**

**Additional context**

**Comment by srallen** [comment]
Dev time: 2 weeks if we can leverage the d3/vx implementation using svg.

**Comment by eatyourgreens** [comment]
This can also be implemented with code that sets the SVG viewbox dynamically. The subject viewer store supports pan and zoom handlers which can be set dynamically by each viewer.

**Comment by eatyourgreens** [comment]
#1389 is a working demo of pan and zoom for SVG images.

**Comment by eatyourgreens** [comment]
#1389 is now a working implementation of pan and zoom:
- pan on pointer drag.
- continuous zoom on long press of the toolbar buttons.
- zoom on wheel scroll.
- drawing and panning mode both available.
- pan and zoom available from the keyboard when the subject viewer has focus.
