### ISSUE TITLE
Branch preview deployments

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1209]
**Package** app-project, app-content-pages

**Is your feature request related to a problem? Please describe.**

We still need a way to deploy preview branches particularly for design reviews and potentially reviews by outside collaborators. We agreed to do this in [ADR 17](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-17.md)

**Describe the solution you'd like**

We have two options:

- A script that can be run manually by the pull request opener that builds the full SSR app, creates a temporary k8 container to deploy to. Then that k8 is teared down upon merge
  - We still don't know how to do this. Helm was described as possible tool, but is still an unknown
- A script that builds the app statically and deploys it to S3.
  - Can the next.js app be configured to variably build as SSR vs static?
  - Can this can be tied into a github hook for branch pushes similar to PFE?
 
**Describe alternatives you've considered**

Not necessarily an alternative, but we are also interested in investigating storybook deployments. 

**Additional context**

**Comment by eatyourgreens** [comment]
Any thoughts about consolidating the various storybooks into one storybook? Deployment would be easier.

**Comment by srallen** [comment]
I'm tracking the storybook deployment in a separate issue: https://github.com/zooniverse/front-end-monorepo/issues/1173

Please comment there so we can keep these scoped. For what it's worth, when I looked the other day, the plugin for deploying to either github pages or S3 supports monorepos now, so I'm not sure if that's necessary.
