### ISSUE TITLE
Classify page has minor rendering issues in Safari

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/front-end-monorepo#1213]
**Package**

`lib-classifer` I guess?

**Describe the bug**
"Finished for the day" and "Your recent classifications" are taller than they should be.

**Screenshots**
![Screenshot 2019-10-08 at 10 30 15](https://user-images.githubusercontent.com/428423/66384657-10b38c00-e9b7-11e9-911b-1241d847d515.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Safari
 - Version: 12.12 (I'm unable to test this in Safari 13 at the moment)

**Comment by srallen** [comment]
@eatyourgreens if you have a moment, would you have a look at this?

**Comment by eatyourgreens** [comment]
I'm able to reproduce it on Safari 12. No idea how to fix it, I'm afraid. I assume Safari doesn't fully support CSS grids?

**Comment by eatyourgreens** [comment]
Safari doesn't support intrinsic or extrinsic grid sizing, so maybe that's the problem.

**Comment by srallen** [comment]
Hm, I wonder if there's a known polyfill or fallback we can use.

**Comment by eatyourgreens** [comment]
Inspecting both those boxes in the DOM, they're styled with `display: flex;` and `flex-direction: column;` if that helps to debug this.

**Comment by eatyourgreens** [comment]
The story for 'Your Recent Classifications' renders at the expected height in Safari 12, so I don't think there's a problem with the box styling. 'Finished for the day?' doesn't have a story so I didn't check it.
https://zooniverse.github.io/front-end-monorepo/@zooniverse/fe-project/index.html?path=/story/project-app-screens-classify-recent-subjects--plain

Maybe the containing grid is causing the problem on both rows?

**Comment by adammcmaster** [comment]
I can now confirm that this is the same in Safari 13.

**Comment by goplayoutside3** [comment]
Can no longer replicate this bus.
