### ISSUE TITLE
Static file paths are broken in production

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1214]
**Package**
app-project

**Describe the bug**
Static images aren't being loaded in production.
![Screenshot showing missing image placeholders for recent classifications.](https://user-images.githubusercontent.com/59547/66393414-62194680-e9ca-11e9-8fee-e82ccf645da7.png)

**To Reproduce**
Load https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify while not logged in, so that the Recent Classifications box is initially empty.

**Expected behavior**
Empty recent classifications should show a grey placeholder, with the Zooniverse logo.

**Comment by rogerhutchings** [comment]
According to https://github.com/zeit/next.js#static-file-serving-eg-images, static files should be in a `/public` folder (ours is called `/static`) and referenced from the baseURL `/` (this URL is `/static/subject-placeholder.png`)

**Comment by eatyourgreens** [comment]
Has that changed recently? I named the static file directory as per the docs here, which said `static` last week. https://nextjs.org/docs#static-file-serving-eg-images

**Comment by eatyourgreens** [comment]
https://github.com/zeit/next.js/pull/8636

**Comment by rogerhutchings** [comment]
Aha - we're on 9.0.3, which does use `static` - back to the drawing board

**Comment by eatyourgreens** [comment]
The URL of that placeholder on https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify is https://static.zooniverse.org/preview.zooniverse.org/panoptes-front-end/master/static/subject-placeholder.png which would explain why it's broken. Static assets are expected to be in PFE.

**Comment by eatyourgreens** [comment]
Re-opening this because static files are still broken on https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify

The placeholder image URL is resolving to https://static.zooniverse.org/preview.zooniverse.org/panoptes-front-end/master/subject-placeholder.png

**Comment by rogerhutchings** [comment]
blork. will take a look

**Comment by eatyourgreens** [comment]
They're also broken on https://zooniverse.github.io/front-end-monorepo/@zooniverse/fe-project/index.html?path=/story/project-app-screens-classify-recent-subjects--one-subject but I think that's because the deployed storybook is in a subdirectory of the site root.

**Comment by eatyourgreens** [comment]
Should `ASSET_PREFIX` be set when the build script runs in Jenkins?

**Comment by rogerhutchings** [comment]
aaaah - we could, but we could also just use run-time config instead
