### ISSUE TITLE
Support more than one annotation per task

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1226]
**Package**
lib-classifier

**Is your feature request related to a problem? Please describe.**
Workflows allow tasks to be repeated more than once (eg. [Roll the Credits](https://www.zooniverse.org/projects/sroosa/roll-the-credits)), storing more than one annotation for each task.

Annotations are mapped in the classification using the task key as an identifier, which allows only one annotation per task per classification.
https://github.com/zooniverse/front-end-monorepo/blob/b3581665747c059d382f2df00c9fc7fdae12bb70/packages/lib-classifier/src/store/annotations/Annotation.js#L3-L5

**Describe the solution you'd like**
`classification.annotations` could be stored as an array, or each annotation could be assigned its own identifier.

**Comment by eatyourgreens** [comment]
Drawing tools tasks which share a common text input task might run into this problem too.

**Comment by eatyourgreens** [comment]
One solution for drawing tools would be to give each mark its own annotations map (or array.) I think we should be guided here by whichever format works best for tools that consume classifications, like Caesar.

**Comment by srallen** [comment]
Making `classifications.annotation` an array sounds good. Then `addAnnotation` could use `lastIndexOf` to get the correct annotation for the current task key if it already exists? I think I initially used the map thinking ahead for the annotation persistence feature (if the annotation already exists, just update it the existing one) but didn't realize this would effectively make task reuse impossible since keys would need to be unique in a map. 

I was trying to think out how we can get it to work with the map, but it would mean touching all the code for the annotation models, so it'd be way more involved and risky as well as probably necessitating a conversion for down stream use, so I don't think we should try to go this route.

**Comment by eatyourgreens** [comment]
Sounds good to me. `lastIndexOf` is what I've used in PFE for exactly the same problem.

Off the top of my head, a map would require annotation identifiers, then tracking those identifiers (maybe through the task model?) so that we know which annotation you are currently editing. I'm not 100% sure how the last bit would work.

The downside of the array, I think, is that it might be harder to move backwards and forwards through it, particularly on a workflow like Notes from Nature where there are multiple tasks per step, and we want to preserve those annotations.

Branching question workflows might be tricky if you go back, then go forward choosing a new branch for your next annotation. Nothing insurmountable though, and we know that we already have this working with arrays in PFE.

**Comment by eatyourgreens** [comment]
>The primary goal of identifiers is not validation, but reconciliation and reference resolving.
https://mobx-state-tree.js.org/concepts/references#identifiers

Mentioning this because it's come up in https://github.com/zooniverse/front-end-monorepo/pull/1434#issuecomment-577441325, where we want to store multiple annotations for the same task (many lines of text on the same page.) 

Even if we store annotations in an array, the task key identifiers that they currently use won't be unambiguous. As far as I can tell, MST expects a node identifier to be unique in the entire tree, so annotations will need unique IDs.

**Comment by srallen** [comment]
We can generate unique ids as needed and toss em on classification submission like we're planning on doing elsewhere.

**Comment by srallen** [comment]
Using unique ids will enable us to support recursion and annotation persistence I think.

**Comment by eatyourgreens** [comment]
True, but it's a big change for PH-TESS. I think we'd have to use annotation IDs, not task keys, when we get an annotation from the classification.

**Comment by srallen** [comment]
Is it? They have a single task / single step workflow, so it's swapping one identifier for another. The basic function remains the same. Regardless, any change to annotation data type would necessitate we put in the due diligence that it works there, which includes the change to arrays, but if we use generated unique ids, we won't have to do that.

**Comment by eatyourgreens** [comment]
It's changing the getter here, so figuring out how to supply the correct annotation ID when requesting an annotation.
https://github.com/zooniverse/front-end-monorepo/blob/29463a6f52e2f321fb6200aca118242ca5519099/packages/lib-classifier/src/store/AnnotationsStore.js#L8-L12

This is where I've got stuck at the moment.

**Comment by eatyourgreens** [comment]
#1434 adds unique IDs to annotations.

**Comment by eatyourgreens** [comment]
#1434 may close this. It would need to a set of tests to make sure. Create more than one annotation with a single task, then verify that the second annotation doesn’t overwrite the first.

**Comment by eatyourgreens** [comment]
Cancel that thought. Tasks still get/set annotations by task key so each annotation store can only hold one stored value for a given task key.

**Comment by srallen** [comment]
I think this is closed by #2050. Reopen if not the case.
