### ISSUE TITLE
Implement workflow steps

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#123]
**Package** lib-classifier

**Feature or Issue Description**
Our new concept of workflow steps is described here and what it would solve: https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-5.md

To this end, A MST store for workflow steps should be created.

Workflows currently are structured as so:
(The `first_task` can be the task key of T1, T2, etc. The lab auto creates an 'init' task which can be later deleted and replaced.)

```
{
  id: '1',
  first_task: 'init', 
  tasks: {
    init: {},
    T1: {},
    T2: {}
  }
}
```

What we would like to change this to:
Note the substantive change here is that the steps map to an array of task objects rather than a single object. The renaming to steps is for clarity, but in theory doesn't need to happen. Also note that the summary is a step type now. There could also be a `validation` type for transcription projects that validate/approve their transcriptions prior to submission.

```
{
  id: '1',
  first_step: 'S1',
  steps: {
    S1: [
      { type: 'multiple', value: [] }
    ],
    S2: [
      { type: 'survey', value: [] },
      { type: 'multiple', value: [] } // This is like the survey + shortcut combo task
    ],
    S3: [
      { type: 'summary', content: '' }
    ]
  }
}
```

**To Dos**

- [ ] Example

**Comment by eatyourgreens** [comment]
I think tasks still need keys, so that task components can update annotations and so that we don't break services that consume classifications. I'm assuming the annotations array still looks something like this: `[{ task: 'T1', value: "something"}, {task: 'T2', value: []}, {task: 'T1', value: "something else."}]` where tasks are identified by keys and may be annotated more than once during a workflow.

**Comment by srallen** [comment]
@eatyourgreens Good point. Here's a revise version of what the structure could look like:

```
{
  id: '1',
  first_step: 'S1',
  steps: {
    S1: {
      tasks: [{ task: 'T1', type: 'multiple' }],
      next: 'S2'
    },
    S2: {
      tasks: [{ task: 'T2', type: 'survey' }, { task: 'T3', type: 'multiple' }], // This is like the survey + shortcut combo task
      next: 'S3'
    },
    S3: {
      summary: { content: '' }
  }
}
```

I don't think the classification annotations would care what step a task is assigned to, just that the annotations map back to a particular task key. I could be wrong about that though and we should probably check in with the back end team. Here I'm still imagining that the tasks are an array, but each object has a `task` property with its key like an annotation object.

**Comment by srallen** [comment]
I'm not sure how important the existing structure would be for aggregation and caesar, but I do like the direction your idea is going. After thinking about it, I think the steps will have to be an object with a property for the next step. This akin to the `next` property the task can have. OR steps is just an array itself without step keys.

Option one with steps as an object:

```
{
  id: '1',
  first_step: 'S1', 
  tasks: {
    init: {},
    T1: {},
    T2: {},
    T3: {}
  },
  steps: {
    S1: { tasks: ['T1'], next: 'S2' },
    S2: { tasks: ['T2', 'T3'] }
  }
}
```

Option 2 with steps as an array and we assume order from the order of the items in the array. We also no longer care about a property on the workflow explicitly stating `first_step` or `first_task`:
```
{
  id: '1',
  tasks: {
    init: {},
    T1: {},
    T2: {},
    T3: {}
  },
  steps: [
    ['T1']
    ['T2', 'T3']
    ['summary']
  ]
}
```

**Comment by eatyourgreens** [comment]
There are projects with branching workflows, and projects wth recursive workflows that repeat steps until you're done, so we probably still need a next step value somewhere, along with question tasks that let you choose the next step.

I think you're right that we can drop `first_step` in favour of just taking the first member of the steps array, as long as the UI allows you to re-order the array. I'm not sure if the lab does that at the moment, but we need to build a new workflow editor anyway.

**Comment by srallen** [comment]
@CKrawczyk, @zwolf could you comment on the step structure ideas here and if this would help or hinder aggregation and classification exports.

**Comment by srallen** [comment]
Ok, I think I'll have to take a look at how branching tasks works, but that alone is enough of a reason to go with the object format for steps.

**Comment by eatyourgreens** [comment]
Branching is only done by single answer tasks at the moment. Each answer can send you to a different task in the workflow.

**Comment by srallen** [comment]
Ok, looking over single choice task types, the answer object includes a property for next. This could point to a step instead of a task:

```
{
  answers: [
    { label: 'yes', next: 'S2' },
    { label: 'no', next: 'S3' }  
  ],
  type: 'single'
}
```

Looking over what Mobx/Mobx-state-tree, I think the steps could be a [javascript map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) (they're almost all entirely supported by all major browsers). We get a few advantages with couple: the keys can be any type, are iterable, and maps are ordered. When defining a property in MST as a `types.map`, the library sets it as an observable JS map type.

In the below example, steps are a map and tasks are as is for backwards compatibility for aggregation and exports. There is an example of a branching single choice task type as well as an optional `next` property in the value of the one of the steps to support recursion. Otherwise the order of the steps are derived by the order of the steps map:

```
{
  id: '1',
  tasks: {
    T1: {
      answers: [
        { label: 'yes', next: 'S4' },
        { label: 'no', next: 'S2' }
      ],
      type: 'single' 
    },
    T2: {...},
    T3: {...}
  },
  steps: [
    ['S1', { tasks: ['T1'] }]
    ['S2', { tasks: ['T2', 'T3'] }],
    ['S3', { tasks: ['T4'], next: 'S1' }]
    ['S4', { tasks: ['summary'] }]
  ]
}
```

Question for @CKrawczyk, @zwolf: The above structure will allow the front end app to drop the need for `first_task` on workflows. Is this used by aggregation or exports?

**Comment by zwolf** [comment]
`first_task` isn't used by the Panoptes exporter, it just `map`s through the classification annotations. Any structure change to individual annotations will require an update to the formatter, though.

**Comment by srallen** [comment]
One small modification:
```
  steps: [
    ['S1', { taskKeys: ['T1'] }]
    ['S2', { taskKeys: ['T2', 'T3'] }],
    ['S3', { taskKeys: ['T4'], next: 'S1' }]
    ['S4', { taskKeys: ['summary'] }]
  ]
```

Let's use `taskKeys` in the steps map just to clarify that this is different from the already present `tasks` on the workflow resource. 

I'm going to open an ADR proposal PR to document this since this is really a follow up to ADR-5.

**Comment by rogerhutchings** [comment]
One thing we haven't addressed yet is how to handle pre/post step hooks. Should these be included in the steps, or do we simply fire off change events and let other stores take care of them?

**Comment by srallen** [comment]
I was initially envisioning using [onAction](https://github.com/mobxjs/mobx-state-tree/blob/master/API.md#onaction) for the `setActive` action on the `WorkflowStep` store. This fires before the action is completed, so it could be an async check for notifications and depending on the response, fire the UI to show the notification and then continue on to set the current active step. 

However, the actual async request and store of the response should probably be a separate `Notifications` store. The `Notifications` (or maybe `Interventions`?) store could be an observer of the `WorkflowStep`'s `setActive` action?

I'm not sure which would be best.

**Comment by srallen** [comment]
Questions/concerns from @chrislintott as summarized from @rogerhutchings 

> 1. For straightforward projects, we don't want people to have to understand steps or use them to specify the logic. Chris doesn't think it is solely a design issue because of the issue of referencing next steps - you'd have to reference a step rather than a task, which introduces this idea and which then becomes an unnecessary distraction

For us, the data structure of steps is for simplifying the data structure for us programmatically; we will actually represent the ordering and combination of all tasks, rather than shoehorning it in with hacks like the current combo task and shortcut which cause difficult to understand recursion.

The suggestion is to make steps a JS Map (this is a new data structure type to javascript that MobX supports) which is ordered like an array, but keyed like objects. Only branching single choice tasks would need a reference to step key. They currently accomplish branching by referencing a specific task key, so this is a minor change to reference a step key instead of a task key. By eliminating the recursion and nesting of combo tasks, we can keep tasks a flat object which is much easier to reason about. 

For project builders and the UI for the lab, I would argue that this has beneficial effect. The current UI for combo task editing is very hard to understand. This confusing UI is eliminated by specifically having the concept of steps. For all other tasks, we can eliminate the drop down for asking what the next step is (currently the drop down is for next task) because what is next is built into the data structure since we'll use ES Maps. Only single choice tasks would need to have the drop down to specify what is next depending on the answer. The ordering of steps can be done like with other step ordering that happens in tutorials or with the ordering of workflows for display on the home page, which is drag and drop of items in an ordered list. 

We don't have to use the words 'steps' or 'step' in the UI, however, I don't think the concept is difficult to understand and the current combo task editor UI already calls it a step (see screen shot in this issue: https://github.com/zooniverse/Panoptes-Front-End/issues/4197). Form builders work this way using the word 'steps' or 'pages': wufoo, survey monkey, google forms, etc and we can borrow a bit from them design wise if we're allocated the time to actually work on the lab design. We can definitely put together a rough UI mock now.  

> 2. Didn't like steps referring to tasks and vice versa, which we decided was almost purely aesthetic, but he posed the thought experiment of explaining how to hook these up to an end user in a single sentence - if it gets confusing, it's a sign the domain model isn't quite right.

If by end user we mean the project builder, then steps are the ordered groups of tasks. If the end user is other programmers, then steps are maps of objects containing the collection of task keys (identifiers for individual tasks).

> Suggested: is it possible to keep all the next values on the task definition, which at least would be purer?

If we use ES Maps for steps we don't need to define next values for typical use cases since maps are ordered. The only exceptions which would need defined next values are recursive workflows and single choice branching. A strong reason to not touch how tasks are structured now is to keep backward compatibility for exports and aggregation and any other auxiliary service.

**Comment by eatyourgreens** [comment]
Drawing subtasks could probably be improved too, in terms of consuming the annotations in Caesar and elsewhere, by referencing tasks that are defined in `workflow.tasks`.

At the moment, I think `task.details` is an array of task definitions, and the annotation for a subtask includes the task value but no key (because they're keyed by array index in the details array.) I think it would be easier to parse task details if they looked something like this `task: { details: ['T1', 'T2'…] }` where `T1`, `T2` etc. point to tasks that are defined in `workflow.tasks`. Annotations would probably look something like `{ task: 'init', value: [{details: [{task: 'T1', value: {}}]]` where details is an array of task annotations, including the task key and value.

**Comment by eatyourgreens** [comment]
I've got one small question about ES6 Maps: is the map order preserved in Ruby and Postgres, when we write a workflow to Panoptes then read it back again? It looks like they're using ordered arrays, so should work, but I just wanted to be sure.

**Comment by eatyourgreens** [comment]
In terms of UI, maybe some sort of drag and drop interface to get your tasks into the order you want, with the option of grouping tasks so that they're presented together. Branching workflows, and recursive workflows, would need a bit more thought.

**Comment by srallen** [comment]
> I've got one small question about ES6 Maps: is the map order preserved in Ruby and Postgres, when we write a workflow to Panoptes then read it back again? It looks like they're using ordered arrays, so should work, but I just wanted to be sure.

It's a bit confusing at first that the syntax for maps _looks_ like arrays, `[[1, 'foo'],[2,'bar']]`, but they shouldn't be read as that. 

From a brief search, we could use a json helper library that has full support for map to [serialize](https://github.com/sonnyp/JSON8/tree/master/packages/json8#ooserialize) and [parse](https://github.com/sonnyp/JSON8/tree/master/packages/json8#ooparse) it or manage it ourselves (and we'd have to choose storing as an array, object, or stringifying): http://2ality.com/2015/08/es6-map-json.html or http://exploringjs.com/es6/ch_maps-sets.html#_arbitrary-maps-as-json-via-arrays-of-pairs on this.

**Comment by rogerhutchings** [comment]
@marten Would you mind pitching in on this issue? During today's zoominar you didn't seem too fazed by the idea of versioning at least part of the API and creating a better workflow structure without the separate concept of steps...

**Comment by rogerhutchings** [comment]
After talking to @srallen, we decided that we're going to carry on implementing the proposed solution. 

1. While versioning the API / workflow resource is tempting, it makes more sense to keep our impact on the backend minimal, in terms of minimising blocking work the front end requires to continue, and the knock-on effects on exports, aggregation etc.
2. During the Zoominar today, we wireframed a kanban-style project editor that both introduces steps and is pretty conceptually straightforward. I'm confident we can eventually create a project builder that includes the step idea and isn't too painful to use.

**Comment by marten** [comment]
Okay, fair enough. Adding a version field wouldn't be too hard, and we probably want to do it at some point just to say that "v1: here be dragons, v2: here be strictly enforced schema". But decoupling it is fine by me. If opinions change just shout and we can definitely make things happen on the backend.

**Comment by srallen** [comment]
I think we could still consider had a version field as we'll have to indicate somehow that this workflow is for the new classifier. I suppose this can be proxied by whether or not steps are defined. The data type I want to use for steps isn't directly supported by JSON as I'm noting in the ADR, so I'm not sure if it can be validated by the API. Regardless though, I'd like to move forward and like you said, we can revisit at another time.

**Comment by CKrawczyk** [comment]
The only place my aggregation code cares about the workflow structure is the [auto-configuration script](https://github.com/zooniverse/aggregation-for-caesar/blob/master/panoptes_aggregation/scripts/config_workflow_panoptes.py) for detecting what extractors and reducers to use.  I will have to update that script regardless of what changes are decided upon.  As long as only the workflow structure is changes and not that annotation structure, the rest of the aggregation code will just fine.

That being said, I would like to echo @eatyourgreens comments that drawing sub-tasks should be restructured.

**Comment by srallen** [comment]
@CKrawczyk thanks for your input and I think that confirmed what I thought. We can address the sub-task structure separately and I think reusing the ideas from the new step structure may be able to aid that.

**Comment by srallen** [comment]
Steps are implemented in Panoptes and documented in the ADRs.
