### ISSUE TITLE
RFC: Adding new tasks can be painful

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1231]
**Package**
lib-classifier

**Is your feature request related to a problem? Please describe.**
We'd like the new classifier to be easily extensible. However, adding new tasks to the classifier involves updating the code in several places:
- add new code in three places:
  - [task views](https://github.com/zooniverse/front-end-monorepo/blob/2e2ac27a442afc8cfaea6f7735b97ebb511367a8/packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks).
  - [task models](https://github.com/zooniverse/front-end-monorepo/blob/2e2ac27a442afc8cfaea6f7735b97ebb511367a8/packages/lib-classifier/src/store/tasks).
  - [annotation models](https://github.com/zooniverse/front-end-monorepo/blob/2e2ac27a442afc8cfaea6f7735b97ebb511367a8/packages/lib-classifier/src/store/annotations).
- import the new modules by name in several places, and register them:
  - [registered views](https://github.com/zooniverse/front-end-monorepo/blob/2e2ac27a442afc8cfaea6f7735b97ebb511367a8/packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/helpers/getTaskComponent.js).
  - [import tasks models for workflow steps](https://github.com/zooniverse/front-end-monorepo/blob/2e2ac27a442afc8cfaea6f7735b97ebb511367a8/packages/lib-classifier/src/store/WorkflowStepStore.js#L5-L18).
  - [import all annotations to the classification model](https://github.com/zooniverse/front-end-monorepo/blob/2e2ac27a442afc8cfaea6f7735b97ebb511367a8/packages/lib-classifier/src/store/Classification.js#L3).
  - [register annotations with the classifications store](https://github.com/zooniverse/front-end-monorepo/blob/2e2ac27a442afc8cfaea6f7735b97ebb511367a8/packages/lib-classifier/src/store/ClassificationStore.js#L111-L120).

It's easy to forget one of these steps and a lot of this could be automated in code.

**Describe the solution you'd like**
- Keep all the code together. Store task views and models next to each other in the filesystem. (#1212)
- Import named modules to a registry object (or similar) then load them in to other code from that register. (#1212)
- Delegate responsibility from the classification to individual tasks. (#1228)

**Comment by rogerhutchings** [comment]
- Be able to dynamically load in tasks as required
- Be able to pass in additional task handlers in a prop to the classifier

**Comment by rogerhutchings** [comment]
It’s also worth pointing out that this model could also be applied to subject viewers as well

**Comment by eatyourgreens** [comment]
Maybe drawing tools too.

**Comment by eatyourgreens** [comment]
Tasks are currently strongly coupled to the classification store. They get annotations from the store and call `classifications.addAnnotation` to update values. That will need to be decoupled before we can work on adding tasks to drawing tools, where the annotations array will be passed in from a mark, not the classification.

**Comment by eatyourgreens** [comment]
I think this can be updated to an ADR as per #1351. Did anyone else have comments?

**Comment by srallen** [comment]
None from me. Thanks!

**Comment by eatyourgreens** [comment]
I've pasted it into #1385 and added some notes about actual implementation and what works/doesn't work from my experience using it.
