### ISSUE TITLE
RFC: drawing sub-task

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1239]
**Package**
lib-classifier

**Is your feature request related to a problem? Please describe.**
https://github.com/zooniverse/front-end-monorepo/blob/1edd001edb31550a023f51b1aa15bbe70e675b3b/packages/lib-classifier/src/store/tasks/Task.js#L7-L26
Task models get their annotations from the classifications store and call `classifications.addAnnotation(value, task)` on update. It should be possible to change both of those depending on the task context (workflow task or drawing subtask.)

**Describe the solution you'd like**
Tasks should be agnostic about where their annotations come from. I think the task view component could have `annotation` and `onComplete` (or `onChange`?) as props. The task area would pass in the annotation from the classification, and `classifications.addAnnotation` as the callback. Drawing subtasks would pass in the annotation from the drawing mark, and a callback that updates the drawing tool annotation.

There might be better solutions which involve passing context to the task model instead, so I'm opening this issue for discussion. Is there a way to replace `getRoot(self).classifications` with something more flexible in the Task model code?

**Comment by eatyourgreens** [comment]
Something to consider: move the annotation code (adding annotations, removing annotations etc.) out of the `classifications` store and into an `annotations` store in its own right. Use that `annotations` model as the model for both `classification.annotations` and `mark.details` (or whatever we call drawing subtask annotations.)

**Comment by srallen** [comment]
For the UI, the subtask will no longer be anchored to the drawing mark anymore and should be a movable div area so that volunteers can see areas of the image as needed. This is based on feedback primarily from humanities/transcription projects.

**Comment by srallen** [comment]
@eatyourgreens if we implemented the idea proposed in this issue, do you have a sense for how long it would take?

**Comment by wgranger** [comment]
For floating modal boxes I used https://github.com/bokuweb/react-rnd. Rnd meaning, resize and drag, because the the ASM boxes were initially resizable.

There are a lot of different options for creating a floating modal, but I chose the option above because it seemed the most straightforward at the time. Overall, I'd say it worked pretty well, although there are a lot of important props you'll have to be mindful of should you choose the Rnd route.

**Comment by eatyourgreens** [comment]
Cheers! Seems like this could be done quickly so I'd put it down as a week.

**Comment by srallen** [comment]
I'm going to open a separate issue about the UI side of this and copy over the comments. The original discussion here was about the data side of how to store the sub-task annotations.

**Comment by eatyourgreens** [comment]
The data side seems straightforward. On starting a task, you explicitly pass an annotation to a task (maybe `task.addAnnotation`?). The task modifies the annotation. On modification of the annotation, or on task completion (`task.onComplete`?), the annotation is passed back to the original source for storage.

For drawings, we'll want the same task to be repeated many times with a different annotation each time, so either the store shouldn't be mapped to task ID, or each line task should be a new instance of the same workflow task.

**Comment by srallen** [comment]
We may want to restructure the sub-task JSON, per this comment: https://github.com/zooniverse/front-end-monorepo/issues/1314#issuecomment-561717018

**Comment by eatyourgreens** [comment]
As of #1335, both `Classification` and `Mark` extend `AnnotationsStore`, so `mark.annotations` has the same structure as `classification.annotations` ie. a map of annotations indexed by task key.

**Comment by eatyourgreens** [comment]
Next up, I think, is extending `Tool` to include `tool.tasks`, probably shared with the `Step` model. That will require #1266 to be merged first.

**Comment by eatyourgreens** [comment]
I'm pretty sure #1434 will close this by removing all references to the classifications store from the task models.
