### ISSUE TITLE
Error state design for text task

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1247]
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**

How and when would the text task have an error state? This question came up in #1232

The current Invision design shows this (ignore the blue highlighting, the keyboard shortcut for a cropped screenshot is enabling those):

<img width="399" alt="Screen Shot 2019-10-23 at 9 46 55 AM" src="https://user-images.githubusercontent.com/5016731/67405270-278edc80-f57a-11e9-8495-586008c7bb82.png">

It should be noted that we have free text input coupled with the dropdown task and this design is representing this, so this error state might be only applying to that use case. I also want to suggest in the new classifier that we decouple the free text input from the dropdown task, but that's a separate issue. 

@beckyrother our question is: should the text task have an error state design? We disable the next/done buttons on required tasks. Is this a visual indicator if someone attempts to click a disabled button or something else?

**Comment by beckyrother** [comment]
This error state is meant to be used for any type of validation, like dates or numbers. It could also be used if someone tries to click on a disabled button as a way to indicate that this field needs to be filled out as well. Jim is correct that this won't be used often, but having an error state planned for is useful.

**Comment by eatyourgreens** [comment]
The project builder doesn't support validation for text input so that would be a new piece of work anyway.

**Comment by eatyourgreens** [comment]
Disabled buttons aren't clickable, so don't fire `click` events.

**Comment by eatyourgreens** [comment]
#688 is linked to this, which is to add support for required tasks (and flag them up as required in the classifier.)

**Comment by srallen** [comment]
Maybe the validation and UI can error if focus leaves the text area if it is required and no text was entered. More complex validations will require specific input types we don't support yet, but could in the future.
