### ISSUE TITLE
PrimaryButton

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1248]
**Package** lib-react-components

**Is your feature request related to a problem? Please describe.**

#1199 Added a shared GoldButton, but a better variant would be a `PrimaryButton` component that takes a color prop that then loads a Grommet `Button` with the appropriate theme customization needed to render the correct fill colors in the light and dark themes. The current variants are: zooniverse brand teal (theme default), gold, green, Done & Talk blue.

**Comment by rogerhutchings** [comment]
Here's a quick gist that lets you derive the second stop for the gradient background: https://gist.github.com/rogerhutchings/bbe782a3718ef1738f54f9b4633a0511

In Photoshop, it was done by creating a black layer (although in testing it works out more as a grey), setting the blend mode to `overlay`, and adding a gradient masking layer
