### ISSUE TITLE
[Project Home Page] Call to action off screen in certain browsers / hardware configs

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1253]
**Package** app-project

**Describe the bug**
The project home page can go off screen, see comment: https://github.com/zooniverse/front-end-monorepo/issues/1152#issuecomment-536608127

This is reproducible on a 13" 2017 MBP in Firefox and on a 13" 2015 MBP in Firefox and Chrome. The difference is with GPU in models using the default display settings.

We should investigate using vh appropriately to guarantee the call to action stays on screen.

**To Reproduce**

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by srallen** [comment]
The issue for FF on the 2017 MBP might have to do with flexbox?

**Comment by eatyourgreens** [comment]
Does that include the Zooniverse navigation at the top? That was the bit that stopped me from styling this with `vh` last time I looked at it.

**Comment by rogerhutchings** [comment]
it does

**Comment by eatyourgreens** [comment]
One thought: maybe it shouldn’t be exactly `100vh`, so that there’s some hint that you can scroll down to the rest of the page. If it exactly fills the viewport, people may assume it’s the entire page.
