### ISSUE TITLE
Warning on clicking the back button

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1270]
We show a warning on clicking the back button that you will lose your work. Mostly used on transcription tasks.

**Comment by rogerhutchings** [comment]
Estimated time: 1 person, 1 week

**Comment by srallen** [comment]
Time estimate: 1 week, 1 person

**Comment by srallen** [comment]
Design: https://projects.invisionapp.com/d/main?origin=v7#/console/12923997/288044640/preview?scrollOffset=5875

We have a `Tooltip` component available in `@zooniverse/react-components`

**Comment by srallen** [comment]
This is deprecated because we have gotten task recursion and annotations persistence using MST features. See #2363
