### ISSUE TITLE
Add remaining feedback strategies

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1274]
The following strategies have been built in PFE and have been copied over to the new classifier:

- Drawing
  - Column
  - Radial
- Dud
- Single answer question

There's also the `Sim notification` feature, which we could recreate using feedback. From `how-to-zooniverse`:

> Hack to support sim notification during SGL. Projects that use this should be migrated to General Feedback and then deprecated.

This is currently an experimental feature.

The other related feature is `Gravity Spy gold standard`, another experimental feature used to provide feedback for the survey task in GS. This is going to be deprecated, and a survey task strategy written for general feedback.

---

So we need to test the strategies that have been copied over, and possibly add an easy way to enable sim notification (this might look a lot like the single answer question strategy)

## Related code in PFE

- [strategies](https://github.com/zooniverse/Panoptes-Front-End/tree/master/app/features/feedback/shared/strategies)
- [classification-summary.jsx](https://github.com/zooniverse/Panoptes-Front-End/blob/b1c6e0e5a7cadefcce5e4d240f6577660885ba3a/app/classifier/classification-summary.jsx#L29)

**Comment by rogerhutchings** [comment]
Estimated time: 1 person, 1 week

**Comment by srallen** [comment]
All the existing strategies are implemented.
