### ISSUE TITLE
Flip image colors feature

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1276]
Color inversion using an SVG filter. This needs a button in the UI to enable it, and is configured on the workflow resource.

**Comment by rogerhutchings** [comment]
Estimated dev time: 1 person, 1 week

**Comment by srallen** [comment]
Seen in the dev classifier: https://master.pfe-preview.zooniverse.org/dev/classifier

**Comment by srallen** [comment]
Needs design time.

**Comment by lcjohnso** [comment]
@mcbouslog Is this issue resolved by your recent invert button work?

**Comment by mcbouslog** [comment]
Yes, closing
