### ISSUE TITLE
Hide previous marks

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1278]
There's a feature for being able to toggle the visibility of every mark up to the most recent one.

**Comment by srallen** [comment]
Penguin Watch example: https://www.zooniverse.org/projects/penguintom79/penguin-watch/classify

**Comment by rogerhutchings** [comment]
This also needs some design time to add a button to the UI

**Comment by eatyourgreens** [comment]
It should be a checkbox, or a toggle that maps to a checkbox.

**Comment by srallen** [comment]
@beckyrother do you have time this month to take a look at this?

**Comment by beckyrother** [comment]
> @beckyrother do you have time this month to take a look at this?

Yep! I'll add it to the list.

**Comment by eatyourgreens** [comment]
Possibly involves adding a `hidden` toggle to the Mark model.

Does this toggle persist across tasks in PFE? I haven't looked to see.

**Comment by beckyrother** [comment]
Here's an InVision link: https://invis.io/UAN6AP0JTBC#/402469916_14-1_Hide_Previous_Marks

Added the toggle to below the image. Uses Grommet's `formView` and `formViewHide` icons

**Comment by eatyourgreens** [comment]
This has to be enabled in the project builder so I'm guessing it's a workflow config option?

The button's easy to add. We've never spec'ed (even in PFE) what it does or when it should appear on the page.

**Comment by srallen** [comment]
Yes, I believe so. Just a quick search through PFE: https://github.com/zooniverse/Panoptes-Front-End/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+hide+previous+marks

**Comment by srallen** [comment]
ASM has a slightly different function with hiding marks. The toggle is for three different states: show all, hide other previous transcriptions, hide all marks. I think this can be adapted for the general hide previous marks toggle rather than support a transcription task vs a drawing task differentiation. The generalized toggle could support these states: show all, show marks only for the current active drawing task, hide all marks.

**Comment by eatyourgreens** [comment]
After hiding all marks, you should also be able to continue marking without your new marks being hidden. See Penguin Watch for an example of this in action.

**Comment by srallen** [comment]
Or being able to mark is disabled when all is hidden and volunteers have to explicitly change the state to start again.

**Comment by eatyourgreens** [comment]
Wouldn't that break Penguin Watch and Seabird Watch, where you want to be able to mark crowded fields without accidentally selecting existing marks?

**Comment by wgranger** [comment]
Another reason for hiding all marks in ASM is the nature of the subjects being a good bit of sometimes tiny handwriting crammed into close lines. In that case, hiding all lines (even the most recently places ones) was desired to help the readability of the document. This doesn't necessarily apply to a task like marking penguins. 

Hiding all marks (and allowing a new mark) does also help if you're trying to make an annotation in a crowded field to avoid accidentally selecting a previous mark, so that is a good point Jim made above.

**Comment by eatyourgreens** [comment]
I think PRN, Seabird Watch and Penguin Watch would also work if marks from the current task are visible (maybe at lowered opacity) but are disabled from being selected/edited. The intention was to allow you to continue drawing on top of existing marks, I think. @vrooje might remember better than I do.

**Comment by srallen** [comment]
Ok, I'd like to get some feedback from a couple of researchers outside transcription projects, so @vrooje and @lcjohnso if you can share your thoughts if possible in the next couple of days that would be appreciated. If there's any doubt or question of the utility of this outside of transcription, then let's plan on applying this functionality only to the transcription task and then implement the standard hide previous mark function for the drawing task.

**Comment by snblickhan** [comment]
> After hiding all marks, you should also be able to continue marking without your new marks being hidden. See Penguin Watch for an example of this in action.

I can confirm this is something that's a bit frustrating in the current version of ASM; if I'm transcribing a long document with cross-writing, I often wish I could hide all marks _up to a certain point_ and then see the new ones I'm making. I'm not entirely sure there's a GLAM/humanities use case other than this, but it definitely maps to the Penguin Watch use case of "This page is getting crowded so I want to hide everything I've done so far."

**Comment by lcjohnso** [comment]
@srallen I don't have much to add here, but concur with a few of the things mentioned above.
- The "hide all, but allow new marks and keep additions visible as I go" feature seems like a good default for the primary / simple case of a single toggle.
- I don't think non-collaborative (here: non-transcription) workflows need any additional complexity in the feature (i.e. 3-state toggle), and I think additional complexity could hurt more than help.
- Even for collaborative workflows, I'm not sure there's significant benefit to the added complexity -- just hiding all up to now seems the most useful. Not sure we've identified any fans of the ASM functionality, so I'm defaulting to keeping the current behavior. But no strong feelings and happy to defer to Sam and others.

**Comment by lcjohnso** [comment]
[Radio Galaxy Zoo: LOFAR](https://www.zooniverse.org/projects/chrismrp/radio-galaxy-zoo-lofar/classify) is an interesting case where multiple marking tasks leading to multiple sets of markings is the single case I can think of where a more complex 3-state toggle might help.  But seems current 2-state would be sufficient as well (and the project doesn't even have that enabled).

**Comment by srallen** [comment]
Ok, so I think the best path forward now would be to implement the boolean PFE version of the functionality for the drawing task and the 3 state version for the transcription task. At a later date, we could consider rolling out the option to use the 3 state version (maybe part of the configuration when enabling it in the lab?)

@wgranger I'll be assigning this to you. Please look over the code base to to familiarize yourself with the task MST models, which are found in the `plugins` folder. Check out the `InteractionLayerContainer` for a way for checking for the transcription task. It's used to determine whether or not to render the `TranscribedLines` component (we may want to consider adding a similar getter function for the drawing task too). There is a design for the standard hide previous marks toggle on invision, but you'll have to coordinate with @beckyrother for design on the transcription task version. Thanks!

**Comment by srallen** [comment]
@wgranger, we have reduction data for the test workflow 3392 now, so the three state version of hiding previous marks should be easier to implement now. Do you have availability to start on this? Thanks!

**Comment by wgranger** [comment]
@srallen Sorry for the belated response! About to get started. Hope to get a working branch this week.

**Comment by wgranger** [comment]
@beckyrother Is there a design for the intermediate stage of hiding previous marks - showing only a user's marks and not the marks of other users? This design only accounts for show all or show none - https://invis.io/UAN6AP0JTBC#/402469916_14-1_Hide_Previous_Marks

ASM uses something similar to [this FA eye slash](https://fontawesome.com/icons/eye-slash?style=solid) when only showing a user's marks, but there will also need to be appropriate text.
