### ISSUE TITLE
Add side-by-side image viewer

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1280]
We need to add a separate subject viewer for side-by-side images - the default should be to use the flipbook, but at some point we're going to want to be able to show independent frames simultaneously.

## Related projects

- ~~Sun Spotter~~ finished
- ~~Radio Galaxy Zoo~~ finished
- Space Warps

**Comment by rogerhutchings** [comment]
Estimated time: 
 - design: 2 weeks
 - dev: 3 weeks

**Comment by beckyrother** [comment]
could be +/- 4 images

**Comment by eatyourgreens** [comment]
We could try to enforce limits on how many images can be compared at once. I'm not 100% sure how that would work, without checking each subject on every linked subject set individually.

Would we be okay with validating the subject when it loads, and maybe erroring if it can't be shown in the viewer?

**Comment by beckyrother** [comment]
Turns out I already did half of this: https://projects.invisionapp.com/d/main#/console/12923997/270495264/preview

Agreed on limiting the number of images to be compared. The brain can really only distinguish between about 6 elements before it gets overwhelmed; I'd recommend limiting to 4 for optimum results

**Comment by beckyrother** [comment]
> Estimated time:
> 
> * design: 2 weeks
> * dev: 3 weeks

@rogerhutchings please update my estimate to 1 week

**Comment by srallen** [comment]
> Would we be okay with validating the subject when it loads, and maybe erroring if it can't be shown in the viewer?

Yes. I think that's a good idea.

**Comment by srallen** [comment]
Possibly being deprecated if no one requests for this. We may be building a side-by-side layout format for an image+text.

**Comment by goplayoutside3** [comment]
This can be accomplished in the existing flipbook viewer. Closing until a project requests and funds a different subject viewer specific to a use case that doesn't fit the flipbook viewer.
