### ISSUE TITLE
Support text subjects

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1283]
We need to add a viewer for plain text subjects.

cc #1296 

## Related code in PFE

- [text-viewer.jsx](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/components/file-viewer/text-viewer.jsx)

**Comment by srallen** [comment]
Diagnosis London: https://www.zooniverse.org/projects/eatyourgreens/diagnosis-london/classify

**Comment by rogerhutchings** [comment]
Estimated time:

- design: 1 week
- dev: 1 week

**Comment by eatyourgreens** [comment]
Demo project on staging: https://master.pfe-preview.zooniverse.org/projects/eatyourgreens/text-highlighter-demo/classify

This should only be built if there's a project that needs text subjects.

**Comment by srallen** [comment]
We have an incoming project to verify OCR that will use an image+text subject, so an underlying text subject viewer should be built.

**Comment by lcjohnso** [comment]
@mcbouslog Is this issue resolved by your recent Digileap work?

**Comment by mcbouslog** [comment]
Yep, closing
