### ISSUE TITLE
Dropdown task

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1284]
Provides a dropdown in the task area. The current implementation can also function as a free text input (see the dev classifier in PFE) - we should make this strictly dropdown only.

## Related code in PFE

- [dropdown](https://github.com/zooniverse/Panoptes-Front-End/tree/master/app/classifier/tasks/dropdown)

## Notes from how-to-zooniverse

Two issues: Translations for project submitted labels may change and currently it is difficult or nearly impossible to aggregate (see: [zooniverse/caesar#842](https://github.com/zooniverse/caesar/pull/842) and [zooniverse/caesar#841](https://github.com/zooniverse/caesar/issues/841). The dropdown task has no limit on number of options causing app performance problems (see: [zooniverse/Panoptes-Front-End#3636](https://github.com/zooniverse/Panoptes-Front-End/issues/3636). Proposed solutions are to drop free text entry, limit the number of allowed options, and leverage S3 for the custom options rather than serialize from Panoptes

## InVision

- https://projects.invisionapp.com/d/main#/console/12923997/270495290/preview
- https://projects.invisionapp.com/d/main#/console/12923997/270495295/preview
- https://projects.invisionapp.com/d/main#/console/12923997/270537252/preview

## Other notes

- This may need a couple of passes. We need this for IMLS, but it should be fairly straightforward in this use case; but for cases where we have thousands of possibilities, it won't necessarily scale

cc #1271 #1268

**Comment by eatyourgreens** [comment]
It renders more than one menu, where the selected option from one acts as a key to determine the content of the next eg. Country > State > City.

**Comment by eatyourgreens** [comment]
What's the problem with aggregation? Keys are used in the annotation, not translated labels.

**Comment by srallen** [comment]
> What's the problem with aggregation? Keys are used in the annotation, not translated labels.

It's discussed in the linked to caesar issues. 

> we should make this strictly dropdown only.

We could consider an HTML datalist like I've asked about in #1268, but I'm not sure if that's a good idea yet.

**Comment by eatyourgreens** [comment]
I explained in the linked caesar issue why there isn't a problem with aggregation.

**Comment by rogerhutchings** [comment]
Estimated dev time: 6 weeks

The Grommet [TextInput component](https://v2.grommet.io/textinput) might be the helpful

**Comment by rogerhutchings** [comment]
Also: the Grommet [TextInput component](https://v2.grommet.io/textinput) might be basically what we want to build

**Comment by srallen** [comment]
We may need some back-end dev time as well to resolve the performance issues with the size of the workflow task.

**Comment by srallen** [comment]
Closing in favor of #1679 since discussion and decisions from that may impact the actual dev time estimate, so consider the estimate in this largely inapplicable.
