### ISSUE TITLE
Survey task

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1286]
Build out the survey task

## Related code in PFE

- [survey](https://github.com/zooniverse/Panoptes-Front-End/tree/master/app/classifier/tasks/survey)

## InVision Links

- [Survey](https://projects.invisionapp.com/d/main#/console/12923997/270495274/preview)
- [Survey Hover](https://projects.invisionapp.com/d/main#/console/12923997/270495276/preview)
- [Filter Open](https://projects.invisionapp.com/d/main#/console/12923997/270495277/preview)
- [Filter Open Filtered](https://projects.invisionapp.com/d/main#/console/12923997/270495280/preview)
- [Filter Open Filtered Hover](https://projects.invisionapp.com/d/main#/console/12923997/270495281/preview)
- [Filter Open Filtered Hover Top](https://projects.invisionapp.com/d/main#/console/12923997/270495282/preview)
- [Survey Filtered](https://projects.invisionapp.com/d/main#/console/12923997/270495284/preview)
- [Survey Some Selected](https://projects.invisionapp.com/d/main#/console/12923997/270495286/preview)
- [Survey Some Selected Hover](https://projects.invisionapp.com/d/main#/console/12923997/270495287/preview)
- [Survey Fewer Selected](https://projects.invisionapp.com/d/main#/console/12923997/270495288/preview)

## Notes

- We had some suggestions from a totally blind volunteer on how to improve the design for use in e.g. NVDA

**Comment by srallen** [comment]
Survey task code in PFE is converted to jsx and has specs. Most of this can probably be copied over: https://github.com/zooniverse/Panoptes-Front-End/tree/master/app/classifier/tasks/survey

**Comment by rogerhutchings** [comment]
Estimated time: 4 weeks, with a question mark over how much we can copy straight over; the facelift alone will probably take a couple of weeks.

**Comment by srallen** [comment]
2 weeks for design time. Becky would like to add dark theme design references and review the choice details design.
