### ISSUE TITLE
Bezier curve drawing tool

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1287]
> an arbitrary shape made of point-to-point curves. The midpoint of each segment drawn can be dragged to adjust the curvature.

A thought - has anyone actually seen this tool in use in the wild? It may be easier to do a freehand drawing; we should run a query to see if it's currently in use.

## Related code in PFE

- [poly-curve.cjsx](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/poly-curve.cjsx)

## Related Issues

- issue number

**Comment by rogerhutchings** [comment]
From discussion, this tool is probably best deprecated. We'll have to determine the best way to communicate this in the future, but I'll leave this open for now to discuss it.

**Comment by rogerhutchings** [comment]
We also need to find out which projects are using this tool

**Comment by srallen** [comment]
@lcjohnso did you come across this drawing tool in use from your query at all?
