### ISSUE TITLE
Crop drawing tool

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1290]
Allows the user to draw a box around part of an image subject, and crop the image view to the box.

It's currently unclear if anyone's using this, so we can think about deprecating it.

## Related code in PFE

- [crop/index.cjsx](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/crop/index.cjsx)

**Comment by eatyourgreens** [comment]
+1 to deprecating this. Noone has asked for it in all the time it's been available.

**Comment by rogerhutchings** [comment]
I just did a query - there's definitely no one using it
