### ISSUE TITLE
Ellipse drawing tool

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1291]
> an oval of any size and axis ratio; this tool can be rotated.

There is also the AnchoredEllipse tool:

> Creates an ellipse in the center of the subject during the first click, and does not allow it to be dragged

It's currently unclear if anyone's using the anchored ellipse, so we can think about deprecating it. We could also replicate it by making it a configurable option on the main ellipse tool.

## Related code in PFE

- [ellipse.cjsx](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/ellipse.cjsx)
- [anchored-ellipse.jsx](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/anchored-ellipse.jsx)

## Related Issues

- #500

**Comment by rogerhutchings** [comment]
@CKrawczyk can we deprecate the anchoredEllipse as a separate tool since we know the annotation shape will be identical to a regular ellipse?

**Comment by rogerhutchings** [comment]
Estimated time: 1 person, 1 week

**Comment by CKrawczyk** [comment]
@rogerhutchings from an aggregation point of view this is identical to an ellipse tool so there is no issue depreciating it.
