### ISSUE TITLE
Fan drawing tool

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1292]
An 'ice-cream cone' shape used to draw fans, originally created for Planet Four.

## Related code in PFE

- [fan.jsx](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/components/Fan/fan.jsx)

## Related Issues

- #500

**Comment by rogerhutchings** [comment]
Estimated time: 1 person, 1 week

**Comment by goplayoutside3** [comment]
Closing for now as there are no immediate plans to build this. Dev team will create a new, more detailed Issue if Planet Four moves to FEM and needs custom-built code.
