### ISSUE TITLE
Freehand drawing tools

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1293]
There are four freehand drawing tools available in PFE:

- `FreehandLine` - a simple freehand line.
- `FreehandShape` - a freehand line that closes with a straight line to the first point on `mouseUp`.
- `FreehandSegmentLine` - a multi-part freehand line where each freehand part is joined to the end of the previous part with a straight line.
- `FreehandSegmentShape` - a multi-part freehand line where each freehand part is joined to the end of the previous part with a straight line, and where clicking on the first point closes the shape.

## Notes

- [Annotation payload size has been an issue](https://github.com/zooniverse/Panoptes-Front-End/issues/3551) with the freehand tools in the past; we've talked about ways to reduce that, including:
  - deduping identical points (pretty sure that's already in PFE)
  - throttling the rate at which points are added to a line
  - changing the annotation structure, currently `[{ x: <float>, y: <float> }, ...]` , either to use the SVG `path` property, or by storing an array of arrays (`[[<int>, <int>], ...]`)
  - changing the accuracy of the points stored (reduced to one decimal place by zooniverse/Panoptes-Front-End#3827)
- `FreehandSegmentLine` and `FreehandSegmentShape` could probably be deprecated.

## Related code in PFE

- [freehand-line.cjsx](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/freehand-line.cjsx)
- [freehand-segment-line.cjsx](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/freehand-segment-line.cjsx)
- [freehand-segment-shape.jsx](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/freehand-segment-shape.jsx)
- [freehand-shape.jsx](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/freehand-shape.jsx)

## Related Issues

- #500

**Comment by rogerhutchings** [comment]
After talking to @srallen, the most performant option for doing this in the browser is simply storing the annotation as a `path` string - no conversion is going to be faster than conversion to another structure. If we _do_ need to convert this for downstream consumers like research teams, we can do it in Caesar / data-digging tools etc

Estimated time: 1 person, 2 weeks, but will require another 2 weeks of testing with a project team like Etch-A-Cell

**Comment by hrspiers** [comment]
Drawing tool improvements:

Eraser functionality
‘warp/move’ drawn lines
Copy and paste
Vary line thickness (as a setting in the project builder)
Data as a subject – overlay a pre-existing segmentation onto a subject
Improve user friendliness of pointer
Continue line from a previous line (stop and start)
Ensure minimum length is appropriate
Make sure deletion cross is in a sensible position that doesn’t obscure segmentations 

Just to note, this list was produced quite some time ago - so it would likely be worth checking in with other teams currently using the drawing tools for more ideas and feedback once this effort is underway (e.g. Crick/Mayo and others)

**Comment by srallen** [comment]
Original PFE issue about the minimum length: https://github.com/zooniverse/Panoptes-Front-End/issues/5097

We have been asked to try to deprecate minimum sizes for tools in general if possible because of their biasing effects too.

**Comment by srallen** [comment]
Instead of an eraser, we will initially try to build an undo button function that will undo the last X length of the line. We'll have to experiment with the UI on placement of such a button.

**Comment by srallen** [comment]
There's still an open question as to whether we want to submit an annotation as just its SVG path. @CKrawczyk how feasible would it be to add into the aggregation suite of tools a SVG path to coordinate converter? I'm thinking aggregation would be an appropriate place for this since it would have to be done for aggregation to work I think? So if the front end doesn't do it, we can at least point researchers to a standard conversion tool that is built? If this should live somewhere else or if there's a reason this really should be handled by the front end do let me know. Also cc @lcjohnso since I think this impacts Floating Forests as well and you may have insight as to what their needs are.

**Comment by CKrawczyk** [comment]
I think it would be fine to add an SVG path extractor to aggregation, seems like a good place for it.  A quick search brought up several python packages that can convert the SVG strings into points.

As a side note, these kinds of shapes are the ones where reduction becomes difficult and depends strongly on the research being done.  I have ideas about how to handle the reduction of closed freehand shapes (e.g. cluster based on fraction overlap), but open freehand lines are much more difficult.

**Comment by CKrawczyk** [comment]
Also, am I right in assuming that the SVG path will already be transformed into image coordinates?  Or would the code also need to parse transforms in addition to the path?

**Comment by srallen** [comment]
@CKrawczyk we're still in the conceptual stage for this, so we can experiment with what transforms it will do, as long as it stays performant.
