### ISSUE TITLE
Highlighter tool

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1296]
For plain text subjects, we need to build out the highlighter tool.

## Related code in PFE

- [highlighter](https://github.com/zooniverse/Panoptes-Front-End/tree/master/app/classifier/tasks/highlighter)

**Comment by eatyourgreens** [comment]
This can wait until we have a project that wants to use text highlighting.

[Demo Text Highlighting Project](https://master.pfe-preview.zooniverse.org/projects/eatyourgreens/text-highlighter-demo).

**Comment by srallen** [comment]
@snblickhan cc'ing you this placeholder issue about the highlighter tool.

**Comment by goplayoutside3** [comment]
@mcbouslog close or keep open in relation to the already built highlighter tool?
