### ISSUE TITLE
Additional features for marking tools

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1297]
- Support required marking
- Enable counters for marking tools
- ~~Add ability to clone marks across multiple frames when multiple subject locations are visible~~
- Delete marks when they move out of bounds

**Comment by rogerhutchings** [comment]
Estimated time: 1 person, 1 week

**Comment by eatyourgreens** [comment]
See #1307 for required tasks.

**Comment by eatyourgreens** [comment]
#1266 adds counters for marks.

**Comment by eatyourgreens** [comment]
Closing this in favour of #1334.
