### ISSUE TITLE
Rectangle drawing tool

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1300]
> a box of any size and length-width ratio; this tool cannot be rotated.

There is also the rotateRectangle tool, which is the same but rotatable. These could be merged, and the ability to rotate made a configurable flag.

## Related code in PFE

- [rectangle.cjsx](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/rectangle.cjsx)
- [rotate-rectangle.jsx](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/rotate-rectangle.jsx)

## Related Issues

- #500

**Comment by rogerhutchings** [comment]
Estimated time: 1 person, 1 week

**Comment by shaunanoordin** [comment]
The Classifier (`lib-classifier`) now supports both the `rectangle` and `rotateRectangle` Drawing Task drawing tools. 🎉
