### ISSUE TITLE
Transcription Task

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1313]
**Package** lib-classifier

As described in ADR 20 (#1268), we will need to implement a new transcription task. It will be a composite of:
- a variant of the line drawing tool
- a pre-configured sub-task with a variant of the text task that includes suggestions

This is an overall tracking issue and individual issues will be opened for the individual pieces to implement this. 

Edited to add the user stories: https://docs.google.com/document/d/16abI-wkRlEXsWgACfFQVqwO76aEopohIjQiRfNQKWiw/edit

G Drive folder with additional info on ASM implementation:
https://drive.google.com/drive/folders/1T3nF4sVd_dnpABjXcX4ypRB4CZmu44mK

**Comment by srallen** [comment]
Associated issues:

- Annotation JSON structure: #1314 
- Drawing sub-task and how to store the annotations #1239 
- Drawing sub-task UI #1315 
- Text task with suggestions UI #1316 
- Requesting data from Caesar #1271

**Comment by srallen** [comment]
The new transcription task will explicitly be a separate model that has its `taskType` defined as `transcription` in the classifier and eventually listed in the available task types in the lab.

**Comment by eatyourgreens** [comment]
Have you any thoughts what the properties of a Transcription task are? Is it a straight copy of the drawing task, with tools, active tool, marks, active mark etc?

**Comment by srallen** [comment]
We're far enough along in implementing this that I'm closing this tracking issue in favor smaller more specific issues for the final pieces.
