### ISSUE TITLE
[RFC] Transcription task annotation JSON structure

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1314]
**Package** lib-classifier

The new transcription task is a composite of new variants of existing tasks: the line drawing tool of the drawing task and the text task with autosuggestions from caesar if they exist. In addition, ADR 20 (#1268) identified the potential need to track in the annotation directionality and page rotation to aid in aggregation. We need to decide how these should be annotated. 

ASM uses a modified polygon drawing tool capped at two points and a standard text task annotation in the sub-task. An example of this annotation JSON:

``` json
{
 "task": "T1",
  "value": [{
      "details": [
         { "value": "the text of the line being transcribed" }
      ],
      "frame": 0,
      "points": [
        { "x": 1, "y": 1 },
        { "x": 100, "y": 100 } 
      ]
  }]
}
```

Here's a proposal of what the new transcription task annotation structure could look like:

``` json
{
 "task": "T1",
  "value": [{
      "details": [
         { "value": "the text of the line being transcribed" }
      ],
      "frame": 0,
      "x1": 194.80206298828125,
      "y1": 356.3935241699219,
      "x2": 339.3945617675781,
      "y2": 356.3935241699219,
      "direction": 0,
      "page_rotation": 0
  }]
}
```

`direction`: a number in degrees to indicate writing direction, with the only possible values being 0 equal to left-to-right, 90 equal to top-to-bottom, 180 equal to right-to-left, and 270 equal to bottom-to-top. I think we should have a consistent definition of what each of these mean, so a document that is written in RTL would likely have most of its transcribed lines annotated with a 180 for direction for instance. This would derived after calculating the slope of the line. 

`page_rotation`: this can be derived from the state of the image meta-tools. This will be a number in degrees of 0, 90, 180, 270.

It seems to me that the direction calculation could happen either client side or downstream in the aggregation code, so it's not clear to me how necessary it is for this to happen in the client. However, page rotation is a volunteer configuration of how they're currently viewing the subject, and we can definitely add that in.

**Comment by eatyourgreens** [comment]
`classification.annotations` is a map by task key (I think) so that will need to be changed in order to record more than one line. We can either generate a new instance of the task model for each line (one task per annotation) or have one task that has many annotations (stored as an array maybe?).

Either way, I think the classification model will need some rewriting.

**Comment by srallen** [comment]
We have an issue already tracking that: https://github.com/zooniverse/front-end-monorepo/issues/1226

**Comment by eatyourgreens** [comment]
True, but I don't think we've figured out how to update a single transcription annotation after clicking on its line and editing it. Maybe just wipe `classification.annotations` for this task and create it again from scratch?

**Comment by eatyourgreens** [comment]
Based on conversations with @CKrawczyk last year, we should deprecate `mark.details` in favour of something like `mark.annotations`, where each annotation has the shape `{ task, value }`. The current structure doesn't record a task key for each subtask annotation, making aggregation a little tricky.

Also, drawing annotations for the line tool are arrays of lines:
```js
[
  task: 'T1'
  value: [ line, line, line…]
]
```

**Comment by srallen** [comment]
That has implications for the sub-task generally. I'll link to this comment in the associated issue.

**Comment by CKrawczyk** [comment]
The proposed structure looks good to me, but what about the cases of text written at 45 deg?  Also what tolerance will be used to place the `direction` into the four categories?

**Comment by srallen** [comment]
@CKrawczyk can you clarify if you're responding to my comment with the proposed structure or @eatyourgreens's comment or both? If both, I want to be sure we clearly document the structure with all the changes proposed here.

**Comment by eatyourgreens** [comment]
Have we got any examples of a classification for ASM? I’d like to see what the annotations look like for multiple lines.

**Comment by eatyourgreens** [comment]
Why does this have `mark.direction` where other tools have `mark.angle` to indicate rotation angle? Following up on @CKrawczyk's comment, why is the rotation angle measured in discrete steps of 90º?

**Comment by eatyourgreens** [comment]
A more general comment from @rogerhutchings about all tools: pixel coordinates should be rounded to the nearest pixel or 0.1 of a pixel.

**Comment by eatyourgreens** [comment]
>`direction`: a number in degrees to indicate writing direction, with the only possible values being 0 equal to left-to-right, 90 equal to top-to-bottom, 180 equal to right-to-left, and 270 equal to bottom-to-top. 

Sorry, another comment about angles. In #500 I think we've pretty much agreed that angles are measured clockwise in the domain `[-180, 180]`.

**Comment by CKrawczyk** [comment]
@srallen as this is a special type of task I think I like @eatyourgreens suggestion of
```
[
  task: 'T1'
  value: [ line, line, line…]
]
```
better.

For the angle I currently calculate this based on the order of the points `arctan2(y2-y1, x2-x1)` and convert to degrees.  If you want to calculate this on the front-end I have no issues with that, but splitting this value into various groups would not be that helpful as there are many cases of writing at non-typical angles, and I would have to calculate the angle again anyways.


@eatyourgreens Here is an example of what the annotation looks like at the moment for project like ASM:

```
classification = {
    "gold_standard": True,
    "annotations": [
        {
            "task": "T1",
            "task_label": "Mark each line.",
            "value": [
                {
                    "tool": 0,
                    "frame": 0,
                    "closed": True,
                    "points": [
                        {"x": 749.7457275390625, "y": 139.9468231201172},
                        {"x": 1373.24658203125, "y": 128.85250854492188}
                    ],
                    "details": [
                        {"value": "John's Island Sept 18th 1856"}
                    ],
                    "tool_label": "Tool name"
                },
                {
                    "tool": 0,
                    "frame": 0,
                    "closed": True,
                    "points": [
                        {"x": 589.2650756835938, "y": 267.0854797363281},
                        {"x": 908.8545532226562, "y": 260.9980773925781}
                    ],
                    "details": [
                        {"value": "Mr Le Blakes"}
                    ],
                    "tool_label": "Tool name"
                },
                {
                    "tool": 0,
                    "frame": 0,
                    "closed": True,
                    "points": [
                        {"x": 643.07177734375, "y": 308.71209716796875},
                        {"x": 1393.4085693359375, "y": 305.293701171875}
                    ],
                    "details": [
                        {"value": "Dear Sir I have just received"}
                    ],
                    "tool_label": "Tool name"
                },
                {
                    "tool": 0,
                    "frame": 1,
                    "closed": True,
                    "points": [
                        {"x": 587.9367065429688, "y": 131.58277893066406},
                        {"x": 1384.6763916015625, "y": 147.67852783203125}
                    ],
                    "details": [
                        {"value": "know the prospects on the next page"}
                    ],
                    "tool_label": "Tool name"
                },
                {
                    "tool": 0,
                    "frame": 1,
                    "closed": True,
                    "points": [
                        {"x": 600, "y": 0},
                        {"x": 600, "y": 100}
                    ],
                    "details": [
                        {"value": "This is vertical text"}
                    ],
                    "tool_label": "Tool name"
                },
                {
                    "tool": 0,
                    "frame": 1,
                    "closed": True,
                    "points": [
                        {"x": 800, "y": 900},
                        {"x": 800, "y": 900}
                    ],
                    "details": [
                        {"value": "This line has 0 length"}
                    ],
                    "tool_label": "Tool name"
                }
            ]
        }
    ]
}
```

**Comment by eatyourgreens** [comment]
Excellent. I've opened #1369 with a first pass at [the transcription line model] without any subtask annotations (https://github.com/zooniverse/front-end-monorepo/blob/417f3c01dbbc76e9201df34a9b3eda13fe1b5709/packages/lib-classifier/src/plugins/drawingTools/models/marks/TranscriptionLine/TranscriptionLine.js). At the moment it's just `{ x1, y1, x2, y2, closed }` for the start and end point of the line plus the `closed` flag. `closed` will always be true so we can probably remove it.

A full annotation would be an array of transcription line marks, like your example.

**Comment by srallen** [comment]
Ok, we haven't implemented the idea of tracking `direction` or `angle` in the annotation on the front end, yet.

> If you want to calculate this on the front-end I have no issues with that, but splitting this value into various groups would not be that helpful as there are many cases of writing at non-typical angles, and I would have to calculate the angle again anyways.

@CKrawczyk if there's a chance you'd have to re-calculate these values anyway, it seems like it wouldn't be helpful for us to do this on the front-end at all. Perhaps it's best we let the aggregation code handle determining direction and angle of the line? Is there any value of having these in the annotation for other uses, @snblickhan?

**Comment by snblickhan** [comment]
The only potential use case I can think of for having the line angle included for teams who want to use transcription data to train machine learning models for Handwritten Text Recognition. But it may be that those folks are running the aggregation code, anyway? In which case it's maybe a moot point. I'll happily defer to Coleman here.

**Comment by CKrawczyk** [comment]
I am happy to continue doing the direction/angle calculation in aggregation.

**Comment by srallen** [comment]
Ok, so it sounds like this isn't useful right now, but might be in the future. If it becomes clear that it would be in the future, then we can consider implementing at a later time. I think this can now close. Thanks!
