### ISSUE TITLE
Drawing sub-task UI

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1315]
**Package** lib-classifier

The current PFE implementation is like a tool-tip that contains the tasks to be completed fixed to the position of the drawn mark. This can be seen in the dev classifier using the ellipse: https://master.pfe-preview.zooniverse.org/dev/classifier

The fixed position is a hindrance to transcription projects, so in ASM, this changed to be a movable pop-up. 

It's not a modal since neither prevent interaction with the rest of the app, though, the ASM version does not allow you to make new marks until the sub-task pop-up is closed. It does allow you to use the image toolbar (i.e. rotate, zoom, etc). 

The new general classifier version UI, @beckyrother has advised that the sub-task should be based on the ASM version. @wgranger used this library for the UI: https://github.com/bokuweb/react-rnd

In the PR for ADR 20 (https://github.com/zooniverse/front-end-monorepo/pull/1268#discussion_r348332981), @eatyourgreens is asking if instead the sub-task appears in the task area similar to the survey task chosen option. @beckyrother, what are your thoughts?

The transcription task, #1313, will use a drawing sub-task of the same design (unless @beckyrother says otherwise), just preconfigured from the lab to have a text task that can be populated with auto-suggestions.

**Comment by eatyourgreens** [comment]
If it is a popup, then it must be movable from the keyboard. If you do move it, it should probably remember the new position so that you don't have to move it again each time it opens.

Copying the survey task modal behaviour seems like less hassle for the volunteers. There's no risk that the transcription box will obscure the page, and the modal blocks the current task while still allowing you to zoom and pan the subject.

**Comment by eatyourgreens** [comment]
Something I'm noticing with the [ASM text input](https://www.antislaverymanuscripts.org/classify) is that it always covers up the text that I'm trying to transcribe. Volunteers have complained about this on other transcription projects that use popup boxes so I don't want us to repeat that experience in the new transcription task.

That pushes me more towards having the text input appear to the right of the page, in or above the task area. @beckyrother do you have any thoughts about this?

**Comment by beckyrother** [comment]
We chose to place the text box on top of the subject image so it would be near the text when a volunteer is transcribing. The ASM text box can be moved around to show the text below it; that would be my recommendation moving forward.

Here is an InVision prototype: https://projects.invisionapp.com/d/main#/console/12923997/396381419/preview

**Comment by eatyourgreens** [comment]
No problem. I think the trick is going to be calculating the position of the box so that it is near the thing you're describing (eg. a line of text or a cat's face) without obscuring it.

We've used Grommet's [Layer](https://v2.grommet.io/layer) elsewhere in the classifier but I don't know if that can be positioned.

**Comment by eatyourgreens** [comment]
Once #1376 merges, subtasks can be rendered by iterating over `mark.tasks` for a new mark and rendering a `Task` component for each. The UI should not allow the task to be completed until `mark.isComplete` is true.

In the case of transcription, ASM deletes the mark if you submit an empty line of text. That can be achieved in the new classifier with something like `if (!mark.isComplete) tool.deleteMark(mark)`. Maybe we should adopt this as general behaviour for marks with required subtasks?

While the task form is open, values can be stored using `mark.addAnnotation(task, value)`, which works exactly the same as `classifications.addAnnotation(task, value)`.

**Comment by srallen** [comment]
Grommet's Layer is absolutely positioned with a few pre-defined positions for the window area that you can set by props. It's not flexible for use in this case. I think we should investigate the recommended library that ASM used: https://github.com/bokuweb/react-rnd

**Comment by eatyourgreens** [comment]
Requires #1369, #1376 and #1432. Maybe #1434 as well?
