### ISSUE TITLE
Transcription task text task with suggestions UI

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1316]
**Package** lib-classifier

Related to #1271 and #1313, the UI for the transcription task sub-task text input can use Grommet's `TextInput` since it supports out of the box suggestions. Here is the story demonstrating this: https://storybook.grommet.io/?path=/story/textinput--suggestions

The advantage of using this is that it'll pick up the zooniverse theme and be styleable.

An HTML input with a datalist is a possibility, but wouldn't be styeable. 

@eatyourgreens comments in #1268 about long lines of text and the text task implements a textarea to deal with this possibility (see: https://github.com/zooniverse/front-end-monorepo/pull/1268#discussion_r348331539).

ASM leverages the pop-up resizing function for long text rather than use a textarea. @beckyrother do you have a preference on dealing with long lines of text?

**Comment by beckyrother** [comment]
Storybook looks great! It would be better if long text wrapped if possible, like on ASM.

**Comment by eatyourgreens** [comment]
This could maybe extend the `TranscriptionLine` mark model to add suggested transcriptions for each line.

**Comment by beckyrother** [comment]
Here's the transcription task on InVision: https://invis.io/UAN6AP0JTBC#/396381419_90_Text_Transcription

**Comment by beckyrother** [comment]
Previous transcriptions: adding a dropdown + 'previous transcriptions' help text:

https://invis.io/UAN6AP0JTBC#/404084878_91-2_Text_Transcription_Line_Text_Box_Collaborative

**Comment by snblickhan** [comment]
A few questions/suggestions:
1. Can the list of Text Modifiers be above the text entry box, so they aren't covered by the dropdown menu when it's open?
2. Will Project Builders have the option of inserting guidelines/instructions on the text entry popup box (in the space below "TRANSCRIBE LINE" but above the text entry field? Thinking of how the transcription box in ASM includes the following: "Please transcribe all of the words in the line of text. Open the dropdown menu to use previous volunteers' transcriptions as a starting point." Could be worth giving PBs the option to give further instruction in that space?
3. Is it worth considering the option to remove the number required from the tool label in this case? With the exception of structured data, it's likely that in most cases there won't be a known number of lines that need to be transcribed, and I worry that this may confuse volunteers.
4. Will the drag-to-adjust option on the text entry field resize the entire popup, or just the text entry field? (This may be a silly question -- apologies if I'm using incorrect terminology regarding any of these components)

**Comment by beckyrother** [comment]
Thank you @snblickhan ! Updated the InVision links with revisions. To answer your questions:

1. Yes, done.
2. I'd recommend not adding anything additional to that box, being conscious of screen real estate. They'll be able to add directions in the task sidebar, where volunteers will need to look to start. 
3. Yes, done.
4. Yes, the entire box will resize.

**Comment by snblickhan** [comment]
Thanks @beckyrother!! Updates look great. And I think you're right re: the 2nd point, just wanted to flag it up after reviewing ASM. :)

**Comment by srallen** [comment]
@mcbouslog I know there's some multi-frame viewer finishing touches still to do, but could you also start to familiarize yourself with this issue to begin work on it next week?

**Comment by srallen** [comment]
I experimented yesterday with trying out Grommet's `TextInput` with suggestions and ideally this is the function we need except:

- The `TextInput` is not resizable like the text area, so we'd have a change in function between the two text task types
- The `TextInput` has a different API than the `TextArea` so the tag insertion functionality broken when I attempted to use it. I didn't want to spend too much time figuring this out because perhaps this is not the direction we should go.

So, our next options are to try out a HTML datalist or do something like ASM and have buttons render than look like a dropdown next to the text area.

**Comment by srallen** [comment]
I figured out what was going wrong with Grommet's TextInput while playing around with html datalists actually, so I think it'll work still. But the question of being able to resize remains. @beckyrother how important is the resize function of the text area itself?

**Comment by beckyrother** [comment]
Do you mean the actual text itself or the area that it's in? The text should definitely be resized; it would be good if the container could also resize but if it can't be done it's probably okay.

**Comment by srallen** [comment]
@beckyrother the pop up itself is resizable and currently the input is a text area like so: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea (the lower right corner allows resizing of the input itself).

I'm asking how important being able to resize the input itself is because the Grommet suggestions functionality is for a text input, which cannot be individually resized (similar to the HTML text input: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text it does not have the resizability like a text area), but can be given a width or just grow with the pop-up container like ASM does now. 

This is a similar problem with HTML datalist (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) if we went that direction. It only works with an HTML text input element.

So, I'm wondering how important being able to resize the input itself is. If it's important to the UX, then our only option is to render buttons separately that superficially look like a dropdown coming off of the text area somehow (which I think ASM did something like this)

**Comment by beckyrother** [comment]
Ohh I see, thanks. 

Two scenarios: 
1. Text input resizes. Feels natural to resize all of the elements on the page as elements zoom in/out (good). At large sizes, the box runs the risk of partially or completely obscuring the subject (bad). Additional dev time / hacking needed.

2. Text input stays the same. Won't completely cover the subject regardless of the size of the text (good). Large sizes of text may get cut off or be a poor reading experience if the box is too small (bad). 

I'm leaning towards the second, keeping an eye on it and possibly revisiting if needed. Does that work?

**Comment by srallen** [comment]
Thanks @beckyrother! So the default text task (one not used by transcription task with previous transcription like this) will continue to use the resizable text area element, then the transcription task will use a Grommet text input with the suggestions UI that is not resizable. Let's see how this goes and can modify as needed. 

@mcbouslog I have a WIP branch implementing the Grommet TextInput component: https://github.com/zooniverse/front-end-monorepo/tree/text-suggestions
It still needs some work with specs. It doesn't have a story or a test project yet, so just trying to get it working in spec only right now.

**Comment by srallen** [comment]
UI is implemented.
