### ISSUE TITLE
Classifier: move survey tool marks underneath video speed controls

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/front-end-monorepo#1342]
**Package**
From [Battling Birds](https://www.zooniverse.org/projects/canagica/battling-birds/classify)

**Is your feature request related to a problem? Please describe.**
Video speed controls are obscured when survey task items have been selected:
![image](https://user-images.githubusercontent.com/1392130/69979036-23e46300-14f3-11ea-8049-309f9d1f33c9.png)

![image](https://user-images.githubusercontent.com/1392130/69979110-4a0a0300-14f3-11ea-9f36-b1ff035357dd.png)

**Describe the solution you'd like**
Move selected survey task items to below the video speed controls

**Additional context**
From Freshdesk: https://zooniverse.freshdesk.com/a/tickets/1723

**Comment by srallen** [comment]
I think this is an issue for PFE. The survey task implemented in the new classifier will track selections in the task area. Designs here: https://projects.invisionapp.com/d/main#/console/12923997/270495286/preview

Closing for now since I don't think we have bandwidth to solve the PFE design issue.
