### ISSUE TITLE
Image subject viewer renders subjects differently in Chrome

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1343]
**Package** lib-classifier

**Describe the bug**
Image subjects render differently between browsers. Chrome specifically is different from the rest (see the screenshot comparisons)

**To Reproduce**
1. Go to http://local.zooniverse.org:3000/projects/srallen086/untitled-project-5-10-2018-11-53-20-am-yep/classify?env=staging in multiple browsers and try to load up the same subject (there's only a few, so should be possible)

**Expected behavior**
Image rendering is consistent between browsers

**Screenshots**
Firefox 70:
<img width="914" alt="Screen Shot 2019-12-02 at 11 32 02 AM" src="https://user-images.githubusercontent.com/5016731/69981317-bd157880-14f7-11ea-9552-ba7a20fcfe15.png">

Safari 13:
<img width="908" alt="Screen Shot 2019-12-02 at 11 40 07 AM" src="https://user-images.githubusercontent.com/5016731/69981772-99066700-14f8-11ea-8cc0-7ff5d903631f.png">

Edge 18:
<img width="732" alt="Screen Shot 2019-12-02 at 11 40 15 AM" src="https://user-images.githubusercontent.com/5016731/69981783-a02d7500-14f8-11ea-8321-ebb84cd475a0.png">

Chrome 78:
<img width="922" alt="Screen Shot 2019-12-02 at 11 31 55 AM" src="https://user-images.githubusercontent.com/5016731/69981332-c3a3f000-14f7-11ea-8d18-81cad2645af9.png">

**Comment by eatyourgreens** [comment]
Chrome might be fixed by styling the image with `width: 100%` but I don't know if that's the correct style, or if the height should be styled so that the subject is always visible without scrolling.

**Comment by eatyourgreens** [comment]
We can also use [`preserveAspectRatio`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAspectRatio) to provide a hint to the browser as to how to render images when their aspect ratio differs from the aspect ratio of the subject viewer.

**Comment by eatyourgreens** [comment]
This was fixed by adding a container `div` in #1388 but the subject viewer is now way too tall, in all browsers, for portrait images. Here's Chrome:
![I Fancy Cats showing a portrait image of a cat which is much taller than the viewport height.](https://user-images.githubusercontent.com/59547/72066970-cc979680-32d9-11ea-83d7-a65d5d47f89e.png)

**Comment by eatyourgreens** [comment]
Note, that screenshot was the dev classifier. The classify page might restrict the maximum height of the classifier component so that it doesn't extend out of the viewport.

**Comment by srallen** [comment]
The height of the viewer is a separate issue, so closing this.
