### ISSUE TITLE
ZoomingScatterPlot tests run slow

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1346]
**Package**
lib-classifier

**Describe the bug**
Running `yarn test` for the classifier, the `ZoomingScatterPlot` tests take between .5s and 1s per test, and flag up performance warnings in the test output.

**Comment by srallen** [comment]
Because of the way vx works with its `Zoom` component, I have to use enzyme's mount which is what is slowing the tests down. I don't have a good solution at the moment.

**Comment by srallen** [comment]
Sometimes there may be a test failure possibly due to slow running tests?

See: https://github.com/zooniverse/front-end-monorepo/pull/1496#issuecomment-584037191

**Comment by camallen** [comment]
I've seen these slow tests cause CI failure due to timeouts, https://github.com/zooniverse/front-end-monorepo/pull/2309/checks?check_run_id=3087781888#step:11:850
