### ISSUE TITLE
Transcription line drawing tool

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1349]
**Package** lib-classifier

This is related to implementing the transcription task (#1313) (Also see [ADR 20](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-20.md). The standard line tool has been identified as not having exactly the UI nor drawing interaction that is desired for transcription task. This variant of the line drawing tool for transcription will instead:

- Be drawn by two clicking actions for the start point and the end point
-  Have a visual indication of which point is the starting point and which is the end

Associated [user stories](https://docs.google.com/document/d/16abI-wkRlEXsWgACfFQVqwO76aEopohIjQiRfNQKWiw/edit)

> As a user I want to click at the beginning of a line of text and see an open circle icon indicating the start of the line.

> As a user I want to see a line connecting the first circle I created to my pointer so I can keep track of which line I’m transcribing.

> As a user I want to click at the end of a line of text and see a closed circle indicating the end of the line.

> As a user I want to see the line connecting the start and end of the line of text I’m planning to transcribe.

**Comment by eatyourgreens** [comment]
Noting that the initial drawing gesture to create a mark is pointer down -> move -> up so you can't create a line from two pointer down events.
https://github.com/zooniverse/front-end-monorepo/blob/28fe4cdddb445a567e99d68b3997fb4b41ce58f3/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js#L39-L59

**Comment by srallen** [comment]
This is the requirement for the tool. That code will have to be refactored if necessary.

**Comment by eatyourgreens** [comment]
Sure. I just wanted to flag this up so that whoever works on the front-end for the transcription task knows that it needs to be done.

I'm don't think a refactor will work. I think public behaviour will have to be rewritten, maybe by flagging mark creation in-progress in the store, until mark creation is complete. PFE does this by adding an `_inProgress` property to new marks, although it also ties that flag to pointer down and pointer up events. https://github.com/zooniverse/Panoptes-Front-End/blob/abab2b0115231dc34fd824f70f46a0c372b3043e/app/classifier/drawing-tools/line.cjsx#L24-L32

**Comment by beckyrother** [comment]
InVision link: https://projects.invisionapp.com/d/main#/console/12923997/396381419/preview

Note that this also illustrates what happens with a very tall subject: both the task box AND the toolbar should stay within the viewport whenever possible, so they should be the same height and be sticky, staying visible as the page is scrolled down. This is to make sure the Field Guide button always stays on screen.

**Comment by eatyourgreens** [comment]
The user stories describe the polygon drawing tool, so let’s use that rather than hacking the line tool.

**Comment by srallen** [comment]
I don't think we should hack the line tool, nor do I think we should hack the polygon tool. This is going to be a distinct tool that renders a line using two clicks. The use of the polygon in ASM is legacy due to restrictions of the downstream aggregation at the time as discussed in the PR for the ADR. There's no reason to be bound by the restriction now. FWIW, the user stories haven't been updated since the ADR discussion.

**Comment by eatyourgreens** [comment]
I'm not thinking of hacking anything. I do think we need the Polygon model in order to get the interactions described in the user stories here.

**Comment by eatyourgreens** [comment]
Implemented in #1369, including tests for the user stories.
