### ISSUE TITLE
Documenting the drawing tools API

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1350]
The DrawingTask folder in plugins should have a readme that describes the tool and task API. [ADR 15](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-15.md) should be updated with notes on how the actual implementation works compared to the decision.

**Comment by srallen** [comment]
This might be an opportunity to try JSDoc

**Comment by eatyourgreens** [comment]
We'll need a few more drawing tools copied over from PFE before we have a generic drawing API.

**Comment by srallen** [comment]
I think a proposal ADR with a sketched out API should be written so that we can choose ahead of time what we want to be similar or different from PFE rather than copy PFE and then document it after the fact. I'm concerned about accidentally painting ourselves into a corner with a copy/paste approach.

**Comment by eatyourgreens** [comment]
In that case, maybe a spec rather than an API?

**Comment by eatyourgreens** [comment]
I'll be a lot happier with the drawing code once we've got the ellipse tool (for shapes that can be rotated) and the polygon tool (for shapes that can be created by any pointer gesture, not just swipe.)

**Comment by eatyourgreens** [comment]
Ideally, the issues for individual tools should be updated with specs for those tools too, or would that be too heavy-handed? That could be:
- the interaction that creates a mark.
- the interactions that modify a mark.
- the expected shape/format of the mark data for aggregation.

**Comment by srallen** [comment]
Those are good ideas for specs, but that's not what I'm requesting here. Why not update ADR 15 with notes on the actual implementation and add a readme in the drawing task folder? I don't see a reason why that can't or shouldn't happen now or while code is being written. 

The drawing tool models and the changes happening with those deserve its own ADR too.

**Comment by eatyourgreens** [comment]
We totally need documentation for all our models, even if it's just an overview of the classifier state tree to start with.

ADR 15 said we'd add an interaction layer to edit marks for the current marking task/annotation and render other marks separately. That's what's been implemented but I'm not sure that the naming is very clear. I find it confusing, to be honest. https://github.com/zooniverse/front-end-monorepo/blob/c925ed75f32734f3be6823b89739914c344725a8/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js#L34-L76

The drawing task component, like all the task components, renders the task in the task area on the right so isn't really covered by that ADR. We can certainly add a readme and story to the tasks section of the storybook.

**Comment by eatyourgreens** [comment]
Actually, we should record that we ditched rxjs.
