### ISSUE TITLE
Add Donate and Highlights About Pages

### ISSUE THREAD

**Issue by wgranger** [zooniverse/front-end-monorepo#1353]
**Package**
app-content-pages

**Describe the solution you'd like**
With the addition of the [donate](https://github.com/zooniverse/Panoptes-Front-End/blob/fd1be592493867aae0b809a3a53fcd576885defc/app/pages/about/donate.jsx) and [highlights](https://github.com/zooniverse/Panoptes-Front-End/blob/fd1be592493867aae0b809a3a53fcd576885defc/app/pages/about/highlights.jsx) about pages to PFE, we need to add this same info into the Monorepo. Content will need to be added into Contentful with the layout for the pages added into the `app-content-pages` repo.

**Additional context**
Content for these pages can be found in the [donate](https://github.com/zooniverse/Panoptes-Front-End/blob/fd1be592493867aae0b809a3a53fcd576885defc/app/locales/en.js#L698) and [highlights](https://github.com/zooniverse/Panoptes-Front-End/blob/fd1be592493867aae0b809a3a53fcd576885defc/app/locales/en.js#L686) locales.

**Comment by goplayoutside3** [comment]
Figma design: https://www.figma.com/file/zN9InDg8CTk2vnWp406moK/About-Pages

**Comment by seanmiller26** [comment]
These standalone pages have been rearranged in the new FEM design. Donate has been moved to the Get Involved section, and Highlights has been merged into the main About page. See the Figma designs for details
