### ISSUE TITLE
Implement the PrimaryButton component

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1362]
cc #1248, #1354 

Following on from #1257, the new `PrimaryButton` component needs to be implemented across the codebase.

- [ ] Remove [the existing `GoldButton` component](https://github.com/zooniverse/front-end-monorepo/tree/master/packages/lib-react-components/src/GoldButton) from `lib-react-components`
- [ ] Remove custom primary buttons from the project app and replace with `PrimaryButton`
- [ ] Remove custom primary buttons from the classifier and replace with `PrimaryButton`

**Comment by srallen** [comment]
I think this is done.
