### ISSUE TITLE
Change the API hosts this app talks to at runtime

### ISSUE THREAD

**Issue by camallen** [zooniverse/front-end-monorepo#1378]
As reported at https://www.zooniverse.org/talk/13/1158150?comment=1957693 - my understanding of how the rebuild apps allow runtime API host configurations was wrong. 

When i specify a URL like https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess?panoptes-api-host=https://localhost:3000 i expect the underlying code to respect this override for all API data requests. As it stands this code base will ignore these query param directives and only reflect on the `?env=` param. 

However auth and token flows still use the older `panoptes-javascript-client` client so do respect those directes, thus leaving my app talking to multiple different API hosts :(

Ideally this application allow runtime app behaviour changes like the old `panoptes-javascript-client` codebase did using query params. My use case is when i want to locally test API changes in development or spin up a standalone UI / API and make them talk to each other. 

Is adding this feature viable?

Related code links - https://github.com/zooniverse/front-end-monorepo/blob/de130a4590690aed5f643697f97ccfb8b1e54c9e/packages/lib-panoptes-js/src/config.js#L55

**Comment by srallen** [comment]
I believe the proposed [ADR 21](https://github.com/zooniverse/front-end-monorepo/pull/1361) is relevant to this discussion. 

One of the proposals:
> The [existing config](https://github.com/zooniverse/panoptes-javascript-client/blob/master/lib/config.js) will be turned into a separate package. Config settings can be imported wholesale from that for convenience.

**Comment by rogerhutchings** [comment]
I also said I wouldn't be supporting query strings in the lib, but they can supported in the consuming app. I don't like the amount of magic the existing client does

**Comment by camallen** [comment]
> I also said I wouldn't be supporting query strings in the lib, but they can supported in the consuming app. I don't like the amount of magic the existing client does

Does this mean that i could consistently modify the API targets, etc in consuming apps / underlying libraries?

**Comment by rogerhutchings** [comment]
It would - you couldn't with the old auth client in an SSR environment because you couldn't pass in query params directly, the client got them itself through the `window` object (which doesn't exist in Node). I could add a helper on the new client to simplify this
