### ISSUE TITLE
Project builder can configure a default frame for display via the subject metadata.

### ISSUE THREAD

**Issue by simensta** [zooniverse/front-end-monorepo#1395]
Time Estimate: Jan 24

**Comment by srallen** [comment]
Is this in the user stories for the subject viewer?

**Comment by srallen** [comment]
I'm going to put this in the 'nice to have' category. Most of the lab updates for the new tools have been put off unfortunately.

**Comment by eatyourgreens** [comment]
Etch-A-Cell is already using this in PFE. Was this issue to make sure we copy that metadata flag across to the classifier models?

**Comment by goplayoutside3** [comment]
Missing description. I'm going to assume this was to implement a config in the lab for project teams to choose a default frame in subject viewers like the multi frame viewer and flipbook. That config does exist.
