### ISSUE TITLE
Subject Viewer is rendering with previous Classification's Drawing Task marks

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#1411]
## UI Bug

Package: lib-classifier

Follows #1407 and #1409 

On a project featuring a workflow with _a single Drawing Task,_ the Subject Viewer of the Classifier UI visually retains the drawn marks of the previous Classification.

Tested on macOS 10 + Chrome 79

### Details

In this example, I'm using the Classifier to view a sample project (http://localhost:8080/?env=staging&project=1895) with only 1x drawing task. (A Point tool)

![Screen Shot 2020-01-14 at 15 55 53](https://user-images.githubusercontent.com/13952701/72360548-fab91400-36e7-11ea-98a9-ffa976cb2182.png)

I receive the 1st Subject, and proceed to make 3x Point marks on the Elephant.

Note that there are 3x Point marks on the _Subject Viewer,_ and the _Task Area_ also indicates that 3x Points were drawn.

I now click Submit.

![Screen Shot 2020-01-14 at 15 56 05](https://user-images.githubusercontent.com/13952701/72360639-20deb400-36e8-11ea-8d01-592551563e54.png)

When the 2nd Subject loads, I still see the 3x Point marks on the _Subject Viewer._ These 3x Point marks persisted from the Classifications from the previous Subject.

The _Task Area,_ however, correctly shows that the number of marks in the Classification is currently 0.

**Follow up:**

- If I immediately click Submit, the Classification will be sent to the API with 0 annotations. (This is correct, because I haven't added any marks for the 2nd Subject)
- If I instead try to add a new Point mark, the previous 3x Point marks will disappear, and my new Point mark will appear.
- If I instead try to click on/interact with one of the previous 3x Point marks, the whole webpage will crash to a white page, with error message: `Uncaught Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type: 'Point', Path upon death: '/workflowSteps/steps/S0/tasks/0/tools/0/marks/ck5e276p100013h5w9w6dnkqy', Subpath: 'id', Action: ''). Either detach nodes first, or don't use objects after removing / replacing them in the tree.` 

### Status

 ⚠️ This is a serious UI bug that can affect scientific classifications.

**Comment by shaunanoordin** [comment]
I may have a lead on where the Drawing Task on the _Subject Viewer_ borks on 'workflow with 1x drawing task' scenarios.

My method involves:

- observing when the InteractionLayer component (`...SubjectViewer/components/InteractionLayer/InteractionLayer.js`) renders.
- observing when the DrawingTask model (`...tasks/DrawingTasks/models/DrawingTask.js`) resets.

My hypothesis is that:

1. `DrawingTask.reset()` is called when a new Subject loads, and _should_ remove all the marks in the store, AND all the visible marks on the Subject Viewer.
2. However, something is wonky with the precedence of rendering/reset actions, or the InteractionLayer component simply isn't listening to changes when the `reset()` triggers.

Note: in the next section, when I talk about **'0 marks'** or whatever, I'm talking about the marks rendered here...

```
function InteractionLayer ({ activeDrawingTask, activeTool, disabled, height, move, scale, width }) {
  return (
    <g
      ...
    >
      <StyledRect
        ...
      />
      {activeDrawingTask &&
        activeDrawingTask.tools.map(tool => {
          return (
            <DrawingToolMarks
              ...
              marks={Array.from(tool.marks.values())}  // <-- these marks here!
              ...
            />
          )
        })
      }
    </g>
  )
}
```

### Testing

- Action: On the `lib-classifier` package, I load a Project with a Workflow that only has 1x simple Drawing Task (Point tool) - e.g. http://localhost:8080/?env=staging&project=1895
  - Observation: Classifier loads 1st Subject
  - `InteractionLayer` component renders (thrice) with **0 marks**
  - `DrawingTask.reset()` is triggered
  - `DrawingTask.start()` is triggered
- Action: with the Point tool selected, I click on the Subject Viewer.
  - Observation: 1 visible Point mark is placed on the Subject image.
  - `InteractionLayer` component renders (twice) with **1 mark**
- Action: I click the Submit (Done) button.
  - Observation: Classification is submitted to the API with 1 annotation. Classifier loads 2nd Subject, but the previous draw mark is still visible on the Subject Viewer.
  - `InteractionLayer` component renders (thrice) with **1 mark** ⚠️ (Expected: this should be 0 marks!)
  - `DrawingTask.reset()` is triggered ❓ (Expected: shouldn't a new InteractionLayer.render trigger when the data is reset?)
  - `DrawingTask.start()` is triggered

**Comment by eatyourgreens** [comment]
I used to have code in `DrawingTask.start()` which reset the view if the current annotation is empty. That would explain why this bug wasn't seen before. The subject viewer is disconnected from the store somewhere, which implies a missing `observer` somewhere.

**Comment by eatyourgreens** [comment]
Or, of course, I could have just made the current task's marks observable in the first place. A fix will be up shortly.

**Comment by eatyourgreens** [comment]
As a side note, marks are still rendering way too large, despite the fix PR having been opened almost a week ago.
![A cat with oversized SVG points and lines drawn on top of it.](https://user-images.githubusercontent.com/59547/72435081-22b28100-3795-11ea-8605-60510b677b7d.png)
