### ISSUE TITLE
[RFC] ADR process

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1423]
There's been discussion on the ADR process and we should evaluate how it's been going, what work works, what doesn't, and any other concerns. This RFC is to centralize a single point for discussion.

**Comment by camallen** [comment]
I think it’s fair to have relevant, in person / slack / emails discussions documented as ADRs as we adopt features into the codebase. 

As long as the ADR processes isn’t blocking folks delivery of features. Remembering that we are a small team working somewhat independently and folks will make choices along the way as they ‘discover’ the system they are building and it might be that going through the ADR processes before implementation might hinder our team. 

I do agree that implementation choices and tradeoffs should be documented as a record as features are accepted into the codebase.

On the flip side  experiments / hacking / playful work should be blocked by an ADR at all, they should only come into play when a team member gets serious about changing the architecture of an app.

**Comment by srallen** [comment]
> As long as the ADR processes isn’t blocking folks delivery of features. Remembering that we are a small team working somewhat independently and folks will make choices along the way as they ‘discover’ the system they are building and it might be that going through the ADR processes before implementation might hinder our team.

I don't think this is actually happening though. Do we have an actual example of hinderance? Or is this just a precautionary concern?

I generally think the process should be RFC > ADR, if we aren't sure on a decision, then it could be, RFC > experiment > proposal ADR > experiment > revised ADR and this has already happened when Rog and I experimented with SSR rendering frameworks finally settling on Next.js. 

Many of the ADRs we *are* fairly sure of because we already know what hasn't been working from PFE and have a reasonable idea of how to go forward. In these cases the initial RFC might be skipped and just go straight into a proposal ADR.

**Comment by srallen** [comment]
Spotify Labs has a really nice article on RFC --> ADR processes especially a helpful guide on using them even for smaller decisions: https://labs.spotify.com/2020/04/14/when-should-i-write-an-architecture-decision-record/

I think what will help us is is to define our own impact assessment and decision flow of when to use RFCs and ADRs?
