### ISSUE TITLE
[RFC] Performance enhancements and tools

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1424]
I've renamed the issue to capture a larger discussion about performance improvements and tools we could use.

Option: Preact
Preact is an alternative to React that is compatible with its API. The motivation for trying it out would be to see if it has any impact on bundle sizes.

Option: size-limit
https://github.com/ai/size-limit
CI tool for limiting bundle size impacts on PR

Option: why-did-you-render
https://github.com/welldone-software/why-did-you-render#readme
Hook for React to investigate unnecessary re-renders

**Comment by srallen** [comment]
State of JS survey shows an adoption rate of 10% in the JS community: https://2019.stateofjs.com/front-end-frameworks/

**Comment by srallen** [comment]
This utility could be helpful to determine what is contributing to the large bundle size: https://github.com/zeit/next.js/tree/canary/packages/next-bundle-analyzer

**Comment by eatyourgreens** [comment]
That will help with the NextJS apps, but I don't think it will tell us why the classifier is so big.

**Comment by eatyourgreens** [comment]
A quick snapshot of bundle sizes in the classifier.
![Output of webpack bundle analyzer for the classifier library.](https://user-images.githubusercontent.com/59547/72693192-a79bf280-3b27-11ea-9e36-166f51dad4ae.png)

**Comment by eatyourgreens** [comment]
Here are the relative client bundle sizes in `app-project`. (Total bundle size is ~2.7MB.)
![Client bundle sizes showing that lib-classifier, lib-react-components and grommet-icons are the largest contributors to bundle size.](https://user-images.githubusercontent.com/59547/72712527-206c7000-3b63-11ea-84d5-e4cc3f9c3bbd.png)

**Comment by eatyourgreens** [comment]
You can try out preact in https://github.com/zooniverse/pandora/pull/153. `vendor.js` is still pretty massive. `main.js` is tiny.

**Comment by srallen** [comment]
What utility is that?

**Comment by eatyourgreens** [comment]
The webpack bundle analyzer.
