### ISSUE TITLE
[VSLCV] Axis inversion for composite viewer

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1425]
**Package** lib-classifier

**Describe the solution you'd like**

The composite subject viewer needs a button that triggers the inversion of the y-axis. This will make the calculations and pass down the updated data via props to the scatter plot. 

Time estimate: 1 week

**Additional context**

Design: https://projects.invisionapp.com/d/main#/console/17294981/360635448/inspect

**Comment by srallen** [comment]
@beckyrother could I get the "up down" for the button as an SVG asset? The inspector in invision shows it as from a typeface. If I can get it as an SVG, I can render it as an icon in the button. Thanks!

**Comment by beckyrother** [comment]
Here you go!
[ic-flip.svg.zip](https://github.com/zooniverse/front-end-monorepo/files/4130546/ic-flip.svg.zip)
