### ISSUE TITLE
Source maps aren't published for the classifier

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1438]
**Package**
lib-classifier

**Describe the bug**
Running a production build of the project app, with the dev tools open, the classifier source map is not being loaded. Errors inside the classifier are always reported as happening on classifier line 1.
![Classifier stack trace for Galaxy Zoo, showing that errors are not mapped back to the classifier source code.](https://user-images.githubusercontent.com/59547/72782942-0abb8100-3c1d-11ea-81a0-d4a6350b4363.png)

**To Reproduce**
Build a copy of the classifier that deliberately errors, then browse to the Classify page in a production build of the project app (`yarn build && yarn start`.)

**Expected behavior**
I'm not sure what the expected behaviour is but shouldn't the source map be published alongside the classifier JS?

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome & Firefox
 - Version: latest

**Additional context**
The classifier source map is present in `packages/lib-classifier/dist/main.map.js` after the classifier is built. The project app is loading the classifier from `packages/lib-classifier/dist/main.js`.

**Comment by srallen** [comment]
The source map URL is present in the main.js build for the classifier, but I think they may be getting stripped once next.js builds the app. There's a related issue: https://github.com/zeit/next-plugins/issues/309#issuecomment-561614663

Following the chat in the thread, I think we need to enable source maps in next.config.js, likely following the suggested setup.

Resolving this might resolve our issue with getting error logs sending to sentry (or at least help toward resolving that).

**Comment by eatyourgreens** [comment]
First thing to check: does that source map URL resolve or are we catching it with our router set-up and 404'ing?

**Comment by eatyourgreens** [comment]
Good point about checking if NextJS modifies `main.js` when it bundles the classifier but that linked issue seems to be about source maps for the Node app. If you want Sentry logging for the NextJS app, I think you'll need to [upload the `app-project` source maps to Sentry](https://blog.sentry.io/2019/02/20/debug-node-source-maps).

**Comment by srallen** [comment]
I think we can continue debugging and discussing in an issue. Can we close this?

**Comment by goplayoutside3** [comment]
Closing this because you can see error source maps in dev mode locally.
