### ISSUE TITLE
[VSLCV] Scatter plot legend for series data

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1441]
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**

The scatter plot doesn't have a legend that labels what the data series is. We have support for axes labels, but having a UI for a legend for what the series is may be helpful, particularly when there are multiple series being rendered. 

**Describe the solution you'd like**

Some kind of legend UI displaying perhaps the symbol next to a label (i.e. red circle next to a text label like "red spectra", blue cross next to its text label, etc). Visual real estate is potentially an issue for this, so maybe it can be collapsed / expandable as needed?

**Comment by beckyrother** [comment]
Added a legend for the entire data set, since each of the graphs show red and blue data:
![image](https://user-images.githubusercontent.com/1392130/73484819-9e045d00-4367-11ea-9121-17c3f9ac3c17.png)

**Comment by srallen** [comment]
This has been integrated into the focus toggles design, closing in favor of #1429
