### ISSUE TITLE
[VSLCV] Composite viewer needs separate zoom function for each scatter plot

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1442]
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**
The sidebar zoom tools work great when it's just a single image or you assume all of the displayed images want to zoom simultaneously. For the scatter plot, again, if it is just a single scatter plot, the sidebar tools can be wired up and work. The variable star viewer will have two scatter plots that need to be able to zoom independently.

**Describe the solution you'd like**
We discussed leveraging click focus (mouse click or tab and enter or space) for each scatter plot first to be able to enable the zoom side toolbar for that specific scatter plot. The UI should have some kind of discoverability to enable this state and then UI to indicate focus on that scatter plot (maybe outline like other focus UI?). 

**Describe alternatives you've considered**
We discussed having both plots both zoom at the same time, but this is not viable for the variable star project. We discussed implementing brush zoom, but it will be confusing for volunteers to have two different zoom functions between different scatter plot instances (i.e. TESS). 

**Additional context**

**Comment by eatyourgreens** [comment]
Focus selection sounds like a good way to set the active viewer. I think the viewer UI store allows a viewer to register itself with the zoom controls, so this could be as straightforward as having each individual viewer component registering itself as the current target of the toolbar when it receives focus.

Space Warps has a requirement to zoom multiple side-by-side subject frames at the same time, so we should be flexible in the code design for this.

**Comment by srallen** [comment]
Noting that the zoom code for the scatter plot and the toolbar still needs wiring up to work with keyboard controls.

**Comment by eatyourgreens** [comment]
There's the [`withKeyZoom`](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js) decorator for that. `SingleImageViewer` and the TESS light curve viewer both use it, so you can look at those for usage examples.

**Comment by beckyrother** [comment]
Display a focus box around the graph to be zoomed in:
![image](https://user-images.githubusercontent.com/1392130/73483800-b2dff100-4365-11ea-82f8-e31c95ac2b21.png)

InVision link: https://projects.invisionapp.com/d/main#/console/17294981/403043950/preview
