### ISSUE TITLE
Drawing: saving and retrieving classifications to/from Panoptes

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1443]
**Package**
lib-classifier

As per [ADR-25](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-25.md#annotation-json-structure-1) we will need to transform classifications into a format that is useful to Panoptes and Caesar before making the POST request.

The transformation will be:

  1. `classification.annotations` is converted from a map to an array.
  2. For each drawing task in the `annotations` array, we loop through each `mark` in `annotation.value`. For each  `mark`:
    1. For each `annotation` in `mark.annotations`:
       1. Add `markIndex` to the annotation.
       2. Add the annotation to `classification.annotations`.
       3. Add an array item to `mark details` consisting of the annotation task key: `{ task }`.
   2. Delete `mark.annotations`.
   3. Delete any private (underscored) mark properties.

On retrieving an incomplete classification from Panoptes, we will need to reverse the above transformation in order to construct a Classification model, with Annotations, from the API response JSON.

In the short term, this transformation can be handled by the `classifications.completeClassification` action. Longer term, should we consider building an adapter  that sits between the classifier and Panoptes, and can convert classifications to and from API responses?

Time estimate: 1 week

**Comment by srallen** [comment]
> classification.annotations is converted from a map to an array.

MST has a built-in feature if you use `toJS` that will remove the observables and convert maps to objects. There is a parameter to disable that and when you do, those data types stay maps. We disable the conversion to objects because maps can be converted to objects *or* to an array of pairs. The latter is sometimes preferable if you need to maintain an ordered structure. For classification annotations, we call `toJS` with the option to convert to an object disabled since the order is important:

https://github.com/zooniverse/front-end-monorepo/blob/29463a6f52e2f321fb6200aca118242ca5519099/packages/lib-classifier/src/store/ClassificationStore.js#L177

Then we manually convert it to an array of the map's values

https://github.com/zooniverse/front-end-monorepo/blob/29463a6f52e2f321fb6200aca118242ca5519099/packages/lib-classifier/src/store/ClassificationStore.js#L179

The utility function: https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/store/utils/convertMapToArray.js

So point number one in the list is already done.

> Add an array item to mark details consisting of the annotation task key and the mark index: { task, markIndex }

This is different from the proposal, so it'd be good to get that feedback where I asked if using `markIndex` was satisfactory: https://github.com/zooniverse/front-end-monorepo/pull/1397#discussion_r367640788 and then get this noted in the example. 

> Delete any private (underscored) mark properties.

Are there any properties that can be volatile state instead of underscored and removed at this point?

> In the short term, this transformation can be handled by the classifications.completeClassification action. Longer term, should we consider building an adapter that sits between the classifier and Panoptes, and can convert classifications to and from API responses?

I'd be for an adapter 👍

**Comment by eatyourgreens** [comment]
>This is different from the proposal, so it'd be good to get that feedback where I asked if using markIndex was satisfactory: #1397 (comment) and then get this noted in the example.

That's a mistake on my part. Do feel free to edit the text here so that it matches what's required.

>Are there any properties that can be volatile state instead of underscored and removed at this point?

Volatile properties should be removed by MST, I think. That might depend on how we clone the marks. Volatile properties aren't copied to snapshots. Beyond that, I'm not sure.

**Comment by eatyourgreens** [comment]
Did we ever write up a proposal to change the project builder and store drawing sub-task definitions in `workflow.tasks` with the other tasks?

**Comment by eatyourgreens** [comment]
Since step 1. is already done, the first step in writing an adapter would just be to copy that code across.

**Comment by srallen** [comment]
> Did we ever write up a proposal to change the project builder and store drawing sub-task definitions in workflow.tasks with the other tasks?

No. There are several ADRs that just note in the consequences section that the lab will need to be updated. Precisely what that is for each change hasn't been done because we don't have any allocated time to work on the lab. Becky is working on some early prototype designs for editing steps though.

**Comment by eatyourgreens** [comment]
> So point number one in the list is already done.

This is done for classifications but should be generalised to the [`AnnotationStore`](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/store/AnnotationsStore.js) model ie. classifications and marks.

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/front-end-monorepo/blob/41dcdc82db2a43beeac2ab25c2dd4fdd15545daf/packages/lib-classifier/src/store/ClassificationStore.js#L178

`classification.id` shouldn't be deleted if we're updating an existing classification in Panoptes eg. an incomplete transcription.

**Comment by srallen** [comment]
> classification.id shouldn't be deleted if we're updating an existing classification in Panoptes eg. an incomplete transcription.

Incomplete classifications that are loaded and then sent again won't be POSTed, so we'll be writing new logic to PUT classifications, in which as you say, the id won't be removed because it's the classification's actual id. Several other changes in that action, like the `finished_at` timestamp being added, should likely be pulled out into their own actions so the completion for POSTing versus PUTing can be differentiated.

**Comment by eatyourgreens** [comment]
I've been playing around with snapshot processors to handle this eg.
```
panoptesSnapshot -> preProcessor -> classifierSnapshot -> Model.create()
getSnapshot(model) -> classifierSnapshot -> postProcessor -> panoptesSnapshot
```

But then I read this and I wonder if each model (`Classification`, `DrawingAnnotation`, `Mark`) shouldn't have a view that returns a snapshot formatted for Panoptes.
>…consider whether you shouldn't be using a dedicated a view instead to normalize your snapshot to some other format you need.

https://www.npmjs.com/package/mobx-state-tree#lifecycle-hooks-for-typesmodel

**Comment by eatyourgreens** [comment]
`getSnapshot(classification)` might be a dead-end since [references are not resolved in snapshots](https://spectrum.chat/mobx-state-tree/general/getsnapshot-with-reference-field~43a6e2d2-9655-4571-b599-9cac4ee9c94d).

ie. `drawingTaskAnnotation.value` serialises as an array of Mark IDs, not an array of Marks.

**Comment by eatyourgreens** [comment]
I've made a start on this using snapshots (7ddb4d1062cf2dff57a021dae4280ea79e4fb24d) but I'm not sure whether to continue with that or drop it and start again from scratch.

**Comment by eatyourgreens** [comment]
>Incomplete classifications that are loaded and then sent again won't be POSTed, so we'll be writing new logic to PUT classifications, in which as you say, the id won't be removed because it's the classification's actual id. Several other changes in that action, like the finished_at timestamp being added, should likely be pulled out into their own actions so the completion for POSTing versus PUTing can be differentiated.

I'm not following this. I'll GET an incomplete classification from Panoptes, complete it (adding the `finished_at` timestamp, new annotations etc.) then PUT it back to the API. The `completeClassification` action is the same as if I'd completed a completely new classification. Only the save action is different.

**Comment by srallen** [comment]
Sorry, meant the line `classification.completed = true` if the classification is still incomplete. `finished_at` doesn't really make sense to add if the classification is still incomplete to me too. How does ASM submit incomplete classifications? Do we know the only difference is the HTTP verb?

**Comment by eatyourgreens** [comment]
That's a really good question. Maybe they have a `classification.save()` which is different from `classification.complete()`?

On complete, we'll need to check if the ID is a temp ID before deleting it. Maybe add a string to it that flags it as a temporary ID?

For initial testing are we going to require that transcriptions are completed in a single browser session? Loading an incomplete classification and initialising the store from it shouldn't be too hard, but it seems like a reasonable chunk of work.

**Comment by eatyourgreens** [comment]
From memory, the Panoptes client that ASM (and PFE) use looks to see if a resource has an ID. If `resource.id` exists, `resource.save()` uses PUT. If it doesn't, `resource.save()` uses POST.

**Comment by srallen** [comment]
Could `toJS` be used instead of snapshots?

@shaunanoordin or @wgranger do you have any notes or pointers on how ASM handles incomplete Panoptes classifications?

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/front-end-monorepo/pull/1475 serialises and flattens `classifications.annotations` before it is saved to Panoptes.

>Could toJS be used instead of snapshots?
All the reading I've been doing suggests that snapshot processors and custom views are the way to go when manipulating data for use by external systems. My understanding is that `getSnapshot` will always give you a snapshot of the classification after any pending transactions are complete but `toJS` may give you a snapshot of the model while it is still changing state.

**Comment by srallen** [comment]
@eatyourgreens is there anything left to do for this? I think possibly item 4 from the original list? I'm not sure though.

**Comment by eatyourgreens** [comment]
After talking to @shaunanoordin it turns out ASM saves work in progress to local storage. Loading incomplete classifications turned out to be a much bigger problem. 

Maybe close this with a note somewhere about persisting state for long transcription sessions? I suspect we’ll have to deal with that just for people who go to Talk, or their inbox, while in the middle of transcribing a page.

**Comment by srallen** [comment]
We'll need to implement something like that regardless of task type. I've opened #1554 to track this.

**Comment by eatyourgreens** [comment]
👍
