### ISSUE TITLE
The pages viewer will only render ten frames (see ADR-19).

### ISSUE THREAD

**Issue by simensta** [zooniverse/front-end-monorepo#1458]
There needs to be a strategy for handling subjects with many, many frames. This affects not only the multiFrameViewer components, but also the Subject Set uploading components. For now, we have decided that the pages viewer is only responsible for up to 10 frames.

**Comment by srallen** [comment]
In the multi-frame container component, do a check for length locations array and if over ten show error message rather than attempt to render the image viewer.

**Comment by srallen** [comment]
We should test this against the ASM subjects.

**Comment by srallen** [comment]
This is implemented.
