### ISSUE TITLE
Volunteer can select a new frame for display by pressing a frame thumbnail with their mouse or keyboard.

### ISSUE THREAD

**Issue by simensta** [zooniverse/front-end-monorepo#1459]
A volunteer should be able to interact with the subject frame carousel via mouse or keyboard to select a new image frame.

**Comment by srallen** [comment]
The onclick handler will reset pan, zoom, scale state and set the currently viewed frame index to the subject viewer store to make it available to the classification annotation.

**Comment by eatyourgreens** [comment]
>The onclick handler will reset pan, zoom, scale state 

PFE preserves scale and translation across frames. You can try it out on [Wildcam Gorongosa](https://www.zooniverse.org/projects/zooniverse/wildcam-gorongosa/classify). Zoom in, pan around a bit then change frame and you don't have to zoom and pan to get back to where you where.

**Comment by eatyourgreens** [comment]
The frame thumbnails, when the thumbnail picker has focus, should also allow for changing frame via the left/right or up/down cursor keys (maybe both combinations?)

**Comment by srallen** [comment]
> PFE preserves scale and translation across frames. You can try it out on Wildcam Gorongosa. Zoom in, pan around a bit then change frame and you don't have to zoom and pan to get back to where you were.

There seems to be some inconsistent behavior because this isn't true for the dev classifier on PFE staging, which is what we checked when meeting yesterday. We need to determine what is the intended or preferred behavior.

**Comment by eatyourgreens** [comment]
The production behaviour was requested by several project owners, so I’d go with that. There was a long-standing bug issue on PFE about each frame zooming independently. I can look that up and link it here. 

From memory, the original request came from either Backyard Worlds or Space Warps.

**Comment by eatyourgreens** [comment]
Here's the original PFE discussions of zoom for subjects with multiple frames.
https://github.com/zooniverse/Panoptes-Front-End/issues/4034
https://github.com/zooniverse/Panoptes-Front-End/issues/3465

**Comment by mcbouslog** [comment]
If zoom should be consistent between frames, I think I need to move `scale` and `viewBox` from the MultiFrameViewerContainer to the SubjectViewerStore? That's what I'm thinking after working on #1518.

**Comment by eatyourgreens** [comment]
#1493 wraps all that up in a component for you. Wrap all your frames, rather than each individual frame.

**Comment by mcbouslog** [comment]
Created #1538 for persistence across frames notes, closing per #1518
