### ISSUE TITLE
Incorporate SingleImageViewer into the MultiFrameViewer

### ISSUE THREAD

**Issue by simensta** [zooniverse/front-end-monorepo#1472]
In order to incorporate the SingleImageViewer as a display component for the currently selected image, the SingleImageViewer will need to be modified. Currently, the SingleImageViewer handles an entire subject as opposed to just a frame.

**Comment by eatyourgreens** [comment]
I’d suggest moving the image viewer itself into a shared component that’s used by both subject viewers, rather than hacking the subject viewer.

**Comment by mcbouslog** [comment]
Notes from discussion:
- multiframe viewer needs container component to handle subject and multiple frame load (including scaling, zoom, rotation)
- initially will be duplication between SingleImageViewerContainer and MultiFrameViewerContainer, we'll refactor subsequently
- multiframe viewer container load subject and locations, save to component state
- scale, zoom, and rotation reset on frame change
