### ISSUE TITLE
Text Task keeps losing focus after each character typed

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#1476]
## UI Bug

Package: `lib-classifier`

On the Classifier, when given a Text Task, the text input will lose focus after every character typed.

### Testing and Reproduction

- With any project, create a simple Workflow with a single free-form Text Task.
- On the Classifier, go to that Workflow.
- Attempt to type in a sentence, such as "good morning", in the Text Task's text input. _Using a keyboard, of course._
  - Expected: the text "good morning" appears in in the text input.
  - Actual: the first letter of the sentence, "g", appears in the text input, but then the text input loses focus, so all other input from the keyboard is ignored (or caught by some other component.)

Tested on macOS 10 + Chrome on commit master (commit 481e121773d868065e9de328ee0b853e09e2a929)

### Status

Serious UI bug, but... _not urgent_ at the moment since no live projects on the monorepo uses the Text task, AFAIK.

**Comment by eatyourgreens** [comment]
Ohhhh, is that why the text task was storing its value via `useState`? This sounds familiar.

**Comment by shaunanoordin** [comment]
🤷‍♂ Might be! But I'm not sure it explains why the _text <input />_ keeps losing focus after each keypress.

**Comment by eatyourgreens** [comment]
This is going to be urgent very soon, because it stops us from building text transcription tasks!

**Comment by eatyourgreens** [comment]
This bug persists after changing `TextArea` to `textarea`, so I don't think it's a Grommet bug. Perhaps something to do with our component re-rendering on each new character (and consequent change to the stored annotation.)
