### ISSUE TITLE
RFC: should we have separate staging and production Docker images?

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1482]
**Package**
app-project
app-content-pages

In staging and production, the NextJS apps are both built from `zooniverse/front-end-monorepo:latest`. Here's the app-project Dockerfile as an example (content pages is pretty much exactly the same.)
https://github.com/zooniverse/front-end-monorepo/blob/c364e6ad457b5166af18e9789e201481569c6592/packages/app-project/Dockerfile#L1-L10

Our build process is:
- *staging*: Pull down the latest master commit, install and bootstrap the monorepo dependencies then push the resulting image to `zooniverse/front-end-monorepo:latest`. Build the app images from that base image.
- *production*: Pull down the `production-release` tag, install and bootstrap the monorepo dependencies then push the resulting image to `zooniverse/front-end-monorepo:latest`. Build the app images from that base image.

My question is: should we continue doing this or would it be safer to build separate base images for production and staging? I guess I'm worried about inadvertently pulling down an image with the latest HEAD of master when what I might really want is the latest production release.

**Comment by eatyourgreens** [comment]
I guess the current process is fine as long as we always rebuild the base image before using it?

**Comment by camallen** [comment]
I get why the boostrap image exists for the `yarn bootstrap` https://github.com/lerna/lerna/tree/master/commands/bootstrap

However I'm confused as to why the `production-apps` image contains both the builds for the `fe-project` and the `fe-content-pages` apps. These artefacts will be in both deployed app images and they really should be split out. 

It seems folks planned to use the combined `production-apps` image for running all services from the root (port 3000 and 3001), however they can use isolated docker builds as well. Ideally this combined images could be used for testing via travis but we don't use that way. Are we using this combined image any other way?

I think we're overcomplicating the root image build process here, we can rebuild the individual packages (using the bootstrap image as base) in both compose for dev and jenkins for deployment. 

Once we've split out the builds, we add docker image `ENV` values for switching to staging / production builds using via compose and jenkins cmds to ensure we're building the versions of the apps we specifically want. 

As it stands any merge to master builds one image for both staging and production deploys. We Can switch to using the tag release system we're using in almost all other repositories to isolate between master -> staging deploys and `production-release` -> production deploys. 

This isolation will allow us to build independent deploy env images and allow master work to progress without impacting staging deploys (can pick a point between release tag and master head to release features).

**Comment by eatyourgreens** [comment]
>It seems folks planned to use the combined production-apps image for running all services from the root (port 3000 and 3001), however they can use isolated docker builds as well. Ideally this combined images could be used for testing via travis but we don't use that way. Are we using this combined image any other way?

Is that from the docker-compose setup that I wrote? I use that to run production builds of both NextJS apps locally for testing. From memory, we've run into bugs that didn't show up with `yarn dev` but were present after `yarn build && yarn start`. Lesson: don't trust the dev app to behave exactly like the production build.

**Comment by eatyourgreens** [comment]
The production images that Jenkins builds are `zooniverse/fe-content-pages` and `zooniverse/fe-project`. Those are each built from `zooniverse/front-end-monorepo:latest` for both staging and production deploys but they _are_ tagged with commit IDs.

**Comment by camallen** [comment]
> Is that from the docker-compose setup that I wrote? I use that to run production builds of both NextJS apps locally for testing. From memory, we've run into bugs that didn't show up with yarn dev but were present after yarn build && yarn start. Lesson: don't trust the dev app to behave exactly like the production build.

Right - that's a local use case that we can accommodate with a different docker file from the base bootstrap image. That use case shouldn't influence the way we build the package apps.

> The production images that Jenkins builds are zooniverse/fe-content-pages and zooniverse/fe-project. Those are each built from zooniverse/front-end-monorepo:latest for both staging and production deploys but they are tagged with commit IDs.

Yep but both FROM image contains all the code for both apps.

**Comment by eatyourgreens** [comment]
>Yep but both FROM image contains all the code for both apps.

This bugs me too. I've never figured out how to install just the project app, say, without having to copy the entire monorepo across to a new image.

I tried to make use of layer caching to make this less slow and painful in the docker-compose builds. From what you've said recently, could volume caching be used here as well? I don't really understand volume caching/sharing so I've avoided it (because I'm sure I would just get it wrong.)

**Comment by eatyourgreens** [comment]
We've got separate builds for production and staging in the Jenkinsfile now, so I'm going to mark this discussion as done.
https://github.com/zooniverse/front-end-monorepo/blob/fcdfd6311c6d799a6c5602bca5a3ff4406895fa4/Jenkinsfile#L45-L55
