### ISSUE TITLE
Classifier: SuRVoS subject cluster viewer

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1485]
**Package**
lib-classifier

**Describe the solution you'd like**
Add a subject cluster view to the classifier. A subject cluster is a group of subjects which are annotated together, so shown in the subject viewer area next to a classification task.

>The Survos team desire the ability to control the way a ‘cluster’ of selected subjects will be presented in the UI. Some clusters may be 1 column X N subject images, others may be presented in a regular grid format. One strategy for determining the ‘cluster’ view model is to have the workflow configuration contain the desired view dimensions, so the UI code can reflect on this information and dynamically wire up the UI. This will require us setting some limits / defaults to avoid poor UX for the cluster dimensions (i.e. 1 X 100).

**Comment by eatyourgreens** [comment]
After discussion yesterday, the viewer could be a single SVG which is composed of several SVG images, arranged in a grid. The subject toolbar would operate on the parent SVG, but individual images would be interactive, focusable elements to enable selection/deselection etc.

**Comment by shaunanoordin** [comment]
Closed by #1556 👍
