### ISSUE TITLE
Classifier: SuRVoS subject cluster Talk links/URLs

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1487]
**Package**
lib-classifier

**Describe the solution you'd like**
Subject clusters won't have Talk URLs so we need to consider what happens to 'Discuss this subject on Talk'. Maybe the behaviour of the Recents queue as well.

>If we choose to implement the dynamic cluster subjects for Survos, we will have to disable the talk notes board as we won’t be able to reliably construct the state of known subjects that the user classified.

**Comment by camallen** [comment]
I'm not sure but I'm thinking about making subjects dynamically on subject selection to fit the current data model for retirement / data tracking etc. If we go down this route on the API for dynamically generated subjects then the talk system for subjects will 'just work'

**Comment by eatyourgreens** [comment]
That sounds good to me. Does this mean a SuRVoS subject is a composite of other subject IDs, or a single subject with many locations?

**Comment by eatyourgreens** [comment]
Thinking about it, this issue has wider ramifications for collections and favourites. I think we've got a few places in the code that assume a subject is a single entity with a unique ID.

**Comment by camallen** [comment]
It would be a single special 'group' subject that looks just like a subject but records the originating subject resources and collates the original linked media resources as well. 

Adding this special grouped subject resource would enable our UI code (talk, collection, favourites, etc) to work as is.

**Comment by eatyourgreens** [comment]
Talk/collections/favourites means, of course, that these subjects will require changes to PFE. Specifically, adding a new subject viewer that can display these subjects.

**Comment by camallen** [comment]
Ah good point - or we disable those components (which would probably be more work). TBD

**Comment by eatyourgreens** [comment]
Depends how much the SuRVoS team depend on Talk and collections to do science, I guess.
