### ISSUE TITLE
Classifier: multiple choice answers don't reflect annotation state

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1507]
**Package**
lib-classifier

**Describe the bug**
Checking answers for the multiple choice task updates the annotation value but the checked answers aren't shown in the browser. Here the annotation value is `[ 1, 2 ]` but it appears be `[]`.
![A screenshot of the multiple choice task, showing no answers apparently selected although two actually are.](https://user-images.githubusercontent.com/59547/74349736-918ef400-4dac-11ea-8057-5179e3352b30.png)

**Comment by shaunanoordin** [comment]
This seems newly introduced - I was able to get Multiple Choice tasks working properly on my `drawing-subtasks` branch, and that's based on commit 91fed9ccaf36c02d73ca94f3c7d70dc5416af5c6. I'll see what changed since then.

**Comment by shaunanoordin** [comment]
Multiple Choice tasks stop working starting from commit b79bf363fdf2905aeec5519cf8d9a9d8364077ee onwards, which corresponds with #1496 

So maybe it's just the CSS that's not working

**Comment by eatyourgreens** [comment]
You're right. `git checkout 91fed9c` and `yarn dev` and it's working again. Thanks for taking a look.
![The multiple choice task working correctly on commit 91fed9c.](https://user-images.githubusercontent.com/59547/74356480-4da0ec80-4db6-11ea-8106-411313ead0d8.png)
