### ISSUE TITLE
Fallback for avatar on homepage not rendering

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1509]
**Package** app-project

**Describe the bug**
The fallback for the avatar for the researcher quote area isn't rendering correctly.

**To Reproduce**
1. Load a project home page that is owned by a user that doesn't have an avatar set

**Expected behavior**
The fallback should render.

**Screenshots**
<img width="371" alt="Screen Shot 2020-02-12 at 10 54 56 AM" src="https://user-images.githubusercontent.com/5016731/74367428-7796e680-4d97-11ea-9b93-3b6b046a4f2f.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Chrome
 - Version 79

**Additional context**
Observed after the update to use the styled-component css helper, but possibly was always an issue.

**Comment by goplayoutside3** [comment]
Example link: https://frontend.preview.zooniverse.org/projects/goplayoutside3/test-bike-lane-uprising?env=staging
