### ISSUE TITLE
Possible incorrect usage of observer + inject decorators for task components

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1511]
**Package** lib-classifier

**Describe the bug**
The console is currently warning twice about this:
`Mobx observer: You are trying to use 'observer' on a component that already has 'inject'. Please apply 'observer' before applying 'inject'`

Can be observed here: http://localhost:8080/?project=1862

The stack trace points to this line: 

https://github.com/zooniverse/front-end-monorepo/blob/52a73f9500d61f8771aeec458eb11e557effb4db/packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js#L59

This warning doesn't pop up for all task types and doesn't seem to immediately cause issue, however, the attempt in #1496 to add the `withTheme` decorator to the single choice task and multiple choice task caused issues. With the single choice task, some integration tests broke. With multiple choice task, issue #1507 happened. The fix was to revert the addition of the `withTheme` HOC. 

We need to investigate a better way to wrap task components with the observer HOC to make sure they're observing for changes from the store observables and then re-render. 

First, we could consider migrating some components away from `inject` since we are on mobx-react v6 with the classifier. Second, we should have integration tests for all of the task types.

**Comment by eatyourgreens** [comment]
`DataVisAnnotation` is the only task that uses `inject`.
https://github.com/zooniverse/front-end-monorepo/blob/7aceaca920df06d831e2de8e653d8d3291b2e5a2/packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/components/DataVisAnnotationTask.js#L36-L38

It has completely different props from the other tasks, which are passed a task and an annotation.

**Comment by eatyourgreens** [comment]
The problem with the `withTheme` decorator might be related to this issue (I'm not sure): https://github.com/mobxjs/mobx-react/issues/471
