### ISSUE TITLE
Classifier: Last workflow step is still selected when a new classification starts

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1521]
**Package**
lib-classifier

**Describe the bug**
On starting a new classification for the second, and subsequent, subject in the queue, the first annotation that is added to the new classification is the annotation for the last task in the workflow.

Here we log calls to `classifications.addAnnotation(task, value)` on classification complete. Task `T3`, the last task, is added to the new classification before `T0`, the first task.
![Screenshot of the console log, showing annotations being added to a classification out of order.](https://user-images.githubusercontent.com/59547/74660838-d04af280-518e-11ea-9292-f20867048dac.png)

When the classification is submitted, the order of the annotations array is `[ T3, T0, T1, T2]`, not `[T0, T1, T2, T3]`.

**To Reproduce**
Classify more than one subject on project 1844, which has four steps.
http://localhost:8080/?project=1844

**Comment by eatyourgreens** [comment]
Investigating further, the `Tasks` component re-renders with the new classification, but old tasks, before the workflow steps store has reset. The old task key gets added to the new classification here:
https://github.com/zooniverse/front-end-monorepo/blob/2234b9cae3f0fc967d430e1016b8636564b8a083/packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js#L53-L60

**Comment by eatyourgreens** [comment]
I'm fairly sure this was introduced by #1434 (or maybe earlier.) Previously, the new annotation was added to the classification when we finish a task. Now, it's added when we start a task, but there's a race condition between the subject loading, the new classification being created and the first task being set.

I think the order of actions should be:
- subject queue advances
- workflow step resets
- classification created
- new task annotation created

The current order of actions appears to be
- subject queue advances
- classification created
- new task annotation created (old task is still active)
- workflow step resets

**Comment by eatyourgreens** [comment]
We could revert to the old behaviour (push the annotation to the annotation store when we finish a task) but that doesn't fix the race condition, just works around it.

**Comment by srallen** [comment]
I would prefer that the annotation is added to the store when we finish a task and this would help answer a question about consistent UI/UX @shaunanoordin has raised in #1517. I dislike that annotations are created on task load and it's something that I find to be a confusing data flow and one I would prefer we did not copy from PFE. 

As you said, this might not fix the observer problem, but I would prefer it.  I believe the race condition might've been introduced at another recent refactor point.

**Comment by eatyourgreens** [comment]
I'm an idiot. Previously an annotation was added to the store when you _start_ a task. You can't annotate a task without having created an annotation in the store first. Each individual task component was responsible for creating its own annotation in the original code. So we had a bunch of components all duplicating code. The change around #1434 or thereabouts was to move `classification.addAnnotation(task, value)` into one place for all tasks.

We could move to a design where each component keeps its value in local state, then creates an annotation when the task is finished. On task component unmount, perhaps? That's a pretty big change from the existing behaviour, in my opinion, but probably a more flexible design as we add more tasks.

**Comment by eatyourgreens** [comment]
A simple, though inelegant, fix might be to have each task component run `annotationStore.addAnnotation(task, value)` on mount, where `annotationStore` is either the current classification or active mark.

**Comment by srallen** [comment]
> We could move to a design where each component keeps its value in local state, then creates an annotation when the task is finished. On task component unmount, perhaps? That's a pretty big change from the existing behaviour, in my opinion, but probably a more flexible design as we add more tasks.

This is closer to I think what Rog and I built initially and what I'm asking for again. I'd prefer annotations being added to the classification on next/done (which should unmount tasks now they're keyed too).

**Comment by eatyourgreens** [comment]
The early versions of the classifier called `classification.addAnnotation(task, value)` when you started a task, but called it from within the task component. I recently switched some of the tasks over to store their value in local state, but reverted that in #1409 because the value would persist across subjects when you only have one task in your workflow.

**Comment by srallen** [comment]
Nope, even earlier than that, before the refactor to make individual task components responsible for calling `addAnnotation`. For example: https://github.com/zooniverse/front-end-monorepo/commit/c7ef395553e2660f1dd7af2655593cf2b2abfc3a#diff-dcf47fd6e735810ecd4c6bad2e8515bb

**Comment by srallen** [comment]
Certainly not suggesting a full revert back to moving that action back into the Classification store, but there was commit history well before many refactors that have happened in the last 6 months.

**Comment by eatyourgreens** [comment]
That action is still in the Classification store. I'm not sure if it gets called though.

**Comment by eatyourgreens** [comment]
If we create annotations after classifying, then we can't key the task components by annotation ID. I think this will need a bit of thought. 🤔 We could perhaps key the task area by classification ID, to force a reload when the subject changes. Or key the subject viewer plus task area on subject ID. I guess that fails for test projects like mine that load the same subject over and over.

**Comment by eatyourgreens** [comment]
If we replace `task.annotation` with `task.value` in the models, that would be one step towards removing the coupling between tasks and annotations. Task validation could then apply task validation rules to the current value. On task complete, we create the new annotation with something like
```js
const { taskKey: task, value } = taskModel
const annotation = annotationModel.create({ task, value })
```

If we go back, we modify the stored value, create an annotation with it then replace the existing annotation with the new one.

**Comment by eatyourgreens** [comment]
`addAnnotation` is injected from the classifications store here:
https://github.com/zooniverse/front-end-monorepo/blob/555b5688314eae35612802c9f27a53c201b62d73/packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js#L12-L14

So the code is still using that same action. I think the point at which it is invoked has changed.

**Comment by srallen** [comment]
Ok, so I'm not exactly sure at the moment if there was code written to try this at some point or if it was just a conversation now, but there was an idea to make the tasks uncontrolled and to add the annotations on next/done. Essentially make the task area more like a form.

**Comment by eatyourgreens** [comment]
I have a fix for this but I'm not sure how good it is. I'll open a PR for comments.
