### ISSUE TITLE
Scale and translation across frames in MultiFrame Viewer

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#1538]
As discussed in #1459, per prior PFE issues/discussions, preserve scale and translation across frames.

https://github.com/zooniverse/front-end-monorepo/issues/1459#issuecomment-582457755

Refactor MultiFrameViewerContainer to match SingleImageViewerContainer per #1493

**Comment by mcbouslog** [comment]
To briefly recap current pan and zoom behavior with multi-frame subjects:
- [PFE - Wildcam Gorongosa](https://www.zooniverse.org/projects/zooniverse/wildcam-gorongosa/classify): maintains pan and zoom across frames
- [Anti-Slavery Manuscripts](https://www.antislaverymanuscripts.org/classify): resets pan and zoom from frame to frame, including previously panned or zoomed frame

I think it makes sense for camera trap type projects to preserve scale, and I think it makes sense for transcription projects to reset scale. Which maybe means the transcription task makes scale reset, otherwise scale preserves? @beckyrother please let us know what you think?

**Comment by beckyrother** [comment]
Completely agree @mcbouslog, thanks for checking! 

At the risk of adding a ton of scope creep, would it be possible to allow project owners to choose the behavior? Maybe starting with those two options as defaults depending on the project type (survey = maintain, transcription = reset)?

**Comment by mcbouslog** [comment]
Next steps for this issue will be to update the [workflow configuration subject viewer configuration](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.js#L9) to reflect the different options noted (survey = maintain, transcription = reset) and the subject viewer scale and translation accordingly.

**Comment by goplayoutside3** [comment]
The current behavior in FEM's classifier is for transcription projects to use the MultiFrame viewer while camera trap + similar projects use the Flipbook viewer. Flipbook viewer preserves any adjustments to zoom, move, or rotate when volunteers nav between frames (i.e [Daily Minor Planet](https://www.zooniverse.org/projects/fulsdavid/the-daily-minor-planet/classify)). The MultiFrame viewer does the same with the exception of rotate. Rotate gets reset when volunteers nav between frames, but zoom or move does not (i.e this [test project](https://frontend.preview.zooniverse.org/projects/blicksam/transcription-task-testing/classify/workflow/13898?demo=true)).

I think my question is for @snblickhan, but tagging in @mcbouslog too. Are we okay with the current viewers' functionality, or do any adjustments need to be made to the MultFrame viewer's behavior between frames?

**Comment by snblickhan** [comment]
@goplayoutside3 In the test project, the image reset the zoom when I changed frames, which is the behavior I would expect. But that seems to contrast with your statement above re: MultiFrame viewer. Am I misunderstanding? 

To be clear, for Transcription projects I would not want to preserve zoom between frames, since there isn't a use case for preserving zoom when working with multi-page text.

**Comment by goplayoutside3** [comment]
https://github.com/zooniverse/front-end-monorepo/assets/23665803/45ca1a8a-9be3-44a9-a407-3662ff2c0631

In the above video, zoom persists when I switch between frames. Does your browser behave differently?

**Comment by goplayoutside3** [comment]
Closing because there's no plans to change the current viewers' functionality.
