### ISSUE TITLE
Inactive Drawing Marks can still be drag-moved

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#1543]
## UI Bug

Package: `lib-classifer`

Expected: If you make drawing annotation marks in Step X of the workflow, then in step X+1 those drawing marks should be visible but not _interactive._ i.e. You should not be able to edit or delete marks made in a previous Workflow Step.

Actual: drawing marks from a previous step CAN be _moved/repositioned_ by the drag action.

![Screen Shot 2020-02-26 at 17 39 08](https://user-images.githubusercontent.com/13952701/75449522-080f2280-5965-11ea-9124-a8b03e67b507.png)
_Two rectangles drawn in Step 1._

![Screen Shot 2020-02-26 at 17 39 24](https://user-images.githubusercontent.com/13952701/75449530-09d8e600-5965-11ea-97b2-0e97c862f79a.png)
_The red rectangle is moved in Step 2._

### Status

A fix is already being pushed, this is just the documentation.

**Comment by eatyourgreens** [comment]
D'oh! Was this introduced by removing the `dragging` attribute in #1534? I thought that attribute wasn't doing anything.

**Comment by shaunanoordin** [comment]
Oh hey! I totally forgot about #1534. Let me jump into my Git time machine and see if the bug was extant prior to 1534, just to confirm

**Comment by eatyourgreens** [comment]
I don't think that `dragging` attribute was doing anything but 🤷‍♂ who knows?

**Comment by shaunanoordin** [comment]
@eatyourgreens Ah, #1534 still looks legit. 👌  The `dragging` attribute still didn't seem to factor in - I jumped back to commit right before 1534 got merged (415cde9361dfe1b28305a2fdc7a4069f495c2798) and the bug still exists.

**Comment by eatyourgreens** [comment]
Good to have it confirmed that it wasn't actually doing anything.
