### ISSUE TITLE
Drawing SubTasks - Follow up for PR 1517

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#1546]
## UI Enhancement

Package: `lib-classifier`

In PR #1517, we introduced a basic subtask popup component for drawing tools. This issue acts as a handover document for further development of the Drawing SubTasks popup, focusing on the UI aspects of the component.

### Current Features

PR #1517 introduces the following features:

![Screen Shot 2020-02-28 at 18 48 20](https://user-images.githubusercontent.com/13952701/75577998-f5771500-5a5a-11ea-9f40-d1b1df90d8e3.png)

- If a drawing tool mark has subtasks, then when you finish creating a new one, a popup will open.
- If you click on an existing drawing tool mark with subtasks, a popup will open.
- The subtask popup functions the same as the right-hand Task Area.
  - All changes to the subtask values are **saved automatically.** (This is important to note because there's a 'Save' button in that UI that only closes the popup. _Not_ clicking the save button to close the popup doesn't revert any changes made.)
  - Classifications are correctly submitted with subtask values.
- When the subtask popup is open, interaction with other elements are blocked (e.g. other drawing marks on the Subject Viewer, the right-hand task panel).
  - There's an **invisible modal layer** blocking interaction.
  - Clicking outside the popup, or clicking the save button, or clicking the close (X) button, or pressing the Esc key, will close the popup.
- The selected/active drawing tool mark is now more visually distinguishable from other marks.

Basically, this allows users to classify on workflows that feature drawing tools with subtasks.

### Implementation Notes

- ⭐️ The popup itself uses [React-Rnd](https://github.com/bokuweb/react-rnd)
  - The `<Rnd />` popup component can be reposition and resized by the user.
  - It can do a lot more (see the docs), but for simplicity, I only chose to set the _default starting position_ and _minimum size_ of the popup.
- The **x-y coordinates** specify the top-left corner of the popup, relative to _its closes parent with position: relative|absolute._ (i.e. `<Rnd />` component has `position: absolute`)
  - Currently, the _default x-y coordinates of the popup_ has the top-left corner of the popup appear at the middle of the drawing tool mar.
- Figuring out the appropriate **size of the popup** can be tricky.
  - On one hand, you don't want to hardcode a popup size, so it can auto-calculate width/height to accommodate any number of subtasks.
  - On the other hand, you might need to get really tricksy if, e.g. you need to know its width so you can offset the x-coord of its initial position, so you can 'centre' the position of the popup relative to the mark.  

### Room For Improvement

Despite the functionality, I found that there were still several areas where the UI/UX experience can be improved. Here are my notes.

**Improvement Item 1: When selecting an existing drawing tool mark with subtasks, the popup shouldn't appear immediately**

- Currently, the 'show popup' action is hooked up directly to the `drawingTools/components/Mark/Mark.js`'s `onFocus` handler. This means as soon as the mark has focus, it gets a popup _that proceeds to steal focus_ and _block interactions with other elements_
- This causes two problems:
  - It gets tricky if you're trying to drag a Mark, because when you initiate the 'drag-to-move' action, the invisible modal layer immediately appears to block all interaction. (Fortunately, it doesn't cancel the drag action so you can still continue dragging the mark, but as soon as you lift the mouse cursor, further interaction is blocked until the popup is closed, so you'll need _two clicks_ to move that Mark again.)
  - The focus-stealing messes with keyboard navigation.
- ⭐️ Preferably, the 'show popup' action should be hooked to 1. `onPointerUp` and 2. `onKeyDown(e => { /* when e === Enter key */ })`
- Note that this is not a problem when a _new_ mark is created, because the 'show popup' action is hooked to the `InteractionLayer`'s `onFinish` handler.

**Improvement Item 2: Consider keyboard navigation**

- Currently, attempting to tab-navigate across existing drawn marks with subtasks is a problem, because of Item 1 above.

**Improvement Item 3: The usage of modals (Grommet Layers) might need to be re-examined due to lack of scrollbars**

- ⚠️ This may seem to be a bit of a weird minor problem because it doesn't really show on `lib-classifier`, but I can see where this _might_ need to be addressed. Or I _might_ be worrying over nothing.
- When a Grommet modal layer appears, it _crops the document size to fit the viewport size._ This means that if the document size is tall enough that it has scrollbars, (i.e. the project page) those scrollbars will _suddenly disappear_ when a popup appears.
- Small problem, right? Wrong! (Maybe?) Scrollbars affect the width of the document, which affects the layout of the document. 
- This means that every time you click and create a popup, the screen might _jitter_ as the scrollbars disappear, causing the layout of the Classifier/the whole page to resize/reposition itself to fit into the tiny margins where the scrollbars should have been.
- Will it be annoying? Maybe?? But this needs to be tested first.

**Improvement Item 4: The initial popup position can be improved**

- This may just be me being nitpicky, but I'd _really_ like it if I could centre-align the popup to the centre of its associated mark
- Also, it'd be nice if we could have better popup position handlers to prevent the popup from appearing, or being moved to, a location that's out of bounds.
  - Although good luck figuring out what to do in the edge case if the popup is larger than the viewport size. 🤷‍♂ I stopped trying to figure out a solution once I realised how unlikely this was, but the question still haunts my nerdy dreams.

### Miscellaneous Notes

**Misc Item 1: what if the modal model is removed?**

- Say you want to remove the invisible Grommet modal layer in the SubTaskPopup component, because you want to approach the "disable interactions with other elements while popup is open" functionality differently. What do you need to account for when you remove the `<Layer modal={true}>` in `SubTaskPopup.js`?
- Problem 1: it's possible for other UI elements in the Classifier (or Classifier page on app-project) to appear 'on top' of the popup. (i.e., z-index problems.)
- Solution 1: this can be solved quite easily by setting z-index of the React-rnd popup component...
  ```
  // In SubTaskPopup.js...
  const SUFFICIENTLY_LARGE_ZINDEX = 10000

  <Rnd
    style={{
      zIndex: SUFFICIENTLY_LARGE_ZINDEX,
    }}
    ...
  />
  ```
- Problem 2: now that popup isn't anchored to a modal layer, its initial x-y positioning _relative to its drawing tool mark_ seems a bit... off?
  - This is because the modal layer is anchored to the top-left of the viewport, so the popup's x-y origin is _also_ at the top-left of the viewport, and since `activeMark.getBoundingBox()` gives x-y coordinates relative to the same top-left of the viewport, it makes calculations super easy. Once you remove the modal layer though, you'll need to figure out where's the new parent of the popup (and hence where is its x-y origin), and then calculate offsets based on that. 
- Solution 2: for _SingleImageViewer,_ a _functional_ parent/visual anchor is the `<svg>` element itself. And that's why I placed the `<SubTaskPopup />` within `<SVGContextProvider>`s: it previously allowed me to calculate the parent offsets like so...
  ```
  SubTaskPopup.getDefaultPosition () {
    const {subTaskMark} = this.props
    const {svg} = this.context
    const svgBounds = svg.getBoundingBox()
    
    if (svgBounds subTaskMarkBounds) {
      const markX = subTaskMarkBounds.x || 0
      const markY = subTaskMarkBounds.y || 0
      const markWidth = subTaskMarkBounds.width || 0
      const markHeight = subTaskMarkBounds.height || 0
      
      x = markX + markWidth * 0.5 - svgBounds.x  // The position of the popup, relative to its mark, needs to be offset by the x-y position of its parent/anchor
      y = markY + markHeight * 0.5 - svgBounds.y  // ditto
    }
  ```
- Uh, my version of Solution 2 may have some issues when you have a multiframe viewer though, since then the `<svg>` element won't be a great visual parent to anchor x-y coords, but that's a solvable problem.

⚠️ Always check that the popup is appearing correctly, relative to the drawing mark, when the window viewport is scrolled above/below the classifier. (i.e. when the SubjectViewer isn't fully in view.)

**Misc Item 2: the SubTaskPopup could use more tests using the multiframe viewer, and other Subject Viewer types.**

This is particularly notable if we choose to remove the modal model, as detailed above.

**Comment by shaunanoordin** [comment]
As of writing, PR #1517 is still open.

I'm tagging @srallen and @mcbouslog here for dev purposes; I hope I left this feature in a way that makes sense to you, and please let me know if there are any question marks in my code that you'd like to talk about.

@mrniaboc and @camallen, the summarised version is here: https://github.com/zooniverse/front-end-monorepo/pull/1517#issuecomment-592661739

**Comment by srallen** [comment]
@wgranger could you have a look at the first item of improvement listed here for next week?

**Comment by srallen** [comment]
I've implemented some minor improvements in the styles in this PR: https://github.com/zooniverse/front-end-monorepo/pull/1629

**Comment by wgranger** [comment]
Sorry I missed my original assigning of this! 

Further notes on **Improvement Item 1:**
I'm trying to close #1640 and am noticing some issues with how a mark gets focus. When using **Chrome** and marking with the **transcription task**, placing the first dot of a line with a touch event gives the mark focus, thus attempting to open the sub-task. 

In that same situation (Chrome/touch events), let's say a line is finished with two dots and I want to close the subtask. In closing the subtask, focus returns to the mark and the subtask opens again. But I wanted the subtask closed! So I close the subtask again, focus returns to the line, subtask opens again. The loop repeats indefinitely.

**Comment by srallen** [comment]
We addressed improvement 1 and 2. The other items need additional feedback from beta testing to determine if and how we address them.
