### ISSUE TITLE
[VSLCV] Fallback for small screen sizes

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1548]
**Package** lib-classifier

One of the ideas from the last discussion with the variable star researchers is to have a message come up on small screen sizes that states that this data is best viewed on tablets and desktop rather than try to come up with a responsive view of the data. We need to make a few decisions:

- What's the screen size cut off for this?
- What should the message say?
- How should the message be displayed?

This effectively scopes this project to not be able to be participated on with mobile users so we should confirm this is ok before designing for it.

**Comment by eatyourgreens** [comment]
Not just mobile users. Also anyone on desktop with a large page zoom. 😞

**Comment by srallen** [comment]
Yes, that's true, but my guess based on taking a look at TESS Google Analytics data on Friday is that these people are self-selecting themselves out of participation because the data is just hard to use and hard to classify once the data points in the visualization get smooshed together. Yes, it's _possible_ with the zoom function to zoom in, but lots of scrolling then becomes necessary and it'd be harder to see patterns for periods. These issues will just get compounded with the variable star version of the LCV. With TESS, they do have a mobile version via the app with image subjects I believe and initial thoughts are that we should discuss this possibility with the variable star research group too.

**Comment by beckyrother** [comment]
I think that's a good assumption. TESS is a really good standard to follow – I'd be interested in screen size analytics for that project, but I'd bet volunteers are choosing not to participate in favor of more accessible images. I'd recommend this either be a stretch goal or that they follow the TESS model and make a mobile-only workflow. 

If we do use messaging, let's do a project-wide (hide-able) banner that says something like 'Apologies for the inconvenience but this project is not optimized for your screen size.' when the screen is smaller than 768px.

**Comment by eatyourgreens** [comment]
If the mobile workflow were available on desktop, that might be a great solution for people who use page zoom or a magnifier. I’m thinking of Claudia or Ron from the gov.uk personas. https://www.gov.uk/government/publications/understanding-disabilities-and-impairments-user-profiles

**Comment by eatyourgreens** [comment]
A banner that points them in the direction of a way that they can contribute might be more welcoming. 'Apologies for the inconvenience' sounds a little negative to me.

**Comment by beckyrother** [comment]
Happy to think more about the language, but still think a banner would be the most appropriate way to go here.
