### ISSUE TITLE
Classifier state should be stored when navigating around the project app

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1554]
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**
If a volunteer is mid-classification, we should stash the state of the classifier if they are mid-classification and navigate to other parts of the project app.

**Describe the solution you'd like**
We could detect for navigation away and stash into either session storage, local storage, or IndexedDB. Then on reload of the classifier, check for any stored data and load that rather than make HTTP requests. We should investigate what is best practice for this.

**Describe alternatives you've considered**
Service workers are used in this context as well.

**Additional context**

**Comment by eatyourgreens** [comment]
While working on setting up a test environment for classifier tasks, in #1553, I've noticed that when I create the root store from a snapshot, it goes ahead and fires off a bunch of API requests anyway. `afterAttach` could maybe check if a store is empty before requesting data. I'm not sure what the implications of that would be, but the logic might be complicated.

@shaunanoordin has a bunch of good ideas about this based on the experience of building local storage for Anti-Slavery Manuscripts.

**Comment by srallen** [comment]
Maybe not necessary if we instead warn before navigating away.

**Comment by eatyourgreens** [comment]
Vercel’s `useSWR` hook implements `stale-while-revalidate` for component data-fetching: https://swr.vercel.app. 

We use it in the classifier to fetch workflow data.

**Comment by goplayoutside3** [comment]
We now warn before navigating away.

**Comment by goplayoutside3** [comment]
Actually, we warn before navigating away FROM the project app.

This Issue is completed as Done though. For instance, I can go to TESS's classify page, draw some marks on the subject, navigate to its home page or about pages, and when I go back to the classify page my work is saved.
