### ISSUE TITLE
Production deployment for next.js

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#156]
**Package** app-project

**Feature or Issue Description**
We should test out deploying the next.js app to production as well as the proxy routing.

**Comment by rogerhutchings** [comment]
cc https://github.com/zooniverse/Panoptes-Front-End/pull/5319

**Comment by srallen** [comment]
Does #808 close this?

**Comment by rogerhutchings** [comment]
It should do - right now, I just need Adam to add the DNS entries and everything _should_ work

**Comment by srallen** [comment]
Gonna close this, but it'd be useful to have a general readme on how the project app deploys up somewhere.
