### ISSUE TITLE
Classifier: Zoom In, Zoom Out buttons ignores keyboard input

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#1581]
## UI Bug

Package: `lib-classifier`

On the Classifier, if a keyboard user **tab-navigates** to the Zoom In/Out button on the toolbar, and then presses **Enter** on their keyboard, the zoom in/out actions don't trigger.

Expected:
- Zoom In and Zoom Out buttons on the Classifier's Image Toolbar should behave like buttons.
  - i.e. they can be tab-navigated to, and pressing 'Enter' on the keyboard should be the equivalent of clicking the button.
  - Compare with the Rotate and Reset buttons on the Image Toolbar, which function like buttons.

Tested on macOS 10 + Chrome / Firefox / Safari

### Status

Medium impact, medium priority? Keyboard users can still zoom in/zoom out using the '+' and '-' keys while the Image Toolbar has focus, but the inability to "click" on buttons via keyboard does screw with standard UI expectations.

**Comment by eatyourgreens** [comment]
I think this is happening because the standard key for buttons is Space, but everyone expects it (quite reasonably) to be Enter.

**Comment by eatyourgreens** [comment]
Oh, and just to confuse things, links and `click` events are activated by Enter.
