### ISSUE TITLE
WCAG 1.3.1: Ensures that lists are structured correctly (Project navigation menu)

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1596]
#### Issue
`Ensures that lists are structured correctly` ([list](https://dequeuniversity.com/rules/axe/3.5/list?application=msftAI))
#### Target application
[Planet Hunters TESS | Zooniverse - People-powered research](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify)
#### Element path
nav[aria-label="Project"] > ul
#### Snippet
`<ul class="StyledBox-sc-13pk1d4-0 jmYunQ">`
#### How to fix
    Fix all of the following:
      List element has direct children that are not allowed inside <li> elements
#### Environment
Chrome version 80.0.3987.149
This accessibility issue was found using Accessibility Insights for Web 2.16.0 (axe-core 3.5.1), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

**Comment by eatyourgreens** [comment]
The issue here is invalid `div` elements in the project navigation.
![Screenshot of the DOM inspector for the project navigation.](https://user-images.githubusercontent.com/59547/78242840-a51c2880-74da-11ea-9bf0-f35f0ea0f599.png)

**Comment by srallen** [comment]
This would be good feedback for the Grommet team with regard to how the gap prop functions.

**Comment by eatyourgreens** [comment]
Yes. Grommet is adding styled, empty divs as spacers here:
https://github.com/grommet/grommet/blob/4288ddcaf49406f014aa16f8d1d9c6d83b8500a1/src/js/components/Box/Box.js#L85-L107

In the meantime, my advice would be to avoid using `gap` on Grommet boxes.

**Comment by srallen** [comment]
Yes, I'm familiar with how gap works. I would guess that its usage wouldn't always result in invalid markup, but sometimes would. Would you be willing to open an issue on their repo about it?
