### ISSUE TITLE
Category filters are broken for the publications page

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1618]
**Package**
app-content-pages

**Describe the bug**
https://www.zooniverse.org/about/publications
The category filters on the left don't do anything when clicked (checked in Firefox and Safari on OSX Mojave.)

https://frontend.preview.zooniverse.org/about/publications does work, so this may be a side effect of the deployment bug that was fixed in #1613. 

Firefox shows a bunch of 404 errors for requests for JS.
![Screenshot of the Firefox network tools, showing 404 errors from requests for JS files generated by NextJS.](https://user-images.githubusercontent.com/59547/79320216-579fb280-7f01-11ea-8c43-3571f4a5109d.png)

**Comment by srallen** [comment]
Confirmed to be fixed by #1613
