### ISSUE TITLE
[RFC] Sub-tasks required task UX

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1623]
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**

A common issue on PFE is that some volunteers get confused when they accidentally do not fill out the sub-task when it is required. See https://github.com/zooniverse/Panoptes-Front-End/issues/5571 and https://github.com/zooniverse/Panoptes-Front-End/issues/5463

The current behavior as described in #1546 is the the sub-tasks, whether they're text or question, save the annotation _when the annotations is made_, not when "Save" is clicked. Changing this would be a big refactor on the tasks in general. 

**Describe the solution you'd like**

We need to have differing behavior and UX if the sub-task is required. A few ideas:

Option 1: The sub-task has UI, focus, and validation if one of the subtasks is required and isn't changed from the default annotation. If it isn't changed, then do not allow the subtask area to close and focus the task that isn't finished yet.

Option 2: Have an ASM-like UX where the mark is deleted if the subtask isn't filled out and one of the sub-tasks is required. (but this doesn't communicate to the user what happened? how do we do that?)

**Describe alternatives you've considered**

PFE originally had a UI that notified users of the requirement, but ~it was removed~ it was removed for main tasks and doesn't fix the issue of marks having unfinished required sub-tasks and you don't know which one is not finished. See: https://github.com/zooniverse/Panoptes-Front-End/issues/1666

ASM deletes the mark if the subtask isn't filled out, but this isn't a generalizable solution since some projects may not require the subtask.

**Comment by srallen** [comment]
A few notes on the PFE interaction.

If the sub-task is required, there is a notice:

<img width="503" alt="Screen Shot 2020-04-16 at 3 48 41 PM" src="https://user-images.githubusercontent.com/5016731/79505349-dbd56100-7ff9-11ea-9971-d4b6c2cb5cef.png">

So I think there are cases of drawing tasks with sub-tasks where the sub-task isn't being set as required when it should be.

But also, even with that notice, an individual can hit esc or click outside of the modal and close it, but the mark remains, with an unfinished required sub-task. If there are a lot of marks, it is unclear which one is unfinished.

**Comment by srallen** [comment]
Maybe we do support deleting the mark if esc is hit when there is an unfinished, required sub-task, but we ask for explicit confirmation. Something like: "Are you sure you want to cancel this task? This will delete the mark."?

**Comment by beckyrother** [comment]
I like that. I'd also support adding the required text back but removing the secondary text, which feels repetitive and not needed.
