### ISSUE TITLE
Content pages are broken with CORS errors

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1630]
**Package**
app-content-pages

**Describe the bug**
Navigate from https://zooniverse.org/about/team to https://zooniverse.org/about/publications (or vice versa) and the page content is blocked by a CORS error.
```
Access to XMLHttpRequest at 'https://fe-content-pages.zooniverse.org/api/publications' from origin 'https://www.zooniverse.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Content pages should be rendered on the server and should not be making XHR requests for content.

**Comment by srallen** [comment]
I'm confused by this since the pages are using `getInitialProps` so the request to contentful should be happening server side.

**Comment by eatyourgreens** [comment]
The publications page loads ~1MB of javascript, then the location change to the team page fires off a request for https://fe-content-pages.zooniverse.org/api/team, which seems to be the team page content encoded as JSON.

**Comment by eatyourgreens** [comment]
Linked: #1326 and #1358.

**Comment by srallen** [comment]
I think this issue is conflating your disagreement with setup and approach with the bug that is happening. The bug, presumably, could be resolved separately from the suggested refactor here. The suggestion if I'm understanding it correctly has a much larger impact to the app in general. This can still be considered, but I think separately, unless you can demonstrate there is no other way to resolve the bug.

**Comment by eatyourgreens** [comment]
You can try out pure server-side rendering by browsing the publications and teams pages with JS turned off in the browser. You'll find it fixes this bug and, I think, also #1054. 

I reviewed and approved the current setup, but I believe I'm allowed to change my mind. What I'm talking about here is following best practice and web standards. I don't think we need a client-side JS app to download static content pages, and I think that approach is giving us bugs, like this one, that vanish if we serve HTML pages to the browser from NextJS. Given that we're already using SSR with NextJS, I'm not sure why that would present a hard problem.

Whether or not we continue to use NextJS for purely static content is a separate discussion, which I started with @rogerhutchings a while ago but haven't really had time to follow up.

**Comment by srallen** [comment]
It is ok for you to have this opinion and for you to propose a change to the app. I'm just not convinced this is the only way to solve it. In addition, the app is setup the way it is so we can have a testing environment for next.js features in production to a low traffic part of the site. It would be good if we learn why this bug is happening and how to fix it. If that can be determined, then I'm happy to continue discussion on turning the feature off.

**Comment by eatyourgreens** [comment]
I looked into this a while ago and I think the solution is to use HTML links in the navigation menu for all the About pages. The NextJS `Link` component hijacks clicks and turns these pages into a single page app.

**Comment by eatyourgreens** [comment]
In retrospect, we should have written an ADR to explain why we set up this new API in #1326 and #1358. Right now, I can't remember what the advantage was, compared with serving each page's content directly as HTML.

**Comment by eatyourgreens** [comment]
As a side note: looking back through the code turned up the `ASSET_PREFIX` environment variable. I've been wondering what that was used for, during the build, or what it should be set to.
https://github.com/zooniverse/front-end-monorepo/blob/3948f1ae452923b11ffb21233a9eff4415af156d/packages/app-content-pages/src/screens/Team/TeamContainer.js#L56-L58

**Comment by eatyourgreens** [comment]
NextJS 9.3 introduced [`getStaticProps`](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation), which may also fix this. I'm going to take a look at that.

**Comment by eatyourgreens** [comment]
Preliminary experiments with SSR in Next 9.3, after ~45 minutes playing with the replacements for `getInitialProps`. I’m not sure how much time I’ll have to look at this but it seems worth exploring.

**Comment by eatyourgreens** [comment]
I'm going to carry on rewriting content-pages to use [the replacements for `getInitialProps`](https://nextjs.org/docs/api-reference/data-fetching/getInitialProps). I've got a WIP branch for that, which looks promising. In the meantime, #1634 will fix the CORS issue by removing client-side navigation for About pages. It may also close #1054, which is our most frequent issue in Sentry.

**Comment by srallen** [comment]
Sounds good. I briefly had looked at the newer next.js API a few days (weeks? I can't keep track anymore) ago, so it'd be good to see it in action. Thanks for digging into this.

**Comment by eatyourgreens** [comment]
It turns out the new API changes the specs, so involves a rewrite instead of a refactor. I've got a branch that works locally but with failing tests. I'll open a draft PR.

**Comment by eatyourgreens** [comment]
#1635 is up now, using `getStaticProps`.
