### ISSUE TITLE
Keyboard controls for pan/zoom interfere with text transcription

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1637]
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**

While typing in the text transcription task, the pan/zoom controls on the keyboard are functional, including +,-, and the arrow keys. If someone is typing and needs to use these keys, having the pan/zoom controls engage interferes being able to successfully type in a transcription

**Describe the solution you'd like**
Possibly disable the keyboard pan/zoom controls while the text transcription input is focused.

**Comment by srallen** [comment]
@eatyourgreens may have some ideas to make sure we support both needs here: pan/zoom by keyboard and typing in the transcription.

**Comment by eatyourgreens** [comment]
I think stopping keyboard events from bubbling up should fix it. Have a look at the `withKeyZoom` component to see which event is triggering the zoom.

**Comment by eatyourgreens** [comment]
So something like
```js
onKeyDown(e => e.stopPropagation())
```

Should trap `keydown` events before they trigger the zoom handler on the subject container.

**Comment by eatyourgreens** [comment]
If you haven't already, it's worth double-checking in Firefox that backspace doesn't take you back a page. `<textarea>` swallows key presses by default, to prevent this, so I'm a bit surprised that the +/- keys (and arrow keys?) are being handled by the container. Maybe the text input traps `keypress` but not `keydown`?

**Comment by snblickhan** [comment]
To follow on Jim's post above, I'll note using the (-) key additionally causes the cursor to jump to the start of the text box. There does not seem to be any way to actually type (-) at this point. 

Backspace works to delete text, but arrow keys don't allow you to move around in your transcription.

**Comment by beckyrother** [comment]
I'm honestly not sure what the solution is here. Seems like if it's possible to disable page events while the text input is active, that's kind of what other apps (github, for example) have been doing. 

The complication would be if someone wanted to zoom in using the keyboard during transcription – is that something that would come up often that we need to do something different to default behavior?

**Comment by srallen** [comment]
I have a possible fix in #1641

**Comment by eatyourgreens** [comment]
After converting PFE to use `React.Portal` for modals, we encountered bugs where clicking in a modal fires `onClick` on its container in the React tree. It turned out that portal events propagate up the component tree, not the DOM, in the React event system. Maybe that’s what’s happening here. 

I can dig out those PRs to see how we fixed it.

**Comment by srallen** [comment]
I fixed the immediate bug by white listing the elements we expect the keydown event to trigger pan/zoom, svg and button, to prevent the text input from calling those handlers, but this could use another iteration. If any other improvements are to be made, please do open an issue to track it.
