### ISSUE TITLE
Classifier: Transcription line tool is broken on touch screens

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1640]
**Package**
lib-classifier

**Describe the bug**
Tapping twice on a touchscreen should place the start and end points of a transcription line, but only places the start point.

**Expected behavior**
The second `pointerDown` event on the drawing surface should place the end of the line, and mark it as finished (or open the subtask box, because the line isn't finished until text has been entered?)

**Additional context**
I've reproduced this on an iPhone, but it should happen on any touch device: iOS or Android. The underlying cause is that I wrote the `TranscriptionLine` tool so that it depends on `pointerMove` in order to place the end of the line. This works with a trackpad or mouse (`pointerDown -> pointerUp -> pointerMove -> pointerDown`), but not with touch (`pointerDown -> pointerUp -> pointerDown`.) The fix is probably to abstract event handling, during mark creation, so that `pointerDown` on the drawing surface is passed down to the active mark, which then figures out how to handle it.

**Comment by srallen** [comment]
@wgranger would you have time to have a look at this as part of your ~50% on monorepo this week?

**Comment by wgranger** [comment]
Some of the fixes when resolving https://github.com/zooniverse/front-end-monorepo/issues/1546 will likely affect how this is implemented. Chrome gives focus to items drawn with a touch event, which automatically opens a subtask window in the current code. That means the first transcription dot drawn with a touch automatically opens the subtask.

**Comment by srallen** [comment]
@wgranger do you have capacity to follow up on this now? Thanks!

**Comment by wgranger** [comment]
I can take a look at this later this week. I need to get caught up on some mapping viz tools stuff early this week as I've been away from it for a while.

**Comment by srallen** [comment]
That's ok. It's a known issue already and we can let people know while we're doing the alpha testing.
