### ISSUE TITLE
Classifier: Seabird Watch subjects are rejected as invalid.

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1644]
**Package**
lib-classifier

**Describe the bug**
Some [Seabird Watch](https://frontend.preview.zooniverse.org/projects/penguintom79/seabirdwatch/classify) subjects are rejected by the store as invalid.

Loading the project in the dev classifier (http://localhost:8080/?project=478&workflow=251&env=production), it looks like the locations array is rejected as invalid.
```
at path "/locations" snapshot `[{"image/jpeg":"https://static.zooniverse.org/seabird-watch-2017/MITTa2015b/MITTa2015b_008164.JPG"}]` is not assignable to type: `SubjectLocations` 
(:8080/Value does not respect the refinement predicate), expected an instance of `SubjectLocations` or a snapshot like `SubjectLocations` instead.
at path "/locations" snapshot `[{"image/jpeg":"https://static.zooniverse.org/seabird-watch-2017/MITTa2015b/MITTa2015b_008164.JPG"}]` is not assignable to type: `SubjectLocations` 
(:8080/Value does not respect the refinement predicate), expected an instance of `SubjectLocations` or a snapshot like `SubjectLocations` instead.
```

**Comment by eatyourgreens** [comment]
The problem might be that `.JPG` isn't an allowed file extension.
https://github.com/zooniverse/front-end-monorepo/blob/50e04dafddf3e2eed4d880722b0a055f575e1b82/packages/lib-classifier/src/helpers/validateSubjectLocations/validateSubjectLocations.js#L3-L15

**Comment by AnansiOmega** [comment]
Hey is this issue still open? If so I'd love to work on it ( guidance would be appreciated.) This is my first time working on open source.

**Comment by eatyourgreens** [comment]
Hi @AnansiOmega and thanks for offering to help. This issue is still open.

I think that what it needs is for one of the broken URLs needs to be added to the tests, so add `{ 'image/jpeg': https://static.zooniverse.org/seabird-watch-2017/MITTa2015b/MITTa2015b_008164.JPG}` to the list of valid URLs in
https://github.com/zooniverse/front-end-monorepo/blob/a173d5767682acd0c509364c2637cd6926bd5832/packages/lib-classifier/src/helpers/validateSubjectLocations/validateSubjectLocations.spec.js#L3-L16

Then the check for a valid file extension probably needs to be updated so that it works for uppercase and lowercase file extensions.
https://github.com/zooniverse/front-end-monorepo/blob/a173d5767682acd0c509364c2637cd6926bd5832/packages/lib-classifier/src/helpers/validateSubjectLocations/validateSubjectLocations.js#L23-L25

**Comment by AnansiOmega** [comment]
@eatyourgreens Hey is it alright if I have questions? I added in '{ 'image/jpeg': https://static.zooniverse.org/seabird-watch-2017/MITTa2015b/MITTa2015b_008164.JPG}' to the validSubjectLocations, but since this is my first time I'm unsure on whether it's alright (all of the other URLs are foobar and this one is a url.)
Furthermore, this is a little embarrassing, but how do I run that file so that I can hit a debugger? ( I assume we are getting the error because the file type is .JPG, and we only accept .jpg/.jpeg.)
A solution could be as simple as just adding in:
``` packages/lib-classifier/src/helpers/validateSubjectLocations/validateSubjectLocations.js

(line 9)  'image/jpeg': ['.jpg', '.jpeg', '.JPG'],
```


into the file extensions. Another solution could be:
```packages/lib-classifier/src/helpers/validateSubjectLocations/validateSubjectLocations.js

(line 24)    return url.endsWith(extension.toLowerCase())
```

Apologies if this is messy.

**Comment by AnansiOmega** [comment]
> @eatyourgreens Hey is it alright if I have questions? I added in '{ 'image/jpeg': [https://static.zooniverse.org/seabird-watch-2017/MITTa2015b/MITTa2015b_008164.JPG}](https://static.zooniverse.org/seabird-watch-2017/MITTa2015b/MITTa2015b_008164.JPG%7D)' to the validSubjectLocations, but since this is my first time I'm unsure on whether it's alright (all of the other URLs are foobar and this one is a url.)
> Furthermore, this is a little embarrassing, but how do I run that file so that I can hit a debugger? ( I assume we are getting the error because the file type is .JPG, and we only accept .jpg/.jpeg.)
> A solution could be as simple as just adding in:
> 
> ```js
> (line 9)  'image/jpeg': ['.jpg', '.jpeg', '.JPG'],
> ```
> 
> into the file extensions. Another solution could be:
> 
> ```js
> (line 24)    return url.endsWith(extension.toLowerCase())
> ```
> 
> Apologies if this is messy.

Used { 'image/jpeg': 'https://www.foobar.org/example.JPG' }
instead of the actual url

**Comment by eatyourgreens** [comment]
Hi,

The dummy subject URL looks fine to me. To try out your changes, first [run the bootstrap script](https://github.com/zooniverse/front-end-monorepo/blob/master/README.md#getting-started) to install and build everything, then run the classifier tests with
```sh
cd packages/lib-classifier
yarn test
```

I think you're right that the best solution would be one that catches any uppercase filename, not just `.JPG`.

**Comment by AnansiOmega** [comment]
Hey it looks like I got it working! Do I just run ```git add. ``` and ```git push```  and wait for review?

**Comment by eatyourgreens** [comment]
Thanks again for taking the time to do this!

You won't be able to add changes directly to the master branch, so you'll need to create a new branch first, then push that. The commands will be something like these, where `branch-name` is a name that you choose for your new branch. You'll also need to add a commit message describing your change.
```sh
git checkout -b branch-name
git add .
git commit -m 'Describe your changes here.'
git push --set-upstream origin branch-name
```

After you've pushed your new branch, GitHub should give you the option to open a new pull request. Once you've done that, we should get a notification and you can wait for a review.

**Comment by AnansiOmega** [comment]
I tried to push but I am getting an error of:
 'ERROR: Permission to zooniverse/front-end-monorepo.git denied to AnansiOmega.
fatal: Could not read from remote repository.'
I assume it's from my end. Here's what I did: 
```
anansi@Ignass-MacBook-Air lib-classifier % git checkout -b urlValidations
Switched to a new branch 'urlValidations'
anansi@Ignass-MacBook-Air lib-classifier % git add .
anansi@Ignass-MacBook-Air lib-classifier % git commit -m 'added dummy url that ends with .JPG and adjusted func validateSubjectLocations to downcase all urls, test are now passing'
[urlValidations 09adc208] added dummy url that ends with .JPG and adjusted func validateSubjectLocations to downcase all urls, test are now passing
 2 files changed, 3 insertions(+), 2 deletions(-)
anansi@Ignass-MacBook-Air lib-classifier % git push --set-upstream origin urlValidations
ERROR: Permission to zooniverse/front-end-monorepo.git denied to AnansiOmega.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by eatyourgreens** [comment]
Sorry. I missed a step. You won’t have permission to modify Zooniverse repos directly.  You’ll need to fork this repo to your GitHub account, push the changes to your fork and then you should be able to open a PR from your fork. 

https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo

**Comment by AnansiOmega** [comment]
Done and done. That was fun.

**Comment by eatyourgreens** [comment]
Thanks very much! Could you do just one last thing for us? Go to https://github.com/AnansiOmega/front-end-monorepo/tree/urlValidations and click on the grey pull request link to open a new PR. Then we'll be able to review it.
![Screenshot of a github branch, showing the location of the PR button.](https://user-images.githubusercontent.com/59547/100909576-d19e9f00-34c4-11eb-9db2-b155e790f808.png)

**Comment by AnansiOmega** [comment]
I did it, let me know if it went through.

**Comment by eatyourgreens** [comment]
Looks good to me. Just waiting for the CI tests to pass now.
