### ISSUE TITLE
Consensus UI

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1660]
**Package** lib-classifier

For the text transcription feature, the [user stories](https://docs.google.com/document/d/16abI-wkRlEXsWgACfFQVqwO76aEopohIjQiRfNQKWiw/edit) include

> As a user I want to be able to read completed (greyed-out) transcriptions.

This is an enhancement over the ASM version where there was just a tooltip that displayed text saying the line is complete. However, volunteers wanted to see which lines went into the retirement. The aggregation code has been updated to support this, so it's now just a matter of having a UI to display this.

In past in person meetings, we decided the UI should be similar to the sub-task UI, a movable modal and in the modal content area, the consensus text and the transcriptions that went into it would be displayed. We don't have a specific invision design for this, but we may not necessarily need one. We can coordinate with @beckyrother as questions arise.

**Comment by beckyrother** [comment]
InVision attached: https://projects.invisionapp.com/d/main#/console/12923997/420788232/preview

Classifications are listed with clear text explaining what this text is and why it can't be interacted with

**Comment by srallen** [comment]
Closed by #1683
