### ISSUE TITLE
Fix arrow direction with headless tippy tooltip

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1675]
**Package** lib-react-components

**Describe the bug**

Can be demonstrated on with the react components stories. Since upgrading and switching to headless tippy.js react, the arrow direction doesn't automatically change based on the position of the tooltip.

**Comment by goplayoutside3** [comment]
I think this is fixed based on the tooltip [story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/react-components/index.html?path=/story/components-tooltip--tip-moves-when-close-to-the-viewport-edge).
