### ISSUE TITLE
Drawing tools: users can tab-navigate across inert drawing marks

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#1684]
## UI/UX Bug

Package: `lib-classifier`
Initially discussed in #1677 

When existing drawing marks are _inert_ (i.e. they cannot be interacted with, because they were made in a previous Workflow step), you can still tab-navigate across them.

- Basically, inert drawing marks can get keyboard focus even though they're supposed to be _inert._
- Inert drawing marks continue to be otherwise un-interactive, though - click-dragging doesn't move the mark, clicking doesn't open the sub-task popup (for drawing tools with sub-tasks) 👌 
- Expectation: inert drawing marks should not be able to get keyboard focus.

Sub-problem:

- Even _if_ we want inert drawing marks to be able to be tab-navigable, it's nigh impossible to visually tell which inert drawing mark has focus.

<img width="836" alt="Screen Shot 2020-06-19 at 18 03 53" src="https://user-images.githubusercontent.com/13952701/85162147-c4645f80-b258-11ea-9815-309b2acfad3b.png">
_The green Point marks on the Subject are inert (note the shape of the marks are different from marks that can be interacted with) but they can still receive focus._

### Testing

Setup:
- Create a workflow with 2 steps
  - Step 1: a drawing task, with 1 drawing tool (e.g. Point)
  - Step 2: any other task (e.g. a single answer question)

Actions:
- On Step 1, draw ~7 marks on the Subject.
- Proceed to Step 2.
- On Step 2, attempt to tab-navigate from, say, the Login button at the header, to the Annotate button on the image toolbar.
- Expected: it should take only ~1 press of the tab key to traverse from the Login button to the Annotate button
- Actual: it takes about ~7 presses to traverse. This number will be proportional to the number of marks made in Step 1.

Test on `http://localhost:8080/?env=staging&project=1898&workflow=3396` on macOS 10 + Chrome 83

### Recommendation

Off the top of my head: in `src/plugins/drawingTools/components/Mark/Mark.js`...

- add a new property called `inert` or `uninteractive` or `cantTouchThis` (hammer time!)
- When `inert === true`, remove the `tabIndex={0}` property of the rendered `StyledGroup`. Uh, or maybe `tabIndex={undefined}`? I haven't thought this through.

### Status

This is a minor issue in terms of functionality, but a more notable issue for accessibility, as it may become _very confusing_ to people who rely on keyboards to navigate through the Classifier.

**Comment by eatyourgreens** [comment]
I wrapped marks in a decorator that makes them interactive, so `tabIndex` could be moved into that?

**Comment by eatyourgreens** [comment]
Or an easier option. Pass `tabIndex` as -1 or undefined here, where previous marks are rendered.
https://github.com/zooniverse/front-end-monorepo/blob/ce5e192301237f242c0f772423fbfc22ffdc87f0/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js#L78-L82

Pass in `tabIndex=0` here, where the marks are rendered for the active task.
https://github.com/zooniverse/front-end-monorepo/blob/ce5e192301237f242c0f772423fbfc22ffdc87f0/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js#L112-L123

**Comment by goplayoutside3** [comment]
I think this is fixed. I'm not able to replicate on [Elephant ID](https://www.zooniverse.org/projects/aeuk/elephant-id/classify).
