### ISSUE TITLE
Mobx store base class for API resources

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#17]
_From @rogerhutchings on March 12, 2018 11:52_

Panoptes resources (project, classification and whatnot) are going to share some common methods for CRUD interactions - given that stores are just classes, we could create a base class containing those methods and inherit from that for resource-specific stores. Given that you've done the most with Mobx, does that sound legit @srallen?

_Copied from original issue: zooniverse/panoptesjs#10_

**Comment by rogerhutchings** [comment]
_From @srallen on March 12, 2018 14:13_

@rogerhutchings, could be classes or it could be functional similar to this example: https://github.com/gothinkster/react-mobx-realworld-example-app/blob/master/src/agent.js

**Comment by srallen** [comment]
MobX-state-tree is being used for each resource requested from Panoptes with a model and store per resource. The exception may be linked translations and attached images where needed.
