### ISSUE TITLE
Layout bug for task area

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1703]
**Package** lib-classifier

**Describe the bug**
The task area just grows with the subject height

**To Reproduce**
Use the dev classifier for http://local.zooniverse.org:8080/?project=1764&workflow=3392

**Expected behavior**
The task area should have a max height and ideally have a fixed position that scrolls with the window. Check with @beckyrother what the max height should be. It's based on the average screen size of our users. 

**Screenshots**
<img width="1435" alt="Screen Shot 2020-07-07 at 11 12 19 AM" src="https://user-images.githubusercontent.com/5016731/86944853-f0fbf080-c10d-11ea-9b1f-70b49b80932f.png">

**Comment by beckyrother** [comment]
In the invision I have the max-height set to 570px. However, I don't want to force the content in the task area to scroll ([Every Name Counts](https://www.zooniverse.org/projects/cseidenstuecker/every-name-counts/classify) for example). Is there a way to account for longer tasks?
