### ISSUE TITLE
Subject image invert button

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1716]
**Package**  lib-classifier

**Describe the solution you'd like**

If enabled for a workflow, this displays a toggle to CSS color invert the subject image. Currently on PFE, it's a toggle that appears below the subject image (highlighted by me with the red square):

<img width="589" alt="Screen Shot 2020-07-20 at 11 17 22 AM" src="https://user-images.githubusercontent.com/5016731/87961249-10ced500-ca7b-11ea-9b3c-8a900c07be4f.png">

I didn't find an existing design for this. @beckyrother do you want this toggle to take a similar placement and design as the below image viewer options or to be a button in the image toolbar with the pan/zoom functions?

**Comment by beckyrother** [comment]
Thanks for asking. It should be in the toolbar
