### ISSUE TITLE
Side-by-side layout for scatterplot + image(s?)

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1717]
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**

The transients project will be a subject with one location being scatter plot JSON and another with an image. The basic layout should be side-by-side.

**Describe the solution you'd like**

We'll need to add a new container/component for this layout type. This is more likely to be reused than the VSLCV. Do we want to support up to N images in this... say 3? 

Here are some super rough wireframes of what I'm imagining:

1 scatter plot and 1 image (this is what is needed):
<img width="753" alt="Screen Shot 2020-07-20 at 11 32 37 AM" src="https://user-images.githubusercontent.com/5016731/87962440-d108ed00-ca7c-11ea-9ac2-01beaf99575f.png">

1 scatter plot and 3 images:
<img width="828" alt="Screen Shot 2020-07-20 at 11 32 01 AM" src="https://user-images.githubusercontent.com/5016731/87962468-debe7280-ca7c-11ea-8dab-5769e5c85d0a.png">

We'll initially build the 1 scatter plot and 1 image, but the latter could be a stretch goal?

Is this looking ok to you @beckyrother?

**Comment by srallen** [comment]
I'm also open on what this subject viewer type should be named! I don't think it should be "transient objects viewer" since it is likely reusable beyond this.

**Comment by beckyrother** [comment]
I think in [most mockups](https://invis.io/9WNF9M73AEN#/373473095_Combo) I've got the images on the left, but this layout makes sense here. Works for me!

Maybe "data viewer" ?
