### ISSUE TITLE
Panning image vs scatter plot

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1739]
**Package**

**Describe the bug**
How the pan up and pan down events work is reverse between the two viewer types. They use different pan/zoom implementations, so the event handlers in `SubjectViewerStore` do not behave consistently between the two.

**Comment by eatyourgreens** [comment]
The image viewer is following the original behaviour in PFE, so I guess we shouldn't change that. eg. https://www.zooniverse.org/projects/penguintom79/seabirdwatch/classify

Panning the scatter plot viewer, from the keyboard, feels quite natural to me, even though it moves in the opposite direction. I'm not sure what the right answer is here.
