### ISSUE TITLE
Allow PlainButton to set the label color prop 

### ISSUE THREAD

**Issue by wgranger** [zooniverse/front-end-monorepo#1752]
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**
The `PlainButton` component does not allow changing the text color since the label prop has a hard-coded default color value.

**Describe the solution you'd like**
We should allow the default color value to be modified through a prop that is passed in.

**Describe alternatives you've considered**

**Additional context**
This came up in a recent [PR review](https://github.com/zooniverse/mapping-viz-tools/pull/9#discussion_r468665609) in the Mapping Viz Tools repo

**Comment by beckyrother** [comment]
👋  not sure what is needed?

**Comment by srallen** [comment]
Assignee should be a dev to make the color configurable for this component. The template assigns you by default for the UX/design issue template. We could remove that?
