### ISSUE TITLE
VXZoom Keyboard Panning is Broken in Safari

### ISSUE THREAD

**Issue by wgranger** [zooniverse/front-end-monorepo#1762]
**Package** lib-classifier

**Describe the bug**
Keyboard panning doesn't work on the VXZoom component in Safari. This first came to our attention via #1749, but the bug existed before that pull request. 

**To Reproduce**
1. Using Safari, go to the lib-classifier package and open storybook
2. Click on ScatterPlotViewer/pan and zoom
3. Make sure focus is on the plot and try using the arrow keys to navigate around
4. Notice nothing will happen, although panning should work on Chrome and Firefox

**Expected behavior**
Keyboard panning should work on all major browsers to meet accessibility standards

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Mojave
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] 12.1.2

**Additional context**

**Comment by srallen** [comment]
This is working in Safari 13 and 14 and our policy is only to support current version and most recent versions of browsers. Closing.
