### ISSUE TITLE
Refactor Transcription Tool Events

### ISSUE THREAD

**Issue by wgranger** [zooniverse/front-end-monorepo#1766]
**Package**
lib-classifier

**Associated PRs**
#1735 

**What should be refactored?**
This initially arose from fixing a bug with the transcription tool being used on touch screens. That fix included using a `handlePointerDown` event to handle another mark being placed while a transcription line was in the process of being created.

From that conversation arose [two options](https://github.com/zooniverse/front-end-monorepo/pull/1735#discussion_r471783712) of how the code could be refactored to account for other tools. 

The idea is to make the code easy to follow and decouple events. Tools could also [their own](https://github.com/zooniverse/front-end-monorepo/pull/1735#discussion_r471784937) `onPointerUp` and `onFinish` handlers rather than adhering to one generic event.

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:
https://localhost:8080/?project=1764&workflow=3392
Project 1764
Workflow 3392

**Additional context**

**Comment by goplayoutside3** [comment]
I think we intentionally moved away from this plan in https://github.com/zooniverse/front-end-monorepo/pull/3431
