### ISSUE TITLE
[VSLCV] Improve styling for data series not focused when there's a lot of data

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1778]
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**
Researcher request: 

> We will have some sources that have a LOT of data (>10 x what is in the current example). When turning off a filter, is it possible to make the symbols even lighter (and possibly also transparent)?

**Describe the solution you'd like**

Perhaps we should actually consider making unfocused series invisible? This will be an underlying change that affects the `ScatterPlot`. I'll see if they can provide us with an example of what "a LOT of data" is.

**Comment by beckyrother** [comment]
I'll defer to them on this – it was my impression that showing both at once was useful, but if not I'm happy to say let's just show one or the other.
