### ISSUE TITLE
[VSLCV] Alpha testing

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1780]
**Package** lib-classifier

This is an issue to capture the initial alpha testing of the variable star light curve viewer. This can be tested here: https://frontend.preview.zooniverse.org/projects/adamamiller/stellar-sleuths/classify

If any issues are found that are not already documented as a separate issue (https://github.com/zooniverse/front-end-monorepo/milestone/36), please try to use the template below to document it.

### Bug Template

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by trouille** [comment]
Mac OS Mojave v10.14.6, with Chrome v84

Minor: the temp-luminosity plot axes are labeled, but then the x-axis label (temperature) is repeated below. 

Minor: when you enable zoom (on either plot), there's a funny movement of the screen when you move the cursor around. Here's a [ video ](https://drive.google.com/file/d/1sog07cwD-31A05QUEoGZpoBVT_lQgPbS/view?usp=sharing) showing the behavior since it's a bit hard to describe. 

Question: When you click the 'visibility' options, should just the color go away, or should the point+color go away?

**Comment by trouille** [comment]
It'll be good to hear from the researchers if the way zoom is working in the plots is as they need/want/expect.

**Comment by eatyourgreens** [comment]
Minor display bug: the tooltip isn't positioned properly for the bar chart in Firefox. I think there's already an issue open for this. I triggered this after scrolling the viewport down a bit, which seems to throw off the position calculation.

![Screenshot in Firefox, showing that the bar chart tooltip is displaced below and to the right of the focussed bar.](https://user-images.githubusercontent.com/59547/91970567-c2665480-ed0f-11ea-85d9-274b5a90009e.png)

**Comment by srallen** [comment]
Yes, we have an open issue for the positioning bug in Firefox. Please check the existing issues first: https://github.com/zooniverse/front-end-monorepo/milestone/36. I'd like this to be new feedback. Thanks!

**Comment by srallen** [comment]
> Minor: the temp-luminosity plot axes are labeled, but then the x-axis label (temperature) is repeated below.

The fig caption is now "HR Diagram"

> When you click the 'visibility' options, should just the color go away, or should the point+color go away?

Resolved by making the label "highlight" instead of "visibility"

> when you enable zoom (on either plot), there's a funny movement of the screen when you move the cursor around. Here's a video showing the behavior since it's a bit hard to describe.

Looks like overflow is being shown / hidden on the document body throughout that. I don't think this actually has anything to do with the VSLCV, but coincidence that you happened to see this... I think there's a Grommet bug causing this as I observed it with the text transcription tools. 

The tooltip bug has its own issue, so I'm closing this as everything is addressed or documented if necessary separately.
