### ISSUE TITLE
Branching workflow previous functionality

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#1781]
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**
Complex workflows including branching tasks don't go to previous step as expected.

**Describe the solution you'd like**
Clicking Previous goes to previous Step.

**Additional context**
Iteration from #1758, related to #687.

**Comment by eatyourgreens** [comment]
I've got an idea for implementing this with either the [UndoManager](https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mst-middlewares/README.md#undomanager) or [TimeTraveller](https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mst-middlewares/README.md#timetraveller) middleware. I might look into that this week.
