### ISSUE TITLE
[VSLCV] Swap position of the controls so that they appear above the bar charts

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1783]
**Package** lib-classifier

**Is your feature request related to a problem? Please describe.**

Researcher feedback: The scatter plots are the most important piece of data for classification, so we have a request to optimize the space and move the controls to be above the bar chart area.

**Comment by beckyrother** [comment]
@srallen This would ostensibly vertically shrink the bar chart (and possibly the HR diagram?) possibly making the bar chart more difficult to read – is that ok with the researchers?

**Comment by srallen** [comment]
@beckyrother I think so, but when I attempted this, the column size of where the bar charts are isn't wide enough, so the only solutions I could see is to widen the bar chart column, which shifts the width of the scatter plots or to stack the controls, which *really* would vertically shrink the bar chart and image. I'm not sure if this is viable... I'll get some screenshots shortly to show what I mean.

**Comment by srallen** [comment]
@beckyrother so here's what happens:

<img width="905" alt="Screen Shot 2020-09-28 at 3 17 12 PM" src="https://user-images.githubusercontent.com/5016731/94482741-615f5e80-019f-11eb-9079-96dcc92df0ef.png">

At certain wide screens, it's fine, but very quickly has an issue. The columns on the grid area are 2/3, 1/3, so we can try 1/2 and 1/2, but that decreases the width of the scatter plots more than we gain in height I think:

<img width="899" alt="Screen Shot 2020-09-28 at 3 18 01 PM" src="https://user-images.githubusercontent.com/5016731/94482826-818f1d80-019f-11eb-8efb-f07a02300c9d.png">

I think wider is more important here. We could explore allowing more height for the controls and stacking them (this is a rough idea):

<img width="901" alt="Screen Shot 2020-09-28 at 3 21 06 PM" src="https://user-images.githubusercontent.com/5016731/94482882-97044780-019f-11eb-8968-b7e8a53187fb.png">

But I think what we should likely do is not make the change at all and recommend against it.

**Comment by srallen** [comment]
Closing this issue unless there's reason to continue working on the layout.
