### ISSUE TITLE
Project: reduce network requests from the Hero component

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1803]
**Package**
app-project

**Is your feature request related to a problem? Please describe.**
The project Hero component makes API requests for a project's active workflows when it mounts. Linked subject sets are also loaded, even if the project home page doesn't display them.
https://github.com/zooniverse/front-end-monorepo/blob/672df219cdd67a7b6d17896fda353c943d68244a/packages/app-project/src/screens/ProjectHomePage/components/Hero/HeroContainer.js#L28-L30

To see this, try the following with the Network tools open. Look for API requests that fetch `workflows` and `set_member_subjects`.
1. Visit https://frontend.preview.zooniverse.org/projects/zookeeper/galaxy-zoo
1. Click through to classify.
1. Click the link back to the project home page.

**Describe the solution you'd like**
Active workflows should be requested once. The request isn't authenticated, so could be made on the server.

Ideally, subject sets should only be requested by projects that use grouped workflows (but we don't know if workflows are grouped until we've requested them from the API.)

**Comment by srallen** [comment]
Another option would be to store a snapshot of the store in localStorage or IndexedDB, check for the existence of this prior to making the request, and load up the snapshot if it exists rather than make the requests. This is the strategy we're planning for the classifier. If we use a snapshot, we can preload via snapshot into the classifier store as well? We would have to make sure the store trees matched between the project app and classifier.

**Comment by eatyourgreens** [comment]
PH-TESS is out of data at the moment, so not loading workflows, but Galaxy Zoo makes four extra requests for subject  sets linked to its workflows. It'd be nice to defer those unless a project is actually using subject set selection.
https://fe-project.zooniverse.org/projects/zookeeper/galaxy-zoo

![Screenshot of the network tab on the new Galaxy Zoo home page, showing requests for set_member_subjects.](https://user-images.githubusercontent.com/59547/93446523-39334e00-f8c9-11ea-8edb-f6ea2f10b81e.png)
