### ISSUE TITLE
Specify response headers for next.js apps

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1807]
**Package** app-project, app-content-pages

**Is your feature request related to a problem? Please describe.**

Related to the caching issues we've seen, we discovered that the static assets do not have cache control headers set on their response from next.js

**Describe the solution you'd like**
As of next.js 9.5, we can customize the headers: https://nextjs.org/docs/api-reference/next.config.js/headers

What precisely should the headers be?

**Comment by eatyourgreens** [comment]
#1812 copies over the server setup from the content pages app, which should include cache control headers.
