### ISSUE TITLE
Explicitly clear cache via jenkins task

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1808]
**Package** all

**Is your feature request related to a problem? Please describe.**

An idea while debugging the caching issues. Can we have a jenkins task purge frontdoor cache? Should this be part of a deploy?

**Describe the solution you'd like**

Let's explore the possibilities of CI for this.

**Describe alternatives you've considered**

We've set the TTL config to be 60s, but maybe it doesn't need to be if we programmatically clear cache at the end of a deploy automatically. 

**Additional context**

**Comment by camallen** [comment]
closing this in favour or #1818, specifically allow the origin server to specify cache headers for auto CDN cache expiration.
