### ISSUE TITLE
NextJS: add SSL for local development

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1813]
**Package**
app-content-pages
app-project

**Is your feature request related to a problem? Please describe.**
http://localhost.zooniverse.org:3000 redirects to https://localhost.zooniverse.org:3000 in Chrome. Try it here in a local copy of the project app:
http://localhost.zooniverse.org:3000/projects/zookeeper/galaxy-zoo/classify?env=production

**Describe the solution you'd like**
We could add a certificate to the local dev server. At the moment, the workaround is to either use http://localhost:3000 or use Firefox (if you need to test with CORS requests on a Zooniverse domain.)

**Comment by eatyourgreens** [comment]
Both Chrome and Firefox now respect HTTP Strict Transport Security for `*.zooniverse.org` so self-signed certificates won't work for local development.

> localhost.zooniverse.org has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

**Comment by srallen** [comment]
Done for project app in https://github.com/zooniverse/front-end-monorepo/pull/2310
