### ISSUE TITLE
Bug with drawing sub-task resizing

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1833]
**Package** lib-classifier

**Describe the bug**

From the transcription task alpha testing: https://github.com/zooniverse/front-end-monorepo/issues/1719#issuecomment-662037815

> If you drag the box to the edge of the page and then use the resize button, the 'save' button gets very big. I think this will be a very rare event and it's easy to 'x' it closed and restart the text box by clicking on the line again, but just wanted to note. (In Chrome on Mac os)

**To Reproduce**

**Expected behavior**

Sub-task should resize correctly and not grow or shrink elements inside the area incorrectly.

**Screenshots**

![image](https://user-images.githubusercontent.com/5016731/94957987-616ba100-04b4-11eb-9c8a-273b696e4930.png)

**Additional context**

We're hoping to get more info for this during beta testing.

**Comment by snblickhan** [comment]
Adding my own experience as I test the beta project setup (Mac OS Catalina, Chrome browser).
- This behavior happens every time I try to resize the **transcription box** using the box resize tool
- Note: this does NOT happen if I use the text box resize tool; that resizes as expected
- When this happens, the Save button takes over the entire transcription box (text entry box disappears completely) as in the example posted above
- There does not seem to be a way to resize the transcription box (using the box resize tool) without this happening

Just flagging, as the original post stated, "If you drag the box to the edge of the page and then use the resize button, the 'save' button gets very big" but my experience was that this happened every time I tried to use the box resize button, not just if I'd dragged it somewhere.

**Comment by srallen** [comment]
Linked Sentry issue likely a red herring: https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded

**Comment by srallen** [comment]
Removing the GoldButton used here fixed the issue with the button resizing and covering up the text. There may be some additional refactors we want to do with the sizing of the pop up, but the immediate bug noted in this issue is fixed.
