### ISSUE TITLE
Text task with suggestions sometimes shows list above input

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1834]
**Package** lib-classifier

**Describe the bug**

From the text transcription alpha testing https://github.com/zooniverse/front-end-monorepo/issues/1719#issuecomment-662751492:

> The dropdown options sometimes appear awkwardly: above the text box, covering the instructions; dropdown options list extends beyond the boundary of the subtask modal. Neither are serious issues, only suboptimal.

**To Reproduce**
Open up the sub-task close to a window edge.

**Expected behavior**

This is default Grommet behavior for responsiveness with the text input that has suggestions defined.

**Screenshots**

![image](https://user-images.githubusercontent.com/5016731/94958364-05554c80-04b5-11eb-8da1-f4184bfd1032.png)

**Additional context**

We could request to have this configurable with the Grommet library?

**Comment by goplayoutside3** [comment]
I think this is fixed. The modal with suggestions always appears with enough room to show the options list below the text input. Example project: https://www.zooniverse.org/projects/blicksam/transcription-task-testing/classify
