### ISSUE TITLE
mobx-react v.6.1.4 breaks classifications without annotations on the first subject

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1839]
**Package**
lib-classifier

**Describe the bug**
>I have been having an issue where the buttons under the "Task" tab all seem to disappear after I classify three charts, meaning that even if I see transits to be classified, I can't because I am forced to reload the whole page. It is particularly strange because it still loads a new chart and everything else, just none of the buttons to indicate I am done with a classification. I have also had intermittent issues with the test charts, in that it sometimes does not pick up that I have marked transits at all, even when I have (accuracy notwithstanding). The only reason I mention this is that the test chart glitch seems to happen in tandem with the buttons disappearing after I submit the chart, and it makes me worry that my other classifications are also being submitted blank.
>
>I have tried using a different browser (I primarily use Chrome, switched to Edge), clearing my cache and cookies, disabling browser extensions, but it does not seem to help. I would really like to continue helping out. Is this an issue on my end, or have I stumbled on some sort of glitch?
https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk/2108/1647967

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:
Project 7929
Workflow 11235

**Expected behavior**

**Screenshots**
Screenshot from volunteer `@ssh`
![Screenshot of a PH-TESS light curve with no classification tools or submission buttons shown in the Tasks panel.](https://user-images.githubusercontent.com/59547/95013160-4d4fad00-0636-11eb-9a9c-0ceb286fb6e9.png)

**Desktop (please complete the following information):**
Fedora 34: Firefox Nightly 83.0a1 (2020-10-01)
Windows 10: Chrome 85.0.4183.121 - Firefox 81.0.1 - Edge 44.19041.423.0

**Comment by eatyourgreens** [comment]
I've been trying to identify the commit that introduced this bug, but I've been unable to reproduce the bug itself in the dev classifier: https://localhost:8080/?project=7929&workflow=11235&env=production

**Comment by eatyourgreens** [comment]
The Sentry stack trace from one of the Chrome errors shows store reference errors:
```
Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. 
(Object type: '(Graph2dRangeXAnnotation)[]', 
Path upon death: '/classifications/resources/ckfwbzmhl00003b6du21e5e6w/annotations/ckfwbzmi800013b6de4lthixn/value', 
Subpath: '', 
Action: '/classifications/resources/ckfwbzmhl00003b6du21e5e6w/annotations/ckfwbzmi800013b6de4lthixn/value.@APPLY_SNAPSHOT()'). 
Either detach nodes first, or don't use objects after removing / replacing them in the tree.

arguments: [{"message":"[mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type: '(Graph2dRangeXAnnotation)[]', Path upon death: '/classifications/resources/ckfwbzmhl00003b6du21e5e6w/annotations/ckfwbzmi800013b6de4lthixn/value', Subpath: '', Action: '/classifications/resources/ckfwbzmhl00003b6du21e5e6w/annotations/ckfwbzmi800013b6de4lthixn/value.@APPLY_SNAPSHOT()'). Either detach nodes first, or don't use objects after removing / replacing them in the tree.","name":"Error","stack":"Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type: '(Graph2dRangeXAnnotation)[]', Path upon death: '/classifications/resources/ckfwbzmhl00003b6du21e5e6w/annotations/ckfwbzmi800013b6de4lthixn/value', Subpath: '', Action: '/classifications/resources/ckfwbzmhl00003b6du21e5e6w/annotations/ckfwbzmi800013b6de4lthixn/value.@APPLY_SNAPSHOT()'). Either detach nodes first, or don't use objects after removing / replacing them in the tree.\n    at https://fe-project.zooniverse.org/_next/static/chunks/38ad93ee305ec30fdfe47b59c02a2f57c5be2b8d.6be8ceb90e2757bc4759.js:1:93841\n    at e.assertAlive (https://fe-project.zooniverse.org/_next/static/chunks/38ad93ee305ec30fdfe47b59c02a2f57c5be2b8d.6be8ceb90e2757bc4759.js:1:93876)\n    at e.getChildren (https://fe-project.zooniverse.org/_next/static/chunks/38ad93ee305ec30fdfe47b59c02a2f57c5be2b8d.6be8ceb90e2757bc4759.js:1:94650)\n    at Array.e.willChange (https://fe-project.zooniverse.org/_next/static/chunks/38ad93ee305ec30fdfe47b59c02a2f57c5be2b8d.6be8ceb90e2757bc4759.js:1:120854)\n    at be (https://fe-project.zooniverse.org/_next/static/chunks/38ad93ee305ec30fdfe47b59c02a2f57c5be2b8d.6be8ceb90e2757bc4759.js:1:192225)\n    at t.spliceWithArray (https://fe-project.zooniverse.org/_next/static/chunks/38ad93ee305ec30fdfe47b59c02a2f57c5be2b8d.6be8ceb90e2757bc4759.js:1:194880)\n    at Proxy.replace (https://fe-project.zooniverse.org/_next/static/chunks/38ad93ee305ec30fdfe47b59c02a2f57c5be2b8d.6be8ceb90e2757bc4759.js:1:1961..."}]
```

**Comment by eatyourgreens** [comment]
This seems to have been caused by #1820 and can be reproduced by submitting a classification with no annotations ie. press the Done button without marking.

**Comment by srallen** [comment]
Noting here that this affects all task types.

**Comment by srallen** [comment]
Closing since issue cannot be replicated since #2009
