### ISSUE TITLE
Highlight function not working

### ISSUE THREAD

**Issue by adamamiller** [zooniverse/front-end-monorepo#1847]
**Package**

**Describe the bug**
Un-selecting the g and r band data does not make the points grey and semi-transparent.

**To Reproduce**
Go to https://frontend.preview.zooniverse.org/projects/adamamiller/stellar-sleuths/classify - click the check box near g band or r band, and the data will remain unchanged.

**Expected behavior**
Un-checking any of the filters should remove their color and make them grey.

**Screenshots**
![image](https://user-images.githubusercontent.com/2434744/95636795-b16ada80-0a55-11eb-84ee-51030a6c3397.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Firefox v 80.0.1

**Comment by adamamiller** [comment]
@srallen Thanks for this update. This function works now when I test it on Mac OS + Chrome. 

I know you just closed this issue, but, I have also tested this on Mac OSX + Firefox and Safari - and for both of those browsers the highlight button does not behave as expected. Should we just proceed for now?

**Comment by srallen** [comment]
@adamamiller the build and deploy takes a few minutes which the merge action triggers. Depending on when you looked at them, it might have been the old javascript still. I just merged #1850, and thus has triggered another CI deploy so we'll give it a few more minutes. I'll message when it's all up to date and we can have a thorough look at that time.
