### ISSUE TITLE
Error in TaskInputLabel

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#185]
**Package**

lib-classifier

**Feature or Issue Description**

React is throwing the following error:

> Warning: React does not recognize the `labelIcon` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `labelicon` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by srallen** [comment]
I think this is fixed in #184. I'll double check.

**Comment by srallen** [comment]
Fixed in #184
