### ISSUE TITLE
[VSLCV] Highlight should move data to the "background"

### ISSUE THREAD

**Issue by adamamiller** [zooniverse/front-end-monorepo#1851]
**Package**

VSLCV

**Is your feature request related to a problem? Please describe.**

The highlight feature is an extremely useful way to focus on a single filter in the light curve viewer. Right now the observations are plotted such that the first filter is plotted, then the second (and in the future subsequent) filters are plotted "on top" of the first filter. If the highlight button is used to de-emphasize the 2nd filter, those points are still shown "on top" of the first light curve. See the screenshot below.

![image](https://user-images.githubusercontent.com/2434744/96157831-6bd86280-0ed8-11eb-8437-1f2f1ebb2c15.png)

**Describe the solution you'd like**
It would be nice if observations that are not being highlighted "recede" to the background. In the screenshot above it is much easier to see the "g" band observations than it is when both filters are shown:
![image](https://user-images.githubusercontent.com/2434744/96158010-a5a96900-0ed8-11eb-9498-0f40424cfe31.png)

However, focusing on just r is much easier than just g because the g band observations are "behind" the r-band observations (when r is the only filter highlighted): 

![image](https://user-images.githubusercontent.com/2434744/96158118-c5d92800-0ed8-11eb-9ad8-d2a9cf235e07.png)

**Describe alternatives you've considered**
If this request leads to performance issues (because the entire plot would need to be re-rendered every time then this feature may not be worthwhile. 

**Additional context**
This feature is *not required* prior to the planned upcoming beta test. But it would be nice to have before the project goes fully live before the public.

**Comment by srallen** [comment]
The z-index of SVG elements is determined by its rendering order, so right now, the data points are programmatically rendered in the array order that they're supplied in the subject JSON. There may be a way to manipulate this via CSS however.

**Comment by srallen** [comment]
@adamamiller this is now fixed and deployed.
