### ISSUE TITLE
Zwicky Stellar Sleuths subject upload error

### ISSUE THREAD

**Issue by trouille** [zooniverse/front-end-monorepo#1856]
Adam Miller posted this in the Zwicky Stellar Sleuths private talk board pre-beta:

Michael Coughlin trying to upload a subject set, which has been created in the same way we create all other subject sets, and we are getting an error we do not understand regarding the loading of the data:

Got session mcoughlin 1378001

static.zooniverse.org/www.zooniverse.org/static/favicon.ico:1 Failed to load resource: the server responded with a status of 403 ()

instrument.js:110 Loading subject 50837812

static.zooniverse.org/www.zooniverse.org/static/touch-icon.png:1 Failed to load resource: the server responded with a status of 403 ()

10Error: <rect> attribute transform: Expected number, “translate(NaN, 1)“.

10Error: <rect> attribute width: Expected length, “NaN”.

Do you have any idea what is going on in this case? Subject set #88646

Thanks.

=====

**Package**

**Describe the bug**

**To Reproduce**

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lcjohnso** [comment]
Likely connected to https://github.com/zooniverse/front-end-monorepo/issues/1845
