### ISSUE TITLE
Classifier: Enable subject selection by subject ID in the subjects store

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1876]
**Package**
lib-classifier

**Is your feature request related to a problem? Please describe.**
When a subject ID is passed into the classifier as a prop, that subject should be loaded into the store and shown as the first classification subject.

When a workflow has prioritised (sequential) selection enabled, subsequent subjects in the queue should follow on from the selected subject eg. if I select page 15 from a volume, I'd expect pages 16, 17 etc. to follow in the queue.

**Describe the solution you'd like**
I'll open an issue on Panoptes for the server-side component for this, but we could pass the subject ID when making a request to `/api/subjects/queued`.

Alternatively, we could wait until the specified subject has been classified before requesting the rest of the queue. I think that should work, since prioritised selection ought to send back subjects based on the last subject that you classified.

**Comment by camallen** [comment]
here is a linked issue that describes a part of your use case, the subject context before / after. https://github.com/zooniverse/panoptes/issues/2043 and this was a start on the feature, https://github.com/zooniverse/panoptes/pull/3156

I could see that end point supporting query params, say `?start_index=0` to change the selection ordering from a middle point (default), e.g. 
` /subjects/:id/sequential?start=0&limit=4 -> [ SUBJECT_ID, A1, A2, A3, A4 ]`

the above could support the surrounding subjects, 'context', feature as well as this use case of show me here onwards. thoughts?

**Comment by eatyourgreens** [comment]
I think that would work. The subjects endpoint would have to be abstracted out of the classifier store in `subjects.populateQueue()`, maybe by having workflows implementing different queue population strategies.
https://github.com/zooniverse/front-end-monorepo/blob/c4f819c2269a9a3937d2f37f447778e593bf635a/packages/lib-classifier/src/store/SubjectStore.js#L160-L173

**Comment by eatyourgreens** [comment]
We may also have the subjects cached already, since the project home page is going to show volunteers a paged, ordered list of subjects, from a single subject set. They then pick a single subject to start classifying from but we could initialise the classifier with 10 subjects from that list.

**Comment by eatyourgreens** [comment]
Another option would be to request subjects from `/queued`, then filter out everything prior to the selected subject. We'd have to make sure not to start too close to the end of the queue. Refreshing the queue at this point would return exactly the same list of subjects again, possibly putting the queue into a loop of refreshing, filtering and refreshing again. Maybe request `N + 10` subjects from `/queued`, where `N` is the number of subjects available to be picked?
