### ISSUE TITLE
Build Custom Controls for Video Player

### ISSUE THREAD

**Issue by ErikOstlund** [zooniverse/front-end-monorepo#1880]
**Package**
`lib-classifier`

The new Video Player needs custom controls for users to interact with the videos.
The video screen will be disabled and only used for annotating.
Features for the custom controls will include:

- Play/Pause
- Adjust playback speed
- Invert Video image
- Display Metadata
- Favorite
- Collect

**Comment by beckyrother** [comment]
A lot of these (metadata, favorite, collect, invert(?)) are part of the image viewer, so @srallen can probably point you to where they can be found. 

- [Play](https://projects.invisionapp.com/dsm/zooniverse/primary-brand/asset/icons/5fa475921bce8f2cb4131d5b)
- [Pause](https://projects.invisionapp.com/dsm/zooniverse/primary-brand/asset/icons/5fa475fe1bce8f194d131d88)
- Adjust speed: [Here's](https://projects.invisionapp.com/d/main#/console/12923997/270495347/inspect) a link to the InVision for a video player with speed controls on the far right side. Using the Inspect mode you should be able to click into the text and find type styles for the numbers

Let me know if there isn't an Invert yet!
