### ISSUE TITLE
Add survey Choice component

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#1904]
Add survey Choice component to:
- display carousel of selected choice images
- description of selected choice
- confused with
- questions

See https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/survey/choice.jsx.
PFE screenshot:
<img width="338" alt="Screen Shot 2020-11-16 at 5 20 05 PM" src="https://user-images.githubusercontent.com/12118751/99319958-1d4c1a00-2830-11eb-9055-981eafa8610c.png">

**Comment by mcbouslog** [comment]
@beckyrother is there a new or updated design in InVision for once a survey choice has been selected an optional image and list of related selected choice questions? No worries if not, it's not necessary, can start on implementing based on PFE, or no rush if would like to update InVision (lots of other pieces to work on).

**Comment by beckyrother** [comment]
Ack, no there isn't. I'll add one asap!

**Comment by beckyrother** [comment]
Here's the InVision link: https://projects.invisionapp.com/d/main#/console/12923997/440284854/preview 

Ideally the arrows on the carousel fade to 30% until hovering over them brings them up to 100%. I also think it would be neat to add an accordion-style collapse for the image that could persist during the user's session, so if they're doing many classifications they wouldn't have to scroll so much, but that's a nice-to-have. 

Let me know if anything's missing!
