### ISSUE TITLE
HMS NHS feedback - NEXT LINE and NEXT buttons

### ISSUE THREAD

**Issue by hrspiers** [zooniverse/front-end-monorepo#1939]
**Describe the bug**
Within the 'LINE BY LINE workflow' of HMS NHS: The Nautical Health Service the last step of the task instructs that, to move to the next line, 'click NEXT LINE and NEXT'. This isn't possible at the moment - there's no NEXT button. 

![Screenshot 2020-12-11 at 15 19 59](https://user-images.githubusercontent.com/22645431/101923379-380f7580-3bc7-11eb-8761-6b8fa8d90e7c.png)

**Comment by srallen** [comment]
This is a recursive workflow. Linked to #1226 and the combo task conversion needs to account for it. The single choice branching, `step.next`, here needs to be updated to map to the correct step key.

**Comment by eatyourgreens** [comment]
If we track annotation history, for the current subject, then we could retrieve annotations by ID here:
https://github.com/zooniverse/front-end-monorepo/blob/a4fea65ccf709e2cfdac0dde94ac46664cb4e2b0/packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js#L20-L23

That would allow for multiple annotations to be updated for the same workflow task.
