### ISSUE TITLE
HMS NHS feedback - NEXT button slippage when back button present 

### ISSUE THREAD

**Issue by hrspiers** [zooniverse/front-end-monorepo#1940]
**Describe the bug**
The 'Next' button moves to the right when the back button is present. Tested within HMS NHS project. 

![Screenshot 2020-12-11 at 15 51 20](https://user-images.githubusercontent.com/22645431/101925996-7e1a0880-3bca-11eb-9a0f-3aeffd9f1f58.png)

**Comment by eatyourgreens** [comment]
This shows up on I Fancy Cats too.
![Screenshot of the Next button bug on step 2 of I Fancy Cats.](https://user-images.githubusercontent.com/59547/101926377-ff719b00-3bca-11eb-9fc0-f0c35b69a9ac.png)
https://frontend.preview.zooniverse.org/projects/brooke/i-fancy-cats/classify?env=staging
