### ISSUE TITLE
Subtask position broken

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#1949]
**Package** lib-classifier

**Describe the bug**

Subtask position is now in the upper left corner instead of with the mark since #1922 

**To Reproduce**
1. Go to https://frontend.preview.zooniverse.org/projects/blicksam/transcription-task-testing/classify?demo=true
2. Make a mark

**Expected behavior**

Subtask is positioned with the mark. Original behavior can be observed if you check out `daf93e79ab5fedff58833f20661d25ae76ad4ae1`

**Comment by eatyourgreens** [comment]
Creating a new mark calls `onFinish(event)` so `node` is undefined here, which then leads to the modal position defaulting to `0,0`. https://github.com/zooniverse/front-end-monorepo/blob/a4fea65ccf709e2cfdac0dde94ac46664cb4e2b0/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js#L102-L116

**Comment by eatyourgreens** [comment]
Maybe give each mark component an effect which listens to `mark.finished` changing from `false` to `true`, then call `.setSubTaskVisibility(true, node)` from that effect.
