### ISSUE TITLE
Transcription Task Beta Feedback

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#1978]
- [x] 'Back' button is missing -- once you've hit next you can't go back and edit a transcription.
- [ ] Can't zoom out past a full-size page. This is helpful, to be able to see more of the page w/out having to scroll (ASM had this feature)
- [x] Need a 'hide previous marks' feature (use case: previous mark is covering text/punctuation & affecting accuracy of transcription)
- [x] Cursor should automatically move to the text box after the second underline dot is placed, so you can just start typing — really annoying to have to click into the box every time.
- [ ] Page scroll position automatically reverts to the top of the page after an annotation is submitted, meaning when you're working on text at the bottom of the page, you keep having to scroll back down for every new annotation. If possible, this automatic move should be disabled.
- [x] When Previous Transcriptions box is open, mouseover scroll on the Previous Transcription box also causes the image to Zoom in (while the transcriptions box is open, and is also scrolling)
- [ ] The "You've Seen Everything" banner doesn't appear automatically -- e.g. I classified all 5 subjects in the set, and was given one again with newly-greyed-out lines but without the "Finished" banner. Banner appears if I refresh the page.
- [x] POSSIBLE BUG: noticed that when I add a transcription for a given line, all the previous (navy blue) transcriptions are changing to the most recent text I’ve input. e.g. I transcribe a line "Pop goes the weasel" and move on to the next one, and transcribe "Mary had a little lamb." If I click back onto the weasel line, it now reads "Mary had a little lamb."

**Comment by eatyourgreens** [comment]
The second bug is #1951. #1953 should fix it.

**Comment by srallen** [comment]
Two more issues, demonstrated in this screenshot:

<img width="1342" alt="Screen Shot 2021-01-20 at 10 56 27 AM" src="https://user-images.githubusercontent.com/5016731/105209172-28147b00-5b0f-11eb-90a7-7219c89b158e.png">

1) The previous transcription marks should be rendered on the second step to be able to answer the question
2) Back button is not rendering when it should

@snblickhan are either of these blockers for continuing ahead with beta? I'll start looking into both of these regardless.

**Comment by snblickhan** [comment]
> The previous transcription marks should be rendered on the second step to be able to answer the question

Can you explain what this means? I'm not entirely sure what the issue is.

**Comment by srallen** [comment]
@snblickhan in the screen shot you can see that I'm on the second step where there is a question task asking if all the marks grey, but none of the previous transcription marks are displaying anymore, so it's not really possible to answer the question.

**Comment by eatyourgreens** [comment]
I'm not sure if this is related, but I came across a drawing bug where going forward, then backward, in a workflow creates ghost marks during the drawing step. Annotations are not affected, only the rendered SVG.
https://github.com/zooniverse/front-end-monorepo/issues/1869

**Comment by snblickhan** [comment]
Ahhhhh okay -- so the marks *you* made are rendering in T2, but not previous marks by others. Got it.

Yes, this is a blocker for beta, as people won't be able to answer T2 without previous marks rendering. 

The back button is less of an issue, as I can't see people needing to use it unless they get to T2 and realize they forgot to underline a line of text or engage with a previous mark. It isn't integral to understanding the Transcription Task, so I wouldn't consider it a blocker for beta in the way that the first one is.

**Comment by srallen** [comment]
Ok, @snblickhan I'm looking at that issue today and will keep you updated on its status.

**Comment by srallen** [comment]
@snblickhan I have a tentative fix, but I'm still working on some new and updated tests for it. I hope to have something up tomorrow. Apologies for this additional blocker.

**Comment by srallen** [comment]
I have a fix here: https://github.com/zooniverse/front-end-monorepo/pull/2001

Hoping to get a review first thing Monday.

**Comment by srallen** [comment]
> Need a 'hide previous marks' feature (use case: previous mark is covering text/punctuation & affecting accuracy of transcription)

We have this, so unless it is bugged and didn't display when it should or didn't hide a previous mark, I'm going to guess that this person just didn't find where this is on the site to use it.

**Comment by srallen** [comment]
> When Previous Transcriptions box is open, mouseover scroll on the Previous Transcription box also causes the image to Zoom in (while the transcriptions box is open, and is also scrolling)

After discussing with @snblickhan, the tentative plan is to disable mouse wheel zoom for now and to refactor it with some enhancements, but as a toggleable feature so we can explicitly have the wheel event either be browser window or the element.

**Comment by srallen** [comment]
> 'Back' button is missing -- once you've hit next you can't go back and edit a transcription.

Transcription task and the following question is now setup to be put into the same step using the lab editor.

**Comment by eatyourgreens** [comment]
>Page scroll position automatically reverts to the top of the page after an annotation is submitted, meaning when you're working on text at the bottom of the page, you keep having to scroll back down for every new annotation. If possible, this automatic move should be disabled.

I think #2080 fixes this, by returning focus to the line that you're currently working on, rather than the top of the document.

**Comment by eatyourgreens** [comment]
I'm still seeing that scroll bug in Firefox, even with the changes from #2080. When the bottom line of a page has focus, Firefox doesn't scroll down to bring the focussed element into view.

**Comment by srallen** [comment]
Closing this as I think most issues have been resolved and/or have separate specific issues dedicated to them now.
