### ISSUE TITLE
ZRC: allow for Modal components that can't be closed

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#1981]
**Package**
lib-react-components

**Is your feature request related to a problem? Please describe.**
#1976 introduces a modal which interrupts a volunteer and can't be closed until they have actively made a choice.

The `Modal` has no close function, but still shows a Close button, which doesn't work when clicked.

**Describe the solution you'd like**
Don't show the Close button for a `Modal` component unless there is a close function defined.

**Comment by beckyrother** [comment]
Is design needed here? Everything else should look the same just without a close button in the corner

**Comment by eatyourgreens** [comment]
I don’t think so. The template automatically assigns you to new design issues.
