### ISSUE TITLE
SingleSubjectImageViewer using SVG image, might want to switch to HTML img

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#201]
**Package** lib-classifier

**Feature or Issue Description**
We store the subject image's `naturalWidth`, `naturalHeight`, `clientWidth`, `clientHeight` per image (stored by frame index) in the classification's metadata. This is to record the original image size versus how it is rendered in the browser. I'm not sure what the equivalent is for SVG `image`, but if we cannot do this, then we need to refactor the viewer to use HTML `img`.

**Comment by eatyourgreens** [comment]
The SingleImageViewerContainer component preloads the image using a [HTML `img` element](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image), so I'd suggest getting the image dimensions when that element loads here: https://github.com/zooniverse/front-end-monorepo/blob/9d1d7ab7a215e5915bd67549d7d5f8b984d34242/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js#L42-L48
