### ISSUE TITLE
Routing to stats page for PH TESS is broken

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/front-end-monorepo#2012]
## Expected Behavior
Clicking the "view more stats" button on project homepage take you to project stats view (classification and Talk histograms).

## Current Behavior
Clicking the "view more stats" button results in a "This page isn't built yet" error message.  

![Screen Shot 2021-02-01 at 10 32 58 AM](https://user-images.githubusercontent.com/2006101/106488215-15883300-6479-11eb-8ee4-3ea2affe5b5d.png)

I'll note that the message appears to imply that some piece of code is still in development mode -- seems out of the ordinary.

## To Reproduce
1. Go to https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/stats
2. Click on "view more stats" button

### Desktop (please complete the following information):
 - OS: Mac 10.14
 - Browser: Chrome 87.0.4280.141

cc: @srallen -- following up from morning stand-up

**Comment by eatyourgreens** [comment]
Sounds like that link is using client-side routing, which doesn’t work for links to external pages. https://github.com/zooniverse/front-end-monorepo/issues/1994

**Comment by eatyourgreens** [comment]
`ContentBox` links are using [`next/link`](https://nextjs.org/docs/api-reference/next/link), which is for client-side transitions only.
https://github.com/zooniverse/front-end-monorepo/blob/9e0ed1cd20574c767dc396b360f68239b3c8ba43/packages/app-project/src/shared/components/ContentBox/ContentBox.js#L55-L63
