### ISSUE TITLE
Engaging Crowds: block the task area for already seen or retired subjects

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#2027]
## Package
lib-classifier

## Describe the solution you'd like
Engaging Crowds should allow volunteers to see previously classified, or retired, subjects but not classify them.

Returning to an already-classified subject would display a modal, in the task area, explaining why they can still look at this subject; same with a retired subject. 
- [Already seen](https://projects.invisionapp.com/d/main#/console/12924056/438011816/preview)
- [Retired](https://projects.invisionapp.com/d/main#/console/12924056/438011817/preview)

The modal has two options: to return to the project home page or to choose another subject from the subject set. Choosing another subject opens the modal to choose another subject within the classify page: https://projects.invisionapp.com/d/main#/console/12924056/440898093/preview  

Should be able to reuse the modal from the project home page on the classify pages, but should not include the 'back to workflow selection' button and has different text ('choose a subject' rather than 'choose a subject to get started').

![Screenshot of a modal blocking the task area for a subject which has already been retired.](https://user-images.githubusercontent.com/59547/107404377-22062e80-6afe-11eb-99e0-f6d05f902a18.png)

**Comment by beckyrother** [comment]
Updated to add more options. Let me know if this feels like too many things; I think the hierarchy helps
![image](https://user-images.githubusercontent.com/1392130/107423709-48b66c00-6ae2-11eb-98ca-a403506855af.png)


https://invis.io/9WNF9M73AEN#/438011817_W-In_Classifier_-_Retired

**Comment by snblickhan** [comment]
@beckyrother suggested edit to the text:

"This subject already has enough classifications, so you won't be able to submit any new data. You can still view this subject for reference."

(note: definitely open to suggestions about the above, but mainly trying to convey the idea that what they'll get is a View Only subject)

**Comment by beckyrother** [comment]
Updated in the InVision https://projects.invisionapp.com/d/main#/console/12924056/438011817/preview

**Comment by eatyourgreens** [comment]
It's just occurred to me that this modal is using links, so the classifier component is going to need to know how the parent app routes links, or even what the parent app's URL structure is (eg. Project Home.)

**Comment by eatyourgreens** [comment]
Depends on #1925 because we want to be able to open the subject picker from the classifier.

**Comment by snblickhan** [comment]
Modal should include a button that lets volunteers classify the subject anyway. Recommendation is to add a 'Close' button to this modal. 

NB: This could be generalizable, in terms of inviting someone to work on something else (even for projects that aren’t using the indexing tool).

**Comment by eatyourgreens** [comment]
@snblickhan 'Close' button is a small change, so no problem.

**Comment by eatyourgreens** [comment]
Here's a screenshot of the latest design, with updated wording. Note that the task area is completely disabled while the popup is open, but the subject viewer and the rest of the page are fully interactive.

![Screenshot of the classifier with a popup that disables the task area, but allows the volunteer to continue using the subject area.](https://user-images.githubusercontent.com/59547/118943859-ef18d580-b94b-11eb-84b0-d1d7bb1e4b70.png)

**Comment by snblickhan** [comment]
@eatyourgreens I just realized that, after the decisions we made last Friday (e.g. adding the close button & allowing people to still submit new data even though it's done), this text needs updating again. Here's my suggestion:

> This subject has enough classifications, so any additional classifications submitted will not be used in its analysis. You can still view this subject for reference.

It's closer to the previous version, but with a slight rewording to show that classifications _from this point on_ won't count, basically a caveat emptor but for further classification...

@mrniaboc @srallen does this wording sound ok to you? I wanted to keep it fairly general.

**Comment by eatyourgreens** [comment]
No problems changing the wording. All the text is going to be localised anyway, so it'll be stored in separate language files that we can update as needed.

The only big changes, I think, are that we don't link to the home page and the popup can be cancelled/closed. As a volunteer, you can either select a new subject to work on (from a variety of options in the popup) or cancel the popup and classify anyway.

**Comment by snblickhan** [comment]
For reference: we chatted today about the possibility of putting the forward/back buttons in the subject banner (e.g. the green bar that tells you where you are in the sequence of pages), but ultimately came to the decision that the MVP version of this means **not including the 'navigation' arrows at all**. Volunteers will have the option to go to the next 'classifiable' subject when they come across one that is complete (via the modal), and they can use the full subject index to go to specific subjects as they like. 

Ultimately, we know that the arrow forward/back navigation is something we want to add to the indexing tool, but we don't have the time on the current Engaging Crowds effort to do it properly, so we're making the call to leave it out of this round of development.

**Comment by eatyourgreens** [comment]
@snblickhan Here's what I've got now, displayed on one of the Scarlets & Blues workflows. Three options: select another subject, next unclassified subject or dismiss the popup and classify anyway.

![Screenshot of a Scarlets & Blues page with the task area disabled and blocked by a popup giving options to select another subject or dismiss the popup.](https://user-images.githubusercontent.com/59547/119961983-83171c80-bf9e-11eb-863e-f559a64d3b02.png)

**Comment by eatyourgreens** [comment]
I should add, all the inputs in the task area are disabled while the popup is open. 

In VoiceOver, the popup content is hidden away at the bottom of the page. That makes it easy to miss, for a blind user. The field guide has a similar problem, so that’s a more general accessibility barrier for popup content that doesn’t block the underlying page. You wouldn’t know it was there if you stopped listening at the page footer.

**Comment by snblickhan** [comment]
Just noting here based on our EC convo that we’re in favor of changing “open subject” to “available subject.”

Additionally, we want to add a "Next available subject" button to the Task area, below the Help text and above the Done button. Sharing here from our Slack thread:
>confirm intent, via an alert box, when volunteers navigate away from a subject that has annotations. Warn them that they will lose work in progress unless they specifically press Done.

**Comment by srallen** [comment]
> Additionally, we want to add a "Next available subject" button to the Task area, below the Help text and above the Done button.

@snblickhan When we spoke a couple weeks ago about these RFCs, I recommended that something like this not go in the task area because of potential confusion with the task navigation buttons. Is there a reason that this is going there?

**Comment by srallen** [comment]
Same with the modal on already seen and retired subjects, people may get confused about the difference between "next available subject" and "select another subject"

**Comment by snblickhan** [comment]
FWIW, we were originally talking about putting the Previous/Next buttons above the subject image. When we circled back here I wanted to put this in the green banner, but was told that wasn't a good idea, since not all FEM projects will use sequential classification, which makes a lot of sense if we're building a generalizable version of this feature. However, since we know we're only working with EC right now, we may have some options.

Two ideas: 
- Could we compromise and put this button directly above the banner area, since we have decided we're only going to roll this out for EC projects as a start? 
- If we do end up putting it in the task area, could we put it at the top of the task area instead? So they would be more likely to see/read it before starting a classification?

@srallen @eatyourgreens would welcome your thoughts around the above options, with the understanding that design will be part of the process of generalizing this feature, once we've hired someone to fill the position, so _the implementation here is limited to EC projects and will be updated if/when we decide to implement it more widely_.

**Comment by snblickhan** [comment]
> Same with the modal on already seen and retired subjects, people may get confused about the difference between "next available subject" and "select another subject"

This is a good point. I think this could be fixed by rewording both buttons slightly. My suggestion would be to reframe the options to: 
-  "Select another subject from list" 
-  "Take me to the next available subject"

**Comment by eatyourgreens** [comment]
I've opened #2225 for adding 'Next Available Subject' as an option on any subject.

**Comment by snblickhan** [comment]
@eatyourgreens 

Looping back on this -- because we need to get moving on this, I'm just going to say that the "Next Available Subject" button should go above the banner/subject image, instead of in the task area. I know we don't have design, but a simple button aligned with the top left corner of the image

On the modal (shown in https://github.com/zooniverse/front-end-monorepo/issues/2027#issuecomment-850281802), the options should read:

- "Choose a new subject"
- "Next available subject"

^^ this gives a clearer distinction that one option will give you a choice based on what's available, and the other does not.

Let me know if anything above is unclear or if there are other related questions. Happy to copy/paste this overview on #2225 if that's useful, too.

**Comment by eatyourgreens** [comment]
@snblickhan there's a screenshot on #2198 showing the latest wording.
