### ISSUE TITLE
Survey task: add survey task configuration to allow multiple identifications of a choice

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#2087]
Currently the FEM survey task only allows one identification per choice, matching the survey task in PFE. If an aardvark is chosen, related questions answered, and the choice is identified, then subsequently selecting aardvark again will reselect/reload the initial aardvark selection, allowing a user to edit previous answers. Some projects (like Chimp&See) would prefer that subsequent selections would create additional identifications.

This issue is for adding a configuration property on a survey task to allow for multiple identifications of a choice.

**Comment by srallen** [comment]
Note: This is an optional enhancement if we're asked for it.

**Comment by goplayoutside3** [comment]
@mcbouslog I'd like to close this since it's not a planned enhancement. Have we been asked for it for a survey task project?
