### ISSUE TITLE
Project home page sections are not horizontally centered like classify page sections

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#2088]
## Package
- app-project

## Is your feature request related to a problem? Please describe.
Not a problem, just noting that the project home page sections are not horizontally centered like the classify page sections. If intentional please close this issue.

## Describe the solution you'd like
Horizontally center the project home page sections?

## Additional context

project home page:
![Screen Shot 2021-03-31 at 12 09 03 PM](https://user-images.githubusercontent.com/12118751/113184027-56eb5380-921a-11eb-85cb-e9e68c941583.png)

classify Page:
![Screen Shot 2021-03-31 at 12 09 47 PM](https://user-images.githubusercontent.com/12118751/113184079-636fac00-921a-11eb-9c35-11d29f7f96e4.png)

**Comment by goplayoutside3** [comment]
Noting that the Project /about pages also do this and should be center aligned

**Comment by Rehan52004** [comment]
Where this page is written.
Give me any link to see the actual problem.

**Comment by eatyourgreens** [comment]
Here's a screenshot:
<img width="800" alt="Project About page content is left-aligned at large viewport widths." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/3827b47e-c64a-45ea-b0e5-9f38d0914b9e">
https://www.zooniverse.org/projects/zooniverse/gravity-spy/about/research

**Comment by goplayoutside3** [comment]
Each page is here: https://github.com/zooniverse/front-end-monorepo/tree/master/packages/app-project/src/screens
