### ISSUE TITLE
X-axis scale for Light Curve Viewer

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#211]
**Package**

- lib-classifier

**Feature or Issue Description**

The X-axis is currently a linear scale; is there any value to converting Julian dates so we can use the D3 time scale (and get things like sensible tick values)?

D3 doesn't support Julian dates OOTB, but we could use something like https://github.com/stevebest/julian

**Comment by rogerhutchings** [comment]
cc @noraeisner

**Comment by rogerhutchings** [comment]
We're using D3 to plot the chart anyway, and currently, the Julian date values are being used to populate the x-axis.

**Comment by noraeisner** [comment]
Ah yes, the original planet hunters did use both. It would be great to have both the Julian data and the time ranging from 0 to 30 days along the bottom again. Is that possible?

**Comment by shaunanoordin** [comment]
I just had a discussion with @noraeisner, and here's an update on the data and x-axis:

- For the x-axis, we will retain the current system (x = decimals to denote days past the first observation)
- For the Subject JSON, the x-range will remain `[0.0, 27.8]` (or rather, 27.8-ish, I can't remember what the exact maximum was)
- For the Classification annotations, the x-ranges will match the input JSON
- *However* the Subjects will also now include the _Date of First Observation_ in the Metadata, which can then be used by the science team to calculcate Julian dates.
- The Light Curve Viewer (Front End) will _not_ use any Julian Dates, and will in effect ignore the new Date of First Observation in the Metadata.

**Comment by shaunanoordin** [comment]
The rationale is that while the Julian dates may be relevant to the scientific analysis by the science team, having the Julian date actually visible to volunteers would be more confusing than anything.

**Comment by eatyourgreens** [comment]
But Julian day number is so easy to understand. It's simply the number of days since 1 January 4713 BC. 😄
