### ISSUE TITLE
Zooming on a specific point in the ScatterPlot viewer

### ISSUE THREAD

**Issue by hughdickinson** [zooniverse/front-end-monorepo#2120]
## Package
lib-classifier (Zooming ScatterPlot)
## Is your feature request related to a problem? Please describe.
For our project (14770) the features of interest are not always in the centre of the plotted range (see image) and the zooming function only seems able to zoom in on the middle of what's currently displayed. 

In addition, when zooming in on a particular section of the data, it would be good to limit zooming to the x direction. I think I can see from the source code that this should be possible with developer intervention, but I may be wrong. 

Also it would be good if we could pad the display area beyond the limits of the data but I'm aware that there is another issue [#1777](https://github.com/zooniverse/front-end-monorepo/issues/1777) on that topic. As is evident from the image part of the interesting feature is actually truncated because it contains (in this case, but not always), one of the extreme points in the data set.
<img width="1159" alt="Screenshot 2021-04-23 at 14 38 14" src="https://user-images.githubusercontent.com/10618717/115879687-dba84680-a441-11eb-9e8f-250d56f3cc20.png">

## Describe the solution you'd like
I would like to be able to zoom in on a particular section of the data, regardless of where it is within the display window or the data range. I would also like to limit zooming to the x direction, keeping the y zoom locked.

## Describe alternatives you've considered
Padding the data with outlier points far outside the real data range so that the display can be panned to have the feature of interest in the centre and zoom in on it that way. The problem is that this makes the range of real data a small fraction of the display at the initial zoom level.

## Additional context
We cannot determine where within the range of the data any feature of interest might be so we cannot prepare data that have the feature pre-centred

**Comment by srallen** [comment]
@hughdickinson 

> For our project (14770) the features of interest are not always in the centre of the plotted range (see image) and the zooming function only seems able to zoom in on the middle of what's currently displayed.

Zoom to point is currently supported for double click and mouse wheel interactions. Is this sufficient for your use case?

> In addition, when zooming in on a particular section of the data, it would be good to limit zooming to the x direction. I think I can see from the source code that this should be possible with developer intervention, but I may be wrong.

I have a plan to support various zoom configuration by way of workflow configuration and in the subject JSON giving a preference order of the subject JSON > workflow config > default values.

**Comment by hughdickinson** [comment]
@srallen
> Zoom to point is currently supported for double click and mouse wheel interactions. Is this sufficient for your use case?
> 
Ah! I hadn't realised it worked like that. Yes, I think that will work well once the zoom can be limited to the x direction.

> I have a plan to support various zoom configuration by way of workflow configuration and in the subject JSON giving a preference order of the subject JSON > workflow config > default values.

Brilliant. Is there any utility in me seeing whether I can implement any of that or would you rather I leave it to the professionals?

**Comment by srallen** [comment]
> Brilliant. Is there any utility in me seeing whether I can implement any of that or would you rather I leave it to the professionals?

I'm in the middle of doing a dependency update with the underlying packages that support the feature, so possibly in the near future, but not immediately. However, I am working on the zoom feature generally, to add support for project builder set zoom configuration (at least initially via python client), so a natural side effect will be support by workflow config for your project as well. See: https://github.com/zooniverse/front-end-monorepo/issues/2110

**Comment by srallen** [comment]
@hughdickinson just so you are aware, the zoom to point behavior when using the mouse wheel may change in the future. See #2075

**Comment by srallen** [comment]
@hughdickinson configuring the scatter plot to only be zoomable either across the x-axis, the y-axis, or both is now supported by way of workflow configuration or subject JSON configuration with #2142 on our staging instance. We'll likely deploy sometime next week. We don't have a UI to do this in the project builder yet, but I'll submit another PR hopefully today to update the readme so you have guidance on how to do it by way of the python client / API.
