### ISSUE TITLE
HMS NHS has workflows with steps that link to themselves

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#2133]
## Package
lib-classifier

## Describe the bug
https://www.zooniverse.org/projects/msalmon/hms-nhs-the-nautical-health-service/classify/workflow/18347
https://www.zooniverse.org/projects/msalmon/hms-nhs-the-nautical-health-service/classify/workflow/18344

Each of those workflows should end on the fifth step, `S4`, but `step.next` is set to `S4` so there's no way to submit a classification.

## Expected behavior
The last step in a workflow should have `step.next` undefined (or set to `summary`), and should show a Done button.

## Additional context
The cause of the problem is that the individual text tasks have been linked to each other in the project builder. This confuses `convertWorkflowToUseSteps` when it converts `task.next` to `step.next`.

**Comment by eatyourgreens** [comment]
I'm going to open a PR to fix `convertWorkflowToUseSteps` but this might be a bug in the Project Builder.

**Comment by snblickhan** [comment]
I've fixed the current workflow issues for HMS NHS in the Project Builder, but good to get a fix in to prevent future project builders from this type of confusion (e.g. only the 'parent' task should be linkable, not the individual steps w/in).

**Comment by eatyourgreens** [comment]
#2134 adds a check (and a test) to make sure that steps don't link to themselves by accident, which is what happened here. I'm not sure how much work it would be to fix the project builder code so that you can't set `task.next` on a task inside a combo.

**Comment by eatyourgreens** [comment]
I've checked the [Admission Numbers workflow](https://www.zooniverse.org/projects/msalmon/hms-nhs-the-nautical-health-service/classify/workflow/18109/subject-set/83482), while working on keyboard focus (#2172), and it's broken again. The Done button doesn't show on the last step, S4, because `step.next` is set to 'S4'.
