### ISSUE TITLE
Done or equivalent should be disabled if survey task choice is in progress

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#2152]
Done or equivalent (Done & Talk, Next) should be disabled if survey task choice is in progress (annotation `_choiceInProgress = true`). Check `isComplete` and `required` functionality for survey task.

**Comment by mcbouslog** [comment]
I'm not sure how to address this issue. The `Step` determines `isComplete` with ([link to code](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.js#L29)):
```
let isIncomplete = false
self.tasks.forEach(task => {
  const [annotation] = annotations.filter(annotation => annotation.task === task.taskKey)
  isIncomplete = task.required && !annotation?.isComplete
})
return !isIncomplete
```

So a survey task with `required` as falsey won't check if the `annoation.isComplete`, which is where `_choiceInProgress` determines annotation completeness, and therefore won't disable Done or related buttons if choice is in progress.

Is the Step completeness check code somewhat duplicative of [this from the Task model](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/plugins/tasks/models/Task.js#L23-L25) (`return !self.required || !!annotation?.isComplete`)?

Maybe I could refactor the Step store to only check task.isComplete, then refactor the survey task `isComplete` to evaluate `_choiceInProgress`? In which case would it make more sense to move the volatile `_choiceInProgress` state up to the survey task model?

cc: @srallen

**Comment by mcbouslog** [comment]
Update per discussion - changing the Step store `isComplete` and updating the survey task `isComplete` might be a good route or checking the validity of the annotations and deleting invalid annotations, similar to #2179, might be preferable.

**Comment by eatyourgreens** [comment]
I think it makes sense to change that block to something like:
```js
let isStepComplete = true
self.tasks.forEach(task => {
  const [annotation] = annotations.filter(annotation => annotation.task === task.taskKey)
  isStepComplete = isStepComplete && task.isComplete(annotation)
})
return isStepComplete
```

Then a step is complete if all its tasks are complete. Each task type is responsible for the logic that determines whether it's complete or not.

Looking at the existing code, I don't think it works if, say, a step has two tasks, the first is incomplete but the second is complete.
