### ISSUE TITLE
Add logging service for classification 422

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#217]
**Package** lib-classifier

**Feature or Issue Description**
Let's try to use a logging service for 422s. Rollbar docs:
https://docs.rollbar.com/docs/custom-log-messages
https://docs.rollbar.com/docs/javascript

**Comment by rogerhutchings** [comment]
Rather than use Rollbar directly, I'd like to use a generic logging package which then picks out events to send to Rollbar - I don't want to end up in a Geordi-type situation requiring lots of code changes to e.g. make a change to our service of choice

**Comment by srallen** [comment]
That's a very good point. The way the logger is written on PFE now takes log adapters, so we could reuse that code and have a logger library that handles both GA and any error reporting log service.

**Comment by rogerhutchings** [comment]
https://github.com/zooniverse/Panoptes-Front-End/blob/21cf42485929a62938112d5e2d4bca1a6702b00e/app/lib/zooniverse-logging.js

**Comment by rogerhutchings** [comment]
or https://github.com/winstonjs/winston, maybe

**Comment by rogerhutchings** [comment]
cc #174

**Comment by rogerhutchings** [comment]
cc #911
