### ISSUE TITLE
Subtask modal can be partially offscreen

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#2178]
## Describe the bug

First reported in #2159 :

![](https://user-images.githubusercontent.com/23665803/117719735-5a6fe400-b1a3-11eb-8fd6-16bddcb03ee5.jpg)

The subtask modal can appear partially offscreen depending on the position of the line.

## Expected behavior

Do we detect if the line is close to the window edge and position the sub-task above (or right) of the line if necessary?

**Comment by goplayoutside3** [comment]
Similar to https://github.com/zooniverse/front-end-monorepo/issues/1834 the modal always appears on screen even if the transcribed line is close to the viewport edge. Example project: https://www.zooniverse.org/projects/blicksam/transcription-task-testing/classify

**Comment by eatyourgreens** [comment]
Fixed by #3338, for future reference.
