### ISSUE TITLE
Transcription lines: unable to focus or drag new lines

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#2180]
Since #2159 merged, I can't drag new green transcription lines, or navigate through lines with Tab:
![Screenshot of a green transcription line, showing the delete button moved away from the focused line.](https://user-images.githubusercontent.com/59547/118292877-ff0a6280-b4d0-11eb-97c1-a590478993bb.png)

When I drag one of the drag handles (in Chrome), the delete button moves but the rest of the line stays where it is.

I'm also seeing that all the grey lines have `tabindex=-1`, as if they were disabled, after I try dragging a green line. That might be a completely different issue. I think Grommet Layer might disable the page as part of the modal subtask popup opening, but the lines aren't being reset to `tabindex=0` for some reason.

_Originally posted by @eatyourgreens in https://github.com/zooniverse/front-end-monorepo/issues/2159#issuecomment-841315237_

**Comment by srallen** [comment]
@eatyourgreens The issue is I forgot to re-add the MobX observer decorator. If you have any ideas on how to test to make sure a component is being observed (or more generally decorated by a particular decorator), I'm open to suggestion.

**Comment by eatyourgreens** [comment]
Weird that transcription lines require the decorator when other mark components don’t use it.

**Comment by eatyourgreens** [comment]
Tab navigation is still broken with the fix in #2181. Maybe that's a separate issue? After I place a green line, all focusable elements in the page have `tabindex=-1' and Tab takes me out to the browser chrome, as if a modal were open. Here's one of the image toolbar buttons, from the DOM inspector, after I placed a new green line:

```html
<button title="Annotate" class="StyledButton-sc-323bzc-0 ilgHLg sc-fznxKY gLziWv" aria-label="Annotate" type="button" tabindex="-1">
  <svg viewBox="0 0 32 32" aria-hidden="true" class="StyledIcon-ofa7kd-0 FimRf">
    <path transform="scale(-1, 1) translate(-32, 0)" d="M28.784 3.226l-10.508 24.556-3.729-10.766-10.756-3.251zM31.389 0.024c-0.191 0-0.422 0.054-0.691 0.167l-29.833 12.659c-1.075 0.456-1.143 1.335-0.151 1.952l12.353 3.862 4.043 12.602c0.29 0.474 0.64 0.71 0.977 0.71 0.373 0 0.728-0.286 0.97-0.852l12.759-29.804c0.346-0.809 0.149-1.296-0.426-1.296z">
    </path>
  </svg>
</button>
```

I'm fairly sure this was working prior to #2159 but I haven't checked.

**Comment by eatyourgreens** [comment]
I've checked on master, and keyboard navigation is broken prior to #2159 merging (I checked out 9bfa439f.) To reproduce, create a new green line from a magenta line, then try to navigate the classifier with the Tab key. You should find that all focusable elements are disabled.

**Comment by eatyourgreens** [comment]
I've opened #2183 for that tabindex bug.
