### ISSUE TITLE
Fix ZooHeaderWrapperContainer pending tests

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#2197]
The [ZooHeaderWrapperContainer tests](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.spec.js) are set to pending and need follow-up.

The pending tests made a `url-parse` breaking (and fixed in subsequent update) change difficult to detect.

**Comment by goplayoutside3** [comment]
Closed by https://github.com/zooniverse/front-end-monorepo/pull/3703
