### ISSUE TITLE
Design: close button spacing is too large in modal popups

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#2201]
## Package
lib-react-components

## Describe the bug
Close buttons are being displayed with too much spacing to the right in modal headers. Here are a couple of examples.

![Header from the Add To Collections modal.](https://user-images.githubusercontent.com/59547/119484105-97180f80-bd4d-11eb-8419-72b26e111d95.png)

![Header from the Field Guide.](https://user-images.githubusercontent.com/59547/119484201-ae56fd00-bd4d-11eb-95a9-6e9508fd2d82.png)

## Expected behavior
The close button should be much closer to the righthand side of the header.

![Header of the subtask confirmation modal, with the correct position for the close button.](https://user-images.githubusercontent.com/59547/119484430-eeb67b00-bd4d-11eb-926b-fd7ae1bec153.png)

**Comment by srallen** [comment]
This is how Becky designed it, it should match the margins all around. The suggested fix makes it no longer in line with the rest of the content. Modal designs are within the classifier section if you want to have a look: https://projects.invisionapp.com/d/main?origin=v7#/projects/prototypes/12923997

**Comment by eatyourgreens** [comment]
Those are all screenshots from master, so it looks like the spacing on the confirmation box is inconsistent? All modals should have 30px padding in the header?
https://projects.invisionapp.com/dsm/zooniverse/primary-brand/asset/components/5ea995ce07156c97c3cd7985

**Comment by srallen** [comment]
Becky advised the drawing subtask to not use the 30px since it's missing the header: https://github.com/zooniverse/front-end-monorepo/pull/1517#issuecomment-590466068

The confirm modal is likely inheriting that variation. 

Unfortunately the invision docs are missing this variation as well.

**Comment by eatyourgreens** [comment]
I'd vote for closing this. It doesn't seem urgent, just looks a little odd. It might be annoying if you're used to clicking the close button in the top right of a box, and it isn't there. That's how I noticed it, while I was working on #2198 I'd accidentally click on the empty space to the right of the close button.
