### ISSUE TITLE
PH TESS team page not showing collaborators

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#2213]
## Describe the bug

The team page doesn't show the collaborator list on the right hand side on the team page. 

## To Reproduce
Run the project app in development and visit: http://localhost:3000/projects/nora-dot-eisner/planet-hunters-tess/about/team?env=production

## Expected behavior
Collaborator list renders.

## Screenshots

<img width="255" alt="Screen Shot 2021-05-26 at 1 09 14 PM" src="https://user-images.githubusercontent.com/5016731/120340592-cbdf1600-c2bb-11eb-9199-97c64e6e5d66.png">

**Comment by goplayoutside3** [comment]
Noting that team info does show up when using a deployed link:
https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/about/team

I believe this behavior has to do with the following code returning a different panoptes response depending on if a project was created in production vs staging such as `i-fancy-cats`.
https://github.com/zooniverse/front-end-monorepo/blob/c4daaf348aeeab7bb7d1da7ef25701ae4979c9ee/packages/app-project/pages/projects/%5Bowner%5D/%5Bproject%5D/about/team.js#L17

**Comment by srallen** [comment]
@goplayoutside3 is this resolved by #2224?

**Comment by goplayoutside3** [comment]
@srallen No, #2224 only fixed styling bugs. The team page data is fetched correctly on the [deployed preview](https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/about/team) for PH TESS, but the same team data is not fetched for PH TESS [locally](http://localhost:3000/projects/nora-dot-eisner/planet-hunters-tess/about/team?env=production) as you noted. I think this has to do with fetching a project created in production versus a staging project such as `i-fancy-cats`, and the query `env` param needs to be included in the following: 
https://github.com/zooniverse/front-end-monorepo/blob/c4daaf348aeeab7bb7d1da7ef25701ae4979c9ee/packages/app-project/pages/projects/%5Bowner%5D/%5Bproject%5D/about/team.js#L17
