### ISSUE TITLE
Link underlining is too short on project navigation links

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#2219]
## Package
app-project

## Describe the bug
![Screenshot of the Beyond Borders home page, showing that the link underline does not span the entire text of each navigation link.](https://user-images.githubusercontent.com/59547/120477011-2901c700-c3a3-11eb-9776-672c6ce10581.png)

Focus or hover links on the Beyond Borders project to see the bug, or go to the classify page, where `Classify` should be underlined.
https://www.zooniverse.org/projects/mainehistory/beyond-borders-transcribing-historic-maine-land-documents/classify

**Comment by srallen** [comment]
@eatyourgreens could you add the information of which browser and version this is for? I'm not seeing this with either the latest Chrome or Firefox here...

**Comment by eatyourgreens** [comment]
Latest Firefox and Chrome.

**Comment by eatyourgreens** [comment]
I'm back at my desktop now, so here's actual version numbers: Chrome 91 and Firefox 89.

**Comment by srallen** [comment]
Here it is for me:

<img width="1438" alt="Screen Shot 2021-06-02 at 11 14 49 AM" src="https://user-images.githubusercontent.com/5016731/120515348-d79e0b80-c393-11eb-8422-c20e61978cfe.png">

**Comment by eatyourgreens** [comment]
We have different display sizes. I see that same layout if I zoom out to 80% with cmd-.

**Comment by eatyourgreens** [comment]
Investigating a bit further, links are being rendered too small on smaller displays. If I add `overflow: hidden` to nav links, so that I can see the boundaries of each link, the navigation looks like the following. The last few letters in each link weren't clickable, because they flow outside the link. I think the spacing between links might be causing this bug.

![Project nav bar with truncated navigation links on a smaller display.](https://user-images.githubusercontent.com/59547/120609669-53f32600-c44a-11eb-9eb3-f63fae993954.png)

**Comment by goplayoutside3** [comment]
@eatyourgreens are you still able to replicate this UI bug? I tried FEM projects in Chrome and could not.

**Comment by eatyourgreens** [comment]
Looks ok to me. There is a different bug, which is that 'Classify' isn't underlined when you first enter the Classify page. It does underline after a re-render. I think we've already got an open issue for that.

<img width="600" alt="Screenshot of the project navigation for Beyond Borders, on the Classify page, showing that Classify is fully underlined and clickable." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/ab43f730-a77a-4cc3-939b-fb95d2572fb9">
