### ISSUE TITLE
Single Image Subject Viewer's "Drag to Pan/Move" action doesn't work on Safari

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#2220]
## UI bug

Package: `lib-classifier`
Commit: c4daaf348aeeab7bb7d1da7ef25701ae4979c9ee
Browser: Safari 12.1.2 + macOS 10 (Laptop)

On Safari, when the Classifier is showing a Single Image Subject Viewer, users cannot use their mouse to click-and-drag to pan the view of an image.

### Testing

1. Using Safari, open any project with a Single Image Viewer. For example:
    - I Fancy Cats: [(local)](https://local.zooniverse.org:8080/?env=staging&project=335) [(fe-preview)](https://frontend.preview.zooniverse.org/projects/brooke/i-fancy-cats/classify/workflow/693?env=staging)
    - Davy Notebooks: [(local)](https://local.zooniverse.org:8080/?env=production&project=9006) [(fe-preview)](https://frontend.preview.zooniverse.org/projects/humphrydavy/davy-notebooks-project/classify/workflow/18575)
2. Click on the four-arrows button to indicate you want to Move/Pan the Subject Viewer
3. Click and drag the image in any direction.
    - Expected: the image pans in the direction that you drag the mouse. The mouse pointer becomes the four-arrows cursor (CSS `cursor: move` style) while this happens.
    - Actual: the image remains static. The mouse pointer changes from the four-arrows cursor to the text cursor while dragging.

Compare these project with Chrome, where the drag action works as expected.

### Analysis

The changing of cursor styles hints to me that there's probably something up with the CSS code that's affecting the mouse interaction. Attempting to perform a drag across the screen actually highlights the text across the entire web page, indicating that the <image /> in the SVG (which is the component that's supposed to capture the drag action, I think?) isn't "eating" the drag action as expected.

### Status

This will affect every Safari user trying to work on a typical "single image project" on the FEM, e.g. Davy Notebooks.

Note that TESS isn't affected since that's not using a Single Image Subject Viewer.

**Comment by shaunanoordin** [comment]
Scratch this: this is ONLY an issue for Safari 12. The current latest version, Safari 14, works fine when tested on Browserstack. If users report an issue with the drag function, we'll need to inform them to upgrade, unfortunately. On that note, I need to get a newer machine too.

**Comment by srallen** [comment]
@shaunanoordin yeah, this is expected since pointer events weren't fully supported in Safari 12 and we dropped the PEP.js polyfill since it went into deprecated status as well.
