### ISSUE TITLE
Transcription Task "Fan Lines" bug

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#2221]
## Fan Lines appearing
When leaving/returning to the classify page, if in-progress transcription isn't submitted the volunteer-drawn underline markings will all gather together in the upper left corner of the image and 'fan out'. 

## To Reproduce
1. Go to https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/classify/workflow/18575
2. Start a classification
3. Click on the project home page link
4. Click on the workflow and return to the classify page

NB: this also works if you log out of your account mid-classification, start a classification while not logged-in and log into your account mid-classification, or press the 'back' button on your browser mid-classification & return to the classify page.

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:

project number 9006
workflow number 18575

## Expected behavior
Honestly, I'm not entirely sure what I would expect here from navigating away & returning. Seems to me like a good use case for the "Are you sure you want to leave?" prompt, though I'm less sure of the expected sign-in behavior -- I don't think I would expect classification data to persist, but am also unsure if we support that for other projects (e.g. I can see a user forgetting to log in, getting halfway through a transcription and realizing it, and wanting to sign in so that the page will be in their Recents).

## Screenshots
['fan' bug + console images](https://imgur.com/a/OmNWD8t)
NB these screenshots were taken after generating the bug through mid-classification sign-out.

### Desktop (please complete the following information):
 - OS: macOS Catalina
 - Browser Chrome 90

## Additional context
[Talk thread](https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/talk/2586/2013546) with original report

**Comment by eatyourgreens** [comment]
I can also reproduce this without starting a transcription. Leave the page, come back, and the previously transcribed lines are all drawn from (0, 0) to their end points.

**Comment by eatyourgreens** [comment]
Just reproduced it on my phone by coming back to this GitHub issue then forward (using the browser navigation buttons) to the linked Classify page. That case seems harder to reproduce, but it’s not linked to starting a transcription or to the Back button specifically.

**Comment by eatyourgreens** [comment]
Here's the code for one of the broken lines, from the DOM inspector in Chrome. Lot's of `NaN` values where there should be numbers. Weird that `x1` and `y1` (start of each line) are affected but not `x2` and `y2` (end of each line.)

```svg
<g role="button" aria-describedby="complete-0" aria-label="53 of same xxxx" tabindex="0" class="sc-fzqPZZ jVixFR">
  <g color="#a6a7a9" fill="#a6a7a9" stroke="#a6a7a9" stroke-width="2">
    <line x1="NaN" y1="NaN" x2="632.46533203125" y2="157.3531951904297"></line>
    <line x1="154.873779296875" y1="166.57310485839844" x2="632.46533203125" y2="157.3531951904297" stroke-width="NaN" stroke-opacity="0"></line>
    <circle cx="154.873779296875" cy="166.57310485839844" fill="transparent" r="NaN" stroke="currentColor"></circle>
    <circle cx="632.46533203125" cy="157.3531951904297" fill="currentColor" r="NaN" stroke="currentColor"></circle>
  </g>
</g>
```

**Comment by eatyourgreens** [comment]
That previous comment was a DOM fragment generated by the `TranscribedLines` component. Just for completeness, here's the same bug for a green `TranscriptionLine` mark, so it's happening somewhere further up the tree.

![Screenshot of the same bug for a green transcription line, with its associated text task popup visible.](https://user-images.githubusercontent.com/59547/120613354-12fd1080-c44e-11eb-89ae-b2195ae45e1c.png)

**Comment by eatyourgreens** [comment]
I'm debugging this with development builds of the libraries, `NODE_ENV=development yarn bootstrap`. I think the project app should then load a build of the classifier (and Zooniverse react components) that has source maps and prop type checking.

**Comment by eatyourgreens** [comment]
Drawing `scale` (the ratio of the displayed subject image size to its actual size) is being passed into mark components as `NaN`. I think that's the source of the bug, which would mean that it affects any drawing task, not just transcription projects.

This might be a bug that's triggered when a subject image loads from the browser cache, rather than over the network.

![Screenshot of a buggy subject in Chrome, with the React components inspector open and the scale prop shown as `NaN`.](https://user-images.githubusercontent.com/59547/121016524-2385f180-c794-11eb-8e04-fe5cbb3ced5a.png)

**Comment by eatyourgreens** [comment]
I can confirm on I Fancy Cats that the drawing task breaks if I go to the project home page mid-drawing, then return to the Classify page and resume drawing. New marks are added to the page, but won't render as SVG shapes. I think that's related to this bug.
https://frontend.preview.zooniverse.org/projects/brooke/i-fancy-cats/classify/workflow/693?env=staging

**Comment by eatyourgreens** [comment]
@snblickhan I'm also finding that leaving the Classify page, then returning, also breaks creating new transcriptions. As well as the previously completed lines being displayed as a fan, any click on the page throws an error and it's impossible to create new lines.

A workaround is to rotate the page by 90º, then hit the reset button to restore it. This redraws all the completed marks in their correct positions and allows drawing to work again.

**Comment by eatyourgreens** [comment]
The root of the problem seems to be refs to DOM nodes that are `null` in the subject viewer, which breaks calls to `element.createSVGPoint()` or `element.getBoundingClientRect()`.

**Comment by srallen** [comment]
@eatyourgreens are you taking this one on? If so, can you assign yourself? Thanks!

**Comment by eatyourgreens** [comment]
I’m afraid I don’t have time to take this on at the moment. Sorry.
