### ISSUE TITLE
Transcription Task modal is obscuring text being transcribed

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#2233]
## Is your feature request related to a problem? Please describe.
Users on Beyond Borders are reporting (see this [Talk thread](https://www.zooniverse.org/projects/mainehistory/beyond-borders-transcribing-historic-maine-land-documents/talk/3952/2019110)) that the transcription task modal consistently obscures the text they're trying to transcribe. This was a similar report from ASM, though they note that it is nice that they can actually move the box around (an improvement from the beta version!). 

## Describe the solution you'd like
The modal should pop up *below* the placement of both dots. Whatever our current metric is for placement, we should increase it.

## Describe alternatives you've considered
None

## Additional context
This was a request from the ASM days, so it may be that whatever we put in place to address that wasn't enough. I think it's worse on projects with closely-spaced lines. For example, it's not that common on the Davy Notebooks Project, but I just tried a few pages on [Beyond Borders](https://www.zooniverse.org/projects/mainehistory/beyond-borders-transcribing-historic-maine-land-documents) and had to adjust every single modal because it consistently covered up the text I was trying to transcribe.

**Comment by snblickhan** [comment]
Additional information/context from a volunteer (via DM):
>On the much belabored Transcription Box location in the Maine Land Document project, I've been trying to figure out how the placement is done by the software. Frankly, it makes no sense. Clearly, the box placement is related to the transcription line that it belongs to. However, there is no consistency whatsoever in that relationship that I can determine. It seems that, typically, the top of the box is below the line enough to recognize descenders and some punctuation - but only in the first few lines of a transcription (full page, 40-60 or more lines of text). It then shifts to just barely below the line and then could be creeping toward and past the line a pixel width per line or possibly be stable for a few lines before it moves up. At the bottom of the page, it often is covering half the line or more (on my monitor at least).

>Now, I'm aware that there are many intermediate factors betwen what is planned and what is seen in this type of graphic interface. And different monitors (and hopefully to a lesser extent browsers and OSs) play a part. BUT, the location should consistent relative to every transcription line and not variable as it is. Then, one could adjust to however it appears on their set up. Now, there is no possible adjustment that will work for an entire document other than moving the box away from the transcription line.

**Comment by eatyourgreens** [comment]
Would something like this be preferable? This popup opened halfway off the bottom of the browser viewport, so I dragged it up into roughly the middle of the screen. It seems like it should be possible to write an algorithm that figures out the box position based on the position of the green SVG line and the viewport boundaries.

<img width="1081" alt="Screenshot of a page transcription, with a green line in progress towards the bottom of the page and a text input open in a modal about halfway up the screen, above and to the right of the text being transcribed." src="https://user-images.githubusercontent.com/59547/173631314-9c5eeb4a-507e-4991-8ddd-600e5cf7c647.png">

**Comment by eatyourgreens** [comment]
The current code computes the mid-point of the green line, then tries to place the top left corner of the popup there. 🤔 
https://github.com/zooniverse/front-end-monorepo/blob/605751fafe413da614d1c5e9677676249b2fbbdb/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/helpers/getDefaultPosition/getDefaultPosition.js#L22-L23

**Comment by eatyourgreens** [comment]
>FYI there are reported issues recently of the transcription box popping up OUTSIDE the viewport due to misplaced lines being pulled very very far to the edge... yeesh. Another good reason to explore your suggested viewport option. https://www.zooniverse.org/projects/mariaedgeworthletters/maria-edgeworth-letters/talk/4462/2474880?comment=4057579&page=1

That's interesting, and useful to know. It must be using coordinates on the page itself, which includes any areas that need to be scrolled into view.

**Comment by eatyourgreens** [comment]
Here's Maria Edgeworth Letters on my PR branch.

<img width="1225" alt="Screenshot of a letter from Maria Edgeworth Letters. The active line is towards the very bottom of the window and the text task popup is above it, more towards the centre of the viewport." src="https://user-images.githubusercontent.com/59547/173846893-622549f1-82e9-4994-afba-caa3030a5040.png">

**Comment by eatyourgreens** [comment]
#3320 is merged now. I'm not sure whether to close this.

**Comment by eatyourgreens** [comment]
I'm still seeing the bottom of the popup obscure the text on some Beyond Borders subjects, so I'll leave this open.


[Beyond Borders: Coll. 60 and Coll. 26.](https://frontend.preview.zooniverse.org/projects/mainehistory/beyond-borders-transcribing-historic-maine-land-documents/classify/workflow/18383)
<img width="833" alt="Screenshot of the transcription tools with a Beyond Borders page. The transcribed line is about halfway down the page. The bottom of the open transcription popup covers half of the text that's being transcribed." src="https://user-images.githubusercontent.com/59547/174045035-fad3817b-d153-4446-8aec-8761effd1be6.png">
