### ISSUE TITLE
Workflow display order

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#2234]
## Describe the bug

The available active workflow list displayed on the home page or on the classify page selector modal doesn't respect the order set by the project builder from the lab. 

## Expected behavior

The order is stored on the project configuration attribute, so the `WorkflowSelector` component should be updated to use this ordering. 

## Additional context

Related to zooniverse/Panoptes-Front-End#5967

**Comment by eatyourgreens** [comment]
This might be a good reason to update the project model, so that workflows are passed as part of `initialState` here:
https://github.com/zooniverse/front-end-monorepo/blob/79b171487e55fa2b6f3dc2015dfc61ffbb0c7d42/packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js#L25-L30
