### ISSUE TITLE
Markdown inconsistency 

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/front-end-monorepo#2252]
## Describe the bug
This bug has been reported by our National Archives collaborator on the Engaging Crowds project:
Project - https://frontend.preview.zooniverse.org/projects/bogden/scarlets-and-blues
Lab - https://www.zooniverse.org/lab/12268

## To Reproduce
From our collaborator:

"I promised to send an example of markdown-in-tasks behaving inconsistently. So here are some screenshots.
 
good_markdown_input is task T9 of the MinutesSimple workflow (workflow #18504, and I think a Checkbox task)
good_markdown_output is visible in the MinutesSimple workflow. Press “Attendance page” on the first screen to see it at the top of the next screen.
bad_markdown_input is task T1 of the IndexSimple workflow (workflow #18505, and a Text task)
bad_markdown_output is visible in the IndexSimple workflow. Press “Yes” on the first screen to see it at the top of the next screen (but I’m going to change this back to a form that doesn’t rely on markdown in a moment).
 
I’m calling this a markdown inconsistency, but the behaviour I’m seeing is just rendering or not rendering line breaks. I guess that happens via markdown, but that could be a bad assumption on my part."

## Expected behavior
A line break should either appear or not appear each time (consistent behaviour)

## Screenshots
![bad_markdown_input](https://user-images.githubusercontent.com/5321335/122574560-aab24f80-d047-11eb-8995-cbab431a2e28.png)
![bad_markdown_output](https://user-images.githubusercontent.com/5321335/122574561-ab4ae600-d047-11eb-9384-856f90e6e6af.png)
![good_markdown_input](https://user-images.githubusercontent.com/5321335/122574564-ab4ae600-d047-11eb-80ca-b3d7c890aec8.png)
![good_markdown_output](https://user-images.githubusercontent.com/5321335/122574567-ab4ae600-d047-11eb-9665-2c8807e9070d.png)

**Comment by eatyourgreens** [comment]
Paragraph breaks aren't allowed in form input labels in HTML. Right now, the text task label is coded as a single line of text, which can't contain paragraphs, headings, lists or links. I remember us discussing this at one of the Engaging Crowds weekly meetings. @beckyrother thought the text task instructions should be limited to a single line, if possible. I tend to agree with her. Is there a case where rich text formatting would be required for text task instructions?

Do we want to change that 'Main text' input, in the lab, from plain text to Markdown? I can see this getting complicated, if project owners decide they want to add headings, paragraphs and lists to task instructions.

**Comment by eatyourgreens** [comment]
The multiple choice question in the 'MinutesSimple` workflow has broken HTML too. Form legends aren't allowed to contain block level elements, like paragraphs.

```html
<legend class="StyledText-sc-1sadyjn-0 nGgvb sc-fznKkj fQkkzS">
  <p class="StyledParagraph-tbetod-0 gALVd">Present (Commissioners)</p>
  <p class="StyledParagraph-tbetod-0 gALVd">Select the people who were at the meeting.</p>
</legend>
```

**Comment by srallen** [comment]
We already allow markdown on PFE for the text task, so updating it to render markdown is getting it to current parity. If we change it, then it should be a holistic change with the lab, and documented, with some kind of migration or time given to project owners to update their workflows. About whether or not it's need for projects currently being built, @snblickhan is better to ask that to. However, if we apply this change to all past projects, then certainly there will be some broken instructions since that's how it renders on PFE now.
