### ISSUE TITLE
HMS NHS workflow 18611 priority subjects not behaving as expected

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#2279]
## Describe the bug
In workflow `18611` something is causing a problem with the priority ordering for subject set `82783`. The first subject set (`82783`) is showing Finished, random subjects (should be priority), and choosing another subject set initially delivers the wrong subject, which can be fixed by refreshing the page.

## To Reproduce
NB workflow `18611` is currently de-activated, but here's what you'd do normally: 
1. Go to the first Workflow (Admissions, `18611`) 
2. Choose the DHS/1 subject set (`82783`) 
3. See a Finished banner with a random subject
4. Choose any other subject set in the same workflow
5. See a Finished banner w/ random subject
6. Refresh the page
7. See the correct 'start' image for that subject set (typically number 4)
8. Return to the DHS/1 subject set (`82783`) 
9. Get the starting subject from the wrong set (number 4/n)
10. Refresh the page
11. Get a random Finished subject

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:
Project number `11429`
Workflow number `18611`
Subject set number `82783`

(NB currently deactivated) https://www.zooniverse.org/projects/msalmon/hms-nhs-the-nautical-health-service/classify/workflow/18611/subject-set/82738

**Comment by eatyourgreens** [comment]
I think there might be a couple of different things going on here. One is getting random, finished subjects when a set is complete. The other sounds like the subject queue might not be reset when you change sets, so you continue to see the same subject in the classifier.

**Comment by eatyourgreens** [comment]
I can reproduce this on workflow 2., now that the first set is complete there too. It also seems like it happens intermittently on incomplete workflows: the subject is sometimes from the previous set, not a subject from the subject set specified in the URL.

Unfortunately, serialised subjects from Panoptes don't seem to include the subject set ID, so it's hard to validate the subject against the set.

@snblickhan For Science Gossip, we adopted a convention of including information about the volume and year in each subject's metadata. Maybe we should be encouraging that as a convention on these projects? The only metadata for each HMS NHS subject is the filename

**Comment by snblickhan** [comment]
According to the Talk boards, it looks like volunteers are using the fraction number to 'recognize' subjects (e.g. 175/210), which is causing people to report that they're seeing the same subject after already classifying it. :/

**Comment by eatyourgreens** [comment]
If that number's the same, then it probably is the same subject. The first number is priority, from `subject.metadata` and the second is the total count, from the set. Looking at the list of sets for each workflow, the subject count seems to be reasonably different for each set.

**Comment by eatyourgreens** [comment]
When I go to the home page and choose a new subject set, I don't see the classifier making any requests for new subjects. I think that's the bug: the subject queue isn't being rebuilt from Panoptes when I return to the classifier.

The network panel here doesn't show any requests to `/api/subjects/queued`. The screenshot was made at https://www.zooniverse.org/projects/msalmon/hms-nhs-the-nautical-health-service/classify/workflow/18612/subject-set/82738, which is a subject set with 101 subjects (not 194.) The classifier does request the subject set from Panoptes, so the active subject set has changed in the classifier.
![Screenshot of the network panel for the classifier showing all the requests made after changing subject set. There's no request for new subjects.](https://user-images.githubusercontent.com/59547/124030235-e8bb5600-d9ed-11eb-966b-cc140829ffe9.png)

**Comment by eatyourgreens** [comment]
I've traced the bug as far as `workflows.selectWorkflow(workflowID, subjectSetID)` here.
https://github.com/zooniverse/front-end-monorepo/blob/9f9834179cea7f72cbe802c98bd60f2d31afec8a/packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js#L59-L81

A change in subject set ID isn't triggering a request for new subjects.
