### ISSUE TITLE
Transcription task: Single-click annotations blocking movement through workflow

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#2292]
## Package
FEM - Transcription task

## Describe the bug
On projects that use the Transcription Task, it is possible to create an annotation with a single click (i.e. 1 instead of 2 clicks, which is what's required to trigger the transcription modal). These single-dot annotations are behaving like empty 2-dot annotations, and are blocking volunteers from being able to click "Next" and move on in the workflow. 

## To Reproduce
1. Go to the [Davy Notebooks Project classify page](https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/classify/workflow/18759).
2. Click on the image to create a first annotation dot. 
3. Click anywhere outside the subject viewer. The dot will remain on the image and be green.
4. Interact with another line on the subject (e.g. click on an existing annotation and select a transcription from the dropdown menu). Once you have done this, the single dot will turn blue.

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:
Davy Notebooks Project ID: `9006`
DNP workflow: `18759`

## Expected behavior
Volunteers should not be able to place a single dot and have it create an annotation. 

### Desktop (please complete the following information):
 - OS: macOS Catalina version 10.15.7
 - Browser: Chrome
 - Version: 91

## Additional context
Related to a previous issue where volunteers were able to create 'empty' annotations and that blocked them from moving forward. This is primarily happening when volunteers try to click on an existing annotation but don't quite hit it, and don't realize they've started a new annotation.

[Talk thread reporting this issue](https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/talk/2586/2050706?comment=3357094&page=1).

**Comment by srallen** [comment]
@snblickhan thanks for the details. I have an in progress solution to prevent a volunteer from being able to click on another mark if there is a half completed mark on the page. As for half completed marks in general, I think we'll have to come up with a notification to highlight that somehow. I have a rough idea on how to do that, but I want to disable the ability to click the already existing marks first.
