### ISSUE TITLE
Classifier: rotateRectangle doesn't resize properly if Rectangle is rotated

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#2296]
## UI functionality bug

Package: `lib-classifier`

The rotateRectangle tool behaves strangely when you attempt to _resize_ a _rotated_ rectangle.

- If you drag the "resize handles" (there's one on every corner), you can correctly resize the rectangle.
  <img width="252" alt="fem-rotate-rectangle-1a" src="https://user-images.githubusercontent.com/13952701/124989373-f9477e00-e036-11eb-9194-0175fd0a2071.png"> ➡️ <img width="247" alt="fem-rotate-rectangle-1b" src="https://user-images.githubusercontent.com/13952701/124989389-fe0c3200-e036-11eb-83f2-3fb8b80a5791.png">
- If you drag the "rotate handle", you can correctly rotate the rectangle arounds its centre.
  <img width="252" alt="fem-rotate-rectangle-2a" src="https://user-images.githubusercontent.com/13952701/124989540-21cf7800-e037-11eb-9044-b441d02704c3.png"> ➡️ <img width="248" alt="fem-rotate-rectangle-2b" src="https://user-images.githubusercontent.com/13952701/124989556-24ca6880-e037-11eb-9770-b742950a40e4.png">
- ❌ However, **if the the rectangle is already rotated,** the drag handles will resize in the wrong direction.
  <img width="248" alt="fem-rotate-rectangle-3a" src="https://user-images.githubusercontent.com/13952701/124989656-4592be00-e037-11eb-8a3b-cdd91b689592.png"> ➡️ <img width="248" alt="fem-rotate-rectangle-3b" src="https://user-images.githubusercontent.com/13952701/124989672-49264500-e037-11eb-8d46-1b0d538425b1.png">

Notes:
- there is no issue if the SUBJECT IMAGE is rotated. 👍 
- the error exists 
- the explanations for the problem was a lot more wordy, _("if you drag the top-right handle of a 180º rotated rectangle (i.e. what was originally the bottom-left handle) towards up-right then the bottom-left corner...")_ but then I said _eff it_ and just took pictures. They really were worth a thousand words.

### Testing

Tested with macOS 10.12.6 + Chrome 91

- Open a project with a Drawing Task with a RotateRectangle tool, e.g. https://frontend.preview.zooniverse.org/projects/darkeshard/prototype-2015/classify/workflow/18372
- Create a rotateRectangle mark.
- Rotate the rectangle to 45º, 90º, or 180º. (clockwise or anti-clockwise. Anything other than rotation=0, basically.)
- Drag any of the corners to resize.
  - Expectation: the corner you clicked on should follow the position of the mouse
  - Actual: not that.

### Analysis

I've traced this issue back to commit 25a311de58729ba674b963e2ee67db233c8c0d72 (PR #2211 which introduces rotateRectangle), so we can rule out the recent [SVG](https://github.com/zooniverse/front-end-monorepo/pull/2255) [refactors](https://github.com/zooniverse/front-end-monorepo/pull/2277) - this will make the debug simpler! 👌 (I don't want to dive into the higher-class SVG structures again, d'oh.)

Anyway, I think I have a good idea of **why** this is happening: the drag-to-resize logic has maths that compensates for the rotation of the Subject image (aka the SVG Transform layer), but NOT the transform of the rotateRectangle.

- Let's take a look at `lib-classifier`'s `RotateRectangle.js`'s `onHandleDrag()` (which is _one function_ that handles the resize logic for _all four corners_)...
  ```
  <DragHandle  // Top-Right handle
    scale={scale}
    x={x_right}
    y={y_top}
    dragMove={(e, d) =>
      onHandleDrag({  // The function is the same, only the variables are different.
        x_left: x_left,
        x_right: x_right + d.x,
        y_top: y_top + d.y,
        y_bottom: y_bottom,
        angle: angle
      })
    }
  />
  ```
- ...and compare it with [PFE's Rotate Rectangle](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/rotate-rectangle.jsx), which has a _four different resize handlers for each of the four corners._
  ```
  handleTopRightDrag(e, d) {
    const difference = this.props.normalizeDifference(e, d);
    const differenceRot = this.constructor.rotateXY(difference, this.props.mark.angle);
    this.props.mark.x -= 0.5 * differenceRot.x;
    this.props.mark.y += 0.5 * differenceRot.y;
    this.props.mark.width += differenceRot.x;
    this.props.mark.height -= differenceRot.y;
    this.props.onChange(this.props.mark);
  }
  ```
- While we can't copy-paste the code (FEM and PFE rotRects are too different, at least on the surface), we can see that the PFE code _factors in the mark's current angle_ (see: rotateXY()) to calculate the final x/y/width/height (analogous to x_left/x_right/y_top/y_bottom)

UPDATE: hmm... a thought occurs to me as I write this. I wonder if the solution is as simple as changing the FEM code's `x_right: x_right + d.x` up there to `x_right: x_right + rotateVector(d.x, d.y, angle).x`

### Status

Fix required, but Rotate Rectangle isn't out in the wild yet (it's only used in an upcoming project), so we have a fair amount of safety time to get a solution running.

**Comment by shaunanoordin** [comment]
Tagging in @ErikOstlund ! Let's rotate those rectangles!

**Comment by eatyourgreens** [comment]
We could change `draggable` so that dragging always happens in the frame of the rotated mark. That’s an easy change to the `draggable` function. It would probably change the maths for the rotation handle.

**Comment by shaunanoordin** [comment]
UPDATE: Okay, I found a solution.

```
// In RotateRectangle.js, add the function...
function rotateXY ({ x, y }, angleInDegrees) {
  const theta = angleInDegrees * (Math.PI / 180)
  const xTheta = (x * Math.cos(theta)) + (y * Math.sin(theta))
  const yTheta = -(x * Math.sin(theta)) + (y * Math.cos(theta))
  return { x: xTheta, y: yTheta }
}

// ...and change the TOP-RIGHT resize handler to...
{active && (
  <DragHandle
    scale={scale}
    x={x_right}
    y={y_top}
    dragMove={(e, d) =>
      onHandleDrag({
        x_left: x_left - rotateXY(d, angle).x,
        x_right: x_right + rotateXY(d, angle).x,
        y_top: y_top + rotateXY(d, angle).y,
        y_bottom: y_bottom - rotateXY(d, angle).y,
        angle: angle
      })
    }
  />
)}
```

So... you'll notice that while resizing the top-right (x_right, y_top) handle, the _left and bottom of the rectangle moves in the opposite way._ You'll still expand/shrink the rectangle as expected, and the x-y centre stays the same, you just have a mildly odd mirror effect to "balance the centre of the rectangle". Is this a worthy tradeoff? (PFE thinks _yes,_ btw.)

If you REMOVE that balancing act though, the x-centre goes all over the place. I haven't been able to fully grok the logic of that yet. 🤷‍♂️

**Comment by ErikOstlund** [comment]
@shaunanoordin, I applied this code and all is looking good! I did have to tweak the `onHandleDrag` for each corner.
I'm finishing this up and will create a PR soon. Thanks for looking into this! 😎
