### ISSUE TITLE
Beyond Borders volunteers seeing repeat images without banners

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#2298]
## Package
FEM

## Describe the bug
Volunteers on the Beyond Borders project are getting repeat subjects, multiple times, without 'Already Seen' banners. The volunteers have not classified every subject in the set.

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:
Project `#12856`
Workflow `#18383`
URL: https://www.zooniverse.org/projects/mainehistory/beyond-borders-transcribing-historic-maine-land-documents

## Expected behavior
Once a volunteer has submitted a classification for a  givensubject, any case of repeat delivery should include an "Already Seen" banner.

## Additional context
See Talk report from volunteer `BarrowTH` here: https://www.zooniverse.org/projects/mainehistory/beyond-borders-transcribing-historic-maine-land-documents/talk/3952/2033702?comment=3361160

**Comment by srallen** [comment]
Closed by #2402
