### ISSUE TITLE
Engaging Crowds: "Finished" modal links and buttons should be centred

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#2327]
## Package
lib-classifier
lib-react-components

## Describe the bug
![Screenshot of the task area for a finished subject, showing the 'Next available subject' button ranged right.](https://user-images.githubusercontent.com/59547/127823937-06092446-aa58-4806-993c-dc85c0b2d3a4.png)

The right and left margins of the buttons should match (compare with the screenshot in #2198.)

## To Reproduce
Use the `finished` query parameter to force the popup on any subject:
https://frontend.preview.zooniverse.org/projects/bogden/scarlets-and-blues/classify/workflow/17076/subject-set/96235/subject/63413209?finished=true

**Comment by srallen** [comment]
https://github.com/zooniverse/front-end-monorepo/pull/2321 included some theme updates for the `PrimaryButton` including a max-width of 350px. The design system actually says the max-width should be 300px, but after inspecting several designs, I found some buttons up to 350px, so I implemented it as a max-width of 350px. To fix this, the container styles should center the children.

**Comment by eatyourgreens** [comment]
Thanks! I'd missed `alignSelf` on that particular button.
