### ISSUE TITLE
Classification highlighting is confusing

### ISSUE THREAD

**Issue by ageller** [zooniverse/front-end-monorepo#2340]
## Package

Variable Star Light Curve Viewer

## Describe the bug

When I select a classification, it still "semi-highlights" (at the level for a mouseover) the top-left option ("Periodic (puslating): Mira variable").  This becomes un-highlighted when I click out of the browser, but then comes back on when I click into the browser again.  Please see this screen grab below.

## To Reproduce
1. Go to https://www.zooniverse.org/projects/adamamiller/zwickys-stellar-sleuths/classify/workflow/16454?demo=true
2. Click on 'Non-periodic' (or any classification other than the top left)
3. Click 'Identify' on the pop-up.

## Expected behavior
The "semi-highlighting" on the top left classification should go away when a classification is made.

## Screenshots
<img width="456" alt="Screen Shot 2021-08-03 at 10 44 38 AM" src="https://user-images.githubusercontent.com/753117/128377076-f5128aef-9e27-43cd-8525-ddde98a76f82.png">

### Desktop (please complete the following information):
 - OS: macOS Big Sur Version 11.15.1
 - Browser Chrome
 - Version 92.0.4515.107 (Official Build) (x86_64)

**Comment by srallen** [comment]
@mcbouslog do you think this is the autofocus firing? The focus should go back to the button clicked.

**Comment by mcbouslog** [comment]
> @mcbouslog do you think this is the autofocus firing? The focus should go back to the button clicked.

Yes I think that's it (autofocus firing to first choice button instead of selected choice button). I'll start debugging today, will update on progress.

**Comment by mcbouslog** [comment]
Editing [the Choices component's `useEffect`](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.js#L33-L35) for `focusIndex` to:
```
useEffect(() => {
  if (selectedChoiceIds.length > 0) {
    const lastSelectedIndex = filteredChoiceIds.indexOf(selectedChoiceIds[selectedChoiceIds.length - 1])
    if (lastSelectedIndex > -1) {
      setFocusIndex(lastSelectedIndex)
    } else {
      setFocusIndex(0)
    }
  } else {
    setFocusIndex(0)
  }
}, [filteredChoiceIds])
```

Seems to have fixed the issue. After deleting a choice the focus goes to the last choice selected or back to the first choice, which might not be ideal, but I think ok. I'll update tests and open a PR asap.
