### ISSUE TITLE
Scrolling within the field guide using the mouse wheel does not (fully) work as expected

### ISSUE THREAD

**Issue by ageller** [zooniverse/front-end-monorepo#2341]
## Package
Variable Star Light Curve Viewer

## Describe the bug
This may not be technically a bug, but it is something that should be looked into for usability.  Depending on the exact mouse placement within the field guide, scrolling by the mouse wheel will move the field guide in three different ways.  It can move the text within the field guide up and down, as the user probably wants.  It can move the container around that text up and down (which should not be necessary), and it can also move the entire website behind the field guide up and down (which is not useful).  Please see movie below for a demo of the problem.   (It may also help to give the two different scroll bars slightly different styling to differentiate them.)

 
## To Reproduce
1. Go to  https://www.zooniverse.org/projects/adamamiller/zwickys-stellar-sleuths/classify/workflow/16454?demo=true
2. Click on field guide
3. Position mouse between the two scroll bars
4. Use the mouse wheel to scroll up and down
5.  Reposition mouse within the field guide information container (and in other locations) and use the mouse wheel 
6. See error

## Expected behavior
Ideally there is no ambiguity about which portion of the field guide scrolls.  If the mouse is within the field guide, the only portion that needs to scroll that the element that contains the images and text.

## Screenshots
https://user-images.githubusercontent.com/753117/128379117-753a34e3-b4f1-4741-b142-fefa271910e8.mov

### Desktop 
 - OS: macOS Big Sur Version 11.15.1
 - Browser Chrome
 - Version 92.0.4515.107 (Official Build) (x86_64)

**Comment by srallen** [comment]
@mcbouslog there may be some CSS we can use to deal with this. This seems like a good article overview the state of the CSS support for scrollbars: https://www.digitalocean.com/community/tutorials/css-scrollbars

Maybe we can do something clever, like set the scrollbar width and then set the inner content width of the modal to be something like `width: calc(100% - scrollBarWidth)` or something like that.

**Comment by goplayoutside3** [comment]
Tagging myself on this issue because I'm refactoring FieldGuideItem with correct usage of Media. I'll be able to investigate this scrolling issue while doing so.

**Comment by goplayoutside3** [comment]
Another example video showing how there are two scrollbars in the field guide

https://user-images.githubusercontent.com/23665803/212375312-1b40f48e-6f48-456e-8be1-05c2ae04bf73.mp4
