### ISSUE TITLE
Back button message is not true

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/front-end-monorepo#2363]
One of the volunteers on HMS NHS reported this issue. When you tab through the tasks in the workflow and get to the 'Back' button at the bottom, you get a message that says "Ging back will clear your work for the current task". However, this isn't true, at least on HMS NHS. The existing annotations persist when you come back. 

![image](https://user-images.githubusercontent.com/5321335/129893279-ba270927-da7e-4ead-b322-c285d50dfb4f.png)

**Comment by eatyourgreens** [comment]
Have you got a link to the broken workflow? That warning is wired up to the 'persist annotations' setting in the project builder, so that might not be set correctly.

Styling's broken too.

**Comment by eatyourgreens** [comment]
Investigating this on I Fancy Cats, there's a couple of bugs here:
- `persistAnnotations` is off by default in the code.
- the warning is enabled by default but doesn't show on mouse events, only focus/blur.

**Comment by eatyourgreens** [comment]
#364 fixes the first of those problems by setting a default workflow config, same as for 'hide classification summaries'.

**Comment by eatyourgreens** [comment]
Should we remove this message from the code? All workflows support undo/redo now, so there's no reason to delete an annotation when going back.

**Comment by srallen** [comment]
@eatyourgreens could you open an issue to track deprecating `persist_annotations` out of the classifier?
