### ISSUE TITLE
Classifier - Drawing Task needs a proper panel

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#239]
## Feature Required

Package: lib-classifier

When the Classifier shows a Drawing Task, it should display a proper task panel instead of "Task component could not be rendered."

![screen shot 2018-11-06 at 17 12 45](https://user-images.githubusercontent.com/13952701/48081222-70257c80-e1e7-11e8-8a5b-3bc1d4ab14e9.png)

**Comment by shaunanoordin** [comment]
### Context
The Drawing task is required by the Planet Hunters TESS project and intertwines with the TESS LCV development. (See [Staging Project 1862, workflow 3280](https://master.pfe-preview.zooniverse.org/lab/1862/workflows/3280) )

For reference, the TESS Light Curve Viewer uses a Drawing Task of type: Column.

**Comment by shaunanoordin** [comment]
That's a legit point, @srallen - I'm open to ideas, as my only question is _"How should the Classifier Task Panel work, when the viewer used is the specialised LCV which has its own range selection task?"_

Two options in my head:
- The LCV ignores whatever Task that appears in the Task Panel (on the right side of the Classifier), and always uses its own specialised annotation tool (the Range Selector tool, which is partly specified in #241 )
  - the question then is, what do we do with the Task panel on the right?
- The LCV respects whatever Drawing Tool is specified in the Workflow (and currently appears on the Task panel, on the right side of the Classifier)
  - ...however, for the sake of the TESS project, the Task given _must_ be a Drawing Task of type Column. (The LCV ignores annotation attempts otherwise)
  - This might be good if we plan to generalise the LCV into a ScatterplotViewer, in the future (outside of the scope of the TESS project).

Good news is, the Light Curve Viewer is only used when the _workflow is manually configured so that workflow.configuration.viewer = 'lightcurve'` so we can make some safe assumptions that whoever is using the LCV _knows_ the caveats for setting up a light curve workflow.

Staging Project 1862 Workflow 3280 is the development workflow that I'm working with at the moment, and it's open to further changes. 👍 We can tweak it as much as we want.

**Comment by srallen** [comment]
I conceptually imagined that data type subject viewers would have a set of data selection tools, not drawing tools. We aren't drawing on the plot. The current column drawing tool is built with the assumption it is drawing on top of a SVG layer that is the same size as a scaled subject image. With a data viewer, we can directly interact with the plot and select the actual data values. They really aren't the same.

As for how it is rendered in the task area for the UI, though, I think it very much can be similar to the drawing tools where there is a set of radio button selectors where you select the tool you wish to annotate with. The annotation recorded would come from the selection event on the plot, where as the radio button onchange would record in the annotation the index of the tool selected, like drawing tools.

Similarly, in the lab, eventually we would have an option in the workflow task builder to select a "Data Annotation Tool" that only become available if a data subject viewer is configured. Then in the editor, you configure the specific tools you want available.

**Comment by srallen** [comment]
Drawing tools are being built out as independent tools from data visualization annotation tools.
