### ISSUE TITLE
Deprecate 'sim notification'

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#2435]
## Package general

A variant of feedback was implement to notify the volunteer that the subject was a sim after completing classification known as `sim notification`. This should be deprecated in favor of the general feedback feature. If there is a task type that is missing feedback, we should build the strategy.

**Comment by goplayoutside3** [comment]
I can't find evidence of `sim notification` related to feedback in FEM. Closing this issue due to lack of detail.
