### ISSUE TITLE
Survey Task: Add an explanatory headline question to the survey task?

### ISSUE THREAD

**Issue by hughdickinson** [zooniverse/front-end-monorepo#2437]
## Expected behavior

Really more like desired behaviour (maybe something to consider for the new FEM), but it would be good if a question could be specified for the survey task. Something like:
> "What type of Xs are present?"
It's not always entirely obvious what the task is. Specific context here is a project classifying knitting patterns and the survey is of garment types. However, there are several other tasks in the workflow and it's not entirely obvious what interaction is required from the user.

I recognise that a project tutorial might help, but not everyone reads or follows the tutorial!

## Current behavior
There is no opportunity to enter a question for the survey task.

## Steps to replicate
N/A

## Additional information

- **Operating system:** Any
- **Browser:** Any

**Comment by lcjohnso** [comment]
@seanmiller26 -- I would be interested to know your opinion on this possible enhancement: should we present question text (optionally?) to instruct volunteers on what they should do when presented with the survey task interface?  If so, is there a good place / way to present this text given the current survey task UI?

**Comment by seanmiller26** [comment]
I am absolutely in favor for anything which adds clarity. It would be as simple as adding an overarching question just above the choices. Is this extra text field something we could add to the project builder? 
<img width="489" alt="Screen Shot 2022-11-29 at 11 09 16 AM" src="https://user-images.githubusercontent.com/89043489/204596333-1800ce07-6496-41c7-80d5-ad95c4320951.png">
