### ISSUE TITLE
Markdownz: Consecutive images can't render inline with each other

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#2462]
## Package
lib-react-components

## Describe the bug

- When using markdown in PFE, multiple, consecutive images can be rendered inline with each other if their widths are small enough:

PFE Galaxy Zoo Example:
![pfe](https://user-images.githubusercontent.com/23665803/134983035-31a63b26-c033-4476-b6a3-bc6a088a38a1.png)

- When viewing the same project with FEM, consecutive images stack on top of each other instead.

FEM Galaxy Zoo Example:
![fem](https://user-images.githubusercontent.com/23665803/134983610-e61e0388-a460-4bd7-abe1-d7098c0d197a.png)

The above example is a screenshot of FEM storybook related to PR #2463 .

In `remark-react`, react components are mapped to html elements, but the custom function mapped to markdown image strings is returning `Media` components inside a `<p>`. This means multiple images cannot be rendered inline with each other even if their widths are small enough.

Note: The current implementation of FEM `Markdownz` is using outdated `remark` packages, and upgrading to the latest may help solve this issue.

## To Reproduce
- Can compare PFE [Galaxy Zoo](https://www.zooniverse.org/projects/zookeeper/galaxy-zoo/about/research) research page and [FEM Galaxy Zoo research page](https://frontend.preview.zooniverse.org/projects/zookeeper/galaxy-zoo/about/research).

## Expected behavior
Consecutive images written in markdown should render side by side if their widths are small enough.

**Comment by lcjohnso** [comment]
An issue here: the mismatch of expectations between what is rendered in the project builder vs. what they see in FEM.

**Comment by eatyourgreens** [comment]
This isn't a bug in `Markdownz`. It's a bug in `Media`. The `Media` component wraps all images in a `div` element:

https://github.com/zooniverse/front-end-monorepo/blob/fedb8d47f701b0ea287e65949f68c0965830c7af/packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js#L47-L61

`div` is a block-level tags and HTML blocks stack on top of one another when rendered on the page.

**Comment by eatyourgreens** [comment]
I suspect that removing that wrapping `div` will have side effects everywhere that the `Media` component is used. ☹️

**Comment by eatyourgreens** [comment]
For images to display side-by-side, they should be displayed as either `inline` or `inline-block`, not `block`.

**Comment by eatyourgreens** [comment]
Project teams are also expecting line breaks to be converted to `<br>`. See the Galaxy Zoo field guide for examples. I've fixed that in #5341 too.
