### ISSUE TITLE
Toolbar for Freehand Line Tool

### ISSUE THREAD

**Issue by ErikOstlund** [zooniverse/front-end-monorepo#2493]
## Package
`lib-classifier`

## Describe the solution you'd like
Create or use the existing banner used in the Classifier component. Similar to the `Next/Prev` toolbar seen here:
![image](https://user-images.githubusercontent.com/9533007/137515326-c9702815-c62c-466b-8f59-b5318e71a2d1.png)

The intention of the `Freehand Line` toolbar is to contain the UI for all features related to the `Freehand Line`.
The scope of this ticket is to have a toolbar appear above the subject when the `Freehand Line` tool is selected.
The toolbar should have three states:

- No paths have been drawn
- No path is active
- Name of the active path

![image](https://user-images.githubusercontent.com/9533007/137516196-647d7189-d815-4c14-bcc2-0700a6b32cd4.png)

## Additional context
This is part of the Freehand Line tool feature. For the complete list of features, see: [GitHub Project](https://github.com/zooniverse/front-end-monorepo/projects/14).

**Comment by goplayoutside3** [comment]
Closing because the drawing tools have a UI in the task area as well as the LineControls component or each mark.
