### ISSUE TITLE
Add zoom out option from default image view

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#2499]
## Package
FEM

## Is your feature request related to a problem? Please describe.
It currently looks like min zoom = default zoom, meaning that if a team has to rotate an image, the landscape view can never fit to the image window (see screen recording below). 

## Describe the solution you'd like
Would like to add a few increments (3-5) of being able to zoom out from the default view.

## Additional context
Use case = cross-writing on transcription projects, where you need to be able to rotate an image and zoom out so that the entire width fits in the view frame.

https://user-images.githubusercontent.com/25958358/137985042-4f5abf25-fdd9-4b9a-bdb1-59497c87d4af.mov

cc @lcjohnso

**Comment by eatyourgreens** [comment]
This might just be a case of setting `minZoom` alongside `maxZoom` here. The default is `minZoom=1`. 

https://github.com/zooniverse/front-end-monorepo/blob/9813e756b490de5cbdc551d7567f1ff235f3b880/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js#L135

**Comment by mcbouslog** [comment]
Yep, was indeed simply adding a `minZoom`, thanks @eatyourgreens !

**Comment by mcbouslog** [comment]
Reopening for MultiFrameViewer
