### ISSUE TITLE
Add Grommet dark theme

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#25]
Currently the grommet theme only supports a standard set of colours - we need to use named colour variables to create a dark theme

#8

**Comment by srallen** [comment]
Grommet team's v2 theme file for reference: https://github.com/grommet/grommet/blob/NEXT/src/js/themes/vanilla.js

**Comment by rogerhutchings** [comment]
cc #653

**Comment by srallen** [comment]
Grommet 2.6.2's changelog is showing fixes for dark theme support, so we should update before doing any more work on the dark theme: https://github.com/grommet/grommet/releases/tag/v2.6.2

**Comment by srallen** [comment]
We've added dark theme support
