### ISSUE TITLE
NextJS: static assets should use the CDN

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#2518]
## Package
app-project
app-content-pages

## Is your feature request related to a problem? Please describe.

Static assets are being served direct from `fe-project.zooniverse.org`. See the list here:

https://www.webpagetest.org/result/211012_AiDc90_8b632dd922250dee0f45d20c722a5bd5/1/performance_optimization/

![Screenshot of a performance test, listing files that are being served direct from the origin.](https://user-images.githubusercontent.com/59547/140491241-4ca71f3a-015d-4bfd-be22-616d9db16f26.jpeg)

## Describe the solution you'd like
Set up prefixes, in the Next config, for the NextJS apps, then use those prefixes to serve `_next` for each app via `www.zooniverse.org/projects/_next` and `www.zooniverse.org/about/_next`. 

There's a couple of static images for projects, which should also be proxied:
https://github.com/zooniverse/front-end-monorepo/tree/master/packages/app-project/public

Static proxying will need to be set up for staging and production, and the asset prefixes for the apps will need to be updated. 

## Context

NextJS 9.5 added [`basePath`](https://nextjs.org/docs/api-reference/next.config.js/basepath), to allow for multiple apps running on a single domain. We can use that to set up both Next apps on `www.zooniverse.org`, which then allows Next's static assets to be served with CDN caching.

I think the order of operations here would be:

1. [x] Add `basePath` to each app's config, and verify that it works.
2. [x] Add rules for `_next/` and `public/` to our static setup. https://github.com/zooniverse/static/pull/253
3. [x] Update the asset prefixes, in this repo, from `fe-project` and `fe-content-pages` subdomains to `www.zooniverse.org` (production) and `frontend.preview.zooniverse.org` (staging.) #2541

**Comment by eatyourgreens** [comment]
Reopened by #4225.

**Comment by goplayoutside3** [comment]
Closed by https://github.com/zooniverse/front-end-monorepo/pull/4292
