### ISSUE TITLE
Deprecate persist_annotations

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#2525]
## Package
lib-classifier

## Is your feature request related to a problem? Please describe.
Now that we have undo/redo for the Back and Next buttons, annotation values are automatically preserved across tasks for all workflows.

## Describe the solution you'd like
`workflow.configuration.persist_annotations` can be ignored and default to `true` in the code.

**Comment by eatyourgreens** [comment]
cc @shaunanoordin because this can be deprecated in the lab too, once this issue is closed in the code.

**Comment by eatyourgreens** [comment]
Still needs to be done. I think the setting still exists, but is ignored.

**Comment by eatyourgreens** [comment]
`workflow.configuration.persist_annotations` is still being used by the Back button. See #5798.

**Comment by goplayoutside3** [comment]
I removed all refs to `persist_annotations` in https://github.com/zooniverse/front-end-monorepo/pull/5818. @eatyourgreens while Github won't allow an official review or approval I would appreciate your glance at that PR to double check I'm on the right track for deprecating the config option.
