### ISSUE TITLE
Add favicon to browser tabs

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/front-end-monorepo#2544]
This is a pretty small issue but the Zooniverse favicon doesn't show in Chrome browser tabs. Now that we have launch a handful of FEM projects it would be good to have the logo show, as with PFE tabs. I think it adds an extra level of trust and signals clearly that you're still on Zooniverse.org.

**Comment by eatyourgreens** [comment]
The favicon is requested when the page loads but the URL is wrong: https://static.zooniverse.org/www.zooniverse.org/static/favicon.ico instead of https://static.zooniverse.org/www.zooniverse.org/favicon.ico.
