### ISSUE TITLE
Light Curve Viewer / Planet Hunters TESS - annotations disappear when going 'Back' to the Classify page

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#2553]
## Functionality Bug

@eatyourgreens pointed an issue where current annotations on a Light Curve Viewer (the "drag-and-draw columns to mark areas of interest") disappear if you navigate away from the Classify page, then press the 'Back' button on the browser (Chrome? Firefox?).

Steps:
- Go to [Planet Hunters TESS](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess), which is an FEM project with the Light Curve Viewer
- Go to /classify (the Classify page).
- **Make one annotation/mark** on the light curve (which is a D3.js graph)
- Click on the general Zooniverse 'About' link, or any link that breaks you out of the FEM environment (which only covers the Project home page and Classify page)
- Press the 'Back' button to return to the Classify page
- Observe that the same Subject reloads (the Subject queue remains in memory *️⃣ ), but **the annotation/mark is no longer visible on the light curve.**

This is part of the _"Classifier acts odd (some things are saved, some things aren't, depending on the browser) any time you press the Back button"_ issue that Jim's investigating.

⚠️ However, of special interest to the Light Curve Viewer is this: **is the one annotation STILL saved in the Classifier memory, DESPITE visually disappearing from the graph?**
- If the annotation data is STILL stored in memory BUT not visible on the graph, then _this needs a fix quickly_
- I need to check this because the D3.js graph isn't as tightly bound to the React stores. I can't 100% recall if I set some code for _"on component load, sync annotations from the Classifications store."_ (Maybe? Shaun tends to be very paranoid about edge conditions.) 

*️⃣ Actually, I need to double check that _all_ the Classifier data remains the same. I mean, it'd also be a problem if the Classification data is saved, but now a different Subject loads. (I'm not sure if it's just a coincidence that the Classifier keeps serving the same Subject, in Jim's example video.)

**Comment by eatyourgreens** [comment]
Home, About and Classify are all part of the project app, which is a single page React app, so the store global should be preserved across those pages at least. I think you can also reproduce this by going Home => Classify => Home => Classify.

Firefox and Safari, I think, go one step further and preserve window JS state across pages on the same origin. At least, I can get my annotations back by going back from any page on https://www.zooniverse.org, as far as I can tell.

**Comment by eatyourgreens** [comment]
Here's a video of the marked transit vanishing for PH-TESS. I noticed this while testing #2552. Even though the mark disappeared, the page still warned me that I had unsaved changes when I tried to leave.


https://user-images.githubusercontent.com/59547/142443423-6edd9a28-dfb6-4a16-91f9-ff4e59154cad.mov

**Comment by eatyourgreens** [comment]
@shaunanoordin Here's a screen recording that isolates just the buggy behaviour.


https://user-images.githubusercontent.com/59547/142605871-acb52081-6820-42d5-bb8d-7478228a3133.mov

**Comment by shaunanoordin** [comment]
## Investigation Update

❗ CONFIRMED: navigating to another (FEM) page then going "Back" to the Classify page **makes existing annotations _invisible_ - they still exist in the store!**
- When you return to the Classify page with **no visible annotations**...
  - ...if you immediately Submit, **you will submit invisible annotations** ❌ 
  - ...if you make NEW annotations, you will DELETE the old annotations, which at least provides correct results. ✅ 
- Expanded behaviour: the bug is true whether you go (Option 1) Classify page -> navigate to another (FEM) page -> press "Back" to return to Classify page, OR (Option 2) Classify page -> navigate to another (FEM) page -> click on the 'Classify' link. (see [Jim's video](https://github.com/zooniverse/front-end-monorepo/issues/2553#issuecomment-973936016))

I'm now cranking this up into a **serious issue.** The UI/visuals must _always match_ the data models to match user expectations.

### Status

Working on fix now. I need to either...
- (preferred) trigger a D3.js "update this graph" action on component load, to sync _store data_ --to-> _UI graph_
- reset the store data on component load, essentially syncing the UI graph --to-> store data
