### ISSUE TITLE
Image URLs are broken on project About pages

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#2554]
## Package
lib-react-components

## Describe the bug
Project About pages are generating invalid URLs for thumbnail images, which then give a 415 error from the thumbnail server.

eg. https://thumbnails.zooniverse.org/200xnone/panoptes-uploads.zooniverse.org/project_attached_image/84f76c20-5c6e-4d6f-81f2-7b2f8cacec13.jpeg

`200xnone` isn't a valid size for the thumbnail generator. Both parameters should be numbers.

## To Reproduce
Watch the network requests for images while loading this page.
https://www.zooniverse.org/projects/hughdickinson/superwasp-black-hole-hunters/about/team

## Expected behavior
Images should be loaded from the thumbnail server, rather than falling back to the original uploaded file.

**Comment by goplayoutside3** [comment]
This is a bug caused by Markdownz in lib-react-components and is not isolated to project About pages.

The following markdown code example is demonstrated in this [test project](https://frontend.preview.zooniverse.org/projects/goplayoutside3/fem-flipbook-viewer/classify/workflow/22532)'s Field Guide Item. Field guide items are markdown edited by project teams.

```
An image without specified dimensions in its url:
![alt text](https://panoptes-uploads.zooniverse.org/field_guide_attached_image/2f9adcde-9cd5-44e1-a5dc-be3cd1a017fa.jpeg)

An image with "=200x" in its url. This should pass through the thumbnailer service, but does not due to a bug:
![alt text =200x](https://panoptes-uploads.zooniverse.org/field_guide_attached_image/2f9adcde-9cd5-44e1-a5dc-be3cd1a017fa.jpeg)
```

Instead of the 2nd image url passing through the thumbnailer service, the browser network tab throws an error trying to fetch `https://thumbnails.zooniverse.org/200xnone/panoptes-uploads.zooniverse.org/field_guide_attached_image/2f9adcde-9cd5-44e1-a5dc-be3cd1a017fa.jpeg`

**Comment by eatyourgreens** [comment]
The correct URL is `https://thumbnails.zooniverse.org/200x/panoptes-uploads.zooniverse.org/field_guide_attached_image/2f9adcde-9cd5-44e1-a5dc-be3cd1a017fa.jpeg` but I'm not sure where the 'none' is coming from. A default height somewhere, maybe?

**Comment by goplayoutside3** [comment]
Yes, `none` comes from our attempt to make Markdownz backward compatible with PFE's "custom image width in its markdown url" feature.

**Comment by eatyourgreens** [comment]
My example image is an invalid format. 😞  I'll try and find one that works.

**Comment by eatyourgreens** [comment]
Ok, each size must be three digits or less. We can change that here:
https://github.com/zooniverse/thumbnailer/blob/39c3f2d4aa33f74dd36af039f3a524bb8e0cb130/nginx.conf#L42-L45

**Comment by goplayoutside3** [comment]
Would you like to make the change to nginx and I'll open a PR to fix Markdownz's handling of `none` height?

**Comment by goplayoutside3** [comment]
Oh, I'd assumed you'd like the thumbnailer to be able to handle more than 3 digits per dimension. However, I'm leaning toward keeping the 3 digit limit because does a thumbnail image need to be larger than 1000px?

**Comment by eatyourgreens** [comment]
Good point. Maybe for background images, or if we ever wanted to run subjects though the thumbnail service. Otherwise, 999px seems like a reasonable maximum size.

**Comment by eatyourgreens** [comment]
We could add an nginx rule something like this:
```nginx
if ($uri ~ "^/([1-9][0-9]{0,2})xnone/") {
  set $width $1;
  set $height 1000;
}
```

I don't know what possible values can be passed to the image resize commad here, so I've guessed at setting a default height of 1000.
https://github.com/zooniverse/thumbnailer/blob/39c3f2d4aa33f74dd36af039f3a524bb8e0cb130/nginx.conf#L89

Seems like it should also be easy enough to translate 'none' to '999' in the Markdownz component.

**Comment by eatyourgreens** [comment]
I found this from a quick search of the nginx docs.

>resize width height
    proportionally reduces an image to the specified sizes. To reduce by only one dimension, another dimension can be specified as “-”. In case of an error, the server will return code 415 (Unsupported Media Type). Parameter values can contain variables. When used along with the rotate parameter, the rotation happens after reduction. 
 
 https://nginx.org/en/docs/http/ngx_http_image_filter_module.html#image_filter

**Comment by goplayoutside3** [comment]
I think 'none' in Markdownz is intended to preserve the aspect ratio of images when only the width is specified in the url such as =200x. In that case we do not want the image to be fetched with 200x999 dimensions, and we do want it to be displayed in a project page with 200x999.

For instance, Galaxy Zoo has a lot of images with a 1:1 aspect ratio, but only a width specified like =200x in the markdown url. Their aspect ratio should preserved when displayed in the browser.

**Comment by eatyourgreens** [comment]
The resizer preserves aspect ratio. The numbers in the URL are maximum possible dimensions, which should be ok unless images are tall and thin. :thinking:

**Comment by goplayoutside3** [comment]
By resizer do you mean thumbnails.zooniverse.org? And I agree that it does preserve aspect ratio.

Where we run into trouble is in the FEM Markdownz code where css rule max-height is used and I believe requires a value. I'll link the lines below, and then open a PR to handle this bug in FEM.

**Comment by goplayoutside3** [comment]
https://github.com/zooniverse/front-end-monorepo/blob/56e35a15055fb49dac48283d8a3716ea77b22f1f/packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js#L10-L13

**Comment by eatyourgreens** [comment]
You can see that in a live project by inspecting the survey task images for Wildwatch Burrowing Owl when you identify an animal. Of course, these are all landscape images.
https://www.zooniverse.org/projects/sandiegozooglobal/wildwatch-burrowing-owl/classify/

eg.
https://thumbnails.zooniverse.org/500x999/panoptes-uploads.zooniverse.org/production/workflow_attached_image/810f7681-74a9-41e9-a251-48f90424d001.jpeg

**Comment by eatyourgreens** [comment]
>By resizer do you mean thumbnails.zooniverse.org? And I agree that it does preserve aspect ratio.

Yeah, the nginx image resize filter.

>Where we run into trouble is in the FEM Markdownz code where css rule max-height is used and I believe requires a value. I'll link the lines below, and then open a PR to handle this bug in FEM.

The CSS value should be 'none', I suppose but isn't that different from the height string that's passed in the URL? The URL needs a filter that translates 'none' to '999'

**Comment by goplayoutside3** [comment]
> The CSS value should be 'none', I suppose but isn't that different from the height string that's passed in the URL? The URL needs a filter that translates 'none' to '999'

Yes I think that's the solution

**Comment by eatyourgreens** [comment]
I think you might be right. I've opened https://github.com/zooniverse/thumbnailer/pull/25 to add support for URLs like `/200xnone/`.

**Comment by goplayoutside3** [comment]
Apologies I misunderstood where the solution to translating none to 999 should be.

Given that FEM Markdownz needs to be refactored due to deprecation of `remark-react`, I recommend we make changes to FEM instead of the thumbnailer service. For instance, we might not actually need max-height of 'none' at all.

**Comment by goplayoutside3** [comment]
There are some additional spots in FEM that incorrectly form urls for the thumbnail service - such as viewing my [test project](https://frontend.preview.zooniverse.org/projects/goplayoutside3/fem-flipbook-viewer/classify/workflow/22532) linked above, then clicking on the Field Guide button.

The field guide icon is trying to be fetched with 
```
https://thumbnails.zooniverse.org/100pxx100px/panoptes-uploads.zooniverse.org/field_guide_attached_image/96fb6b7a-9371-462a-a4f0-edb232e80108.jpeg
```

For some reason 'px' is inserted into the image url.

**Comment by eatyourgreens** [comment]
Sounds like CSS dimensions are being passed straight through to the thumbnail URL. There could be a small transformer function which takes a CSS dimension and returns a number. 

It might still be convenient to have a URL syntax that tells the resizer to resize only on width, but let’s try replacing ‘none’ with ‘999’ first. That’s what PFE currently does.
