### ISSUE TITLE
Engaging Crowds: Next Available Subject crashes the classifier

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#2556]
## Package
app-project
lib-classifier

## Describe the bug
https://www.zooniverse.org/projects/bogden/scarlets-and-blues/classify/workflow/18504/subject-set/98889
Choose a retired subject, then either Next Available Subject or Choose A New Subject. The page crashes with:
```
Application error: a client-side exception has occurred (see the browser console for more information).
```

In the console, the classifier has crashed with:
```
annotation missing for T11
TypeError: r is undefined
```

**Comment by mcbouslog** [comment]
might be helpful to other devs - https://local.zooniverse.org:8080/?project=12268&workflow=18504&subject-set=98887&subject=69734730&env=production
