### ISSUE TITLE
Add test to ensure `SubjectViewer` is passing in the subject id as a separate prop

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#257]
**Package**

lib-classifier

**Feature or Issue Description**

Following on from #250, there should be a test to ensure that `subject.id` is being passed to the viewer component by `SubjectViewer` (read https://github.com/zooniverse/front-end-monorepo/pull/250#pullrequestreview-172734742 for why)

**To Dos**

- [ ] Add test for SubjectViewer to pass the correct props to the selected viewer component

**Comment by eatyourgreens** [comment]
Superseded by #720, I think.
