### ISSUE TITLE
Warning banners for Already Seen subjects use inconsistent colours across projects or workflows

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#2577]
## Package
lib-classifier

## Describe the bug
The colour of the warning banner for an Already Seen subject depends on the type of workflow.

Workflows that don't use grouped, prioritised selection show a green banner, eg. Beyond Borders here:
<img width="1276" alt="A page from Beyond Borders, showing a green Already Seen warning." src="https://user-images.githubusercontent.com/59547/145565623-ad90273c-900e-42b6-bf84-a77f12accfb4.png">

Workflows that do use grouped, prioritised selection show a red banner eg. HMS NHS here:
<img width="1280" alt="A page from HMS NHS, showing a red Already Seen banner." src="https://user-images.githubusercontent.com/59547/145565952-9f1a064a-9452-4511-bb93-7d692eb14033.png">

## To Reproduce
Load up either Beyond Borders or HMS NHS with a subject that you've already classified.

## Expected behavior
Warning messaging should be consistent across projects. I'd expect the banner colours to be the same.

**Comment by lcjohnso** [comment]
@eatyourgreens Is this resolved?

**Comment by eatyourgreens** [comment]
Still open, I think.

**Comment by eatyourgreens** [comment]
You can check it in the storybook https://zooniverse.github.io/front-end-monorepo/

**Comment by eatyourgreens** [comment]
This Already Seen banner is green
https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/banners-alreadyseenbanner--default&globals=locale:en;locales.en:English;locales.test:Test+Language

but this Already Seen banner is red
https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/banners-subject-set-progress-banner--with-already-seen-subject&globals=locale:en;locales.en:English;locales.test:Test+Language

**Comment by lcjohnso** [comment]
@seanmiller26 Do you have a recommendation on this difference?  Change both to white text on red background?

**Comment by seanmiller26** [comment]
Yes, we should change it to red. It is inconsistent with other banners on Storybook

**Comment by eatyourgreens** [comment]
I'll open a PR.
