### ISSUE TITLE
Browser back button leads to already seen subject

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/front-end-monorepo#2610]
For projects with ordered subjects (like HMS NHS) when you finish classifying a subject and click 'Done & talk', if you navigate back to the classification interface using the browser back button you are given the same subject you previously submitted a classification for.

This is not the case for FEM projects with random subject delivery, such as PH TESS.

Desired functionality would be to load the next subject in the ordered queue.

**Comment by eatyourgreens** [comment]
@mrniaboc is this happening in Chrome or Firefox, or both? I've been seeing different behaviour in those two browsers when the classifier loads. Firefox seems to preserve previous page state when you go back, but Chrome loads the classifier from scratch, including making all network requests to Panoptes again (workflow, subjects, tutorial, field guide etc.) So Chrome does show me a new subject queue, but Firefox seems to give me a cached subject.

**Comment by eatyourgreens** [comment]
#2627 is a first step towards remembering the active subject across page visits, so that we can show you the correct subject when you return from Talk.

**Comment by eatyourgreens** [comment]
As far as I can tell, the underlying cause here is that the classifier always loads in the subject queue, from Panoptes, when you return from Talk. For a project like PH-TESS, that will always show you a random subject, so no problem.

For a project like Davy Notebooks or HMS NHS, a request to `/subjects/queued` will always send back the first unclassified subject for the workflow (and optional set.) It seems like the classifier is requesting the queue before Panoptes has updated it to mark the last subject as seen.

Something to check: does this bug also exist on projects that request subjects from `/subjects/selection`, like Scarlets & Blues?

**Comment by mcbouslog** [comment]
cc @snblickhan 

This issue might still be active. I was unable to reproduce in demo mode or after 1 actual classification, I'll try another actual classification or two and will report back.

**Comment by eatyourgreens** [comment]
Did we ever determine if this is browser dependent? I’ve not been able to reproduce it in Firefox. 

One thought that occurs to me now: I think I’ve only ever tested it with the browser cache disabled, which might make a difference.

**Comment by eatyourgreens** [comment]
Links to the Talk discussions of this bug might be useful too, so that we can find them again.

**Comment by eatyourgreens** [comment]
I can still reproduce this on HMS NHS or Davy Notebooks, if the classifier mounts before `cachePanoptesData` has been set (so the classifier mounts with session storage turned off.)

To reproduce, either choose a workflow from the HMS NHS home page, or load the Davy Notebooks Classify page directly. The message 'store hydrated from local storage' will not be printed to the console when the classifier loads.
https://www.zooniverse.org/projects/msalmon/hms-nhs-the-nautical-health-service
https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project?demo=true

**Comment by mcbouslog** [comment]
Noting https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/src/screens/ClassifyPage/ClassifyPage.js#L52 should be `true` when loading a HMS NHS or Davy Notebooks classifier.

For Chrome, you can see your session storage (should be empty to recreate bug, should note store as shown if working as expected):
![Screen Shot 2022-02-04 at 4 48 36 PM](https://user-images.githubusercontent.com/12118751/152615501-4d03ce85-5ad7-4ec5-b32a-f91b589d9f8e.png)
