### ISSUE TITLE
Get snapshot testing working again

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#266]
**Package**

All React packages

**Feature or Issue Description**

cc #118, #220 

We removed `mocha-snapshots` as it was breaking the tests - it'd be nice to add this back in.

**Comment by rogerhutchings** [comment]
Jest also has snapshot testing built in - https://jestjs.io/docs/en/snapshot-testing

**Comment by srallen** [comment]
Yep, but that would mean switching over to Jest as the test runner, etc, too.
