### ISSUE TITLE
Add callback support for login / logout

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#267]
**Package**

lib-auth

**Feature or Issue Description**

The consuming app should be able to pass in a callback for cleaning up state etc. when the user logs out.

**Comment by eatyourgreens** [comment]
If cleanup involves auth'ed API calls, eg. saving incomplete classifications to Panoptes, those should be invoked before logout invalidates the auth token. I learnt that the hard way on ASM.

**Comment by srallen** [comment]
It's up to the consuming app what clean up is. However, `onLogout` is a bit of a misnomer. I think I'll rename it to `afterLogout` and add one for `beforeLogout` and similarly rename for the login callbacks. I've also wrapped them in promises, so a promise might be more appropriate than a callback in some cases, so it's really up to what's using this to decide what's best.
