### ISSUE TITLE
Cached Stores: when switching Workflows from the Project home page, the wrong Subject can appear on the wrong Workflow

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#2690]
## ~~Major~~ Situational Bug

Package: `app-project`
Initial discovery: #2677
UPDATE: only affects projects that use cached stores (i.e. mst-persist)

If I switch between two workflows _on the Project home page_, I can cause the Subject Set of Workflow A to appear while classifying Workflow B
- The trigger is very very weird. You need to start at the _Project home page,_ open WF A, go back to the home page, open WF B, back to the home page, then open WF A. 
- The issue doesn't trigger if you switch workflows from the `/classify` page 🤷 
- ⚠️ Again, I'm not sure if this is related to `swr` or `mst-persist`! Additional tests tomorrow.

Steps to replicate:
- In a new incognito window, open the test project home page: https://local.zooniverse.org:3000/projects/darkeshard/test-project-2022
- click the Transformers WF
- click the project title to return to the home page
- click the Ultraman WF
- click the project title to return to the home page
- click the Transformers WF
  - Expected: a Transformers subject should be displayed alongside the Transformers task
  - Actual: an Ultraman subject is displayed alongside the Transformers task

![image](https://user-images.githubusercontent.com/13952701/150868836-f70cdc29-dae6-4b6c-9f3a-1a63cb32e411.png)

_Above: that's an Ultraman, not a Transformer! After switching back and forth between the Transformers WF and the Ultraman WF, I'm able to confuse the Classifier to serve me Ultraman subjects with Transformers tasks._

### Status

~~I'm marking this as a major bug. Investigation ongoing.~~

UPDATE: This is now a situational bug, not a major bug.

**Comment by eatyourgreens** [comment]
Copying over my comment from #2677, to explain why the home page triggers this bug. 

https://github.com/zooniverse/front-end-monorepo/pull/2677#issuecomment-1021122341

**Comment by shaunanoordin** [comment]
## Investigation Update

PR #2676 solves this issue by preventing the "cached stores" by default. (i.e. for most projects, we won't use mst-persist to store the Classifier store into sessionStorage) 👍 

I've repeated the tests on `master` commit b7636d7 and can no longer trigger the bug 👌 

### Status

Downgrading the severity of this bug.

This bug now ONLY affects projects that use cached stores (mst-persist), which is now (as of b7636d7) disabled by default. Jim, since you're still working with mst-persist, would it be helpful to keep this issue open to keep track of things, or would it be less noise to close it? (Since the bug doesn't affect live projects? At least, once deployed.)

**Comment by eatyourgreens** [comment]
I think leave it open, because remembering the subject queue status across a session is needed for #2610, which is affecting HMS NHS and Davy Notebooks.

**Comment by eatyourgreens** [comment]
#2657 fixes #2610 for prioritised workflows, but I think it might trigger this bug too.

**Comment by eatyourgreens** [comment]
Something that's missing from the classifier model is a means of validating the stored subjects against a workflow or subject set. `store.subjects` isn't linked to a workflow ID or subject set ID, so it's possible to store subjects which don't match the active workflow and subject set.

**Comment by eatyourgreens** [comment]
I think I know what’s happening here. 
1. Add workflow A to the store. This triggers a reaction that starts an API request for subjects. 
1. Before that promise resolves in the subjects store, add workflow B to the subjects store. The empty subjects store resets and starts an API request. 
1. The promise from step 1. resolves, populating the queue with subjects for workflow A.

**Comment by eatyourgreens** [comment]
It should be possible to write a test that mocks that scenario.

**Comment by eatyourgreens** [comment]
#2657 fixes this by removing the workflow observer from the subjects store, but that’s a bit of a heavy-handed solution.
