### ISSUE TITLE
Classifier: Classifications in progress "disappear" when revisiting tab (related to `swr` and workflow completeness)

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#2749]
## Major Functionality Bug

Package: `lib-classifier`

When a user starts classifying on the FEM Classifier, then goes to another tab/window, and then returns to the Classifier, _sometimes_ all their work is **reset.** The Subject remains the same. The time required for a classification to be lost is _inconsistent,_ but is triggered across all major browsers (Chrome, FF, Safari)

Analysis:
- The recent introduction of `swr` (#2677) changed the Classifier behaviour when a user re-visits the FEM Classifier (i.e. when the tab/window is viewed again after losing visibility/focus)
- The new behaviour states: "every time the tab/window gains visibility, fetch the **Workflow data**, and IF **the workflow data is new/changed/modified,** update the stores accordingly."
- This makes sense when a project owner changes the workflow tasks, etc.
- Unfortunately, what we didn't realise is that the "IF" condition also triggers when the **workflow's completeness** changes, and this changes OFTEN.

Notes:
- When the workflow store is updated, it triggers the "Loading Subject 1234..." action, which reloads (the same) Subject and resets the Classifications store. (Hence, lost classifications, but the Subject stays the same)
- The Subject Queue isn't affected, as far as I can tell.

Possible solution:
- Change the "IF" condition to only trigger when there's a different workflow ID or workflow version.

### Status

High severity bug. Solution currently being worked on by @eatyourgreens . Tagging @mcbouslog as an FYI

**Comment by eatyourgreens** [comment]
This is the cause:
https://github.com/zooniverse/front-end-monorepo/pull/2677/files#r790942113
