### ISSUE TITLE
Corresponding with Quakers: Can't move on to next task

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#2810]
## Describe the bug
Bug report from Talk (https://www.zooniverse.org/projects/rachaelsking/corresponding-with-quakers/talk/4893/2336091): "Sometimes when I am done transcribing I try to exit the page by checking the "are all the lines gray" prompt and it will get stuck, I can click either 'no' or 'yes' and neither will work and bring me to the "next" prompt and I will be left unable to leave the page without knowing if my work is saved."

From volunteer:
> I notice this last time that it seems like one of the lines I have annotated is not closing properly, like I'll go through look the pages and one dialog will still be open ie. is still green, almost like there's an error in being able to close out a line that keeps me from properly exiting because it isn't finished.

Sounds like they can still interact with the Y/N buttons:
> When it happens again, it has been when I've annotated many pages of a single document, when I go to the "grey lines" prompt it doesn't matter if I press 'yes' or 'no' the 'next' button will not turn green.

Possibility of being more likely to happen when they're the first annotator?
> I have been able to finish several documents. I suspect has something to do with the length of time I'm on a document. I do snatches of annotation throughout a day. If I'm luck I'll get to do a full one in one sitting, but sometimes I'll come back and forth too it over several hours (I really like being able to get a full letter...it's very satisfying) I can't recall exactly, but I think it's more likely to happen if I'm the first one on a document. ie. I'm spending a lot of time trying to decipher the words, and less time just checking and confirming.

## To Reproduce
Haven't yet been able to reproduce, but sounds like it might be similar to what we were trying to fix with #2179 (invalid marks causing the Next button to be disabled)

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:
Project 14978

## Expected behavior
My understanding is that the #2179 fix would delete extraneous marks, so perhaps something else is blocking the way to the next task?

## Device information
Firefox on Macbook

**Comment by snblickhan** [comment]
Update: I'm like 90% sure this is the same issue as before, and have recreated it with a video:

https://imgur.com/a/b0tosJL

Basically, it's still possible to create a single dot on the image without placing the rest of the annotation, which then disables the 'Next' button. It's unfortunately really easy to do, so it would be helpful if we could explore some options for mitigating this possibility.

I told the volunteers it might not be a quick fix, but that will rely on the team being responsive in their communication.

**Comment by eatyourgreens** [comment]
Can this happen if you change frame, using the thumbnails on the left, while you're in the middle of placing a line?

To me, it looks like I could click or tap to place a green dot, select a thumbnail to change the active frame and I'd now have an invalid task annotation, which would disable the Next button. 

We're storing the active mark and active frame in global variables, but it might be better to store those in local component state. Global variables make it easier to introduce bugs.

**Comment by mcbouslog** [comment]
Noting #2930 will hopefully fix most cases of the issue noted, by deleting an incomplete line if the frame is changed, but an incomplete line on the current frame will still prevent a user from clicking Next or Done. An incomplete line will continue to show as a green dot with an X, so hopefully will be noticed, and can be deleted or completed by the user so they can proceed. 

I don't think transcription projects (usually with one frame per subject) before Corresponding with Quakers had an issue with incomplete lines preventing advancement - users must have noticed and completed/deleted - so hopefully the same will be applicable for users working on Corresponding with Quakers when the incomplete line is on the selected frame.
