### ISSUE TITLE
Verified icon gets squashed in narrow window

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/front-end-monorepo#2816]
## Package
??

## Describe the bug
If the browser window is narrow, but not small enough to actually change the layout, the tick icon gets squashed so it's no longer a circle.

## To Reproduce
1. Go to e.g. [Black Hole Hunters](https://www.zooniverse.org/projects/hughdickinson/superwasp-black-hole-hunters)
2. Click on resize the browser window

## Expected behavior
The icon should have the same shape regardless of the width of the window.

## Screenshots
![Screenshot 2022-02-10 135623](https://user-images.githubusercontent.com/428423/153422443-e9073f01-b956-4452-9c6b-a2f750de8bb5.png)

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome
 - Version: 98.0.4758.82

**Comment by eatyourgreens** [comment]
The navigation links also get squashed, in that the clickable region is shorter than the displayed word.
https://github.com/zooniverse/front-end-monorepo/issues/2219

**Comment by MaysaB** [comment]
Fixed by #3447
