### ISSUE TITLE
Improvement for Thumbname view

### ISSUE THREAD

**Issue by mbiesiad** [zooniverse/front-end-monorepo#2855]
## Describe the bug
Thumbname sticks out of the window (modal-form modal-dialog).

## To Reproduce
1. Go to [Active Asteroids](https://www.zooniverse.org/projects/orionnau/active-asteroids/classify) - classify
2. Click on 'Metadata'
3. Change browser window to the smallest size
4. See the issue

## Expected behavior
Thumbname is inside the mentioned window.

## Screenshots
Correct view:
![image](https://user-images.githubusercontent.com/18367606/154535267-bf3fa26f-cb09-4c86-8ac4-9b0df46a5962.png)

Incorrect view:
![image](https://user-images.githubusercontent.com/18367606/154535368-5e857d48-6f34-4c22-8f78-8cef9ac06ab5.png)

Best wishes,
Michal

**Comment by goplayoutside3** [comment]
I'm not able to replicate at: https://frontend.preview.zooniverse.org/projects/orionnau/active-asteroids/classify. The above screenshots are of the project on [PFE](https://github.com/zooniverse/Panoptes-Front-End).
