### ISSUE TITLE
Fix WorkflowStore tests

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#286]
**Package**

lib-classifier

**Feature or Issue Description**

The tests for the WorkflowStore are currently broken, and need to be refactored. However, I needed to diagnose a separate issue with the deploy process, so I disabled them in 71dced70968c6d2f16e992d28801a991f866ec8b

**Comment by rogerhutchings** [comment]
related: #283, #285

**Comment by srallen** [comment]
We really should get standard tests done for production launch.
