### ISSUE TITLE
Light curve viewer feedback doesn't show expected colors

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#2877]
## Package
- lib-classifier

## Describe the bug
The light curve viewer feedback doesn't show the expected colors (green for success, red for failure) unless the graph is interacted with (dragged or zoomed within).

## To Reproduce
1. Go to https://frontend.preview.zooniverse.org/projects/nora-dot-test/planet-finders-beta/classify/workflow/3317?env=staging&demo=true
2. Make a few random annotations, click on Done
3. Get feedback (if don't get feedback, go to another subject)
4. See feedback modal with graph showing annotations and actual, but note no green or red transits
5. Drag within graph or zoom within, expected colors will appear

## Expected behavior
Expected transits shown as green or red.

**Comment by eatyourgreens** [comment]
Marking this as high priority, because we've taken PH TESS down until it's fixed.

**Comment by eatyourgreens** [comment]
This is fixed if the fills are added to brushes when they are drawn. I'm not sure if that's the most efficient solution, but it seems to work.
https://github.com/zooniverse/front-end-monorepo/blob/35315633b215e6702e924f40a9a9c4236c9f3ca4/packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js#L79-L96
