### ISSUE TITLE
Workflow selection modal showing on PH TESS

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/front-end-monorepo#2910]
The workflow selection modal that was built as part of the Engaging Crowds Indexing Tool effort is now showing on Planet Hunters TESS. It was originally designed to only show on projects with more than one live workflow, and should not be showing on PH TESS as it adds an unnecessary extra step for the volunteers to get through when they navigate to the classify tab.

See https://zooniverse.slack.com/archives/CANKLB50E/p1645782976011779

![image](https://user-images.githubusercontent.com/5321335/156203196-8deeecd8-c477-41c1-a35e-5deefcc8231d.png)

**Comment by eatyourgreens** [comment]
We used to set a default `workflowID` in the Classify page props, but I think I removed that, somewhere along the line. Probably a mistake, to be honest.
https://github.com/zooniverse/front-end-monorepo/blob/745e946789c424052e0d572b90a5047b64361d00/packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js#L26-L30

**Comment by eatyourgreens** [comment]
I removed the default workflow in #2580. I think that was an accident.

**Comment by mcbouslog** [comment]
> I removed the default workflow in #2580. I think that was an accident.
> 
> EDIT: Declaring a default, with URL params taking precedence, might fix this issue:
> 
> ```js
> const workflowID = params.workflowID || store.project.defaultWorkflow
> ```

I think removing reference to a default workflow was ok, is in line with [ADR 34](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-34.md#consequences). 

Shortly I'll open a PR that sets the workflow ID to the only workflow if there's only one active workflow. I think that solves the issue and is consistent with our intent to remove default workflow? Completely open to suggestion though, I don't have a staunch opinion.

**Comment by eatyourgreens** [comment]
`project.defaultWorkflow` returns a project’s single active workflow. 
https://github.com/zooniverse/front-end-monorepo/blob/745e946789c424052e0d572b90a5047b64361d00/packages/app-project/stores/Project.js#L47

**Comment by eatyourgreens** [comment]
Sorry, that was the wrong link but this should save you some work.
https://github.com/zooniverse/front-end-monorepo/blob/745e946789c424052e0d572b90a5047b64361d00/packages/app-project/stores/Project.js#L41-L48

**Comment by eatyourgreens** [comment]
See also the comments here.
https://github.com/zooniverse/front-end-monorepo/pull/1976#issuecomment-761023499

The tutorial appears when `workflows.active` changes in the classifier.
