### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#292]
**Package**

lib-classifier

**Feature or Issue Description**

We need to ensure we have documented keyboard shortcuts, aiming ideally for parity with current PFE.

Links:

- [Talk thread](https://www.zooniverse.org/talk/17/610656?comment=1313158&page=1 ) discussing a marking area <-> task area 
- Grommet [`Keyboard` component](https://v2.grommet.io/keyboard) - only a limited set of keys available though :(

**Comment by goplayoutside3** [comment]
Closing for now. Can open new Issues specific to certain keys and expected behavior if needed.
