### ISSUE TITLE
Transcription Task: previous transcription dropdown staying open when it shouldn't

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#2948]
## Describe the bug
The 'previous transcriptions' dropdown menu is staying open when it shouldn't.

## To Reproduce
1. Go to a project using the Transcription Task (e.g. https://www.zooniverse.org/projects/rachaelsking/corresponding-with-quakers or https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project and find a page with previous transcriptions. 
2. Click on a pink annotation. The 'previous transcriptions' dropdown list will open automatically.
3. Click on a previous transcription to populate it into the text area.
4. Start to edit the text. The dropdown menu _should_ close when you start to edit the text, but it stays open (this is the bug). If you click outside the text area or press Esc the dropdown will close, but it will immediately open back up when you start to type again.
5. The dropdown is often covering up the button to submit your work, which is causing confusion among volunteers.

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:
project 9006
https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project 

project 14978
https://www.zooniverse.org/projects/rachaelsking/corresponding-with-quakers 

## Expected behavior
The dropdown box should close after a previous transcription has been selected.

### Desktop (please complete the following information):
 - OS: MacOS Big Sur
 - Browser: Chrome
 - Version: 99

**Comment by eatyourgreens** [comment]
#2787 bumped Grommet from 2.17.4 to 2.20.1, but that was merged a month ago. It seems odd that changes wouldn’t be noticed until now.

**Comment by eatyourgreens** [comment]
I’ve merged #2898, which bumps Grommet to 2.21 on staging.

**Comment by eatyourgreens** [comment]
Grommet 2.20 fixed a bug where the suggestions menu closes when you type in the box. https://github.com/grommet/grommet/pull/5860

**Comment by eatyourgreens** [comment]
From the original report on Talk, there's a more serious aspect to this bug. The annotation that it saves is not the text that you type in. 

> If they are above my entry line, then clicking "Save & Close" saves not my line but a previous one.

https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/talk/2644/2376902?comment=3903448

**Comment by eatyourgreens** [comment]
I think the broken code is here. `suggestions` is a constant value that should change as you type in the box. Or perhaps clear when you start to edit?

https://github.com/zooniverse/front-end-monorepo/blob/05db539dabfc7ad41de8736aeb506c33031dc6cc/packages/lib-classifier/src/plugins/tasks/text/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.js#L60-L70

**Comment by eatyourgreens** [comment]
Also worth noting that `onSelect` is deprecated for text inputs. 

https://v2.grommet.io/textinput

**Comment by eatyourgreens** [comment]
Following up on text annotation values being wrong, the storybook for a text input with suggestions here:

https://storybook.grommet.io/?path=/story/input-textinput-default-suggestion--default-suggestion

It appears that the value must be the selected suggestion. If I type "Hello world", then Enter, the text changes to "suggestion 2". 

That means that previous text annotations cannot be edited now, on live transcription projects.

**Comment by goplayoutside3** [comment]
> It appears that the value must be the selected suggestion. If I type "Hello world", then Enter, the text changes to "suggestion 2".

@eatyourgreens I was unable to replicate this behavior on production. I visited [Corresponding with Quakers](https://www.zooniverse.org/projects/rachaelsking/corresponding-with-quakers/classify/workflow/20543?env=production&demo=true) in demo mode, clicked a pink transcription line, edited the text to say "hello", submitted the classification and inspected it in the console log. The `value` of my submitted transcription was "hello". That happened when I hit enter to close the suggested text dropdown and it also happened when I closed the suggested text dropdown by clicking outside of it.

**Comment by eatyourgreens** [comment]
Oh cool. I was worried because the report on Talk says that edited text isn't being saved, and I think a lot of volunteers would miss that, if it happened. It's reassuring to know that you're able to save edited lines.

**Comment by eatyourgreens** [comment]
> Start to edit the text. The dropdown menu should close when you start to edit the text, but it stays open (this is the bug).

Grommet text inputs should show suggestions when you type in the text box, but didn’t due to the following issue, now fixed:
https://github.com/grommet/grommet/issues/5426

Our code needs to be updated to turn off suggestions after you’ve selected an option, but in such a way that you can still correct a wrong choice and choose a different option.

**Comment by eatyourgreens** [comment]
This might be fixed by checking whether the text value is empty before showing suggestions. 

```js
const displayedSuggestions = !value ? suggestions : undefined 
```

It depends whether we still want the menu to be available after you’ve entered text into the box. For example, after making a mistake, how do you open the suggestions menu in order to choose the correct option?
