### ISSUE TITLE
`ZooniverseLogotype` breaks with SSR

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#296]
**Package**

lib-react-components

**Feature or Issue Description**

The `ZooniverseLogotype` component generates IDs dynamically, which causes a mismatch between the server and client

**Comment by srallen** [comment]
The ID is for accessibility; I believe it is generated to make sure they're unique to that SVG element.

**Comment by rogerhutchings** [comment]
This issue talks about it more: https://github.com/facebook/react/issues/5867

**Comment by eatyourgreens** [comment]
I think you can label the SVG element directly with its alt text, rather than giving it an ID and linking it up to an external label.

**Comment by rogerhutchings** [comment]
Then instead of generating an ID, we should create one by hand based on its location on the page and pass it in as a prop. It's not like these are repeated so often it'd be onerous.

**Comment by eatyourgreens** [comment]
:+1: Good idea.
