### ISSUE TITLE
Classifier is tightly coupled to auth

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#297]
**Package**

lib-classifier, lib-auth

**Feature or Issue Description**

The classifier requires an auth client as a prop to work at all (currently errors out on trying to find the `getToken` method). It'd probably be better if it worked without one and submitted anonymous classifications, if for dev purposes if nothing else.

**Comment by srallen** [comment]
I coupled it on purpose as we should know whether there's a user or not before classification submission. Open to refactoring here. Perhaps make the prop not required but have prominent console messages warning that all classifications are being submitted anonymously? I want to prevent any setup errors for consumers of the library forgetting to wire up auth.

**Comment by rogerhutchings** [comment]
I'd prefer adding prominent warnings - aside from dev, I can imagine a kiosk-type use case where we wouldn't need auth.

**Comment by srallen** [comment]
As discussed with @rogerhutchings on call yesterday, the classifier will be changed to not require auth, but have warnings whenever API requests happen that auth is not setup with the classifier.
