### ISSUE TITLE
User can access workflow above assigned level

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#2991]
## Package
- app-project

## Describe the bug
On a project with workflow assignment a user can access a workflow above their assigned level.

## To Reproduce
1. Signed out, Go to https://frontend.preview.zooniverse.org/projects/srallen086/workflow-assignment-testing/classify/workflow/2619?demo=true&env=staging

## Expected behavior
A signed out user should be prompted with the workflow assignment modal, with only the Beginner workflow accessible.

**Comment by mcbouslog** [comment]
I think defining [the workflowID here](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js#L60) per the workflowFromUrl (which has been filtered based on if a user can access per workflow assignment) will fix the issue, I'll open a PR accordingly asap.

**Comment by eatyourgreens** [comment]
This line assumes you have access to all project workflows, by default. 
https://github.com/zooniverse/front-end-monorepo/blob/3e363a4a899f0e1fe0942274d4e6232e906df91d/packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js#L19

**Comment by eatyourgreens** [comment]
@mcbouslog be careful not to regress the bug fixed by https://github.com/zooniverse/front-end-monorepo/pull/2465.
