### ISSUE TITLE
Create ADR for server-side auth

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#302]
**Package**

lib-auth

**Feature or Issue Description**

We've created a sweet auth library that only works in the browser. Given that we're moving towards SSR, we should create a strategy for handling auth on the server as well.

While researching the issue, I came across [next-auth](https://github.com/iaincollins/next-auth/), which I managed to get working out of the box with OAuth2 with minimal pain. This also has the benefit of hiding the `accessToken` from the client.

However, to actually get authenticated requests up and running, there's additional wiring needed:

- It uses [Passport.js](http://www.passportjs.org/) under the hood, which is an express middleware. To make authenticated requests, we'd need to proxy the API to a route on the app, pass that route to Panoptes.js, and make requests through that.
- Passport encourages the use of a session database
- We should probably create custom strategies for Passport.js to simplify config.

This will probably require us to abstract things out slightly differently to the way we have it now:

- The user stores get moved into their own package, so they can be used server and client side.
- The interface components get moved into their own package.
- We write a small wrapper for stores and interface so they can be used easily in a client-side only app

This is probably more work than we can fit in the time available before we down tools on TESS, so we should create an ADR to document this next section of work.

**Comment by srallen** [comment]
Instead of a separate lib for the views, they could be added to the existing react-components lib.

**Comment by rogerhutchings** [comment]
We'll also need to get the User Project Preferences on the server as well, since it's used in workflow selection, which is done in the project app rather than the classifier: #1132
