### ISSUE TITLE
Add subject dimensions to classification metadata

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#304]
**Package** lib-classifier

**Feature or Issue Description**
This was left out during development because of #201. The subject's natural width and height as well as client width and height should be saved. The metadata should be updated on load of the image: https://github.com/zooniverse/Panoptes-Front-End/blob/6e1ed81cd338ec9e3d782318807a69607219d627/app/classifier/classifier.jsx#L200-L201

@shaunanoordin For non-image subject types like data, should we record the dimensions of the plot displayed?

**Comment by shaunanoordin** [comment]
If by "non-image subject types", we mean the TESS light curve data, then I'm inclined to say the information is unnecessary.

My rationale is that knowing the client width/height of a subject only matters if we're trying to understand users' classification behaviour, and if that were the case, what we'd need to focus on is tracking how the user uses the Light Curve Viewer's _zoom_ tools. That said, I can easily be swayed on this position - adding the dimensions of the plot on Classification submit should be fairly trivial, and only cost us a few extra bytes per Classification in the long run.

I'd best pass this question to @noraeisner, in case there is some potential research question about how the _size of the data, as displayed in the browser window,_ affects user accuracy/etc.

**Comment by srallen** [comment]
@shaunanoordin Did we have a definitive answer about this for TESS?

**Comment by shaunanoordin** [comment]
I recall that the answer was _"no, we don't need browser metadata",_ but I'm pinging @noraeisner to confirm. I should have documented this, sorry.

**Comment by noraeisner** [comment]
I'm inclined to say that if it's easy to store this information then we should (just in case we do ever want to use it) but if it's not easy to store then it's definitely not essential.

**Comment by shaunanoordin** [comment]
👍

**Comment by eatyourgreens** [comment]
Thinking about it, natural height/width aren't relevant for SVG, since it can be scaled to any size. Client height and width should be available from the SVG DOM node or its containing HTML element.

**Comment by eatyourgreens** [comment]
That said, we record viewport dimensions so we've already got a measure of what size screen the classification was made on, which might be the important number for data analysis.
