### ISSUE TITLE
Refactor subject text location request with hook

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#3042]
Would it be worth moving this into a hook in the text viewer? Similar to the hook that fetches images for the image viewer, or the hook that fetches JSON for the data viewers.

_Originally posted by @eatyourgreens in https://github.com/zooniverse/front-end-monorepo/pull/3034#discussion_r858495973_

**Comment by mcbouslog** [comment]
Per Slack: 
- "...copy of this hook for the DigiLeap subject viewer, replacing await response.json() with await response.text()."
- https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/helpers/useJSONData/useJSONData.js

**Comment by eatyourgreens** [comment]
Here’s an example that uses that hook. 
https://github.com/zooniverse/front-end-monorepo/blob/153c0568f0a83d79f63399916e4923c7c9a3913f/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js#L81-L85
