### ISSUE TITLE
Task validations

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#305]
**Package** lib-classifier

**Feature or Issue Description**
Current PFE has validations to check for completeness for each task type, i.e. https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/single/index.jsx#L77-L79

Its purpose according to PFE's readme:

> Given a task and an annotation, this determines whether or not the classifier will allow the user to move on to the next task.

It's checked in the task nav: https://github.com/zooniverse/Panoptes-Front-End/blob/21cf42485929a62938112d5e2d4bca1a6702b00e/app/classifier/task-nav.jsx#L75-L79

These were static methods on the components. Instead, we could add these to the annotation type model using an onAction MST listener?

**To Dos**

- [ ] Example

**Comment by srallen** [comment]
The LCV task should have a validation.

**Comment by srallen** [comment]
The models themselves are a kind of validation, so we need to think about if we need additional validations and what they should be.

**Comment by eatyourgreens** [comment]
Should be closed by #1307.
