### ISSUE TITLE
Hide Tools in ImageToolbar for Certain SubjectViewers

### ISSUE THREAD

**Issue by ErikOstlund** [zooniverse/front-end-monorepo#3093]
## Package
`lib-classifier`

## Is your feature request related to a problem? Please describe.

For some SubjectViewers, e.g. the SingleVideoViewer, the tools in the ImageToolbar are not needed. This was discussed and confirmed with @mcbouslog 

- MoveButton
- ZoomInButton
- ZoomOutButton
- RotateButton
- FullscreenButton
- ResetButton

![Screen Shot 2022-05-06 at 11 19 09 AM](https://user-images.githubusercontent.com/9533007/167172657-23c21387-e685-407c-ab4b-d46f98102a13.png)

## Describe the solution you'd like

When certain SubjectViewers are loaded, the above listed tools should not be visible (should not render).

The FieldGuide should always be visible.

## Describe alternatives you've considered

We discussed having all tools listed above being visible but disabled. This may confuse volunteers and is not an ideal solution.

**Comment by eatyourgreens** [comment]
PH TESS hides the Rotate button, so we could revisit how that was done. I think it’s a flag that’s set in the store.

**Comment by eatyourgreens** [comment]
The solution might be as simple as making the default handlers null, then only rendering a button if it has a handler defined by the current subject viewer.
