### ISSUE TITLE
Connect MST to redux dev tools

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#31]
This should be possible, but I struggled to get it working. There's some code demonstrating this in the [mobx todo-mvc example](https://github.com/mobxjs/mobx-state-tree/blob/4c2b19ec4a6a8d74064e4b8a87c0f8b46e97e621/examples/redux-todomvc/src/index.js#L6)

**Comment by srallen** [comment]
I'm having difficultly getting it to work too. Also trying this out: https://github.com/mobxjs/mobx-devtools

I'm wondering if it's just not picking up the init store with next.js?
