### ISSUE TITLE
Workflow UPP observer: More robust conditions on when to request new workflow

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#316]
**Package** lib-classifier

**Feature or Issue Description**
Right now, the workflow store will request a new workflow if the UPP changes. There are conditions where we might not want this to happen even if the UPP changes: If the user signs in in the middle of annotation, possibly others. For Gravity Spy though, we definitely want to update the workflow back to default on sign out regardless on if they're in the middle of classification. There might be other scenarios we can think of....

**To Dos**

- [ ] Example

**Comment by rogerhutchings** [comment]
Gravity Spy is an edge case. We could come up with a plugin-style system by creating a dictionary of alternative rules where the keys are project / workflow ID, and do something different if we get a match. There's a definite need to be able to do different things for different projects, but I don't want to end up with a mess of `if/else` statements again.

**Comment by srallen** [comment]
Yes GS is, though if it's by workflow or project, then it should just be defined in their respective configs. I was thinking more along the lines of feature detection, i.e projects with `workflow assignment`, (Gravity Spy, Snapshot WI) enabled should clear and load the default workflow on sign out. This _might_ be the only exception case, but I thought we should have the discussion to think it out first.

**Comment by srallen** [comment]
Closing in favor of #1132
