### ISSUE TITLE
GraphQL and Talk

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#323]
At some point we're going to rebuild Talk, and should we go ahead and build our own again, we could link the Talk and Subject schemas to get everything we need in one GraphQL request (I've been talking to @marten about this recently)

**Comment by srallen** [comment]
We'd build Talk again from scratch?

**Comment by srallen** [comment]
I was hoping we could fork something like https://github.com/coralproject/talk and modify as needed.

**Comment by rogerhutchings** [comment]
Sure; I just wanted to save the idea for whenwe do
