### ISSUE TITLE
FOUC when using react-components lib with Next

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#327]
**Package**

lib-react-components, app-project

**Description**

When using components from the `react-components` lib in a Next app, their styling isn't rendered on the server, causing a FOUC to occur before the client bundle is loaded.

This doesn't happen with components defined in the consuming app, even if those use Grommet / styled-components; just those from the library.

**Comment by srallen** [comment]
They were working and then broke again when I bumped minor versions on styled-components while doing work on the subject metadata modal. I was gonna look at this this week.

**Comment by srallen** [comment]
Bumping styled-components to 4.1.2 seemed to fix it on my branch for the subject metadata modal.

**Comment by rogerhutchings** [comment]
This seems to affect the classifier as well, and I _think_ it may be a class name collision caused by multiple styled components instances.

I have a nuclear option for fixing this as well, which is straight up copying the tooling from Grommet, since that _is_ picked up correctly on server side builds.

**Comment by rogerhutchings** [comment]
# Updates

- I created a minimal repo at https://github.com/rogerhutchings/fouc-example
- I've spoken to a couple of the Grommet devs, who ruled out anything blindingly obvious
- I got SSR working with Gatsby in my test repo, so it could be an issue with how Next is picking up styled components from our lib

**Comment by rogerhutchings** [comment]
Backup plans, from a catchup call just now:

- Symlink the contents of the component lib into `app-project`, and create a webpack alias for where to find them.
- Move the components from the components lib into `app-project`
- Don't SSR

**Comment by rogerhutchings** [comment]
I've determined that:

- The issue is not with Next, as trying out my Gatsby app in production revealed the same effect
- The issue isn't with Grommet, as I've also created a pure styled-components lib and am experiencing the same issue

**Comment by rogerhutchings** [comment]
cc styled-components/styled-components#2442
