### ISSUE TITLE
Losing Icons for Field Guide Items

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#3295]
## Package
lib-classifier

## Describe the bug
Image thumbnails for field guide items are not consistently appearing in the menu of the field guide modal.

## To Reproduce
Received May 10 via Talk (FEM project 15597): "I'm losing icons for topics in the Field Guide. They all appear when editing the guide, but when clicking on the Field Guide button during the transcription process, most are missing. When I go into the actual topic page, they are also missing." All the icons are appearing as they should on the Field Guide page in the lab. See screenshots below:

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:
https://www.zooniverse.org/projects/pmlogan/poets-and-lovers/classify

## Screenshots
FG boxes as they currently appear on FEM project pag
![image](https://user-images.githubusercontent.com/23665803/173106013-cb56e16a-5ea0-4a64-88d6-288cab9e44e1.png)

FG icons as they appear in PFE lab:
![image](https://user-images.githubusercontent.com/23665803/173106042-f9b9d4d3-5020-42a1-a523-8ecf9b06b63c.png)

**Comment by mcbouslog** [comment]
Might be related to #2554 .

**Comment by eatyourgreens** [comment]
The field guide icons do appear on Talk, so their URLs are ok.

<img width="1274" alt="Screenshot of Poets and Lovers Talk, with the field guide open to show the item menu and icons." src="https://user-images.githubusercontent.com/59547/173339305-d3d178f7-4b06-4e88-a670-3f15c3bdab4e.png">

**Comment by eatyourgreens** [comment]
Those `100px` sizes are set here:
https://github.com/zooniverse/front-end-monorepo/blob/46d06a89dc2b28aeab140d1db0336c10cc5a75e2/packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/FieldGuideItemAnchor.js#L19

**Comment by lcjohnso** [comment]
This issue remains open, and also affects Gravity Spy ([preview link](https://frontend.preview.zooniverse.org/projects/zooniverse/gravity-spy/classify/workflow/1610)). Some work has already been done on this (see related #2554 and #4132) but the problem persists.

attn: @eatyourgreens @goplayoutside3

**Comment by eatyourgreens** [comment]
TBH, you could safely change the page size to 100 in that code and that would fix the problem in a single HTTP request.

**Comment by mcbouslog** [comment]
> TBH, you could safely change the page size to 100 in that code and that would fix the problem in a single HTTP request.

I was thinking the same! 

We know the field guide item count at point of attached media request, is there a reason to do `100` vs `fieldGuide.items.length`? I think either would be fine, both will fix the issue.

**Comment by eatyourgreens** [comment]
100 is the largest page size allowed by Panoptes, but I imagine field guides are a lot smaller than that.

**Comment by eatyourgreens** [comment]
If someone has more than 100 items, we probably want to talk to them about editing their guide anyway.

**Comment by mcbouslog** [comment]
Makes sense, thanks!
