### ISSUE TITLE
Transcription modal drag is broken

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#3340]
## Describe the bug
Dragging the transcription modal no longer works - if you drag it it snaps back to its original position.

## To Reproduce
1. Go to any FEM transcription project, e.g. https://www.zooniverse.org/projects/pmlogan/poets-and-lovers 
2. Click on a workflow
3. Either draw a new line or click on an existing line
4. When the transcription modal pops up, click & drag to reposition.
5. See error: repositioning doesn't work, as the box will snap back to its original position.

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:

## Expected behavior
When the modal is dragged to a new position, it should stay there.

## Screenshots

https://user-images.githubusercontent.com/25958358/175122890-78e50c3e-7692-4ed2-a7a9-1e05fa8e08a4.mov

### Desktop (please complete the following information):
 - OS: Mac OS Big Sur
 - Browser: Chrome 
 - Version: 102

**Comment by eatyourgreens** [comment]
Resize snaps back to the original size too.


https://user-images.githubusercontent.com/59547/175248339-347757de-63b3-4bd1-8fe9-36d904ed0542.mov

**Comment by eatyourgreens** [comment]
I added fixed positioning (`position`) and sizing (`size`) to the popup in #3332, to fix the problem where the popup would open on top of the text that you're transcribing (#2233.) Removing that should fix this bug.
