### ISSUE TITLE
Classifier: layout isn't responsive on medium widths

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#3410]
## UI Issue

Package: `lib-classifier`
Follows: #3337 
Noted on commit 9fedf9157926adfc3f599598f2124595718486bf (not deployed to production yet) with macOS + Chrome 103 / FF 102

The Classifier is no longer responsive on "medium" viewport widths.

Expected: Task Area should always be visible in viewport, for medium widths. Subject image should shrink accordingly
<img width="400" alt="Screenshot 2022-07-07 at 18 43 40" src="https://user-images.githubusercontent.com/13952701/177837560-e7b515ab-426e-4be8-9839-69ccdb8cda9a.png">

Actual: Task Area is cut off at medium widths. Subject image does not shrink.
<img width="400" alt="Screenshot 2022-07-07 at 18 43 21" src="https://user-images.githubusercontent.com/13952701/177838684-103c6dfd-8a32-4c29-b152-ca597ffa6c8e.png">

**Steps to Reproduce**

- Boot up `lib-classifier`
- Go to https://local.zooniverse.org:8080/?env=staging
- Gradually shrink the width of your browser window's width and observe the various responsive states.
- Wide format (> 1280px I think?) works fine, narrow/mobile format (< 700px) works wine, but medium format (anything in between) has no responsive layout.

### Dev Notes

I've stepped into the TARDIS to figure out when this bug was introduced, and can confirm that this is a result of the changes to Classifier's DefaultLayout in #3337.

- I don't think the loss of responsiveness is intended, as 3337 was supposed to fix the Subject's visual size when the browser zoom is activated
- A quick fix is to roll back 3337, but that would reopen #3336

### Status

Major UI issue, I think, but we have some time to take care of it.

This UI issue was noticed while I was giving @seanmiller26 a demo on QuickTalk on my localhost. As of 7 Jul 18:58 BST, this isn't out in the wild yet, so isn't an urgent problem yet, but should be fixed before the next deploy.

**Comment by shaunanoordin** [comment]
Tagging @eatyourgreens and @mcbouslog , in case either of you can think of a quick solution for this. If not, I'll dive into this Monday. 👌 

(I just spent 15 minutes bumbling around with the grid layout CSS and have only succeeded in breaking _both_ page zoom and responsive layouts. 👀 )

**Comment by eatyourgreens** [comment]
The project Classify page seems ok, but I'd have to double check on an iPad. I'm looking at Davy Notebooks. 

https://frontend.preview.zooniverse.org/projects/humphrydavy/davy-notebooks-project/classify/workflow/21240

**Comment by eatyourgreens** [comment]
The dev classifier isn't used by volunteers so it isn't such a big deal if that's broken.

**Comment by mcbouslog** [comment]
I think I see what you're referring to, if I use the Chrome Device Toolbar (needs confirmation with BrowserStack or actual device) and set it to iPad Mini the viewer width exceeds the view width:
![Screen Shot 2022-07-07 at 3 08 50 PM](https://user-images.githubusercontent.com/12118751/177863626-950b481f-6450-4bfa-be00-daa3a098c2ab.png)

**Comment by eatyourgreens** [comment]
We can set the minimum size of the left hand track to a size that’s more appropriate to a small viewport. At the moment, it’s adjusted for ~1200px.

**Comment by eatyourgreens** [comment]
At the moment, the minimum track size is `45.333rem` so I’d start by experimenting with smaller values. Max size is `auto`, which should expand the track to fill available space. 

https://github.com/zooniverse/front-end-monorepo/blob/6dbeb0d04598848ee97f75d7a39274ee45409530/packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js#L15

**Comment by mcbouslog** [comment]
I think the following changes works well, but there are prob a bunch of different ways to approach this:
```
@media (min-width: 801px) {
    grid-template-columns: minmax(${subjectSize}, auto) minmax(1fr, ${taskSize});
  }

  @media screen and (max-width: 800px) {
 ```
 
If the subjectSize is `45.333rem`, which with 16px base font size equals ~725px, I think it makes sense to break on a width larger than 700px?

**Comment by eatyourgreens** [comment]
I don’t think `1fr` means anything on its own. What minimum size is it setting the task area too there? Is that code the same as `minmax(auto, ${taskSize})`?

**Comment by eatyourgreens** [comment]
> If the subjectSize is 45.333rem, which with 16px base font size equals ~725px, I think it makes sense to break on a width larger than 700px?

I could be wrong but I think the breakpoint should be the sum of the smallest subject and task width: `70.667rem`. We can adjust for smaller subjects, though.
