### ISSUE TITLE
Transcription Line and Polygon Drawing Tools: "taps" crash on mobile devices

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#3498]
## Platform-Specific Bug

Package: `lib-classifier`

**Problem:**
- if you try to create a Polygon mark (on the Classify page) by tapping on a touchscreen (to place a point), the action crashes the page.
- Error message in dev console: `[mobx-state-tree] Failed to resolve reference 'cl6di4hnr00033c6sv87ru1k6' to type '(Circle | Ellipse | FreehandLine | Line | Mark | Point | Polygon | Rectangle | RotateRectangle | TemporalPoint | TemporalRotateRectangle | TranscriptionLine)' (from node: /workflowSteps/steps/S0/tasks/0/activeMark)`
- Curiously, if you tap-and-HOLD to place a point, then move your finger/pointer away from the initial location (where a point was placed), then no crash happens. 

**Analysis**
- This is probably something to do with the life cycle of the active mark, in relation to how it reacts to touch events specifically.
- Lifting your finger _on_ a node (touchend event) triggers a delete, perhaps?

**Testing/Bug Reproduction Steps**
- Choose a workflow with a Drawing Task with the Polygon drawing tool, e.g. https://frontend.preview.zooniverse.org/projects/darkeshard/test-project-2022/classify/workflow/3596?env=staging
- Either (1) view the Classify page on a mobile device or (2) view it on Chrome desktop, enable emulation for Pixel 5 or similar
- Choose the Polygon drawing tool and then click/tap to place the initial point.
  - Expected: initial point should be placed
  - Actual: page crashes with an "Application error: see dev console for deets" message

### Status

Medium severity? This is part of a larger family of issues affecting drawing tools on mobile

**Comment by eatyourgreens** [comment]
You can also reproduce this with the transcription line tool eg. by tapping to start a line on Davy Notebooks.
https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/classify/workflow/21734

**Comment by eatyourgreens** [comment]
I'm not 100% sure but I think this bug was introduced when I refactored the validation of incomplete marks: https://github.com/zooniverse/front-end-monorepo/pull/3424

**Comment by eatyourgreens** [comment]
Tapping the screen (as opposed to clicking with a pointer) focuses the new active mark, which then runs `onSelectMark` here. `onSelectMark` always finishes the active mark, even if you're still drawing it.
https://github.com/zooniverse/front-end-monorepo/blob/87f789d502ceb5601770de45cf3faa4f204511fa/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js#L143-L147
