### ISSUE TITLE
Radio buttons in Tutorial change ImageAndTextViewer frames

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#3532]
## Package
- lib-classifier

## Describe the bug
- clicking the first or second radio button input in the SlideTutorial StepNavigation component change the frame in the ImageAndTextViewerContainer

## To Reproduce
1. Go to https://frontend.preview.zooniverse.org/projects/markb-panoptes/digileap-testing-staging/classify/workflow/3594?env=staging
2. Click on Tutorial in the TaskArea
3. Click the second radio button input
4. See subject viewer change from image to text viewer

## Expected behavior
Clicking the StepNavigation in the SlideTutorial should not change the frame in the subject viewer

## Additional context
Related to grommet/issues/3352 - solution is for options to be unique between RadioButtonGroups. Different names won't fix. Currently, the first and second options are the same between the ImageAndTextViewerContainer and SlideTutorial implementations of StepNavigation. Editing the option ids with a unique identifier fixes the issue (PR incoming).

Linked to #3190

**Comment by eatyourgreens** [comment]
Here’s a link to the Grommet issue: https://github.com/grommet/grommet/issues/3352
