### ISSUE TITLE
Workflow Selector in project homepage exceeds bounds of layout after refresh

### ISSUE THREAD

**Issue by MaysaB** [zooniverse/front-end-monorepo#3541]
## Package
app-project

## How it should look:

Initial landing page of project page eg Davy Notebooks page is fine. The workflow selector on the right hand side is within the bounds of the container.

(Screenshot of correct view)
<img width="1115" alt="Screenshot 2022-08-16 at 13 45 06" src="https://user-images.githubusercontent.com/49612167/184895421-bf61d5e6-46b2-488b-b8ad-1b0a704aff5b.png">

## How it actually looks

When page is **refreshed**, workflow selector component shifts down and behind the Zooniverse Talk thumbnails.

(Screenshot of incorrect view)
<img width="1325" alt="Screenshot 2022-08-16 at 13 47 08" src="https://user-images.githubusercontent.com/49612167/184895501-5d760f87-f6cd-4b3f-b5fa-c864fa3c2d2a.png">

## Steps to Replicate

1. Go to 'https://frontend.preview.zooniverse.org/projects/humphrydavy/davy-notebooks-project'
2. Scroll down so you can see the five workflow options.
3. **Refresh the page.**
4. See how the entire component shifts down.

### Desktop (please complete the following information):
 - Confirmed MacOS, Chrome 104.
 - Chrome, 104. Firefox, 103.

## Additional context
Problem may be less obvious if the project has single workflow.
**Please test on incognito window to confirm.**
Bug does not exist as of the most recent production (commit 839972e)
Can confirm that bug exists on most recent master(commit [e502449](https://github.com/zooniverse/front-end-monorepo/commit/e502449841cb3444d2802a80991381c08f0877dc))

**Comment by eatyourgreens** [comment]
The Workflow Selector code assumes that the component needs to wait for a user to load from the API, but that's no longer true as of this PR: https://github.com/zooniverse/front-end-monorepo/pull/2979

I think the bug is in the `Loader` component, or in the logic that shows the loader while waiting for a user to load.
