### ISSUE TITLE
Links to related organization from project home page

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#3579]
In PFE, if a project is part of an organization, then the project home page includes:
1. a link to the related organization above the project description (only on project home page)
2. a link to the related organization in the project sub-navigation after Recents (available on all project pages, i.e. About, Classify, etc.)

See https://www.zooniverse.org/projects/md68135/notes-from-nature-wedigflplants as an example.

An FEM project home page should have similar links to a related organization as PFE, if applicable.

**Comment by mcbouslog** [comment]
CCing @seanmiller26 to put on your radar, I don't think there are any related existing designs, but I'm not 100% sure.

**Comment by mcbouslog** [comment]
More links,

Wildcam Gorongosa:
- PFE: https://www.zooniverse.org/projects/zooniverse/wildcam-gorongosa
- FEM: https://frontend.preview.zooniverse.org/projects/zooniverse/wildcam-gorongosa

Notes from Nature - Big Bee Bonanza!
- PFE: https://www.zooniverse.org/projects/md68135/notes-from-nature-big-bee-bonanza
- FEM: https://frontend.preview.zooniverse.org/projects/md68135/notes-from-nature-big-bee-bonanza

**Comment by seanmiller26** [comment]
@mcbouslog Here's a screenshot of a simple solution for FEM Organization navigation. The home page link appears below the project's description. The header link is in the same place where the language dropdown used to be in PFE. Is that positioning possible in FEM?

<img width="1274" alt="Screen Shot 2022-10-03 at 1 01 31 PM" src="https://user-images.githubusercontent.com/89043489/193646907-0d6ee0d2-7b12-416a-ab61-32f5f639d72a.png">

**Comment by seanmiller26** [comment]
An updated design can be previewed here: https://www.figma.com/proto/SFjE75AOBeiYwbA0v3oVQ8/Project-Page?node-id=1%3A1539&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=3%3A5505

<img width="1442" alt="Screen Shot 2023-02-16 at 11 12 06 AM" src="https://user-images.githubusercontent.com/89043489/219438647-6f9313ae-bb3b-4e5f-9699-873ffb64f4fb.png">

Both the header link and the Project Card link should underline on hover (This action can be previewed with the above Figma link).

<img width="1443" alt="Screen Shot 2023-02-16 at 11 11 43 AM" src="https://user-images.githubusercontent.com/89043489/219438662-92934167-5f81-4ff8-92c4-aab2aae19191.png">

The organization link is present on all project pages (About, Classify, Talk, etc).

**Comment by mcbouslog** [comment]
@seanmiller26 - how should the organization link in the project header look when the project header is narrow (nav moves to a dropdown nav)?

**Comment by mcbouslog** [comment]
In the project content component the Zooniverse Grommet theme colors the link text neutral-1 and accent-1. Should I keep the link text color as per the theme or change to black/white per Figma design?
![dark_project_info_org_link](https://user-images.githubusercontent.com/12118751/235962144-ce8ae036-3caa-4e09-9a7f-b2837740a904.png)
![light_project_info_org_link](https://user-images.githubusercontent.com/12118751/235962149-93a61a92-be86-4edd-b038-76374a5e36f5.png)

**Comment by mcbouslog** [comment]
Noting per discussion we're going to go with the Hero section organization link font color per Grommet theme (light - neutral-1 and dark - accent-1) and keep the Project Header organization link font color white.

**Comment by mcbouslog** [comment]
Screenshot with many workflows and project introduction:
![manyWorkflowsProjctIntro](https://github.com/zooniverse/front-end-monorepo/assets/12118751/ad93da35-ae45-41ed-86b6-62e599a4fb9c)

**Comment by seanmiller26** [comment]
@mcbouslog  If possible we should incorporate the phrase "From the organization:" into the Explore Project dropdown for consistency. This is for mobile sizes (<768px width). I've added an example here:

<img width="418" alt="Screen Shot 2023-05-25 at 12 12 05 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/89043489/e4dcd82f-66c0-47e0-a2f1-17c9c29ddba1">
