### ISSUE TITLE
Content Pages: can't use filters / incorrect asset deployment URL

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#3587]
## Functionality Issue

Package: `app-content-pages`
Pages: https://zooniverse.org/about/team and https://zooniverse.org/about/publications
Noted as of 31 Aug deployment

The problem:
- If you open our About > Team or About > Publications page, you'll get the page content, but the page isn't interactive.
- Clicking on the filters/sections (e.g. "Oxford" under About > Team) does nothing.

The analysis:
-  None of the JavaScript files (which would add the interactivity) are being pulled correctly 
    <img width="1275" alt="Screenshot 2022-09-01 at 01 00 13" src="https://user-images.githubusercontent.com/13952701/187738788-268c3ac1-d454-48fc-862b-787d13a13d8b.png">
- Here we see the page trying to get `https://fe-content-pages.zooniverse.org/_next/static/chunks/webpack-743de9e125f46c7a.js` (which uses the incorrect `fe-content-pages.zooniverse.org` base URL) when it should be calling `https://www.zooniverse.org/about/_next/static/chunks/webpack-743de9e125f46c7a.js` (note the `www.zooniverse.org/about` base URL)
- This must be an issue with the app-content-pages deployment that we're only noticing now.

The solution:
- PR fix ready: #3586

### Status

Problem identified and a solution incoming. I do believe this is a low-priority problem that can wait until next Wednesday's deploy, though.

Tagging @lcjohnso and @snblickhan as an FYI, and just in case either of you think the About pages need to be patched on the live servers ASAP as a hotfix.

**Comment by eatyourgreens** [comment]
>I do believe this is a low-priority problem that can wait until next Wednesday's deploy, though.

This also affects live projects, which have the asset prefix set to `https://fe-project.zooniverse.org`, which means that JS will stop working on the Classify page across a deploy.

**Comment by shaunanoordin** [comment]
OK, that would definitely crank the priority to critical.

For the moment though, I can't confirm that the Project pages are borked - I'm looking at [Planet Hunters TESS](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235) and I can see that e.g. the webpack JS file is pulling from the correct `https://www.zooniverse.org/projects/_next/static/chunks/webpack-780cd452283a8b0b.js` URL and not the URL with the incorrect prefix.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/13952701/187742470-9c136765-f9bc-4bb6-b2f0-a202d4093551.png">

We may need more eyes on this to confirm, I may be missing something with my tests.

**Comment by eatyourgreens** [comment]
You'd need to be in the middle of classifying while a deploy happened, so that you have a pre-deploy page loaded in your browser just as it goes offline.

**Comment by eatyourgreens** [comment]
Aha! The Jenkinsfile environment will be used to build the Publications and Teams page HTML during the initial build of the content pages app (`yarn build`.) The apps then get deployed to kubernetes, which has the correct environment set up and that environment will be used for subsequent page builds. Expect the asset URL to change from `fe-content.zooniverse.org/_next` to `www.zooniverse.org/about/_next` about an hour after deployment, since the page revalidation time is set to 3600s in the code.

The project app doesn't use static pages, so no HTML is built during the initial Docker build and so it won't have this problem. Even on #2531, project static pages are built on demand, not during the initial `yarn build` step.

**Comment by eatyourgreens** [comment]
One change we could make: upgrade the content pages app to use ISR and build HTML on demand.
