### ISSUE TITLE
Classifier Page: Subjects in "Your Recent Classifications" lose links when page refreshed

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#3606]
## UI Bug

Package: `app-project` (not `lib-classifier`!)

Problem:
- the Subjects in "Your Recent Classifications" have "disappearing links" when the page is refreshed.
- when we refresh the page, we expect to see this:
    <img width="400" alt="image" src="https://user-images.githubusercontent.com/13952701/188568520-66a9e2f1-bbb4-44df-9325-5100ff8036f9.png">
- instead, we see this:
    <img width="400" alt="image" src="https://user-images.githubusercontent.com/13952701/188568572-a0076024-f842-4b9f-aa8f-8c67b2b59938.png">
  (nothing else down here!)

Context:
- Originally discovered by @eatyourgreens on FEM Classifier page + Planet Hunters TESS (production/live) [(Example URL)](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235)
- Also confirmed on other test projects (staging/master) [(Example URL)](https://frontend.preview.zooniverse.org/projects/darkeshard/test-project-2022/classify/workflow/3581?env=staging)

### Testing / Replication

Replication steps:
1. Go to the PHTess Classify page (example URL above) then log in (on an account that's previously classified on PHTess)
2. Scroll down to view "your recent classifications"
3. Observe that Subjects have 3 links each, very visible
4. Refresh the page (Cmd+R) (done at 00:14 in video)
5. Expectation: Subjects should each still have 3 links visible / Actual: Subjects' links have "disappeared"

(macOS + Chrome 105, incognito window. Replicated on Safari 15.4 & Firefox 104)

https://user-images.githubusercontent.com/13952701/188567705-debd05de-e8a7-468d-9580-765221c38a9a.mov

Alternate replication steps:
1. (alternative to step 1) If you're already logged in, navigate to home page, then navigate back to Classify page.
2. (step 2 onwards are the same)

This means the problem only occurs on page refresh.

### Dev Notes

Analysis:
- (1) Under normal conditions (either by logging in on the Classify page; or navigating to the Classify page from the home page, after already logged in), the `<div>`s surrounding the Subject + links have `height: 100%`
    <img width="800" alt="Screenshot 2022-09-06 at 14 45 19" src="https://user-images.githubusercontent.com/13952701/188569115-21841f25-f10c-467d-a770-c1d9f9849775.png">
- (2) Upon refresh, those same `<div>`s have `height: 200px` and a bunch of other junk
    <img width="800" alt="Screenshot 2022-09-06 at 14 45 56" src="https://user-images.githubusercontent.com/13952701/188569241-5ff54250-57be-41b0-84ba-78629fc80d32.png">

Figuring out what's causing this switch should let us spot the solution. Not sure if this has anything to do with Next.js. 🤔 

### Status

This is a Low/Medium priority bug, as far as I can tell.

**Comment by eatyourgreens** [comment]
Those extra styles are the styles for the placeholder, which shows while recents are loading.
https://github.com/zooniverse/front-end-monorepo/blob/5b7058dc3c75b13439ff5d6037112ddaf27d1a1c/packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js#L54-L63

This is a similar bug to #3541. Like #3543, the quick fix is not to render those placeholders during SSR.
