### ISSUE TITLE
Rename `app-project` to `app-project-classify`

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#362]
**Package**

`app-project`

**Feature or Issue Description**

This should be renamed to `app-project-classify`; I'm seeing this app solely handling the classifier (`/projects/owner/slug/classify`), and everything else under a project's route can go into a separate app.

We'll need to update:

- Docs
- `package.json`
- Jenkinsfile
- Deployment to swarm? (cc @adammcmaster)

**Comment by eatyourgreens** [comment]
After our lunchtime conversation last week, my feeling is that this app should serve a HTML skeleton for the project, including localised text for the home page and about pages, then the JS can handle classifying, authentication and collections. Something similar to the approach that [zooniverse/zooniverse-readymade](https://github.com/zooniverse/zooniverse-readymade) took to publishing a project, but with index.html being generated on the server instead of written by hand.

**Comment by srallen** [comment]
I think my concern still stands. I don't think the rest of the project warrants an entirely separate app whether the routes match a javascript component for rendering in a SPA or returns an HTML file for that page.

Also, do we have an idea how CSS would be shared between a vanilla HTML page and the Grommet theme? I don't want to duplicate effort between the Grommet theme and writing CSS for a standard HTML/CSS page.

**Comment by rogerhutchings** [comment]
My reasoning for separating out the classifier screen into a separate app was to enable it to be scaled independently. Probably a premature optimisation though.

**Comment by eatyourgreens** [comment]
@srallen I agree. This should be an app that renders the basic HTML for the whole project on the server, then the browser runs JS to handle authentication, classifying and anything related to personalisation, like your stats and recent subjects.

Won't Grommet be handled by Server-Side-Rendering, or have I misunderstood?

**Comment by rogerhutchings** [comment]
So yeah, probably doesn't make sense to break this out yet - if it's worth investigating later on, we can reopen the issue.

**Comment by eatyourgreens** [comment]
@rogerhutchings  I'm thinking even the stats box and recent subjects will be rendered server-side, then data optionally added in dynamically after a user logs in. That way, we have some initial HTML for anonymous users.

If the language changes, should we do a full page refresh and just request the project in the new language?
