### ISSUE TITLE
Dropdown task marked as required, not required

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#3639]
## Package
- lib-classifier

## Describe the bug
A dropdown task set as required doesn't have to be answered to proceed with Done or Next in the classifier.

## To Reproduce
0. Create workflow with dropdown task that's required - (production test project - https://www.zooniverse.org/lab/4312/workflows/3852)
1. Go to production test project - https://frontend.preview.zooniverse.org/projects/markbouslog/test-project-mb/classify/workflow/3852
2. Note can click Done or Done & Talk

## Expected behavior
Done, Done & Talk, or Next is disabled for a required task until answered, production test project - https://www.zooniverse.org/projects/markbouslog/test-project-mb/classify?reload=0&workflow=3852

## Additional context
Staging test project:
- lab - https://master.pfe-preview.zooniverse.org/lab/1693/workflows/3504?env=staging
- PFE - https://www.zooniverse.org/projects/markb-panoptes/test-project-1-mb-fem-lab/classify?reload=0&workflow=3504&env=staging
- FEM - https://frontend.preview.zooniverse.org/projects/markb-panoptes/test-project-1-mb-fem-lab/classify/workflow/3504?env=staging

**Comment by eatyourgreens** [comment]
The dropdown task story works for a required task. That’s interesting. 

https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/tasks-simple-dropdown--light-theme&args=required:true&globals=locale:en;locales.en:English;locales.test:Test+Language

**Comment by eatyourgreens** [comment]
The `required` flag isn’t copied over from old-style dropdown tasks. 
https://github.com/zooniverse/front-end-monorepo/blob/0c7bab65eaba1959662293dc5e5235cd97e69d2f/packages/lib-classifier/src/plugins/tasks/dropdown-simple/models/helpers/legacyDropdownAdapter/legacyDropdownAdapter.js#L6-L13
