### ISSUE TITLE
[RFC] How to handle auth?

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#365]
I want to write up an ADR on this eventually, but first I want to collect together ideas / opinions on the subject, especially given my limited understanding of the OAuth2 spec.

At the moment, we have two methods for doing auth: 

 - First party, where a trusted app collects username / password, sends it off to Panoptes and gets back a token [OAuth2 Resource Owner Password]
- Third party, where an untrusted app redirects a user to a URL served by Panoptes and grants permissions to the untrusted app [OAuth2 Implicit Grant]

## Things to consider about this, in no particular order

- Auth is currently part of the Panoptes API, rather than being a separate service.
- It's currently recommended not to use Implicit Grant (https://tools.ietf.org/html/draft-ietf-oauth-security-topics-09)
- AFAIK we don't add a state string to Implicit Grant requests in any repo
- My ideal end state would be to have a standalone app that can be suitably prettified and that acts as the central point for all things auth. 
- We'd then have a drop-in library that handles the token / code exchange as needed. This library would also need to handle token expiry, and session expiry warnings etc; it would be the job of the consuming app to handle state preservation.
- We'll need to train our users to be okay with full-page refreshes on auth.

What do other people feel would be the ideal manner for handling authentication, both on zooniverse.org and custom front ends?

cc @srallen @camallen @eatyourgreens @marten 

related issues: #360, #302

**Comment by camallen** [comment]
> AFAIK we don't add a state string to Implicit Grant requests in any repo

I think the library we use supports the state variable if it's present in the original request. So should be a simple test / addition to see it it works.

> It's currently recommended not to use Implicit Grant

Right - implicit security model seems to be flawed but over TLS it should be ok and old code bases will still need it. It seems the code flow is more secure, though only it seems through a layer of complexity as the value is still returned via the URL. So i guess we should try to move to it as a default for our web apps that can't keep a secret, https://www.oauth.com/oauth2-servers/single-page-apps/

Using code flow instead should be a straightforward switch as it's supported by the API already for public clients https://github.com/zooniverse/Panoptes/pull/2847/files. Though nothing is ever simple with oauth ;)

https://github.com/doorkeeper-gem/doorkeeper/wiki/Supported-Features
https://developer.okta.com/blog/2018/04/10/oauth-authorization-code-grant-type

> We'll need to train our users to be okay with full-page refreshes on auth.

I think this kind of authentication system is prevalent enough it won't worry them but we should do our best to signal the changes though.

**Comment by rogerhutchings** [comment]
Additional thoughts since I opened this - I'd like to be able to save a user's credentials in a cookie, since we can use that for SSR

**Comment by srallen** [comment]
Yes, to a separate lib or app, but I don't want to maintain and duplicate effort for maintaining any views. The app should solely be for maintaining any auth related data, not UI. We already have views on Panoptes for registration and sign in and we currently have to maintain these forms in multiple places right now. 

I'm 💯 for moving toward all apps using the same auth strategy and not maintaining first party and oauth. I agree that enough users would be familiar with a page refresh for sign in at this point that it shouldn't be too jarring. What we should do though is spruce up the Panoptes views to make them look more in line with our client apps with branding to ensure that trust in the user. 

A cookie is the only way to go if we do SSR? Are there any other options?
