### ISSUE TITLE
With Safari v16 light curve viewer height expands unexpectedly

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#3654]
## Package
- lib-classifier, [LightCurveViewer](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js#L427)

## Describe the bug
Introduced in Safari v16, and only Safari v16, the light curve viewer height expands unexpectedly. 
Related to #3119 , #3139 , and #3646 .

## To Reproduce
1. In Safari v16, go to https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235?demo=true
2. Note the light curve subject viewer height continues to expand, making classifier unusable.

Staging project local links:
- lib-classifier - https://local.zooniverse.org:8080/?project=1862&workflow=3317
- app-project - https://local.zooniverse.org:3000/projects/nora-dot-test/planet-finders-beta/classify/workflow/3317

## Expected behavior
The light curve viewer height is reasonably large, depending on browser sizing about 400-500px

### Desktop (please complete the following information):
 - OS: macOS Monterey 12.5.1
 - Browser: Safari
 - Version: 16

**Comment by eatyourgreens** [comment]
The storybook should have the bug too. 
https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/subject-viewers-lightcurveviewer--light-theme&globals=locale:en;locales.en:English;locales.test:Test+Language

**Comment by mcbouslog** [comment]
> https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/subject-viewers-lightcurveviewer--light-theme&globals=locale:en;locales.en:English;locales.test:Test+Language

Interestingly I'm not seeing the bug in the story, I think because we're [setting a set height in a Box parent component](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.stories.js#L58).

**Comment by mcbouslog** [comment]
If we can't find a more elegant solution, I think setting a maxHeight of something around 500px in the wrapping Box for the LightCurveViewer will fix the issue if only temporarily, i.e. [these lines of code](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js#L655-L671) to:
```
render () {
    return (
      <Box
        className='light-curve-viewer'
        fill
        height={{ max: '500px' }}
        ref={this.svgContainer}
      >
        <ReactResizeDetector
          handleWidth
          handleHeight
          onResize={this.drawChart}
          refreshMode='debounce'
          refreshRate={500}
        />
      </Box>
    )
  }
  ```

**Comment by mcbouslog** [comment]
Hmm, adding the max height might be restricting the viewer height in Chrome, recreating the issue noted in #3119.

**Comment by eatyourgreens** [comment]
Removing the resize detector might fix it too.
