### ISSUE TITLE
Freehand Line Tool: excessive Undo can crash page 

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#3667]
## Classifier Bug

Package: `lib-classifier`
Affects: experimental Freehand Line tool
Noted on: dfad6db9460f2c6aae82aa5cff395f8bb1f3063a , also exists on latest Freehand Line dev branch (#3598)

Problem:
- if we create a Freehand Line mark, and then click on the "Undo" (⬅️) button excessively, the entire Classifier crashes to white.
- Error message: `Cannot read properties of null (reading 'x') at FreehandLine `

https://user-images.githubusercontent.com/13952701/190612595-e1a8fe5a-875c-4d77-a568-ec375f5d68a1.mov

Analysis: this is a pretty straightforward case of the "Undo" action (actually deleting the last _n_ amount of points in the path array) **not** checking for the fact that the Freehand Line mark _assumes_ the existence of at least 1 point in its path. (The first point would be used to mark the position of the Delete button, for example.)

Suggested solution:
- Long term: implement a proper undo stack
- Short term:

```
// in marks/FreehandLine/FreehandLine.js

shortenPath() {
  let lengthToRemove = 20
  while (lengthToRemove--) {  // Change this to something like... (lengthToRemove-- && self.points.length > SOME_POSITIVE_NUMBER)
    self.points.pop()
  }
},
```

### Status

Medium priority; short-term fix should be a quick implementation.

**Comment by eatyourgreens** [comment]
Issues with the Undo button came up on our most recent Correct-A-Cell call. @shaunanoordin should we include you in those calls so that you can keep up with where we are on freehand tool development?

**Comment by eatyourgreens** [comment]
Thinking about, you won’t be able to undo or delete the initial line that’s shown to you in Correct-A-Cell, only edit it. So we could get rid of these buttons for the ‘correct a line’ tool.

**Comment by goplayoutside3** [comment]
@kieftrav can I assign you this issue to see if it can be replicated? Because the correct-a-cell freeland line tool has been updated with LineControls, etc, I'm not sure if this bug still exists.
