### ISSUE TITLE
Notifications and Messages links vanish on iOS

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#3672]
## Package
app-content-pages
app-project

## Describe the bug
When you use the Back button to return to a page in mobile Safari, or follow a link to another page, the Notifications and Messages links vanish from the top of the page.

![Screenshot of Maria Edgeworth Letters, showing that the links for Notifcations and Messages are missing.](https://user-images.githubusercontent.com/59547/190898566-54c4f5e9-78d2-4e83-a183-071e11849d62.png)

## To Reproduce
1. Go to [Maria Edgeworth Letters](https://www.zooniverse.org/projects/mariaedgeworthletters/maria-edgeworth-letters)
2. Navigate to Talk.
3. Use the Back button to return to the home page.

Alternatively, go to one of the About pages and navigate from Research to The Team.

## Expected behavior
Notifications and Messages should always be available (while logged in.)

### Smartphone (please complete the following information):
 - Device: iPhone Xs
 - OS: iOS 15.6.1
 - Browser Safari
 - Version 15.6.1

## Additional context
~~This bug doesn't exist in the page header for the Publications or Team pages, only in the page header for project pages.~~ Since #3671, where I connected the content-pages site header to the store, this bug also affects the Team and Publications pages.

**Comment by eatyourgreens** [comment]
Here’s a screen recording. 


https://user-images.githubusercontent.com/59547/190901542-ca4921dc-b9e9-409e-bbfd-39cb2d7b74b5.MOV

**Comment by eatyourgreens** [comment]
I don't know if this is the same bug, but my unread notifications vanish when I navigate between project pages in desktop Firefox.


https://user-images.githubusercontent.com/59547/191475339-393efda3-8e6f-4db6-9554-3854ded00b7f.mov

**Comment by eatyourgreens** [comment]
In that Firefox video, my unread notifications seem to be reset after the User hook runs here, so it could be related to the initial loading of notifications when the user is first fetched from Panoptes. 

https://github.com/zooniverse/front-end-monorepo/blob/f03872b95727960cb4db210885dbebd93a37e77b/packages/app-project/pages/_app.js#L48

**Comment by eatyourgreens** [comment]
I can reproduce this, on my phone, on the content pages NextJS app. Go to Publications then Teams, or vice versa, and Notifications and Messages will vanish from the top bar.

**Comment by mcbouslog** [comment]
Related to #3692

**Comment by mcbouslog** [comment]
I think self.notifications.fetchAndSubscribe() is missing from the [UserPersonalizaiton store load action](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/stores/User/UserPersonalization/UserPersonalization.js#L71-L74), I'll update a related issue or open a PR asap.

**Comment by eatyourgreens** [comment]
There’s an `autorun` function that calls `fetchAndSubscribe()` when the store first loads. I guess that runs before the `load()` action? 

In the video above, my unread notifications do appear briefly before vanishing.

**Comment by mcbouslog** [comment]
Separate from the issue of whether unread notifications or messages are shown (filled icon), @eatyourgreens - do you still see the icons disappear when navigating from project home, talk, back or from about/research to about/team?

Testing with Safari Responsive Design Mode the icons appear to stay? - 

https://user-images.githubusercontent.com/12118751/206271058-716f054f-c3f7-44f1-99da-183b98c53ee6.mov

**Comment by eatyourgreens** [comment]
I still get this bug on my phone, iOS 16.

**Comment by mcbouslog** [comment]
I tried using BrowserStack, iPhone Xs iOS v15 (didn't see 16), Safari, and the icons appear to stay as I navigate to about/research then to about/team

https://user-images.githubusercontent.com/12118751/206305917-6e816e0a-f835-4626-95c0-ac4ad426b12e.mp4

Apologies I'm sure I'm not reproducing correctly, please let me know what's inconsistent?
I'm focusing on the icons disappearing, not whether they show as filled or empty, hopefully that's fixed in #3975.

**Comment by eatyourgreens** [comment]
This is an older screen recording of an iPhone XS on iOS 15. 
https://github.com/zooniverse/front-end-monorepo/issues/3672#issuecomment-1250257396

**Comment by eatyourgreens** [comment]
I’m not seeing it now on Maria Edgeworth Letters. I think the only change since my earlier comment is that the `production-release` tag has changed.

**Comment by mcbouslog** [comment]
Yes, I see that video, that's what I'm trying to recreate. 
BrowserStack doesn't have iOS v16 with iPhone XS, so I used the closest device I could. I can't recreate the icons disappearing with iPhone XS iOS 15 or on iPhone 12 Mini iOS 16.

**Comment by eatyourgreens** [comment]
This is the list of commits between those two comments. 
https://github.com/zooniverse/front-end-monorepo/compare/zooniverse:9d78390...zooniverse:d8e7eec

**Comment by eatyourgreens** [comment]
One of those commits seems to have fixed it. 🤷🏻‍♂️

**Comment by eatyourgreens** [comment]
Closing this since it’s not happening any more.
