### ISSUE TITLE
HTML entities can crash Markdown components ("document is not defined")

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#3679]
## Uncategorised Bug?

Package: `app-project`, possibly others
Affects: ⚠️ anything that uses Markdown, e.g. Project About Team page, About Project, Announcements banner, etc

The problem: if a Markdown component tries to render an escaped HTML entity such as `&amp;` (ampersand), it crashes the _whole page._

- The error only occurs if you access the FEM page directly (via URL or via reload). It does not affect the page if you _navigate to it_ (e.g via project links) 
- The error only triggers if the escaped HTML entity is bracketed by both `&` and `;`
  - Markdown text such as `&` and `&amp` render as `&` on the webpage correctly.
  - `&amp;` on the other hand will crash.  
  - Note: I don't think we're supposed to use escaped entities like `&amp;` in Markdown to begin with.
- This issue only affects FEM pages (confirmed on app-project), and not PFE pages.
- This only affects server-side rendering?
- Error message is `document is not defined`. Rest of the page is blank.
- This is a more general version of #3673 

### Dev Notes

Some notes from our investigation:

**Scenario 1:** literal symbols in the Markdown text
`Play "Dungeons & Dragons" ©, it's > Cthulhu ♥`
- This renders fine
- NOTE: trying to add the `<` character in our Project Builder causes some things to go bonkers. Typing `<` will transform it into `&lt;` and convert all `>` into `&gt;` , `&` into `&amp;` . Copy-pasting, especially when creating a HTML tag, causes even more WTF-ery. This is a separate project builder discussion.

**Scenario 2:** proper HTML entities
`Play &quot;Dungeons &amp; Dragons&quot; &copy;, it's &gt; Cthulhu &hearts;`
- This causes a crash :x: 

Scenario 3?: sorta-proper HTML entities
`Play &quotDungeons &amp Dragons&quot &copy, it's &gt Cthulhu &hearts`
- This renders everything except the `♥` , which is just rendered as literally `&hearts`
- Trivia: looking at the WHATWG [webpage](https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references), it turns out `&amp &quot &copy &gt` are all legit, so certain HTML entities apparently don't need the `;` . I learn something new every day.

So anyway, it looks like HTML entities only crash our page if they're bracketed by both `&` and `;` , but ALL HTML entities can crash us (not just the `&amp;` )

### Status

~~Unknown priority.~~

EDIT: possibly solved by #3678

**Comment by eatyourgreens** [comment]
Was this closed by #3678? Entities still raise a 'document is not defined' error, but it doesn't crash the page any more.

**Comment by shaunanoordin** [comment]
I say let's close this issue for now, as the important thing is that the pages aren't crashing. 👌 

(Context for anyone who didn't read #3678: instead of crashing the page, HTML entities in Markdown now render as `<p>document is not defined</p>` on the page, and only _if_ you have JS disabled.)

The only ways I can think of that the _new_ "document is not defined" error could _remotely_ be a problem are if (1) people notice "document is not defined" as the project's preview in their, erm, Google search results? (super unlikely, since our meta-description tags & etc now render fine)) or (2) we have a new logging system that automatically picks up the flood of console.errors in the dev log.

**Comment by eatyourgreens** [comment]
@shaunanoordin People will see 'document is not defined' when the page loads in their browser.
https://www.zooniverse.org/projects/mariaedgeworthletters/maria-edgeworth-letters/about/team

https://user-images.githubusercontent.com/59547/191921740-f59175d5-62a0-4367-b07d-ed27d26d2838.mov
