### ISSUE TITLE
Correct-A-Cell feedback

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#3709]
Here are some questions that we had for this tool:

1. Intuitive way to present the editing of the line for an user:
  a. Double clicking + single click for line segment selection vs. other approaches? Is there a way to present this as a UI element for the volunteer?
  b. Would a detailed tutorial suffice to help with the new functionality?
  c. Is a toolbar with the “edit path” button + undo features helpful?
2. Tool’s functionality optimization for large number of points. Is the current point coordinate slicing slow for large N?
3. An undo feature (true or pseudo-undo) – where true undo is undoing the last action done by the volunteer vs. pseudo undo is deleting a set N points backwards.
  a. Will the current version of the undo erase existing points that are currently being edited?
  b. Is it a concern if the current version of undo deletes N set of points and starts deleting outside the dashed region (i.e. outside of the editable section)
4. User experience: When editing/drawing line (solid curve) interfering with the original proposed path (dashed line) – will this be a concern?
  a. Ability to create new paths or delete existing ones:
  b. Able to handle special but possibly important cases when multiple merged cells/lipid droplets are initially proposed as one contiguous shape by the machine, but the user should be able to separate and close them as N separate shapes.
  c. Conversely, certain regions of the subject image can be falsely provided with proposed line shapes (by the machine) which the volunteer may consider removing completely. So a possibility to delete an entire shape should be enabled.
5. Usability and optimization on other devices: Is the new functionality optimized for devices such as Ipad etc?
6. Auto-close: Although auto-closing of the shape may not be desirable in this case, for shapes that straddle the subject image boundaries, it may be worth thinking about an auto-close button in the tool bar. E.g., a volunteer encounters a shape that is on the edge that needs correction, however, they can draw over the shape that is in the image and correct it as needed, but can also choose to auto-close shapes that just closes end to end for the edge pixels. However, an overuse/misuse of such feature may be feared.

_Originally posted by @ramanakumars in https://github.com/zooniverse/front-end-monorepo/issues/3680#issuecomment-1259927708_

**Comment by eatyourgreens** [comment]
>1. Intuitive way to present the editing of the line for an user:
  a. Double clicking + single click for line segment selection vs. other approaches? Is there a way to present this as a UI element for the volunteer?
  b. Would a detailed tutorial suffice to help with the new functionality?
  c. Is a toolbar with the “edit path” button + undo features helpful?

I don't think the project builder's drawing task, which we're using at the moment, will allow us to add a toolbar. It's a fairly simple task. A single drawing task consists of a set of drawing tools. Each tool produces an SVG shape and the corresponding annotation eg. line annotations, rectangle annotations, freehand path annotations etc. So you can't add a line-slicing tool without also adding a line-slicing annotation, for example.

If the task is sufficiently complex, we could have a new task in the project builder. That's how transcription workflows work. They use a specialised transcripton task, rather than the basic drawing task.

It's probably going to be easier to answer this question once we have some example subjects to work with, so that we can see how complicated the task is.

For what it's worth, I conducted some unscientific user research with two people, both of whom said that, given a line to correct, they would immediately tap on it with a pen, or click with a pointer, and start drawing. If we do have a specific editing mode, that can be toggled from a button, it should be on by default when the subject first loads.

**Comment by eatyourgreens** [comment]
> 2. Tool’s functionality optimization for large number of points. Is the current point coordinate slicing slow for large N?

It seems reasonably fast when I try it out with long-ish lines on [Etch-A-Cell](https://frontend.preview.zooniverse.org/projects/h-spiers/etch-a-cell/classify/workflow/8921). It does seem to slow down as the line gets longer, drawing one continuous path around the whole nucleus. I haven't tested it with a path around the entire nucleus, only partial shapes.

**Comment by eatyourgreens** [comment]
> 3. An undo feature (true or pseudo-undo) – where true undo is undoing the last action done by the volunteer vs. pseudo undo is deleting a set N points backwards.
a. Will the current version of the undo erase existing points that are currently being edited?
b. Is it a concern if the current version of undo deletes N set of points and starts deleting outside the dashed region (i.e. outside of the editable section)

Undo is pretty broken at the moment. It removes the last 20 points from the SVG path, regardless of whether those were the last points that you drew.
https://github.com/zooniverse/front-end-monorepo/blob/153c0568f0a83d79f63399916e4923c7c9a3913f/packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js#L219-L225

It also crashes if you press Undo until all of a line's points have been removed (#3667), and there's no corresponding Redo to restore editing history.

I think Undo needs to be rewritten to observe and record changes to the SVG path, with the option to step backwards (Undo) or forwards (Redo) through the change history.

**Comment by eatyourgreens** [comment]
> 4. User experience: When editing/drawing line (solid curve) interfering with the original proposed path (dashed line) – will this be a concern?
a. Ability to create new paths or delete existing ones:
b. Able to handle special but possibly important cases when multiple merged cells/lipid droplets are initially proposed as one contiguous shape by the machine, but the user should be able to separate and close them as N separate shapes.
c. Conversely, certain regions of the subject image can be falsely provided with proposed line shapes (by the machine) which the volunteer may consider removing completely. So a possibility to delete an entire shape should be enabled.

You can edit a single SVG path, adding and removing points, but you can't cut one path into two new paths eg. cut an open line into two lines, or cut a closed shape into two new shapes.

**Comment by eatyourgreens** [comment]
> 5. Usability and optimization on other devices: Is the new functionality optimized for devices such as Ipad etc?

Seems ok-ish on my phone (iOS 15.) I find drawing hard when my finger obscures the line that I'm trying to trace. A tablet with a pen might work better. Large SVG shapes might use a lot of memory, which would make them slow on smaller devices.

**Comment by eatyourgreens** [comment]
> 6. Auto-close: Although auto-closing of the shape may not be desirable in this case, for shapes that straddle the subject image boundaries, it may be worth thinking about an auto-close button in the tool bar. E.g., a volunteer encounters a shape that is on the edge that needs correction, however, they can draw over the shape that is in the image and correct it as needed, but can also choose to auto-close shapes that just closes end to end for the edge pixels. However, an overuse/misuse of such feature may be feared.

I'm not sure about this. Etch-A-Cell always has the shape centred in the frame, and volunteers aren't asked to trace shapes that straddle the edge of the frame.

**Comment by goplayoutside3** [comment]
@ramanakumars Can this Github issue be closed as a complete feature? Also tagging @kieftrav here.

**Comment by ramanakumars** [comment]
Yes, I'm happy to close this, but also want to tag @AgentM-GEG to make sure there are no issues with the new Correct-a-cell project.

**Comment by AgentM-GEG** [comment]
Thanks for the ping. I think closing sounds good. The correct a cell project will go to beta soon and we are hoping to get more wide spread feedback and might come back with specific issues as needed.
