### ISSUE TITLE
Classifier should have 'persist annotations' setting

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#379]
## Feature Required
package: `lib-classifier`

- The Classifier, by default, removes the annotations made by the user on the current step/task, whenever the user goes back to a previous step/task.
- In PFE, the user is given a (small) warning before they go back a previous step and this happens.
- However, there is a 'persist annotations' setting that can be enabled. (See the [dev Classifier](https://master.pfe-preview.zooniverse.org/dev/classifier), with the 'persist annotations' option at the bottom of the page.)

Follows discussion on https://github.com/zooniverse/front-end-monorepo/pull/378#issuecomment-456138485 . Also see full Slack discussion on `#dev-frontend` between @shaunanoordin @eatyourgreens @srallen on 21 Jan 2019.

**Comment by srallen** [comment]
The todo for this issue should be the second point: 

In PFE, the user is given a (small) warning before they go back a previous step and this happens.

We need to add the tooltip warning.

**Comment by srallen** [comment]
Note the actual TESS project will only have a single step, so, the warning isn't strictly necessary for its launch.

**Comment by srallen** [comment]
We should make sure that this works with recursive workflows.

**Comment by rogerhutchings** [comment]
It may be that instead of this being available as a setting that toggles visibility in the classifier, we have some other UI for showing what you've added already (since this is primarily used in transcription projects)

**Comment by srallen** [comment]
It was noted in https://github.com/zooniverse/front-end-monorepo/issues/1272#issuecomment-553828531 that projects may be using this as a means to have a in-progress summary when using text and dropdown tools, usually used by humanities projects. Maybe we should totally rethink this instead as an UI/UX in-progress summary that is needed. Are there any use cases for annotation persistence outside of the transcription and humanities use case?

**Comment by srallen** [comment]
If we re-concept this feature, then we need 1 week of design time and unknown amount of time for dev. 
If we implement as is, then 1 week dev time.

**Comment by eatyourgreens** [comment]
Do we know how often this gets used to go back and edit annotations for complex drawing and transcription workflows? That would influence whether or not it's a high priority item.
