### ISSUE TITLE
"Your statistics" widget

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#38]
<img width="376" alt="screenshot 2018-06-07 16 50 12" src="https://user-images.githubusercontent.com/2725841/41111178-30fa07e2-6a73-11e8-9644-416390faf92d.png">

**Comment by rogerhutchings** [comment]
@camallen This is the widget that would use the new stats API

**Comment by eatyourgreens** [comment]
Those day names on the x-axis are going to need to be localised, aren't they?

**Comment by eatyourgreens** [comment]
Sorry to be asking dumb questions but is this a modal box or is it displayed somewhere on the classify page?

**Comment by srallen** [comment]
It's further down the page. Here are the redesign in invision: https://projects.invisionapp.com/d/main#/projects/prototypes/12923997

**Comment by rogerhutchings** [comment]
On the classify page, between "Finished for the Day" and "Project Statistics":

<img width="678" alt="screenshot 2019-01-16 16 15 14" src="https://user-images.githubusercontent.com/2725841/51262272-f5789a80-19a9-11e9-87db-a2bc7e92b2cc.png">

**Comment by camallen** [comment]
Noting there that the counts of volunteer activity (daily, total, etc) will ideally come from the new graphql stats API (currently down for db maintenance) instead of the old stats API (planned deprecation this year).

**Comment by eatyourgreens** [comment]
Is this high priority for the TESS launch, or something that can be added once we have a working classify page up and running on a server?

Can the stats API send back day-of-the-week with the daily counts? I'm thinking about how the histogram might be rendered with the days along the x-axis for the last 7 days (or is it this week with future days blank if I'm classifying on Tuesday say?)

**Comment by camallen** [comment]
> Can the stats API send back day-of-the-week with the daily counts? I'm thinking about how the histogram might be rendered with the days along the x-axis for the last 7 days (or is it this week with future days blank if I'm classifying on Tuesday say?)

Stats API will return the 'interval' (daily by default) histogram for the past only (all data i believe - a limit on this would be nice and easily supported i think). 

The new stats api code needs docs on the API itself and how to use it but you can see the code here https://github.com/zooniverse/zoo-stats-api-graphql/blob/9382005d6d2e33cd864fe8fe00125e292e13fb1f/app/graphql/types/query_type.rb#L7

**Comment by eatyourgreens** [comment]
Thanks. The histogram in the design is labelled Monday, Tuesday, Wednesday etc. I'm thinking about how that would work in practice (in screenreaders and across languages.)

**Comment by eatyourgreens** [comment]
[Plotly has some good histogram options](https://plot.ly/nodejs/histograms/). I'm not sure if they're accessible. For screen readers, we could also publish the numbers as a table or definition list that's hidden behind the plot (or pushed offscreen.)

**Comment by rogerhutchings** [comment]
D3 is already being used for other widgets on the page, and a bar chart is pretty simple

**Comment by eatyourgreens** [comment]
It needs some thought if it’s to be read out properly in VoiceOver. Here’s a d3 implementation. https://bl.ocks.org/d3noob/96b74d0bd6d11427dd797892551a103c

**Comment by eatyourgreens** [comment]
Depends on #360.

Project classification count is stored in user project preferences, so this component probably needs to be connected up to the classifier preferences store.

**Comment by eatyourgreens** [comment]
I'm thinking get the initial project classification count from `preferences.activity_count`, then increment by 1 in the browser each time a classification is submitted.

If the user isn't logged in, start `activity_count` at 0 for each browser session.

**Comment by rogerhutchings** [comment]
When not logged in, it'd be nice to show a set of dummy stats / graphs, drop down their opacity, and have a "You need to be logged in" shown over the top to indicate what you're going to get.

**Comment by eatyourgreens** [comment]
URL for the stats API is https://stats.zooniverse.org/graphql

**Comment by eatyourgreens** [comment]
Quick thought about making the graph accessible:
```svg
<svg role="img" alt="Monday: 150, Tuesday: 200, Wednesday: 305…">
  …
</svg>
```
The tip about labelling images comes from this excellent post about [writing useful alt text](https://axesslab.com/alt-texts/).

**Comment by rogerhutchings** [comment]
I'm going to bump this from the TESS production milestone, as it's not really required for launch.
