### ISSUE TITLE
Session ID changes when navigating to different app

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/front-end-monorepo#3863]
## Package
app-project (?)

## Describe the bug
Navigation from FEM project to Talk (or PFE or other app) leads to a new session ID.  Navigation from Talk to FEM does not change the session ID -- it remains unchanged.

Are there any consequences to the session ID changing during app change? (e.g., clearing of local storage, unsubmitted classifications, cached items, etc)

## To Reproduce
1. Go to [Planet Hunters TESS](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess)
2. Click on [Talk](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk) to exit FEM.
3. Click on [Classify](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify) to return.

## Expected behavior
Session ID should remain constant during app-to-app movement.

**Comment by eatyourgreens** [comment]
How can we check the session ID? Out of interest, what is it used for?

**Comment by eatyourgreens** [comment]
A couple of useful links:
Session IDs in PFE:
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/lib/session.coffee

Session IDs in the new classifier (should be more-or-less a straight copy of that CoffeeScript):
https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/store/utils/session.js

**Comment by eatyourgreens** [comment]
These tests don’t check the value of the generated ID, only that the function that generates them runs. 

https://github.com/zooniverse/front-end-monorepo/blob/9196190311ff1d4b19ace48367e9718de30ef4f9/packages/lib-classifier/src/store/utils/session.spec.js#L46-L56

**Comment by eatyourgreens** [comment]
> Are there any consequences to the session ID changing during app change? (e.g., clearing of local storage, unsubmitted classifications, cached items, etc)

Why would changing the session ID clear local storage or remove classifications? I am genuinely curious about this, if only because that would make this a serious bug.

**Comment by eatyourgreens** [comment]
You can examine `session_id` by watching browser session storage for `www.zooniverse.org`.

<img width="1037" alt="Screenshot of the browser dev console, showing session storage for www.zooniverse.org." src="https://user-images.githubusercontent.com/59547/201120445-88b220fd-e426-4812-b924-0be189a90eee.png">

When you leave the Classify page and enter Talk, a new session ID is generated, so this is a bug in PFE. When you leave Talk and go back to Classify, the session ID is unchanged, so the monorepo code doesn't have this bug.

I'm going to close this as a bug in PFE.
