### ISSUE TITLE
Use HEAD request to determine mime-type instead of external lib

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#392]
**Package** lib-react-components

**Feature or Issue Description**
From @eatyourgreens about the new Media component:
> Making a HEAD request for the resource URL, then using the response Content-Type, might be safer. A malicious service could still fake that, but there's only so much you can guard against.

> That would also fix the problem with the placeholder service. HEAD requests should be much faster than GET too, since you don't actually download the media file.

**To Dos**

- [ ] Example

**Comment by eatyourgreens** [comment]
I thought about this a bit more and it means making a load of network requests every time we want to render Markdown as HTML. So I’m not sure if it really is a good idea to do this in the browser.

**Comment by eatyourgreens** [comment]
In retrospect, this was a daft idea of mine, but I can't remember why.

**Comment by srallen** [comment]
Ok I'll close for now.
