### ISSUE TITLE
Survey task mobile styling refactoring

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#3926]
## Package
- lib-classifier

## Describe the bug
Refactor survey task for better mobile styling, including (please add/edit as see fit):
- choice button labels

The FEM default layout shrinks the task area more than the PFE task area with a survey task shrinks, which I think is highlighting mobile styling discrepancies.

**Comment by mcbouslog** [comment]
Local testing:
- task with more than 20 options -> https://local.zooniverse.org:3000/projects/markb-panoptes/survey-task-test-project/classify/workflow/2434
- task with more than 5, less than 20, options -> (⚠️ production project) https://local.zooniverse.org:3000/projects/sandiegozooglobal/wildwatch-burrowing-owl/classify/workflow/21141?env=production&demo=true

**Comment by mcbouslog** [comment]
more than 20 options

- ✅ - iPad, landscape:
![Screen Shot 2023-01-20 at 10 50 28 AM](https://user-images.githubusercontent.com/12118751/213756758-0ac3c5da-0fb6-4c71-8987-12bd8a38e261.png)

- ❌ - iPad, portrait:
![Screen Shot 2023-01-20 at 10 51 08 AM](https://user-images.githubusercontent.com/12118751/213756802-e24a6e59-f03d-45a0-a18c-097a3f8f3173.png)

- ❌ - iPhone, landscape:
![Screen Shot 2023-01-20 at 10 52 34 AM](https://user-images.githubusercontent.com/12118751/213756839-39cb7f9e-3c80-45ab-8e09-38ef1d9810c4.png)

- ❓ - iPhone, portrait:
![Screen Shot 2023-01-20 at 10 51 58 AM](https://user-images.githubusercontent.com/12118751/213756866-1d79041e-a9b8-498e-a8bd-65302feb130c.png)

**Comment by mcbouslog** [comment]
more than 5, less than 20, options (2 columns):

- ✅ - iPad, landscape:
![Screen Shot 2023-01-20 at 10 56 37 AM](https://user-images.githubusercontent.com/12118751/213757945-7eb804cc-c424-4905-9ef8-74de71d6fa13.png)

- ❌ - iPad, portrait:
![Screen Shot 2023-01-20 at 10 57 04 AM](https://user-images.githubusercontent.com/12118751/213757988-f3e86c82-ec3b-447c-aa28-1ff696462383.png)

- ❌ - iPhone, landscape:
![Screen Shot 2023-01-20 at 10 57 41 AM](https://user-images.githubusercontent.com/12118751/213758010-7042cb4d-4073-475e-8358-4508b71b6c2c.png)

- ✅ - iPhone, portrait:
![Screen Shot 2023-01-20 at 10 58 13 AM](https://user-images.githubusercontent.com/12118751/213758041-93151dac-3476-46bb-92a7-e35721dcfa5c.png)

**Comment by mcbouslog** [comment]
Possible solutions:
- adding a minimum width to the choices component
- changing buttons so text falls below image when button is below a certain width
- changing 3 or 2 column lists to become 2 or 1 column lists when below a certain width
- other...

**Comment by seanmiller26** [comment]
I'm wondering if this could be implemented into the button components to help with longer words which need to break to 2 lines? 

https://developer.mozilla.org/en-US/docs/Web/CSS/hyphenate-character

I would rather see:

eleph-
ant

than:

elephan
t

**Comment by mcbouslog** [comment]
I agree, but unfortunately I think `hyphenate-character` only applies if the text we're applying css to already includes a "hyphenate character," which I didn't understand the css/browser complexities to before looking into this, but apparently could be `&shy;` or I think "-" too. Different rules apply to different languages, as per https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#browser_compatibility. I did not expect hyphens to be the can of worms it appears to be!

**Comment by seanmiller26** [comment]
I would propose we try option 1: changing buttons so text falls below image. And we initiate that change at the Medium breakpoint (769px - 1279px). That should take care of most of the styling issues. I could see it still being a little funky approaching the smaller side of that breakpoint but I'd have to see it in action.

Then the format can go back to the default (side-by-side) for the Small breakpoint since the Task area then stacks under the subject.
