### ISSUE TITLE
Subject viewer: widescreen monitor means subject viewer requires scrolling

### ISSUE THREAD

**Issue by vrooje** [zooniverse/front-end-monorepo#3958]
## Package
lib-classifier? not sure

## Is your feature request related to a problem? Please describe.
I recently looked at the SLSN project on FEM while using my widescreen monitor and the light curve subject image was enormous, to the point of being unclassifiable. I had my browser on full screen, with a normal zoom level (100%).

Browser: Safari Version 15.6 (17613.3.9.1.5) on macOS Monterey (12.5) 

## Describe the solution you'd like
My guess is a simple fix would be to put a max height for the image size, perhaps based on the user's screen size.

## Additional context
Screenshots:

![Screenshot 2022-12-03 at 21 16 44](https://user-images.githubusercontent.com/2357126/205603670-9c536e7b-eb3c-49f8-95f3-29506e7fd64a.png)
![Screenshot 2022-12-03 at 21 15 44](https://user-images.githubusercontent.com/2357126/205603690-de68a88a-bbd2-424b-9970-ffb582d55212.png)

**Comment by eatyourgreens** [comment]
#3961 restricts the classifier width so that it has the same big margins as the rest of the page on wide displays.

**Comment by goplayoutside3** [comment]
Re-opening after PR 4002. See more explanation on Slack here: https://zooniverse.slack.com/archives/C0Z7YNTSL/p1671224333420949
