### ISSUE TITLE
Add to collections button and modal

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#398]
**Package** lib-classifier

**Feature or Issue Description**
We need an 'add to collections' button and modal to get to parity with the current classifier interface. For the collections search, we may be able to use Grommet's Select component which has props for search: https://v2.grommet.io/select

Or the Masked Input: https://v2.grommet.io/maskedinput

**To Dos**

- [ ] Example

**Comment by srallen** [comment]
Designs: https://projects.invisionapp.com/d/#/projects/prototypes/12923997

**Comment by eatyourgreens** [comment]
Depends on #360.

**Comment by eatyourgreens** [comment]
Is it possible to export the SVG icon from InVision for this button? I haven't been able to figure out how to download it.

**Comment by srallen** [comment]
Yes, in the inspect mode for the design. If you click on it, on the right hand side, there should be an option to download the asset file:

<img width="780" alt="screen shot 2019-02-19 at 3 15 45 pm" src="https://user-images.githubusercontent.com/5016731/53048007-52f48100-3459-11e9-8e59-6ab86f7c593e.png">

**Comment by eatyourgreens** [comment]
Cheers! I'm old and my eyes are weak. I completely missed that download arrow against the dark background.

**Comment by srallen** [comment]
The contrast on that wouldn't pass an accessibility audit, for sure.
