### ISSUE TITLE
Going directly to a project's about page (owner/project/about/research) removes sidebar nav highlight

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#3982]
## Package
app-project

## Describe the bug
The sidebar for navigating a project's about pages should display a teal highlight to indicate the current page. Navigating from a project's home page correctly shows the highlight, but going directly to a project's about page (owner/project/about/research) removes the sidebar nav highlight.

## To Reproduce
Point a browser directly to a project's about page such as TESS [Research](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/about/research), TESS [Results](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/about/results), etc, and the highlight is missing.

Refreshing the browser while viewing an about page also removes the sidebar highlight.

## Screenshots
![highlight](https://user-images.githubusercontent.com/23665803/206287065-31ea16f1-c448-4fff-9ff8-fd78e4186227.jpg)
![no highlight](https://user-images.githubusercontent.com/23665803/206287080-f17a71db-2da6-499e-8a55-c5cdfeaf101a.jpg)

## Additional context
Likely has to do with latest Next.js updates to its Router.

**Comment by goplayoutside3** [comment]
This bug also applies to the project header's navigation links. The underline indicating current page also disappears upon refresh.
![Screen Shot 2022-12-07 at 2 52 53 PM](https://user-images.githubusercontent.com/23665803/206293354-7737fd9d-5695-478e-b9de-6444e59468b8.png)

**Comment by eatyourgreens** [comment]
This could be the SSR bug we’ve seen before, where component state isn’t hydrated properly on the first render in the browser. See #3606 and #3541.

**Comment by eatyourgreens** [comment]
Slightly related: the active link in a navigation menu should use [`aria-current=‘page’`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) so that it’s announced as the current page.

**Comment by eatyourgreens** [comment]
I'm not sure but I think this might be the cause of this problem:
>Avoid using the `asPath` value on [next/router](https://nextjs.org/docs/api-reference/next/router#router-object) in the rendering tree until the router's `isReady` field is true. Statically optimized pages only know `asPath` on the client and not the server, so using it as a prop may lead to mismatch errors.

https://nextjs.org/docs/advanced-features/automatic-static-optimization#caveats

**Comment by goplayoutside3** [comment]
I looked into this a bit more, and agree part of the bug is due to looking for `asPath` on the server.

However, I think we need some refactoring of how an active NavLink is styled in ProjectHeader > Nav because we can’t rely on the `href` of those links to be consistent with the actual current page. We’re currently comparing to `addQueryParams(href)`, but that doesn’t account for the extra subpaths after /about or /classify.

For example:
    - `/classify` is always in the ProjectHeader for a multi-workflow project, but an HMS NHS classify page is actually `/classify/workflow/18613/subject-set/83775`
    -     `/about/team` is different than the ProjectHeader link for “About” which is always `/about/research`

In ProjectHeader's case, when someone clicks the "Classify" link and it points them to /classify/[workflow], the ProjectHeader component doesn't rerender the nav links until you refresh the page.
