### ISSUE TITLE
CFE can't import @zooniverse/react-components v1.3.1

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#3994]
## Package/Build Bug

Package: `lib-react-component`
Noted as of: `@zooniverse/react-components` [v1.3.1](https://www.npmjs.com/package/@zooniverse/react-components/v/1.3.1)

When a React-based CFE (Custom Front End) attempts to install and then import `@zooniverse/react-components`, the app crashes completely on the page that imports the Z/RC library.

### Additional Details

The CFE is set up as follows:
- package.json:
  ```
  "dependencies": {
      "@zooniverse/grommet-theme": "^3.1.1",
      "@zooniverse/react-components": "^1.3.1",
      "grommet": "^2.28.0",
      "react": "^18.2.0",
      "react-dom": "^18.2.0"
    }
  ```
- App.js: (main page)
    ```
    import React from 'react'
    import { base as baseTheme, Box, Grommet, Heading, Paragraph as P } from 'grommet'
    import { deepMerge } from 'grommet/utils'
    import zooTheme from '@zooniverse/grommet-theme'
    import { ZooHeader } from '@zooniverse/react-components'
    
    const appTheme = deepMerge(baseTheme, zooTheme)
    
    export default function App () {
      return (
        <Grommet theme={appTheme}>
          <Box>
            Nothing, no need to even import ZooHeader.
          </Box>
        </Grommet>
      )
    }
    ```

When I load the main page on a browser (macOS + Chrome 108), the page crashes (doesn't render, only a white page) with the following error message in the dev console:
```
Uncaught Error: Cannot find module 'polished'
    at webpackMissingModule (getGradientShade.js:5:85)
    at eval (getGradientShade.js:5:168)
    at ./node_modules/@zooniverse/react-components/dist/es6/PrimaryButton/helpers/getGradientShade.js (main.js:1206:1)
    at __webpack_require__ (main.js:10195:33)
    at fn (main.js:10406:21)
    at eval (blue.js:8:83)
    at ./node_modules/@zooniverse/react-components/dist/es6/PrimaryButton/themes/blue.js (main.js:1228:1)
    at __webpack_require__ (main.js:10195:33)
    at fn (main.js:10406:21)
    at eval (PrimaryButton.js:12:70)
```

Similarly, in the webpack dev server, I see errors:
<details>
  <summary>Errors on Webpack Dev Server</summary>

```
ERROR in ./node_modules/@zooniverse/react-components/dist/es6/PrimaryButton/helpers/getGradientShade.js 1:15-34
Module not found: Error: Can't resolve 'polished' in '/Users/shaun/projects/community-catalog/node_modules/@zooniverse/react-components/dist/es6/PrimaryButton/helpers'
 @ ./node_modules/@zooniverse/react-components/dist/es6/PrimaryButton/themes/blue.js 3:0-59 22:26-42
 @ ./node_modules/@zooniverse/react-components/dist/es6/PrimaryButton/PrimaryButton.js 13:0-38 19:8-17
 @ ./node_modules/@zooniverse/react-components/dist/es6/PrimaryButton/index.js 1:0-42 1:0-42
 @ ./node_modules/@zooniverse/react-components/dist/es6/index.js 10:0-91 10:0-91 10:0-91
 @ ./src/App/App.js 5:0-57
 @ ./src/App/index.js 1:0-35 1:0-35
 @ ./src/main.js 4:0-27 8:30-33

ERROR in ./node_modules/@zooniverse/react-components/dist/es6/Tabs/theme.js 1:0-43
Module not found: Error: Can't resolve 'polished' in '/Users/shaun/projects/community-catalog/node_modules/@zooniverse/react-components/dist/es6/Tabs'
 @ ./node_modules/@zooniverse/react-components/dist/es6/Tabs/Tabs.js 3:0-32 4:38-47
 @ ./node_modules/@zooniverse/react-components/dist/es6/Tabs/index.js 1:0-33 1:0-33
 @ ./node_modules/@zooniverse/react-components/dist/es6/index.js 14:0-50 14:0-50
 @ ./src/App/App.js 5:0-57
 @ ./src/App/index.js 1:0-35 1:0-35
 @ ./src/main.js 4:0-27 8:30-33

ERROR in ./node_modules/@zooniverse/react-components/dist/es6/helpers/getGradientShade/getGradientShade.js 1:0-43
Module not found: Error: Can't resolve 'polished' in '/Users/shaun/projects/community-catalog/node_modules/@zooniverse/react-components/dist/es6/helpers/getGradientShade'
 @ ./node_modules/@zooniverse/react-components/dist/es6/helpers/getGradientShade/index.js 1:0-45 1:0-45
 @ ./node_modules/@zooniverse/react-components/dist/es6/index.js 27:0-82 27:0-82
 @ ./src/App/App.js 5:0-57
 @ ./src/App/index.js 1:0-35 1:0-35
 @ ./src/main.js 4:0-27 8:30-33
```
</details>

### Analysis / Dev Notes

It seems that `lib-react-components` has `"polished": "~4.2.2"` installed under its package.json's **devDependencies** instead of _dependencies,_ even though polished is used during runtime. (See [NPM](https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file).) devDependencies aren't installed when you run `npm install --production`(see [StackOverflow](https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies)), so the distributed Z/RC bundle might be missing some necessary code.

Note that this problem isn't affecting FEM itself; we're able to build `app-project` which uses `lib-react-components` with no issues. I think Community Catalog is the first CFE that's attempting to use Z/RC, so perhaps this is why the issue wasn't spotted before. Or maybe I set up my CFE funny. Let's find out!

### Status

Investigation ongoing.

Currently I'm trying to figure out how I can test my fix (i.e. simply moving `polished` to Z/RC's dependencies) on my local without publishing Z/RC v1.4.1 or whatever. Changing my Community Catalog's package.json to use `file:(path-to-local-lib-react-components)` was a... hmmm, it raised _different errors,_ so I'm not sure if that's the way to go.

**Comment by eatyourgreens** [comment]
[Mapping Viz Tools](https://github.com/zooniverse/mapping-viz-tools/) uses the new Zooniverse React Components, but I think it's an older version.

**Comment by shaunanoordin** [comment]
Update:
- I tried to install `@zooniverse/react-components v1.2.1` (with `npm install --legacy-peer-deps`) on Community Catalog, which failed with other error messages.
- This time, the missing dependency was `styled-components`
- Z/RC has styled-components as a dev dependency & peer dependency, not a standard one.
- (Mapping Viz Tools uses Z/RC v1.1.0, and has styled-components installed as standard dep)

I'm going ahead and installing styled-components (v5+) to ComCat since it'll probably need it anyway, so let's see what happens.

**Comment by shaunanoordin** [comment]
Hmm, I'm hitting a bit of an error wall testing for v1.1 and v1.2. I'm going back to testing with v1.3.1 and seeing what's required to make that work.

**Comment by shaunanoordin** [comment]
OK, the solution to get `@zooniverse/react-components@1.3.1` running on ComCat was to simply add `polished@4.2.2` to ComCat's package.json

_Screenshot: ZooHeader imported and rendered on ComCat._
<img width="592" alt="image" src="https://user-images.githubusercontent.com/13952701/207038787-528f9b7f-b8cf-48f9-bc90-8aa1921bdede.png">

Awright, now I'm fairly confident about moving `polished` from devDependencies to dependencies in FEM/lib-react-components. Fix + version bump coming later. 👌

**Comment by eatyourgreens** [comment]
The version bump should be 1.3.2 for a bug fix.
