### ISSUE TITLE
Create `data-layer` package

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#4]
Create base mobx lib for handling the data layer

**Comment by srallen** [comment]
Since we haven't started work in the panoptesjs repo, should we just transfer the issues there into this one?

**Comment by srallen** [comment]
I still like this example as inspiration for what to do with the API calls: https://github.com/gothinkster/react-mobx-realworld-example-app/blob/master/src/agent.js

Just a very basic set of pre-written functions for the common requests per resource that then get used in the base mobx classes for each resource. If anyone needs to write some other kind of request, they can either use superagent directly or import in `get`, `put`, `post`, or `del` as needed.

**Comment by rogerhutchings** [comment]
Closed as we now have `lib-panoptes-client`
