### ISSUE TITLE
"Latest Talk Comment" widget

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#40]
This widget goes at the bottom of the Classify page

<img width="564" alt="screenshot 2018-06-07 16 50 36" src="https://user-images.githubusercontent.com/2725841/41111234-4f798cec-6a73-11e8-8161-b97dd2563a6d.png">

<img width="1214" alt="Screenshot 2019-09-19 12 33 35" src="https://user-images.githubusercontent.com/2725841/65240781-fa15c580-dad9-11e9-9bf3-fdb56a8fa2a2.png">

**Comment by srallen** [comment]
I'm going to move this to post-tess milestone

**Comment by eatyourgreens** [comment]
Won't this bias classifications if it's for the current subject?

**Comment by adammcmaster** [comment]
I guess it cloud just exclude the subjects board?

**Comment by eatyourgreens** [comment]
That’s a good idea but people leave comments with linked subjects on the other boards, so it might not be that straightforward.

**Comment by srallen** [comment]
@beckyrother there's a concern about biasing with the latest talk comment design. Let's us know your thoughts.

**Comment by rogerhutchings** [comment]
Copying over comments from Slack:

Sam:

> I’d quite like it for transcription projects. Can it be an option that gets selected in the PB?
>
> Edit: seems like a different thing than I’m thinking of, actually. I’m thinking of latest comment for that subject, not a random one for the project

Helen:

> I think it’s a fair point that it could bias the classification, even if the comment wasn’t for the current subject. Rather than showing the latest comment, could you instead have a compromise and use this space to show ‘Talk Boards with recent activity’ and then provide the names/links to the boards with the most recent posts

**Comment by srallen** [comment]
@shaunanoordin maybe something here to revive as related to the quick talk experiment.

**Comment by goplayoutside3** [comment]
@seanmiller26 I'm going to close this because there's no plan to build the feature, but please feel free to re-open if you think it should remain open.
