### ISSUE TITLE
Classifier - Scatter Plot Viewer - how do we handle separate X-zoom and Y-zoom?

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#401]
## Feature Plan?
package: `lib-classifier`
theoretical component: `SubjectViewer > ScatterPlotViewer`, a generalised spinoff of `SubjectViewer > LightCurveViewer`

We want to create a generalised Scatter Plot Viewer. When we do, we need to consider how we're going to handle **zooming/panning in the X-axis and the Y-axis separately.** 

### Discussion

TL;DR:
**Problem:** How do we handle zooming, if we only _sometimes_ want to zoom in on the y-axis, but mostly want to zoom/pan in the x-axis?
**Solution:** we need to implement the X-zoom and Y-zoom separately.

(See Context below for full breakdown)

**Problem:** the standard zoom functions (Classifier's zoom in/out buttons, and the mouse-wheel action) would not be able to differentiate whether a user wants to zoom in on the X-axis or the Y-axis.
**Solution:** we'll assign one axis (say, the x-axis) the the standard zoom function. The SECONDARY ZOOM, which controls the y-axis, can be built into the ScatterPlotViewer as custom Zoom In/Zoom Out buttons.

Notable things to look out for:
- resizing/repositioning elements of the graph for the secondary zoom (e.g. D3 brushes, axis)
- where to store the separate Y-zoom value (in the Subject Viewer store? locally on the component?)
- separating the custom Y-zoom from the built-in D3-zoom data controller
  - This will make more sense when you see how `d3-zoom`'s `zoom()` object not only listens for zoom behaviour (mouse scrolls, etc), it also _stores_ the current transform values generated by that action.

**Problem...?:** Wait hang on, won't the d3-zoom's default panning behaviour also be a bit wonky if there's a separate y-zoom? Because the `zoom()` object stores pan data in that same `transform` as the x-zoom? 
**Solution...?:** let me math that and get back to you.

### Context
- In the initial version of the TESS Light Curve Viewer - the prototype for generalised scatter plot viewers - we only allow users to zoom/pan on the light curve on the X-axis (time). This is because the full range of the y-axis (brightness) had to be visible no matter which time-range (x-axis) we've zoomed into, since users are comparing changes in brightness over time.
- A standard zoom - i.e. zooming x-axis and y-axis simultaneously, wouldn't work as it would hide brightness values outside a small zoom window.
- However a question arose: what if we DO need to zoom in on the Y-axis anyway? e.g. a chart that averages in y-values of 0 to 10 has one outlier at a y-value of 1000000, causing the chart to be ridiculously "squashed"?

See #400 for more the root discussion.

### Status
Ideas stage

**Comment by srallen** [comment]
I've re-categorized this as Post-TESS since this would be an optimization for supporting either a general scatter plot or other LCV variants.

**Comment by srallen** [comment]
I've implemented this as a configuration using props with a default to zoom both. The constraint functions in vx then return differently depending on the config. See #1256
