### ISSUE TITLE
Navigating to a locale code that includes a hyphen won't load dictionaries

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#4078]
## Package
app-project

## Describe the bug

Although app-project contains translation dictionaries for `zh-cn` and `zh-tw`, the dictionaries will not load when a browser is pointed to an FEM project with `zh-cn` or `zh-tw` in the subpath. However, if the dictionary files and subpath are named `zhcn`, they will successfully load. Note that this is not a character limit bug because `zh-c` does not work either.

## To Reproduce
Visit TESS in zh-cn [locally](https://local.zooniverse.org:3000/projects/zh-cn/nora-dot-eisner/planet-hunters-tess?env=production) or in [production](https://www.zooniverse.org/projects/zh-cn/nora-dot-eisner/planet-hunters-tess).

Note that project-specific translations fetched from panoptes do load successfully. For instance: https://frontend.preview.zooniverse.org/projects/zh-tw/zookeeper/galaxy-zoo

## Additional context

This might not be specifically an FEM issue, it could be caused by PR [285](https://github.com/zooniverse/static/pull/285) to static repo.

**Comment by eatyourgreens** [comment]
You can reproduce the bug locally, so it isn’t being caused by the static proxy. 

NextJS middleware maybe? 🤔

**Comment by goplayoutside3** [comment]
Ah that's a good point! I'll take a look at middleware.js

**Comment by eatyourgreens** [comment]
`zh-cn` isn’t a valid identifier in JavaScript, so that could be a problem if the language code is used as an object property.

When, I refactored task types, I ran into this problem with `simple-dropdown` so there are now workarounds in the code.

**Comment by eatyourgreens** [comment]
`zh-cn` isn’t a valid language code. The language code is `zh-CN`. See https://github.com/i18next/i18next/issues/1467

**Comment by eatyourgreens** [comment]
Using the correct language code should fix this, but means changes throughout our systems where we’ve used the wrong code.

**Comment by eatyourgreens** [comment]
See also https://github.com/i18next/next-i18next/issues/963

**Comment by eatyourgreens** [comment]
This link redirects to `zh-cn` when I try it on my phone. I’m not sure what’s happening there. 
https://frontend.preview.zooniverse.org/projects/zh-CN/zookeeper/galaxy-zoo

The locale is used for links to Talk etc. Are you thinking that both versions of the project URL should work as links?

**Comment by eatyourgreens** [comment]
Altering the API query to use `language.toLowerCase()` would be trivial. 
https://github.com/zooniverse/front-end-monorepo/blob/96ce36c63be21343c20faae8217f5ea4396ae781/packages/app-project/src/helpers/fetchTranslations/fetchTranslations.js#L14

That change would have to be made in the libraries too, where they fetch data from the API. I think that only happens in the classifier, but I could be wrong.

**Comment by goplayoutside3** [comment]
> This link redirects to `zh-cn` when I try it on my phone. I’m not sure what’s happening there. https://frontend.preview.zooniverse.org/projects/zh-CN/zookeeper/galaxy-zoo

The middleware redirect only works locally because the translations dictionaries have to be renamed to zh-CN. When the Chinese dictionary files are renamed to zh-CN and zh-TW, a lowercase query param such as zh-cn is converted to projects/zh-CN/zookeeper/galaxy-zoo.

> The locale is used for links to Talk etc.

We might need to convert to an all-lowercase language code in links to PFE pages.

> Altering the API query to use language.toLowerCase() would be trivial.

Agreed!

**Comment by eatyourgreens** [comment]
>We might need to convert to an all-lowercase language code in links to PFE pages.

I'm reasonably sure that would break PFE, unless we also rewrite its translations code to replace `zh-cn` with `zh-CN`. Here's a test link, which loads the English page:
https://www.zooniverse.org/projects/zh-CN/zookeeper/galaxy-zoo/talk

Probably best to keep lowercase URLs for links.
