### ISSUE TITLE
Remove devcert from app-project and app-content-pages

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#4103]
Related PRs for additional context:
- #2310
- #4004 

Devcert creates a local certificate authority to generate self-signed SSL certificates (more info on how this works: https://github.com/davewasmer/devcert#how-it-works). 

This allows devs to use https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats or https://local.zooniverse.org:3000/about/team with working auth with Panoptes.

However, devcert isn't well maintained. If you do use it to generate a local certificate, it is recommend removing the local CA that it installs, just for the peace of mind of knowing that your browser isn't using an untrusted CA to validate certifcates.

At the moment, I'm not aware of an alternative approach, so this issue can help document and discuss alternative approaches and a path forward towards removing devcert.

**Comment by eatyourgreens** [comment]
We use https://local.zooniverse.org with a self-signed certificate for the dev classifier without devcert. How is that certificate generated?

**Comment by eatyourgreens** [comment]
Answering my own question, it’s magically handled by webpack. 

https://github.com/zooniverse/front-end-monorepo/blob/873aded786cdbad9d2495426a8159bd650e3da62/packages/lib-classifier/webpack.dev.js#L30-L38

**Comment by eatyourgreens** [comment]
How to create a self-signed certificate for Express:
- https://flaviocopes.com/express-https-self-signed-certificate/
- https://medium.com/@invingagan/an-express-https-server-with-a-self-signed-certificate-and-socket-io-42d1f02d4d1a

**Comment by eatyourgreens** [comment]
The production app doesn’t use `https`. That’s interesting. I’ve always assumed that it did. 

https://github.com/zooniverse/front-end-monorepo/blob/873aded786cdbad9d2495426a8159bd650e3da62/packages/app-project/server/server.js#L17-L31

**Comment by eatyourgreens** [comment]
An alternative to self-signed certificates would be to use a signed certificate for `local.zooniverse.org` from the same CA that we use to generate the certificate for `www.zooniverse.org`.

**Comment by eatyourgreens** [comment]
#4108 adds a shell script that generates a certificate and key with `openssl`.

There's also [`next-dev-https`](https://github.com/TobiasMelen/next-dev-https), which modifies `next dev` to support HTTPS. I guess that needs to be kept up-to-date with new versions of NextJS but I haven't looked into it in depth.

**Comment by eatyourgreens** [comment]
https://github.com/jfromaniello/selfsigned looks useful too. It's a native implementation in NodeJS, using [node-forge](https://www.npmjs.com/package/node-forge) and might be easier in day-to-day use than `openssl`.

**Comment by eatyourgreens** [comment]
I think the only open question, for me, is: can we detect whether `server.js` is being run from a local terminal? I think my ideal solution would be to avoid having two `server.js` scripts (one for local builds and one for deploys.)

**Comment by eatyourgreens** [comment]
Bonus: `selfsigned` doesn't ask for root access and require you to weaken security on your work machine.
