### ISSUE TITLE
Must do sign-out process twice 

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#4119]
## Package
app-project?

## Describe the bug

I initially noticed this bug because the FavouritesButton and CollectionsButton are supposed to be enabled or disabled based on whether a user is signed in. Currently if a user is viewing the classify page such as [Poet & Lovers](https://www.zooniverse.org/projects/pmlogan/poets-and-lovers/classify/workflow/21362/subject-set/104809), all four meta tools buttons are enabled. However, if they sign-out the four buttons are still enabled.

Then I realized that refreshing the page after "first" sign-out shows that I'm still signed in to my account. Only after going through the sign-out process a second time and refreshing the page do I know that I'm signed-out for sure.

## To Reproduce

1. Go to [Poets & Lovers](https://www.zooniverse.org/projects/pmlogan/poets-and-lovers/classify/workflow/21362/subject-set/104809) classify page (or any FEM project)
2. Sign in if you're not already.
3. Signed-in UI: All four meta tools buttons are enabled, you can see your stats and recent classifications, your username is in the ZooHeader.
4. Sign out using the ZooHeader.
5. The ZooHeader will show you're signed-out, as does Recent Classifications and Stats. However, MetaTools still shows all four buttons enabled.
6. Refresh the page and everything shows the signed-in UI again.
7. Use the ZooHeader to sign-out again.
8. Refreshing the page will show that you're truly signed out this time.

## Expected behavior

Authentication with ZooHeader menu should work immediately.

### Desktop (please complete the following information):
 - OS: MacOS
 - Browser: Brave Incognito Window or Safari

**Comment by eatyourgreens** [comment]
Signing out should also refresh the classifier and start a new classification. I’m not sure if that’s happening either. Hard to tell on a project that doesn’t use random subjects.

**Comment by goplayoutside3** [comment]
Agreed - we definitely want the classifier to refresh when a user signs-out.

I can't seem to replicate this bug on the Home or About page for any project. It seems to be unique to the Classify page.

**Comment by eatyourgreens** [comment]
I just tried signing out on the burrowing owl project. It gave me the same owl to classify again, but the classifier did seem to reload. 🤔

**Comment by goplayoutside3** [comment]
If you sign-out, and then refresh the page does your username still appear in the ZooHeader? I want to make sure I'm not going crazy and the only user account experiencing that haha

**Comment by eatyourgreens** [comment]
The project app has an explicit sign-out but I don’t think the classifier does. It should inherit the user session from the parent page, via props.

**Comment by eatyourgreens** [comment]
This discussion might be useful. 
https://github.com/zooniverse/front-end-monorepo/discussions/2362

**Comment by goplayoutside3** [comment]
I'll take a look - but I do think this is a bug larger than the Classifier. When a user is signed-in, components such as YourStats, RecentSubjects, and ZooHeader have a specific signed-in state. I can see that signed-in state ever after I've signed-out and then refreshed the page. All of those components are outside of the classifier.

Do you think this a bug related to the app-project store?

**Comment by eatyourgreens** [comment]
Reading back through that, I added a `usePanoptesUser` hook so we could maybe use that to check if you’re logged in. Problem is, we don’t want to hit the auth API on every subject for every volunteer, which I think could happen if we simply add that hook to the Favourites button.

**Comment by mcbouslog** [comment]
I've confirmed the steps up to 5, on Poets & Lovers and [I Fancy Cats](https://frontend.preview.zooniverse.org/projects/brooke/i-fancy-cats/classify/workflow/693?env=staging), but when I refresh after signing out (step 6) the Add to Favorites and Add to Collections is disabled as expected. So I can confirm the general bug.

**Comment by goplayoutside3** [comment]
@mcbouslog what happens to the other components that have specific signed-in UI states when you refresh at step 6?

**Comment by mcbouslog** [comment]
> @mcbouslog what happens to the other components that have specific signed-in UI states when you refresh at step 6?

After initial sign out and after refresh components that have specific signed-in UI states appear as expected (Stats and Recents are gray / show no info).

**Comment by mcbouslog** [comment]
Ok I think I did get the persisted sign-in after signing out and refresh now at least once. But then tried again and didn't. So was able to reproduce all steps noted at least once, but not consistently.

**Comment by goplayoutside3** [comment]
How strange that it doesn't happen every time 🤔 I tried the steps on my phone just now and am able to replicate the bug in a mobile browser too.

**Comment by goplayoutside3** [comment]
Here's an interesting development - I discovered the following behavior on TESS's classify page:

1. Sign-in. Wait 60sec. Sign-out. Refresh and components show that I am truly signed-out.
2. Sign-in. Sign-out immediately. Refresh and components show that I'm still signed-in to my account.

Perhaps this bug has to do with SWR? There are a few places in the /pages directory of app-project that set `revalidate: 60`, but still surprisingly the buggy behavior is unique to the classify page.

**Comment by eatyourgreens** [comment]
The classifier is keyed by user ID here, so it will unmount when you sign out. 
https://github.com/zooniverse/front-end-monorepo/blob/ef4d5d4075711c859e86420bb9141faa374a5c84/packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js#L94

**Comment by mcbouslog** [comment]
The MetaTools use the active upp, maybe the related upp store needs `self.active = undefined` in the [related `clear` action](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/store/UserProjectPreferencesStore/UserProjectPreferencesStore.js#L19-L22).

**Comment by eatyourgreens** [comment]
`self.resources.clear()` will remove the active resource. 

Is that store cleared when the classifier unmounts and remounts? 

The store is a global variable, so it will persist in the open tab after the classifier unmounts.

**Comment by eatyourgreens** [comment]
I think Mark’s right that the stored user preferences are persisting in the global store after you log out. 

However, I’d expect them to be cleared when the classifier mounts and tries to request UPP without a user session. Maybe that request doesn’t happen when there’s no user.

**Comment by mcbouslog** [comment]
If I change [this line in Classifier](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/Classifier.js#L59) from `reset` to `clear` it clears the UPPs when I log out and disables the MetaTools Add to Favorites and Add to Collections, however, if I then sign back in it doesn't re-enable those same Add tos like I'd expect. I think we're getting close to something (in Classifier checking/loading of UPP and in UPP store) though.

**Comment by eatyourgreens** [comment]
This is the block of code in the classifier that handles user sessions. `upp` will be null when we can’t get a bearer token from Panoptes Auth. 

https://github.com/zooniverse/front-end-monorepo/blob/ef4d5d4075711c859e86420bb9141faa374a5c84/packages/lib-classifier/src/components/Classifier/Classifier.js#L52-L69

**Comment by eatyourgreens** [comment]
>however, if I then sign back in it doesn't re-enable those same Add tos like I'd expect. 

You haven’t reset the store loading state, so you shouldn’t expect those buttons to change. 

To be honest, I find the classifier resource stores very hard to debug. The MobX docs do warn against handling API requests in the store, and that might have been a mistake for UPP. I made a start on removing them from the store, which is why UPP now use a data-fetching hook.

**Comment by eatyourgreens** [comment]
@shaunanoordin might have thoughts about storing API loading state in global state too, based on experience with ASM. 

I find tracking request loading state with hooks much easier to reason about.

**Comment by eatyourgreens** [comment]
The project app persists the store when you leave and return, so that we aren’t constantly hitting the Panoptes Auth API when you leave to go to Talk and come back. 

However, the stored user should still be cleared when you sign out.

**Comment by eatyourgreens** [comment]
If I log out immediately after signing in (mobile Safari), the Your Stats box rerenders to say ‘You are signed out’ but the subject viewer buttons are disabled when the classifier rerenders. 

The classifier does unmount though. There’s a brief gap when it reloads the subject.

**Comment by eatyourgreens** [comment]
This might be useful for debugging the project app, at least. `panoptes-user`, in session storage, is a snapshot of the current user when logged in and when logged out.
<img width="699" alt="Screenshot of browser session storage in Firefox dev tools, showing the contents of the panoptes-user key." src="https://user-images.githubusercontent.com/59547/212116474-2ca7dcde-9664-41c5-9bd3-f92ed8da86a1.png">

**Comment by shaunanoordin** [comment]
### Dev Notes

**Test 1: Base Test** 

I tried replicating the issue, based on the [described steps.](https://github.com/zooniverse/front-end-monorepo/issues/4119#issue-1529858976)

- I can confirm that I **can** replicate the issue on macOS + Chrome 108 (Incognito)
- If I sign in on the Classify page as zootester1, and then sign out...
  - The user details in the Zoo header (part of app-project) indicate I'm logged out
  - ❗ The Meta Tools (favourites, add to collection, etc) indicate that _I'm still logged in._

I can confirm the basic premise of this issue, and I have little more to add to the current investigation path on this, except for this oddity...
- if you're logged in and add a Subject to your Favourites,
- and then log out,
- ❗ the Subject _still_ looks like it's in your Favourites, _even if the button is disabled_
    <img width="509" alt="Screenshot 2023-01-13 at 01 40 18" src="https://user-images.githubusercontent.com/13952701/212151465-58592a57-6c63-4e91-98bc-649b9035e4f9.png">
- ❗ and if you login as _another user,_ the Subject _still_ looks like it's in your (or _someone's_) Favourites.

I didn't fully keep track of wtf actually happens with favouriting/unfavouriting when you're either logged out or logged in as a different user; I might look into this later.

**Test 2: Quick Talk**

QuickTalk is another system that 1. is based in lib-classifier and 2. requires knowledge of the current logged-in user. I thought I'd dig into this to better understand how lib-classifier handles the user data.

- The QT gets the user via [usePanoptesUser()](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/hooks/usePanoptesUser.js) in [QuickTalkContainer](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js)
  - (Side note: [usePanoptesAuth](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/hooks/usePanoptesAuth.js) is also related) 
  - (Question for self: how & when/where do the metatools get user? Compare and contrast)
- usePanoptesUser uses `useSWR()` which 1. _revalidates_ (i.e. checks if the user is still logged in or not) only on _certain conditions,_ but 2. those conditions may not map 1-to-1 with the state of the user in app-project.

Let's test this. Testing steps, using macOS + Chrome in an Incognito window:

-  Open the Classify page of a project with QuickTalk enabled. (example: [staging Test Project 2022](https://frontend.preview.zooniverse.org/projects/darkeshard/test-project-2022/classify/workflow/3581?env=staging))
  - You should be not-logged-in.
- Open the QuickTalk panel. (Click on the little "chat bubble" icon on the lower right)
  - The panel should say "Please login to post a comment". This is a good visual indicator of "does usePanoptesUser() think I'm signed in?"
- Sign in as `zootester1` (or whatever)
  - Page should "refresh", though Classifier might still show same Subject?
- Open the QuickTalk panel.
  - You should now see a form that allows you to post comments.
  - (Try posting a comment, if you feel like it.)
- Sign out.
  - Page should "refresh", though Classifier definitely still shows the same Subject
  - QuickTalk panel should have closed itself.
- Open the QuickTalk panel.
  - ❗ The "post comment" form is still visible, despite the user having logged out
- Attempt to post a comment via the form.
  - ❗ **You can actually still post a comment as zootester1**
  - This can be confirmed by opening the link to the Subject Discussion on Talk (NOTE: don't forget to append `?env=staging` to the Talk URL, if you're using the example project above.)
- View another window/tab, then return.
  - **The "post comment" form should now disappear, indicating that the code has now finally correctly identified that you've logged out.**
  - This is in line with _one of the conditions_ that triggers useSWR: the window losing focus and then regaining focus, I believe.

Main takeaways:
- For QuickTalk, useSWR isn't triggering when _I thought it should._
- Which, in retrospect, does make sense, as a change of state (user logout) in an external component/super-component (app-project) probably might not trigger any of the conditions (e.g. window refocus, component re-render/update) (wait, not even component re-renders? I thought the Classify page flashes a re-render when you log out. Shaun, check this) that SWR listens for. (Double-wait, Shaun, why does SWR listen correctly on login then?)

Note 1: At the moment I'm still trying to figure out of it this is part of this issue, related to this issue, or a new spore of madness that I should document this separately. Blargh.

Note 2: prior to using useSWR, the QuickTalk would double-check the logged-in user (call the `/me` endpoint) _at almost every step of posting a comment._ SWR is supposed to reduce the number of checks needed.

Note 3: I actually have a video of this, but accidentally captured a bit too much private login info while I was at it, whoops. Double blargh.

**Comment by mcbouslog** [comment]
Maybe the problem is related to the user getting cleared in the app-project user store before auth clears the user. 

On sign-out 
1. the app-project user store updates/clears, 
2. the app-project/ClassifyWrapper `key` changes to 'no-user' and 
3. the lib-classifier/Classifier refreshes

lib-classifier/Classifier gets the user with `const user = usePanoptesUser()` and it appears after sign out it's still getting a user (which is consistent with "Signed out" logging to the console after logs I've added to lib-classifier/Classifier).

If I refactor https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js#L13-L27

with

```
await auth.signOut()
  
  user.clear()
  // resetting the alreay seen subjects during the session tracking should move
  // once we refactor the UPP and User resource tracking in the classifier
  // Current implementation in classifier is possibly buggy (see discussion https://github.com/zooniverse/front-end-monorepo/discussions/2362)
  // likely a user id prop will be passed to the classifier and that will be reacted to with an effect hook
  /// which would reset the subject already seen tracking
  // I needed to guarantee that this happened on sign out only so that's why this is here for now
  const seenThisSession = (window) ? window.sessionStorage.getItem("subjectsSeenThisSession") : null

  if (seenThisSession) {
    window.sessionStorage.removeItem("subjectsSeenThisSession")
  }
  ```
  
  It appears to disable the metatools on sign-out as expected, but this is all very fresh.

**Comment by eatyourgreens** [comment]
The user context could be passed into the classifier as a prop, like the project context is at the moment.

**Comment by eatyourgreens** [comment]
#4131 refactors `usePanoptesUser` to subscribe to changes in the user session with `auth.listen`.
