### ISSUE TITLE
Text from subject viewer - Restyling to match other FEM subject toolbars

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/front-end-monorepo#4166]
## Is your feature request related to a problem? Please describe.
The current design for Text from Subject viewer should be restyled to match the new Flipbook viewer FEM styling.

## Describe the solution you'd like
Review the below screenshots for more details.

## Additional context
<img width="1055" alt="Screen Shot 2023-01-23 at 9 03 47 AM" src="https://user-images.githubusercontent.com/89043489/214073253-126c2099-6be0-4a68-83ef-42ab5f97c5d4.png">

The toolbar directly below the subject image should now contain a white area for thumbnails and icons. Thumbnails should correspond to the subject image (similar to Flipbook viewer), and a 'text' icon (to denote an OCR text output is being displayed). These are accompanied by a Previous and Next button so the volunteers can switch between views. These buttons should have the same functionality as Flipbook viewer (https://github.com/zooniverse/front-end-monorepo/pull/3972). 

<img width="1055" alt="Screen Shot 2023-01-23 at 9 12 28 AM" src="https://user-images.githubusercontent.com/89043489/214075357-80be056d-cc99-4717-b3ad-67d02d9a9157.png">

**Comment by seanmiller26** [comment]
Responsive handling should also be similar to Flipbook viewer:

<img width="576" alt="Screen Shot 2023-01-23 at 10 06 28 AM" src="https://user-images.githubusercontent.com/89043489/214089128-815cacd6-acd0-4d20-accf-bfc37b9e7d57.png">

'Next' and 'Previous' are omitted, icon sizes are reduced, etc.

**Comment by mcbouslog** [comment]
@seanmiller26 - with the image and text viewer, there'll only ever be one image and one text file (2 items), so maybe the previous and next buttons are redundant? I don't have a strong opinion either way, just noting/wondering.

**Comment by seanmiller26** [comment]
There's three reasons to keep them:

1. To be consistent between different tools - Flipbook and Filmstrip both make use of the arrows.
2. Another accessibility (or just a general) option to tab through the images besides clicking on the thumbnails.
3. I could see, at some point in the near or far future, a use case for more than 1 page-worth of OCR and text correction.
