### ISSUE TITLE
Add 404 pages for projects

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/front-end-monorepo#4257]
## Describe the solution you'd like
All 404 pages should feature a random background from the provided [Images](https://github.com/zooniverse/Design-Resources/tree/main/404%20Images) folder with a black overlay at 50%. The logo is found in the [Logo](https://github.com/zooniverse/Design-Resources/tree/main/404%20Logo) folder. Various screen size examples below: 

<img width="533" alt="Screen Shot 2023-02-10 at 1 59 25 PM" src="https://user-images.githubusercontent.com/89043489/218186375-57252766-76af-45c5-a31b-0cc8778ca83a.png">

Fluid responsiveness is preferred but breakpoints are also acceptable. See these annotated screenshots for more detail:

<img width="994" alt="Screen Shot 2023-02-10 at 12 19 32 PM" src="https://user-images.githubusercontent.com/89043489/218168300-4d6393a1-f610-42dc-a5dd-d97e95c319a5.png">

<img width="992" alt="Screen Shot 2023-02-10 at 12 19 52 PM" src="https://user-images.githubusercontent.com/89043489/218168303-d33ea08e-bd07-4faf-a5cb-9a4a01b7da42.png">

**Comment by seanmiller26** [comment]
I would recommend this solution for old inactive workflows https://github.com/zooniverse/front-end-monorepo/discussions/2445

> From a bookmarked Classify page

1. If workflow, subject set, etc are still active
- Go directly to classifying subject, or open a modal as described above

2. If part of the path is retired
- Redirect to project home page with small popup explaining that the classify page is no longer active and asking to choose a different workflow, etc. [InVision](https://invis.io/9WNF9M73AEN#/443437830_1_Choose_Workflow_Copy)

![FEM Workflow not available](https://user-images.githubusercontent.com/89043489/219455825-3ba34665-8a74-4ee6-bb24-721d605db574.png)

**Comment by sumitshinde-84** [comment]
i would like to work on this issue , can you please assign it to me?

**Comment by goplayoutside3** [comment]
Just going to link the new Figma link to these page designs: https://www.figma.com/file/ZuYDEMK56dlnvasBAa5jNB/404-Pages?type=design&node-id=0-1&t=UCpTlp4RRcI44VfE-0

**Comment by seanmiller26** [comment]
@kieftrav updated Figma designs here: https://www.figma.com/file/ZuYDEMK56dlnvasBAa5jNB/404-Pages?node-id=101%3A70&mode=dev

Be sure to select the Design Documentation page on the left menu. 

And just to resurface this discussion from earlier: https://github.com/zooniverse/front-end-monorepo/issues/4257#issuecomment-1433532400
