### ISSUE TITLE
Query params don't make sense when requesting a specific resource

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#429]
Package: lib-panoptes-js
https://github.com/zooniverse/front-end-monorepo/blob/5ec9b1b1935dbb75a51d606defa36a17d162efd8/packages/lib-panoptes-js/src/resources/projects/rest.js#L24
`queryParams` here doesn't make sense, since we're requesting a specific resource by ID.

API GET requests should be either `/projects/1234` (returns project 1234 or 404) or `/projects?{searchParams}` (returns an array of projects that match the search parameters.)

**Comment by srallen** [comment]
Projects can take the `include` query param. The naming also makes it clear that this is what is passed on to superagent's `query` method.

**Comment by eatyourgreens** [comment]
Good point. `admin=true` could be added to any API call too.
