### ISSUE TITLE
Design: Classifier's Annotate Button should look like a pencil ("edit" icon)

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#4435]
## UI Enhancement

Package: `lib-classifier`
Context: idea brought up during front-end call today

On the Classifier's Image Toolbar, the Annotate Button (which indicates that users can make drawing annotations on the Subject) looks like this:

<img width="51" alt="image" src="https://user-images.githubusercontent.com/13952701/230438934-ddbe6e0c-b622-450c-a572-4dac6eea6bfe.png">

But maybe it should look like this?

<img width="64" alt="image" src="https://user-images.githubusercontent.com/13952701/230438993-4c4e09eb-0cd9-4b04-9f96-eab79d123598.png">
_(Source: Grommet "Edit" icon)_

### Dev Notes

I can very easily swap [AnnotateButton's](https://github.com/zooniverse/front-end-monorepo/tree/master/packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton) [Pointer Icon](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/PointerIcon.js) , but I need the appropriate SVG.

@seanmiller26 do you have a pencil SVG of size 32x32 we can use? I'm not sure why we're not using [Grommet Icons](https://icons.grommet.io/?s=edit), nor for that matter, where the original SVGs for these FEM buttons ([eg1](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInIcon.js) [eg2](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetIcon.js)) came from. 🤷 

### Status

Low priority, but should be a minor effort for something - actually, if you think about it - makes a lot of sense.

**Comment by seanmiller26** [comment]
Thanks for searching for that icon. I found a slightly more minimal version which should hold up better at smaller sizes. I'm uploading it here in 2 sizes. One at 32px and one at 20px (which can then be put into a 32px viewbox). I believe that's how we use these icons, but let me know if you need it some other way.

<img width="345" alt="Screen Shot 2023-04-06 at 11 50 31 AM" src="https://user-images.githubusercontent.com/89043489/230444452-a015e59c-aa2c-4ce0-baa1-c12e784701ea.png">

![Edit Icon 32px](https://user-images.githubusercontent.com/89043489/230444233-4f80a1c9-0c75-4375-97f1-63f2edcfa22e.svg)

![Edit Icon 20px](https://user-images.githubusercontent.com/89043489/230444230-a4dda30f-8073-469f-ac8a-026265069ecb.svg)

**Comment by shaunanoordin** [comment]
Thanks Sean! 👍 

I've made the changes (PR coming up soon for you to review), but I want to make some notes here for future me:

OK, it turns out that our FEM ImageToolbar SVG icons use **fills** instead of **strokes,** despite the icons being _lines_ with a lot of inner empty space? (Specifically, fill=(black or white depending on hover), stroke=transparent)

_Below, I've set the SVG value of fill=blue for clarity. Turns out those lines are actually fills!_
<img width="60" alt="image" src="https://user-images.githubusercontent.com/13952701/230458996-0ffd4483-d61b-419f-9cb0-fcc1cb7d511f.png">

_This is what happens when I replace the "Arrow" icon with the "Pencil" icon; the pencil gets filled in, which is not what we want._
<img width="50" alt="image" src="https://user-images.githubusercontent.com/13952701/230460338-4ed49bb0-4a95-4c84-94c8-cd9580e2b4b6.png">

Fortunately, there's a simple tool for converting "SVG stroke/lines to SVG fill/paths", found [online](https://iconly.io/tools/svg-convert-stroke-to-fill) and with a [library](https://github.com/oslllo/svg-fixer) to boot. 👌 I've already done the conversion for the pencil icon.

I'm assuming the decision to use fill instead of stroke was made to ensure that, if the icon was blown up to large sizes, the ratio of negative-space-to-positive-space would remain consistent? 🤷‍♂️ Ah well.

**Comment by seanmiller26** [comment]
@shaunanoordin what are your thoughts on changing the cursor to this icon when selected? Of course, willing to have a wider discussion on Slack, but just wondering

**Comment by shaunanoordin** [comment]
For the record, Sean & me had a chat about cursors on Slack today. The discussion about how we use mouse/pointer cursors in Drawing Tasks has now become its own thing: please see #4456
