### ISSUE TITLE
Classifier isn't getting the correct env

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#444]
**Package**

app-project

**Feature or Issue Description**

- Running `npm run dev` sets the `PANOPTES_ENV` environment variable to `staging`. 
- When firing up `http://localhost:3000/projects/brooke/i-fancy-cats/classify`, the page errors out with a MST error (can't resolve resource). 
- Adding the `?env=staging` parameter fixes it.

The `PANOPTES_ENV` value can't be being passed through to the classifier, and for some reason it's defaulting to the production env rather than staging.

Also, error handling / logging needs to be improved so we provide an actual record of where the classifier has got to. That might need to go in a separate PR though

**Comment by rogerhutchings** [comment]
oh right https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/webpack.dist.js#L8

**Comment by srallen** [comment]
We need a development build configuration.

**Comment by rogerhutchings** [comment]
Also true, but I think it may be better to change the client to accept the API URL as a parameter, and move the config to the consuming app. I know it would lead to a lot of changes, but it would actually   prevent this from occurring, and mean that the desired endpoint could be set as environment variable across the whole app (server and client side)

**Comment by rogerhutchings** [comment]
Fixed by #482

**Comment by rogerhutchings** [comment]
Nope, this isn't fixed - the panoptes env parameter is correct in app-project, but still isn't correctly being picked up by the classifier (presumably because it's still set at build time). Soooooo I'm going to keep the env config in a store, and pass the API url to the classifier as a prop.

**Comment by eatyourgreens** [comment]
This seems to be fixed now. I'm able to test staging projects locally without adding `env=staging` to the URL.
