### ISSUE TITLE
Sentry v7.47 bugs related to sign-in and classifier loading

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#4441]
## Package
app-project
app-content-pages

## Describe the bug

First reported by Cliff in Slack: https://zooniverse.slack.com/archives/CANKLB50E/p1680894101093009

Sign-In Bug:
    -Scenario 1: I open a fresh browser window, I sign-in to Zooniverse while viewing a PFE project such as https://www.zooniverse.org/projects/zooniverse/gravity-spy, then visit its FEM preview url https://frontend.preview.zooniverse.org/projects/zooniverse/gravity-spy and the UI shows I am not signed-in. The browser console says `TypeError: Cannot set properties of undefined (setting 'Content-Type')`. When I try to sign-in, I receive the error message `Cannot set properties of undefined (setting 'Content-Type')` in the sign-in modal or sometimes `undefined is not an object (evaluating o.request_headers[n]=r)` in the sign-in modal.
    -Scenario 2: I open a fresh browser window, I am not signed-in to Zooniverse at all. Then immediately visit a FEM preview url https://frontend.preview.zooniverse.org/projects/zooniverse/gravity-spy and try to sign-in. I receive the error message `Cannot set properties of undefined (setting 'Content-Type')` in the sign-in modal.

Other buggy behavior:
    -For any FEM project on frontend.preview: Visit TESS’s FEM preview URL [https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess](https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess) and click on /classify. The classifier does not load.

Also noting that all of the above scenarios are replicable if trying to sign-in to a project with `?env=staging` as well. Such as https://frontend.preview.zooniverse.org/projects/brooke/i-fancy-cats?env=staging.

## Expected behavior

Sign-in should work for any Zooniverse project whether on PFE, FEM, staging, or production. The FEM classifier should always load for a project that has workflow data.

## Screenshots
![error1](https://user-images.githubusercontent.com/23665803/230677550-91e3d90f-b79c-4d88-b59b-25ca5f0fa30e.png) ![error2](https://user-images.githubusercontent.com/23665803/230677552-f6783993-c593-4f22-b60f-c74a74f30884.png)

## Additional context

Determined that these bugs are caused by #4433, #4434, #4437.

## Steps during investigation

Looking at wepback bump
    -I ran FEM production build locally (`yarn start`) on the commit belonging to Wednesday’s production-release tag. This is one commit prior to merging dependabot’s webpack bump to 5.78.0. I can open a fresh browser window, visit [https://www.zooniverse.org/](https://www.zooniverse.org/) and the UI shows I’m signed-out. I can successfully sign-in. In the same browser window I view TESS locally, and the UI shows I’m signed in. I can sign-out and then sign-in again without issue while viewing TESS locally.
    -I ran FEM locally on dependabot’s webpack bump branch, and repeated the steps above. I did not experience any of the bugs. Also, the version bump to webpack is for a dev-dependency in lib-classifier which makes it less of a culprit for bus we’re seeing on a deployed production build of FEM on frontend.preview.

I’d also like to note that on Thursday while demoing the separate frames view, I visited my FEM test project while signed in successfully to show what flipbook looks like on frontend.preview: https://frontend.preview.zooniverse.org/projects/goplayoutside3/fem-flipbook-viewer/classify

Next, I ran FEM locally on the commit directly prior to bumping @sentry packages from 7.46 to 7.47. I did not experience the bugs.

I ran FEM locally on dependabot branch `dependabot/npm_and_yarn/sentry/tracing-7.47.0` and encountered all of the bugs above.

**Comment by goplayoutside3** [comment]
🚫 ⚠️ Note that Sentry packages version 7.47 deprecates `Integrations` methods that were added as performance tracing for app-project in https://github.com/zooniverse/front-end-monorepo/pull/4394. 🚫 ⚠️  This must be taken care of before bumping Sentry packages.
![image](https://user-images.githubusercontent.com/23665803/230678879-eacd7a16-fdc7-4712-9f54-12cafe17b0d4.png)

**Comment by eatyourgreens** [comment]
`Integrations` isn’t the problem. PFE staging is also on 7.47, with browser tracing, and sign in works there. 🤔
https://master.pfe-preview.zooniverse.org/

**Comment by eatyourgreens** [comment]
This is the 7.47 setup code in PFE:
https://github.com/zooniverse/Panoptes-Front-End/blob/c4bbac732d32abf91b7ac208f11c29cdada39043/app/lib/init-sentry.js#L1-L16

**Comment by eatyourgreens** [comment]
I think the problem might be that this script is still on v7.45.
https://github.com/zooniverse/front-end-monorepo/blob/1d47030621025382715ede1d53381f3e8ef0b421/packages/app-project/pages/_document.js#L82-L88

**Comment by eatyourgreens** [comment]
Closed by #4445.
