### ISSUE TITLE
Design: Classifier's Annotate Button should only appear for Drawing Workflows

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#4454]
## UI Enhancement

Package: `lib-classifier`
Follows: #4435, #4436, and discussions with @seanmiller26 

On the Classifier's Image Toolbar, the Annotate Button button has no practical function for _Workflows without Drawing Tasks._

Current behaviour:
- The Annotate button is always visible on the Image Toolbar
- _When the Classifier loads,_ the Annotate button is always selected by default.

_Screenshot below: a non-Drawing Workflow shows the Annotate button, selected_

<img width="349" alt="image" src="https://user-images.githubusercontent.com/13952701/231199870-471ae1d8-b8da-481b-867d-3c44f67b6d9f.png">

New behaviour that we want:
- If a Workflow has NO Drawing Tasks...
  - The Annotate button should be hidden
  - The Move button should be selected by default
- If a Workflow has ONE OR MORE Drawing Tasks,
  - The Annotate button should be visible
  - The Annotate button should be selected by default
  - ⚠️ This would be true even for multi-Task branching workflows. So for example, if the first task is a branching Question Task: "Do you want to draw anything? Yes -> (go to Drawing Task) No -> (submit)", then the Annotate button would still be visible and selected by default, even if the volunteers never ends up doing a Drawing Task (tagging @seanmiller26 to confirm this)

_Screenshot below: a non-Drawing Workflow shows the Move button, selected. The Annotate button is not available._

<img width="350" alt="image" src="https://user-images.githubusercontent.com/13952701/231200321-37fb8dc3-1e19-45a6-a02e-17dd687354c1.png">

_Screenshot below: a Drawing Workflow shows the Annotate button, selected._

<img width="345" alt="image" src="https://user-images.githubusercontent.com/13952701/231200127-4a50aed0-9735-4a58-9bd7-ff367549b239.png">

### Dev Notes

- [ ] ⚠️ When implementing, check that the "hasDrawingTask()" function correctly checks Combo Tasks.
- [x] ❓ Sanity check: does the selected Annotate/Move button reset when you load a new Subject? (UPDATE: answered.)
  - In PFE, we always reset back to Annotate mode whenever a new Task (Step) renders.
  - In FEM, the selected Annotate/Move button persists when a new Subject loads. i.e. the "default selected button" ONLY matters _when the Classifier loads._

@seanmiller26 this is a bit of an oddity; it seems to be a very small difference in behaviour, but I'm not sure if it's intended or not. (No harm either way, as far as I can tell.) Still, I thought it might be worth noting, since PFE's small undocumented _"automatically switch back to Annotate mode when changing Tasks"_ behaviour seems similar to PFE's also small and also undocumented _"if you click on the Subject Image when there's no Drawing Task, automatically switch to Move mode"_ behaviour that we were just talking about.

_Video below: "reset to Annotate mode" behaviour on PFE version_

https://user-images.githubusercontent.com/13952701/231237188-f9610d05-a5c5-4aed-a9b5-a3522ef4acef.mov

_Video below: "persist selected mode" behaviour on FEM version_

https://user-images.githubusercontent.com/13952701/231237164-918648ae-147d-42ef-a679-2ebc83b92e72.mov

### Status

For the sake of a coherent UI, this enhancement should be addressed before #4436 gets merged.

**Comment by eatyourgreens** [comment]
There’s also `workflowSteps.findTasksByType(type)`, which does much the same thing for any task type. 
https://github.com/zooniverse/front-end-monorepo/blob/fb46fba683181e2c523e913a46c3e2f20eb94b01/packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js#L51-L63

Side note: it would be useful to document these interfaces somewhere.

**Comment by seanmiller26** [comment]
To address your points:

> If a Workflow has ONE OR MORE Drawing Tasks,
The Annotate button should be visible
The Annotate button should be selected by default
⚠️ This would be true even for multi-Task branching workflows.

Correct, we would show the annotate button in this case. Also not positive on how detecting a drawing task works if it isn't the first task, but that should be the intended behavior.

I like the functionality in FEM of remembering the tool choice when going to the next subject. It would be great if we can match that in PFE, but if not, not the biggest concern.

**Comment by shaunanoordin** [comment]
Related: #3093

Notably, 3093 argues that certain Image Toolbar items should be hidden _depending on the Subject Viewer._ 4454 argues a similar action, but _dependent on the Workflow._

**Comment by goplayoutside3** [comment]
@kieftrav I think the state of this Issue documents the desired edit to the image toolbar for drawing vs non-drawing. Sean noted above that even if a drawing task is not the first task in a multi-task workflow, the annotate button should still be visible. However, if a workflow has zero drawing tasks, then the annotate button should be hidden.

Here's a list of example projects to consider. Drawing tasks like points, lines, freehand all count as a drawing tasks, and so does transcription. I think the only task type not discussed yet is a data selection task like PH TESS or Black Hole Hunters where a volunteer "draws" by selecting an x-range on a data plot.

- [Black Hole Hunters](https://www.zooniverse.org/projects/cobalt-lensing/black-hole-hunters) (data selection)
- [PH TESS](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess) (data selection)
- [Elephant ID](https://www.zooniverse.org/projects/zookeeper/elephant-id-ey) (mix of drawing/non-drawing)
- [Correct a Cell](https://www.zooniverse.org/projects/willcharlie/etch-a-cell-correct-a-cell) (drawing task)
- [PRINT](https://www.zooniverse.org/projects/printmigrationnetwork/print) (transcription)
- [Daily Minor Planet](https://www.zooniverse.org/projects/fulsdavid/the-daily-minor-planet) (zero drawing tasks, flipbook + separate frames)

FEM live projects [spreadsheet](https://docs.google.com/spreadsheets/d/1X9345vQ_xNX6BJf9_xwVCQCjxjbWWErGmV7Xe8WpHZo/edit#gid=0) for further reference

**Comment by kieftrav** [comment]
@seanmiller26 - following up on the conversation we had regarding permutations of how this feature currently works:

- Workflow that is Drawing => SingleChoice: Annotate button visible always
- Workflow that is SingleChoice => Drawing: Annotate button visible always
- Workflow that is SingleChoice: Annotate button is hidden always
- Workflow that is SingleChoice => MultipleChoice => SingleChoice => Drawing => SingleChoice: Annotate button visible always

If we wanted to change this so that the Annotate button showed a little more contextually, we'd have to make some decisions regarding the two situations when the active Task goes from NonDrawing to Drawing and Drawing to NonDrawing.

**Comment by kieftrav** [comment]
Closed with https://github.com/zooniverse/front-end-monorepo/pull/5932
