### ISSUE TITLE
Classifier: (previous) marks should be non-interactive when not on Drawing Task

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#4467]
## UI Bug

Package: `lib-classifier`
Related: #4456, which documents general cursor behaviour on Drawing Tasks.
Confirmed on 9e25158

On multi-task workflows, when a volunteer is on a _non-Drawing Task,_ then _previous_ drawn mark should be non-interactive.

- Expected: drawing annotations (marks) from Drawing Tasks from _previous Steps_ should still be visible on the Subject, but should not be interactive. (This is the behaviour on the PFE Classifier.) This means:
  - mouse/pointer cursor shouldn't change when on the mark
  - click/drag/etc events on the mark should be ignored
  - the mark should not be able to receive keyboard focus
- Actual: drawing annotations (marks) from Drawing Tasks from _previous Steps_ can have keyboard focus. Moving the mouse/pointer over the mark will show a "grab" cursor, though clicking/dragging still doesn't do anything.

### Testing

Confirmed with macOS + Chrome on a Macbook with a touchpad. (No touchscreen)

Setup:
- Create a simple Workflow with two tasks - T1: Drawing Task with a Circle tool, and T2: Text Task

Testing Steps:
- Open the Workflow in the Classifier.
- In T1, make a Circle mark, then proceed to T2
- In T2, move the mouse/pointer over the Circle mark created previously. Observe what happens.

### Status

Medium priority? Tagging @seanmiller26

**Comment by eatyourgreens** [comment]
You can also test this on any transcription workflow that has two steps eg. [Davy Notebooks](https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/classify/workflow/21979).
