### ISSUE TITLE
Image zoom controls by key don't work in Safari

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#4520]
## Package
- lib-classifier

## Describe the bug
Keying + or - doesn't zoom in or out of an image in Safari

## To Reproduce
0. Open Safari
1. Go to https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/classify/workflow/21979
2. Click the cross-arrow button to go into pan-zoom mode
3. Press the + or - keys
4. See nothing happen

## Expected behavior
Keying + or - should zoom in or out in an image subject viewer, as it does in Chrome, Edge, and Firefox.

**Comment by eatyourgreens** [comment]
By coincidence, I was using Safari this afternoon for something else, and keyboard controls worked fine to pan and zoom an image subject.

The keyboard controls only work if the subject or the image toolbar has focus.

**Comment by eatyourgreens** [comment]
In this case, you need to tab to the button. Safari doesn’t focus controls when you click them, IIRC.

**Comment by mcbouslog** [comment]
Ah interesting! Yes indeed. Thanks for noting! 
I'm having trouble seeing what has focus in Safari.
Hmm, I think I'll close this then. Not entirely satisfyingly resolved, but I think working well enough.

**Comment by eatyourgreens** [comment]
It’s been a few years since I checked, but I think there might be an open WebKit issue for this.

**Comment by eatyourgreens** [comment]
We do call `element.focus()` in the drawing code, so you might also find that keyboard controls magically start working after you add a line to a page in Davy Notebooks. I agree that it’s not ideal.
