### ISSUE TITLE
Classification metadata user_language not updating for current classification

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#4521]
## Package
- lib-classifier

## Describe the bug
- changing the language doesn't update the `classification.metadata.user_language` for the current classification

## To Reproduce
1. Go to https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235?demo=true
2. Click on a different language (French or Spanish)
3. Confirm in `?demo=true` mode
4. Click Done (won't actually save classification, because in demo mode)
5. inspect console logged `classification.metadata.user_language` noting incorrect language

## Expected behavior
- changing the language is reflected in `classification.metadata.user_language` for the current classification on classification completion

**Comment by eatyourgreens** [comment]
I’m 90% sure the classification metadata is created when you start a new classification, so it reflects the language when the subject loads. 

Easy enough to change, though. Have the classification metadata model listen to locale changes with `autorun`.
