### ISSUE TITLE
Multi frame viewer: classifications recording to incorrect frame

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#4543]
## Describe the bug
A report from the Maria Edgeworth Letters project noted volunteers were seeing the 'wrong' transcriptions on 2 subjects, noting that lines from the following page of the letter were appearing on the current page.

## To Reproduce
1. Go to https://www.zooniverse.org/projects/mariaedgeworthletters/maria-edgeworth-letters/classify/workflow/18542/subject/87415922
2. Go to frame 1 (page 2) and click on the 11th annotation from the top (see screenshot below)
![Screenshot 2023-05-01 at 4 38 47 PM](https://user-images.githubusercontent.com/25958358/235536246-41c4a3d0-3e78-42ac-a384-ec056426cc32.png)
3. Go to frame 2 (page 3) and click on the line in the same physical position (see screenshot below) 
![Screenshot 2023-05-01 at 4 40 23 PM](https://user-images.githubusercontent.com/25958358/235536460-f8fc168e-6790-4175-abc9-bf44b1a73343.png)
4. See how classification data from frame 2 (page 3) is appearing on frame 1 (page 2), including physical lines (note mid-page line placement gets really wonky around the middle of frame 1, leading me to believe these annotations were actually drawn on frame 2.

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:
[Freshdesk ticket](https://zooniverse.freshdesk.com/a/tickets/16692)
project ID 15969
workflow ID 18542
reported subject 1: 87415922 (shown in examples above)
reported subject 2: 87415870

## Expected behavior
Annotations are shown on appropriate frames

## Screenshots
See above

### Desktop (please complete the following information):
 - OS: MacOS Ventura 13.3.1
 - Browser: Arc/Chrome 112 on macOS (13.3)

## Additional context
Current speculation is that the classifier was showing the image for frame 2, but recorded the frame as 1 in the classification.

**Comment by snblickhan** [comment]
Assigning @yuenmichelle1 for initial investigation

**Comment by yuenmichelle1** [comment]
Oops apologies for the delay I just saw that this was assigned to me. 

https://caesar.zooniverse.org/workflows/18542/extractors/alice/extracts?subject_id=87415922 it looks like the problem extract is extract id 271400884. frame1 is not heavily transcribed, but there is some bit of a consensus in later classifications (that came after the extract `271400884`); my guess is that the "problem extract" came first and that's why it's showing in the reduction. 

I am going to re-reduce first and if that does not fix it then I will remove the extract and see what happens.

**Comment by yuenmichelle1** [comment]
@snblickhan I removed the problem extract and the reduction looks fine now. Let me know if this happens again.

**Comment by snblickhan** [comment]
@yuenmichelle1 Any chance you happened to catch the time/date that each one was submitted? Np if no, just wondering if there were any similarities between the two situations we could record, in the event that this happens again down the line. Otherwise I'm going to close this issue, as I've passed the outcome along to the project team.

**Comment by yuenmichelle1** [comment]
@snblickhan  Sorry for delay (unsure how I missed your message). Yes classifications should be available on data export if you wanted to pull those. (I can also query related classifications and save them to a csv to send to you so that you have a more concentrated csv). 

Let me know!

**Comment by goplayoutside3** [comment]
@snblickhan okay to close this Issue? Have there been any more reports of incorrectly recorded frame number?

**Comment by snblickhan** [comment]
@goplayoutside3 Yes, fine to close -- no additional reports, just seemed to be a one-off.
