### ISSUE TITLE
Better theme organisation

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#458]
**Package**

all

**Feature or Issue Description**

Our styling has gotten a little haphazard:

- `lib-grommet-theme` includes styling for `lib-react-components` (mea culpa)
- We have a long list of very similar colours in `lib-grommet-theme`
- I'm pretty sure there are string values being used some places for colours
- We use styled-theming, grommet theming and styled components in conjunction with the grommet theme in a pretty inconsistent way

For our post-TESS reorganisation, I'm going to propose that:

- we have a separate colour definitions package
- `lib-grommet-theme` exports a pure Grommet theme, that includes the colour definitions
- Theming for shared components is done by a `theme.js` file in the component dir that looks like this:

    ```
    export default {
        dark: {
            ...
        },
        light: {
            ...
        }
    }
    ```
    
    ...with the component passing in the theme name as part of the object path. Where we need to use styled-components for theming, we have access to the colour definitions and therefore the actual hex codes

**Comment by srallen** [comment]
This was more or less done in #532

**Comment by rogerhutchings** [comment]
shout out to #534
