### ISSUE TITLE
"Don't show again" option for workflow selection pop-up does not work 

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/front-end-monorepo#4804]
## Describe the bug
When a project is using the leveling-up / workflow assignment feature, and a user is classifying on a workflow other than the highest unlocked level (which is allowed, but perhaps the user is unaware they can work on a higher level), a pop-up message is shown offering the option to move to the higher level or stay on the current level. This prompt also includes an option to "Don't show this again this session" to prevent the prompt from appearing again (e.g., on workflow reload or when promoted -- a change to upp.settings.workflow_id).

![popup](https://github.com/zooniverse/front-end-monorepo/assets/2006101/a3562fa9-c1bc-483f-be5e-44e0802da818)

## To Reproduce
1. Sign-in as zootester (where user is configured to be leveled-up to second workflow for Gravity Spy)
2. Navigate to first Gravity Spy workflow: [Level 1: Neutron Star Mountain](https://frontend.preview.zooniverse.org/projects/zooniverse/gravity-spy/classify/workflow/1610)
3. On page load or reload, you should be prompted with pop-up message.  Try clicking on "don't show again" option.
4. After reloading page, you should see pop-up again, showing the "don't show again" option isn't working.

## Expected behavior
Clicking the "don't show again" option should store that information in a session cookie or similar, and the prompt should not be shown again during that session.

## Related Items
#2522, #2523 -- issue and short-term fix related to polling
#2431 -- long-term fix related to polling
#2393 -- closed issue; helpful for understanding expected polling behavior

**Comment by lcjohnso** [comment]
This issue persists, even after #4840 has merged to staging / frontend.preview: ticking the "don't show this again this session" box correctly adds `workflowAssignmentModalDismissed:"true"` to session storage, but if I return to the project landing page, then back to the same not-highest-unlocked workflow, I see the modal again.

However, here is the interesting / telling behavior: after ticking the box and `workflowAssignmentModalDismissed` is set in session storage, if I **reload** the page (note: this action _does not_ clear session storage), then the modal correctly _does not_ appear.

Looks like there could be a caching / not-updated-variable issue that the page reload resolves.

To reproduce:
1. Visit https://frontend.preview.zooniverse.org/projects/zooniverse/gravity-spy in a new window and login as zootester (on prod, where Level 2 is unlocked). Confirm that `workflowAssignmentModalDismissed` is not set in session storage.
2. Visit Level 1, where you are prompted with the workflow assignment modal.  Tick the "don't show this again" box and reply "no, thanks". Confirm that `workflowAssignmentModalDismissed` is now set in session storage.
3. Navigate back to project landing page (https://frontend.preview.zooniverse.org/projects/zooniverse/gravity-spy), select Level 1 again.  Currently, you should be prompted with the modal again, even though `workflowAssignmentModalDismissed` is set.
4. Navigate back to project landing page (https://frontend.preview.zooniverse.org/projects/zooniverse/gravity-spy), reload the page, and confirm that `workflowAssignmentModalDismissed` is still set.  Select Level 1 again. This should result in the workflow loading without showing the modal.

attn: @goplayoutside3

**Comment by goplayoutside3** [comment]
I've got an idea of what's going wrong here, and will get a PR up in just a moment 👍
