### ISSUE TITLE
Styling: "choose a workflow" dialog has overlapping buttons

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/front-end-monorepo#4806]
## Describe the bug
In the case of many workflow options, separated into multiple categories (i.e., in case of leveling-up / workflow assignment: locked and unlocked), the resulting dialog can have overlapping sections / buttons if screen height is small (e.g., ~600px).

Example for single unlocked workflow ("Locked" title is hidden):
![Screen Shot 2023-06-13 at 12 14 39 PM](https://github.com/zooniverse/front-end-monorepo/assets/2006101/f085bfeb-c520-467a-94b5-b2f800951d54)

Example for multiple unlocked workflows (overlapping buttons):
![choose-workflow-popup](https://github.com/zooniverse/front-end-monorepo/assets/2006101/562b7ad4-afb1-4205-9743-e5f3c280c838)

## Desired Solution
Buttons and titles (i.e., locked and unlocked) are displayed such that they never overlap and a scroll bar is used if necessary.

**Comment by lcjohnso** [comment]
cc: @seanmiller26

**Comment by seanmiller26** [comment]
Hmm this one is interesting because a scroll bar is present but everything has still been cramped to fit. My first thought would be to mock-up a 'small choose-a-workflow' modal for mobile views. I can work through this over the next week if you think its worth the effort. The other option is leaving as is and making sure it follows the correct spacing, alignment etc. but would still rely on the scroll bar. That option is more on the front-end team.

**Comment by lcjohnso** [comment]
I assumed that this issue is an implementation bug -- workflow categories didn't account for case of small height for modal and their spacing / arrangement was defined poorly. I'm OK with keeping scroll, I just want the sections & buttons to not overlap.

**Comment by shaunanoordin** [comment]
## Investigation update

I've been able to successfully replicate the issue with the following setup:

- Project: Gravity Spy, on FEM preview, on the base Classify route (with no workflow selected)
  - URL: https://frontend.preview.zooniverse.org/projects/zooniverse/gravity-spy/classify
- Browser: macOS + Chrome 114
  - Incognito window
  - Window size set to 900x520
- User: anonymous

_Screenshot: once the window size goes from "tall enough" (> 520px height) to "short enough" (< 520px), we start to see the "locked workflows" div getting shoved 'under/behind' the "unlocked workflows" div_

<img width="923" alt="image" src="https://github.com/zooniverse/front-end-monorepo/assets/13952701/367b665b-7686-42e1-ac88-4b16952de0bf">

The issue will be more visible at "higher levels", i.e. if a user has a lot of unlocked workflows available, the "short enough" threshold increases so it'll be easier to see the problem.

### Analysis

Basically, something's wonky with the "unlocked workflows" div's flex settings. Actually, maybe the "locked workflows" div as well.

_Screenshot: "unlocked workflow" div (red border) and "locked workflow" div (blue border) are squeezing in to fit the parent container (pink border), DESPITE the fact that all the children are overflowing. Basically, the divs aren't respecting the size of the content (i.e. workflow buttons)._

<img width="925" alt="image" src="https://github.com/zooniverse/front-end-monorepo/assets/13952701/764b6269-bfb2-40a2-b8e1-6bd7d9ba6bbb">

One quick fix is to remove the `min-height: 0px` CSS rule used by both divs, but I'll need to double check that this doesn't eff something else up instead.

_Screenshot: by removing min-height=0px, the two divs respect the size of their contents._

<img width="925" alt="image" src="https://github.com/zooniverse/front-end-monorepo/assets/13952701/434970f5-2c86-49f6-87d9-d3e2c5a4559a">

### Status

Code dive commencing

**Comment by shaunanoordin** [comment]
OK, I've got a fix for this in PR 4821 👍 

Yes, that PR has 267 words to explain _one line of code change._ 👀
