### ISSUE TITLE
Add some Github Checks

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#485]
I'd like to add some more automated checking. After talking with @camallen, I think I'm going to add Travis for running the tests, but I'd also like to do more on code style etc. More research needed...

**Comment by rogerhutchings** [comment]
@adammcmaster Could you add https://github.com/marketplace/wip to this repo to start off with?

**Comment by adammcmaster** [comment]
That should be set up now.

**Comment by rogerhutchings** [comment]
cc https://github.com/zooniverse/front-end-monorepo/pull/487#issuecomment-466361535
