### ISSUE TITLE
Classifier: Subject Queue for logged-in users sometimes fetched twice

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#4875]
## Behaviour Bug

Package: `lib-classifier`
First noted on PR #4848's [review](https://github.com/zooniverse/front-end-monorepo/pull/4848#pullrequestreview-1489300490) (20 Jun)
Confirmed to exist at least from 78c9baf (1 Jun) to 18d65f3 (21 Jun)

If you're already logged in AND start by opening the Classify page, there's a chance the Classifier will send 2x requests to /queued (with the correct header auth, etc) instead of 1x request.

Here's how you trigger the problem:
- Ensure you're logged in as a user (e.g. darkeshard), and ensure you can monitor network connections
- Open the Classify page of a test project [(example)](https://frontend.preview.zooniverse.org/projects/darkeshard/test-project-2021/classify/workflow/20333)
- Observe the number of times /queued is called as soon as the Classify page is loaded
  - Expectation: the /queued endpoint should be hit once (with the user's auth in the headers)
  - Actual: the /queued endpoint is _sometimes_ hit _twice_ (with the correct auth)
- ⚠️ NOTE: keep refreshing the page to see the results, there's a level of inconsistency to triggering this problem.

_Screenshot: the page loads, and the /queued endpoint is hit twice instead of once_

<img width="1257" alt="image" src="https://github.com/zooniverse/front-end-monorepo/assets/13952701/461a1d85-ff69-462b-8462-f63db117ba41">

### Dev Notes

Initial notes:

- The problem is very easy to replicate on localhost development build (as Jim pointed out, this is likely due to React Strict Mode trying to find bugs due to impure renders)
- The problem is harder (more inconsistent?) to replicate - but still possible - on frontend.preview (which uses a production build?)
  - e.g. TESS on frontend.preview and www very very rarely triggers double fetches ; while a rando test project on frontend.preview [(example)](https://frontend.preview.zooniverse.org/projects/darkeshard/test-project-2022/classify/workflow/22164) will trigger double fetches 50% of the time.
  - UPDATE: take my "very very rarely triggers" with a pinch of salt. Jim has confirmed that he managed to trigger the bug on Gravity Spy and Planet Hunters TESS. (See [Slack](https://zooniverse.slack.com/archives/CANKLB50E/p1687364601026659?thread_ts=1687363524.775759&cid=CANKLB50E)) 
- localhost testing shows that the bug exists as far back as 78c9baf at least (that's 1 June), as shown by local testing.

Updates:

- Q: do the number of subjects available from /queued affect how likely the bug is to trigger?
  - A: I can't confirm if this is a factor.
  - Early on (on local dev), my test projects that triggered the double fetch only had < 10 subjects available to the workflow, and they triggered the bug more-or-less consistently. Meanwhile, an actual project like Planet Hunters TESS (also on local dev) almost never triggered. (About 10 refreshes for each test) 
  - However, I've since upped the number of subjects on my test project's workflows (> 20 subjects) and can still see the double-fetch bug happening.
  - And then I took a look at Davy Notebooks...

- Q: what's with Davy Notebooks?
  - A: Davy Notebooks is weird. (This is on production btw, so that's the www URL at the latest 18d65f3 commit.)
  - Let's start by logging in and opening the [root Classify page](https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/classify) (no WF selected)
      <img width="1274" alt="image" src="https://github.com/zooniverse/front-end-monorepo/assets/13952701/b479c458-a5ff-48b4-aca9-fed1d9a592bd"> 
  - If I _switch to_ Workflow 22114 (92% complete, which has >= 10 Subjects), the /queued endpoint is hit exactly once and returns 10 subjects.
      <img width="1280" alt="image" src="https://github.com/zooniverse/front-end-monorepo/assets/13952701/53affc2f-f469-4553-a4c0-ed1ef3ebcbee">
  - If I _switch to_ Workflow 22814 (97% complete, which as exactly 1 Subject), the /queued endpoint is hit _twice_ and returns 1 subject.
      <img width="1276" alt="image" src="https://github.com/zooniverse/front-end-monorepo/assets/13952701/d7c5ec17-76fc-4fbd-b73e-1f23623f9f8c">
  - If I then _refresh_ the page to reload WF 22814... the queued endpoint is never hit. What?
      <img width="1280" alt="image" src="https://github.com/zooniverse/front-end-monorepo/assets/13952701/c4688545-6c23-4a08-b685-702baa2c2e7e">
  - Is this cached? Auto-hydrated from the server side? etc etc

- Q: does the number of Subjects served by the /endpoint affect how likely the bug is to trigger?
  - A: Can you give more specific scenarios? 

- OK, sure. How about... Q: does the project being "finished" (e.g. Planet Hunters TESS) make the bug less likely to trigger? After all, if a project is finished, the /queued endpoint will always serve the same 10 Subjects, so there's some consistency there.
  - A: uuuhhh

- Q: does the user affect how likely the bug is to trigger? e.g. if `darkeshard` has already seen so many Subjects in the test project, perhaps that reduces the pool of Subjects the /endpoint has to offer him?
  - A: uuuhhh

### Status

Requires further investigation

**Comment by eatyourgreens** [comment]
How does this bug affect projects that use prioritised workflows AKA ordered subjects?

Will the second fetch re-introduce an old issue, from Engaging Crowds, where volunteers reported that their subject queue would leap forward by 10 pages.

**Comment by eatyourgreens** [comment]
I've been doing a bit of testing for this, and I think that it can be reproduced by the `onURLChange` effect running twice during login.

https://github.com/zooniverse/front-end-monorepo/blob/bb9b448f2ea41479216bf26ff1129c45837a3d60/packages/lib-classifier/src/components/Classifier/Classifier.js#L83-L90

Maybe there need to be three possible return values from `usePanoptesUser`:
- `null`: not logged in.
- `User` object: logged in.
- `undefined`: still logging in.

**Comment by eatyourgreens** [comment]
This might be fixed by https://github.com/zooniverse/panoptes-javascript-client/pull/212.

**Comment by eatyourgreens** [comment]
Or maybe not. I think #4935 still has this bug.

**Comment by eatyourgreens** [comment]
Definitely fixed by #4803.
