### ISSUE TITLE
Add project home page

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#49]
![project-home](https://user-images.githubusercontent.com/2725841/41460596-3179a458-7085-11e8-9a49-9325113fad9a.png)

**Comment by lancesnider** [comment]
I was tinkering with this this morning and want to double check my plan before I push up any PRs. Following the convention of the classify page, I was going to split each block in this page into its own component. Something like: 

```
<div> 
  <ProjectHeader />
  <ProjectHero />
  <ProjectGettingStarted />
  <ProjectTalkingAbout />
  <ProjectStatistics />
  <ProjectAbout />
</div> 
```

Do you plan to add Storybook or similar? That'd make it easier to test the individual component with different content. 

What's your preference for PR size? Would you expect this to all be done in one big PR or split it into a bunch of bite-sized PRs. For example, I might do 1 PR for the overall structure and another one for each component.

**Comment by srallen** [comment]
Just an FYI for this issue, @beckyrother has a new home page design that we should be using for this.

**Comment by beckyrother** [comment]
Indeed I do: https://invis.io/GAQFBVX9CUN You can use the arrow keys to navigate through various pages I've built out for this project.

**Comment by lancesnider** [comment]
@beckyrother Nice! I really like this version. A couple of questions: 
1. Under `Get started` where it says `Classify`, is that a button, a progress bar or both?
2. On the other progress bar where it says 65%, the white text won't be visible over the gray bar if it's under about 40%. How do you want that to work? How would it work at exactly 50% where its half over the gray background, half over the gradient background?
3. Is there a design for how each of these should look on mobile? 
4. Does that pic with the antelopes go all the way to the edge of the screen, regardless of screen width?

**Comment by beckyrother** [comment]
@lancesnider, @srallen reminded me that there are a few updates I need to make to these pages before they're completely ready for development, so I'll post here when they're ready to go. That said, you can use the controls panel down at the bottom right to see all of the variations I've designed for this page, including mobile and wide-screen views. I've also left a few comments which you should be able to access by turning on Comment Mode from that controls panel. 

Your questions:
1. Both! One of the main goals of this page redesign was to distinguish different workflows' progress – it's possible that the entire project can be nearly finished but one workflow is still at 10% complete. Adding in separate progress bars for each workflow solves this problem. 
2. Good catch, that white text should be black. 
3. Yes, you can find all the variations in the grid tool from the controls panel
4. See above :) 

Thanks so much for jumping in on this!

**Comment by rogerhutchings** [comment]
Also:

- Small PRs, please, I want to keep velocity up and making things easy to review / grok is the best way to do that;
- Some of these components are identical to those used on the Classify page, so there's a PR open (#454) to set that up

**Comment by beckyrother** [comment]
Made updates to the InVision prototype and added some comments regarding the interaction design. Let me know if anything's missing or unclear: https://invis.io/GAQFBVX9CUN, but this should be ready to get started on.

**Comment by rogerhutchings** [comment]
Is there a menu button for narrow widths?

**Comment by beckyrother** [comment]
This should use the same headers and footers as the current site.
