### ISSUE TITLE
temporal tools do not obey maximum number of annotations

### ISSUE THREAD

**Issue by ramanakumars** [zooniverse/front-end-monorepo#4905]
## Package

`lib-classifier`

## Describe the bug
Currently, the temporalPoint and temporalRotateRectangle tools do not obey the maximum number of annotations set in the Project Builder lab. See example of this in [this workflow](https://frontend.preview.zooniverse.org/projects/ramanakumars/tasktest/classify/workflow/24624). However, it does obey the minimum number of annotations (the 'Done' button is grayed-out until there are at least the minimum count)

## To Reproduce
1. Create a workflow with temporalPoint or temporalRotateRectangle
2. Set the minimum and maximum annotations
3. Click 'Test this workflow'

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:
Workflow 24624 is a test bench for this. This bug is mainly applicable to Workflow 21225 for the Solar Jet Hunter project which is planning to go to beta soon with the new temporal tools.

## Expected behavior
The front-end should not allow annotations greater than the the maximum allowed.

## Screenshots
![Screenshot](https://github.com/zooniverse/front-end-monorepo/assets/8140744/fe0a8b30-6c84-4f2a-a39d-0c351de20b57)

### Desktop (please complete the following information):
 - OS: Windows
 - Browser: Firefox
 - Version: 114.0.2 (64-bit)

**Comment by eatyourgreens** [comment]
I can also reproduce this bug on this workflow. 
https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify/workflow/3370?env=staging

**Comment by eatyourgreens** [comment]
The code should be checking `activeTool.disabled` but that check has been removed at some point. 

https://github.com/zooniverse/front-end-monorepo/blob/d53847593299ab2271bf80e97b6a7e0ac4e288cd/packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js#L47-L49
