### ISSUE TITLE
FEM 'Add to Collection' button is non responsive

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/front-end-monorepo#4918]
## Describe the bug
The Add to Collection button does not function. You cannot click it.

## To Reproduce
Chrome browser version 114.0.5735.133 
Project: People's Contest Digital Archive

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:

## Screenshots

https://github.com/zooniverse/front-end-monorepo/assets/89043489/5a335db0-5cc8-4ffa-8258-9233722a5c6f

**Comment by snblickhan** [comment]
Recreated this issue -- clicking "Add to Collections" does nothing.

Desktop 
OS: [e.g. iOS] MacOS Ventura
Browser [e.g. chrome, safari] Chrome 
Version [e.g. 22] 114

Recreated issue on project [PRINT](https://www.zooniverse.org/projects/printmigrationnetwork/print)

Screenshot of error message that appeared in the console when I pressed "Add to Collections" from the classify page:
 
![Screenshot 2023-06-29 at 12 00 54 PM](https://github.com/zooniverse/front-end-monorepo/assets/25958358/2ecc1fda-403f-4ae8-a21c-263151fcb3d4)
