### ISSUE TITLE
Subject preview not showing anything for text location

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#4936]
## Package
- app-project (maybe lib-react-components)

## Describe the bug
For subjects with a first location of type text the subject preview doesn't show anything.
Related [Talk post](https://www.zooniverse.org/talk/14/2983249?comment=4900223).

Live ⚠️ production ⚠️ project for reference - https://www.zooniverse.org/projects/md68135/notes-from-nature-labs

## To Reproduce
1. Go to https://www.zooniverse.org/projects/md68135/notes-from-nature-labs
2. Note the recents section shows the subjects with IDs but blank media

Also applies on classify page "Your recent classifications" section

app-project [SubjectPreview](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.js) component
lib-classifier [Media](https://github.com/zooniverse/front-end-monorepo/tree/master/packages/lib-react-components/src/Media) component

## Expected behavior
The subject preview should show something. If only a text location, maybe the text icon used in frame controls should show. If the subject is an image and text subject, should we preview the first image location instead of a text icon?

## Screenshots
![subjectPreviews](https://github.com/zooniverse/front-end-monorepo/assets/12118751/6714e9a8-f1d4-4365-b4f4-e39957c072b4)

**Comment by mcbouslog** [comment]
@seanmiller26 - what are your thoughts on the following for an initial fix?

project home / talk section
![Screenshot 2023-07-19 at 4 16 03 PM](https://github.com/zooniverse/front-end-monorepo/assets/12118751/79f01d0a-663b-4b8e-8c5c-497bd3e8e7c2)
![Screenshot 2023-07-19 at 4 16 10 PM](https://github.com/zooniverse/front-end-monorepo/assets/12118751/106e8e48-be7b-4a60-ab9c-8db874a4e81e)

project classify page / your recent classifications section
![Screenshot 2023-07-19 at 4 43 56 PM](https://github.com/zooniverse/front-end-monorepo/assets/12118751/80e6b207-c4cd-41ff-8c4e-48d4fd08865d)
![Screenshot 2023-07-19 at 4 44 08 PM](https://github.com/zooniverse/front-end-monorepo/assets/12118751/6712b01e-15af-4bc8-9016-50f36d7e2dd0)

Noting these screenshots include a drop shadow to subject preview cards on the project classify page / your recents section that is not currently present.

**Comment by mcbouslog** [comment]
Changes pictured are from this branch's WIP - https://github.com/zooniverse/front-end-monorepo/compare/text-subject-preview

**Comment by seanmiller26** [comment]
I like it as an initial fix. We should probably think more about data as subjects and what that should look like.

Specific fixes:
Project home / talk section - I'd like the icon to look like its centered vertically. The subject ID throws that off a bit. Can we push the icon up in the frame a little? (if not, good as is)
Project classify page / your recent classifications section - Can the icon be slightly increased in size?

**Comment by mcbouslog** [comment]
The sizing is based on the Grommet t-shirt sizing, previously pictured is `'large'`, here is `'xlarge'`:

![classify_recents_dark](https://github.com/zooniverse/front-end-monorepo/assets/12118751/df3f1575-ba4d-4185-8255-0c6ef880b5ff)
![classify_recents_light](https://github.com/zooniverse/front-end-monorepo/assets/12118751/9ae5dca1-5136-4962-acc7-c0f9a83caa13)
![project_home_talk_dark](https://github.com/zooniverse/front-end-monorepo/assets/12118751/dfb76b9a-f949-4d41-8843-2b84e682c743)
![project_home_talk_light](https://github.com/zooniverse/front-end-monorepo/assets/12118751/81ee80e2-c4cf-48f3-95fe-c864225f302f)

I think the "xlarge" might look a little better? But could be easily convinced either way.

Unfortunately edits per parent component (project home vs classify) would require a lot more customization, not impossible, but I think out of initial scope.

**Comment by seanmiller26** [comment]
> Unfortunately edits per parent component (project home vs classify) would require a lot more customization, not impossible, but I think out of initial scope.

In that case I think you had it right the first time. Let's stick with Large sized icons. Looks good otherwise!

**Comment by seanmiller26** [comment]
Mark and I discussed PFE's media component and how it displays a text as subject. 

<img width="1207" alt="Screen Shot 2023-07-26 at 1 18 26 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/89043489/b94e45aa-e189-4491-9c2b-5a70b11ca2bf">

We may end up matching this styling depending on effort required. Notable changes would be: Left aligned text, restricted height ~200px, and the ability to scroll within the component to see the full text. 

More to follow

**Comment by eatyourgreens** [comment]
For help.zooniverse.org, we dynamically build images of text to use for page banners. 

![Best Practices banner image.](https://github.com/zooniverse/help/blob/gh-pages/assets/images/social/best-practices/1-great-project.png)
