### ISSUE TITLE
Ideas for additional code checking?

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#494]
**Package**

all

**Feature or Issue Description**

cc #485

We could write some scripts for Travis to run prior to running the main test suite:

- Check for `.only` in tests
- Run Standard (although we have some non-compliant syntax, mostly in tests e.g. `expect(true).to.be.ok` evaluates to an expression)

Other ideas?

**Comment by srallen** [comment]
We could add dirty-chai so that `expect(true).to.be.ok()` works.

**Comment by rogerhutchings** [comment]
cc #503

**Comment by rogerhutchings** [comment]
There is an eslint plugin for `no-only-tests` - https://github.com/levibuzolic/eslint-plugin-no-only-tests/. We could move the linter to the root, and use that with https://github.com/standard/eslint-config-standard

**Comment by srallen** [comment]
Coveralls sort of indirectly checks for leftover `only`s because the test coverage dramatically drops when this happens.

**Comment by eatyourgreens** [comment]
I've updated the repo settings to block merges if Travis or WIP checks fail. We can also block merges if coverage decreases too much.

**Comment by camallen** [comment]
You can also run scripts in travis to detect left over only statements in your tests, etc. we use in on the API to check we haven't left any `focus` (same as only) statements:

https://github.com/zooniverse/Panoptes/blob/5789c89c99d024a6e1df8e8f8e459afb6e8accb2/.travis.yml#L14

https://github.com/zooniverse/Panoptes/blob/5789c89c99d024a6e1df8e8f8e459afb6e8accb2/scripts/no_focus.sh
