### ISSUE TITLE
Styling: Featured projects title cards should collapse to a 2x2 grid on med / small viewports

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/front-end-monorepo#4976]
## Is your feature request related to a problem? Please describe.
The Featured Projects title cards wrap to the next line as the browser width decreases. Currently only 1 title card wraps to the next line at a time. This happens on 3 pages: logged out home page, logged in profile page, projects page.

<img width="872" alt="Screen Shot 2023-07-10 at 7 52 27 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/89043489/115be6ab-c6d8-4670-af1b-b9659dac3da1">

## Describe the solution you'd like
Featured Projects title cards should collapse to a 2x2 grid and never to a 3x1 layout.

<img width="818" alt="Screen Shot 2023-07-10 at 7 52 18 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/89043489/ba8daa10-41d1-4af4-86b9-ea5be240f527">

**Comment by goplayoutside3** [comment]
@seanmiller26 Is this on the home page zooniverse.org? If so, that page is handled by the PFE repo

**Comment by goplayoutside3** [comment]
Yes the following are all PFE:
1. Logged out https://www.zooniverse.org
2. Logged in https://www.zooniverse.org
3. https://www.zooniverse.org/projects

**Comment by seanmiller26** [comment]
Transferred to the PFE repo, thanks!

**Comment by seanmiller26** [comment]
Transferred to the PFE repo, thanks!
