### ISSUE TITLE
Add project about pages - research

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#50]
![fireshot capture 9 - emammal about zooniverse_ - https___www zooniverse org_projects](https://user-images.githubusercontent.com/2725841/41460718-7d0c451a-7085-11e8-92c1-56f419816b83.png)

This will need the Pages resource adding to the store.

**Comment by eatyourgreens** [comment]
Note that project page content is localised, and should be requested from the Panoptes translations endpoint eg. https://www.zooniverse.org/projects/y-dot-liefting/snapshot-hoge-veluwe/about/research?language=nl
