### ISSUE TITLE
Intermittent bug: Workflow choices and Classifier aren't displayed

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#5008]
## Package
app-project

## Describe the bug
I'm not sure how to trigger this, but it's possible to load the project app in such a state that neither the classifier nor the workflow selector components are shown to a logged-in user.

## To Reproduce
I've run into this on Gravity Spy. @snblickhan has triggered it on How Did We Get Here? and I think @mcbouslog might have managed to trigger it too.

I think it happens when `appLoadingState` in the project app is never set to 'success', so the workflow selector and classifier are permanently waiting for a user session to sign in.

## Expected behavior
Once authentication is complete, and any user resources are loaded, workflow choices should display on the home page and the classifier should display on the project Classify page(s).

## Screenshots
<img width=300 alt="Screenshot of the Gravity Spy home page, with a white space where the workflow menu should be." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/271c5235-89d0-4fd5-bc1b-3ca807a65ab8">
<img width=300 alt="Screenshot of the Gravity Spy Classify page, with a white space where the classifier should be." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/8919f3ed-7b9b-4872-af12-26da200b9df2" >

**Comment by goplayoutside3** [comment]
Some more bugs and errors for documentation in case they are linked to the same cause:

Intermittently: When running `master` locally with `yarn dev`, I can visit Gravity Spy's classify page while signed in. I sign out and the classifier shows the following:
<img width="1332" alt="Screenshot 2023-07-13 at 2 21 56 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/88911b05-9c05-4c32-a651-02b4d56025f0">



When running `master` locally with `yarn dev`, 1 out of 3 times I view any project's classify page I see an error thrown in the WorkflowStore and no subject or task is shown, such as Gravity Spy:
<img width="942" alt="Screenshot 2023-07-13 at 2 20 16 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/0ba4efc2-ea79-4fce-8e27-6c36133f8412">
Or i-fancy-cats:
<img width="942" alt="Screenshot 2023-07-13 at 2 27 11 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/01183270-54f4-43d1-a6d6-000500dc18b1">

**Comment by eatyourgreens** [comment]
That second error has been happening for a while in development mode. You’ll probably see it if you check out last week’s production release too.

**Comment by eatyourgreens** [comment]
Development mode errors are useful but can we keep this issue focused on errors that have been seen on live projects?

**Comment by eatyourgreens** [comment]
Updated to include pictures of the actual bug, where the home page and classify page both wait forever for app loading status to change to 'success'.
