### ISSUE TITLE
Your Recent Classifications section Add to Favorites button doesn't add subject to project favorites

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#5016]
## Package
- app-project

## Describe the bug
On a project's classify page, in the Your Recent Classifications section, clicking a subject's Add to Favorites button doesn't actually add a subject to your project favorites, but the button appears as it did.

## To Reproduce
1. Go to https://www.zooniverse.org/projects/zooniverse/gravity-spy/favorites/[your username], note if/how many favorites
2. Go to https://www.zooniverse.org/projects/zooniverse/gravity-spy/classify/workflow/1610?demo=true
3. Make demo classification
4. Should have new subject in Your Recent Classifications section
5. Click Add to Favorites, note subject now shows "Added to Favorites"
6. Go to step 1 url, refresh, note subject not actually added to favorites

## Expected behavior
Clicking Add to Favorites should add subject to project favorites.

## Console Error
`Project App MST error: TypeError: Cannot read properties of undefined (reading 'addFavourites')`

**Comment by eatyourgreens** [comment]
`store.collections` is undefined here, because collections and recents are both stored in the user model. 

This line should be using `getParent` to get the user. 
https://github.com/zooniverse/front-end-monorepo/blob/e9962d11ab7f648b4b17165179b06e6aca30a768/packages/app-project/stores/User/Recents/Recents.js#L14

**Comment by eatyourgreens** [comment]
A better solution might be to move that action up the tree, so that it isn’t accessing models outside of its own subtree.
