### ISSUE TITLE
@zooniverse/react-components breaks Storybook

### ISSUE THREAD

**Issue by lancesnider** [zooniverse/front-end-monorepo#502]
## Issue Description

I tried creating a Story for the `ProjectStatistics` component, but when I added it, it messed up the CSS on ALL the stories, not just the new one. 

Here's the warning that I get. 

> vendors~main.195f7e90ed1a9881362e.bundle.js:58446 It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles not rendering properly, errors happening during rehydration process and makes your application bigger without a good reason.

> See https://s-c.sh/2BAXzed for more info.

## The problem package

After some digging I discovered that adding any component that uses `'@zooniverse/react-components'` causes this error. As soon as you remove that, the error goes away. 

## Steps to reproduce

If you want to replicate the error, add this to the existing `Stat.stories.js` 
```
import { SpacedText } from '@zooniverse/react-components'
```
It should still look fine after a hot reload, but if you refresh the page, the styling will be lost.

**Comment by rogerhutchings** [comment]
Just guessing, but I wonder if there's a conflict going on in the webpack config: looks like we have an `externals` block _and_ we using `peer-deps-externals-webpack-plugin`

**Comment by eatyourgreens** [comment]
Is this the same bug that's causing styling problems when ZRC components are rendered in the project app? eg. the lack of styling for the user account menu, or the flash of unstyled content when the app first loads (#327).

**Comment by srallen** [comment]
Storybook uses its own webpack config which can be customized. I think we need to add the aliasing for styled-components to it?

**Comment by srallen** [comment]
I think this can be closed. We have the storybooks deployed to github pages now.
