### ISSUE TITLE
Styling / Accessibility: Refactor Talk thumbnails on FEM to include a gradient

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/front-end-monorepo#5053]
## Is your feature request related to a problem? Please describe.
Currently the SUBJECT ID overlay can be hard to read - especially with certain transcription subjects or similar white background subjects.

<img width="1495" alt="Screen Shot 2023-07-24 at 12 09 25 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/89043489/f8a23a06-0ecf-4d98-9022-2bc8336fc082">

## Describe the solution you'd like
Add a gradient overlay behind the text and in front of the subject image. 5C5C5C 100% opacity at the bottom to 0% opacity at the vertical middle point of the image. This will also match future Recents redesigns.

<img width="1171" alt="Screen Shot 2023-07-24 at 12 31 02 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/89043489/ea12509e-40ca-42bc-ba36-b53764f605ae">

**Comment by goplayoutside3** [comment]
Closed by https://github.com/zooniverse/front-end-monorepo/pull/5940
