### ISSUE TITLE
Test storeMapper functions

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#507]
At the moment, we don't test our `storeMapper` functions ever. However, a broken `storeMapper` can break the app _without_ breaking the tests, since we usually pass the results of those in to the component under test as props.

This would be easy to test - export `storeMapper` as a named function, pass in a mocked store as an argument and see if you get the things out you expect.

**Comment by rogerhutchings** [comment]
cc @eatyourgreens

**Comment by eatyourgreens** [comment]
Makes sense to me. I guess the expectation would be `it should pass, x, y and z as props` and we can catch missing or misspelt props?

**Comment by srallen** [comment]
mobx-react v6 recommends the built in React context API, so we should over time convert to use this and move store connections into a "Connector" component that is the top level parent of a composed component. I tried this out in #1728 and wrote tests for the separate connector component and this worked well.
