### ISSUE TITLE
Update Zooniverse Grommet theme to match designs

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#508]
@beckyrother's designs appear to use multiples of `10px` for spacing; Grommet uses something else, so we need to go through and fix those. Plus it uses px for sizing, so I suggest:

- We add a requirement for setting the font size to `10px` in a consuming app;
- We import the whole sizing block from the Grommet theme
- We use `rem` multiples to set the various sizes in the theme

**Comment by srallen** [comment]
I think we've mostly updated the theme where we have needed to. Do you still want to convert to rem?

**Comment by beckyrother** [comment]
Here's a doc showing spacing throughout, lmk if there are questions about a specific element: https://invis.io/a/PM1A9Z18C9SWY2
