### ISSUE TITLE
Workflow with multiple combo tasks doesn't load

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#5084]
## Package
- lib-classifier

## Describe the bug
A workflow with multiple combo tasks fails to load:
- lab: https://www.zooniverse.org/lab/4312/workflows/24807?femLab=true
- classify page: https://frontend.preview.zooniverse.org/projects/markbouslog/test-project-mb/classify/workflow/24807

## To Reproduce
1. Go to [workflow with multiple combo tasks FEM classify page](https://frontend.preview.zooniverse.org/projects/markbouslog/test-project-mb/classify/workflow/24807)
2. Note tasks don't load
3. Go to [workflow with multiple combo task PFE classify page](https://www.zooniverse.org/projects/markbouslog/test-project-mb/classify?reload=0&workflow=24807)
4. Note tasks load

## Expected behavior
Tasks load.

## Additional context
With steps/pages editor this won't be an issue, can use steps/pages editor instead.

**Comment by eatyourgreens** [comment]
Workflow 24807 has a `steps` object, so it will ignore the combo tasks and use the steps that were added by the project builder.

<img width="300" alt="Screenshot of workflow 24807 in the dev console, showing that it has a steps object with 5 steps." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/f3c810d1-aec4-4082-b489-745c0a638a1e">

**Comment by eatyourgreens** [comment]
When this happened to me, it was because projects with transcription enabled automatically add `workflow.steps` to all workflows.
https://github.com/zooniverse/Panoptes-Front-End/issues/6585

**Comment by eatyourgreens** [comment]
I turned off the transcription task for your test project, then built a combo task workflow. This works:
https://www.zooniverse.org/projects/markbouslog/test-project-mb/classify?reload=0&workflow=24812

This is a really annoying bug in the project builder.

**Comment by eatyourgreens** [comment]
More annoying because you can't delete `workflow.steps` once it's been created, except directly via the Panoptes API.

**Comment by mcbouslog** [comment]
Thanks @eatyourgreens ! Interesting and indeed frustrating.

I think I'm only seeing the first step / 2 combo tasks on https://frontend.preview.zooniverse.org/projects/markbouslog/test-project-mb/classify/workflow/24812 ? I don't see the second step / 3rd combo task and it's Done (instead of Next) on the first step.

![Screenshot 2023-07-29 at 7 34 27 AM](https://github.com/zooniverse/front-end-monorepo/assets/12118751/1f98f868-108f-43e6-8a0c-af364ad8adfa)

**Comment by eatyourgreens** [comment]
Looks ok to me. 

![Screenshot of two question tasks with a Next button underneath them.](https://github.com/zooniverse/front-end-monorepo/assets/59547/ec0d1b77-fb61-4cae-ae49-46ffdeb59ddd)

**Comment by eatyourgreens** [comment]
Oh wait, that's the wrong page. You might need to dig into the code to figure out how the next step is calculated. The next task should be set on the combo task.

**Comment by eatyourgreens** [comment]
We used combo tasks to build Engaging Crowds projects so they should just work.

**Comment by eatyourgreens** [comment]
Seems to be working now. I think the single question task determines the next step when you choose an answer, so that you can build branching workflows.

**Comment by mcbouslog** [comment]
Yes, that appears to have fixed it, thanks for working through this.

The impetus behind this issue is this Notes from Nature Lab workflow - https://www.zooniverse.org/lab/9485/workflows/24808. I've seen the same issue/resolution in that the question task answers in the first combo did not have a next task defined, but once I selected a next task for the question task answers, the steps/combos work as expected.

Yep the single question task answers and combo next task are conflicting somewhere in https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/store/helpers/convertWorkflowToUseSteps/convertWorkflowToUseSteps.js, but it's not jumping out to me. I'll try and take a closer look during the week.

**Comment by eatyourgreens** [comment]
The questions here work for me, in mobile Safari. 
https://frontend.preview.zooniverse.org/projects/md68135/notes-from-nature-labs/classify/workflow/24808
