### ISSUE TITLE
Task area is not responsive for Survey tasks

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/front-end-monorepo#5093]
## Describe the bug
When reducing the browser window the subject continues to get smaller but the task area does not, taking up the same amount of space. This makes the subject area unusable, blocking many elements on the screen.

<img width="773" alt="Screen Shot 2023-08-01 at 10 40 30 AM" src="https://github.com/zooniverse/front-end-monorepo/assets/89043489/ebafd8f3-bdfe-42ed-ab75-a878102f407b">

## To Reproduce
1. Go to Snapshot Serengeti
2. Shrink your browser width to just above 768
3. See unusable subject area

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:

## Expected behavior
Similar to other FEM task areas, which shrink alongside the subject area:

<img width="768" alt="Screen Shot 2023-08-01 at 10 41 50 AM" src="https://github.com/zooniverse/front-end-monorepo/assets/89043489/69b2caa9-91c7-4cf9-992d-a8ea1fe1900c">

### Desktop:
 - Browser: Chrome

**Comment by Saicbmm** [comment]
For the Snapshot Serengeti bug, it appears that there are already zooming features available for the subject (represented as magnifying glasses) and they do just fine. You shouldn't have to shrink your browser width if you want to zoom in on the subject.

**Comment by mcbouslog** [comment]
@seanmiller26 - adding `word-break: normal; overflow-wrap: anywhere;` creates the following:
![SnapshotSafariscreenshot](https://github.com/user-attachments/assets/bf3a8d8c-3d30-4093-b59c-0b6cec600149)

Is this preferable, addresses this issue?

**Comment by seanmiller26** [comment]
I think we should hold off on this issue and address #6237 and #6238 first. Let's unify the styling and then we can go from there.

If we have time I'd be happy to talk further about breakpoints. I think there's a lot of options we can explore, but the above isn't the ideal solution.
