### ISSUE TITLE
Confused With Modal - design improvements

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#5112]
## Package
lib-classifier

## Is your feature request related to a problem? Please describe.

This Issue stems from this Talk [post](https://www.zooniverse.org/talk/17/3015323). In that post, the volunteer explains that in FEM, they have a difficult time classifying workflows that use the survey task. 

The "Confused With" modal is part of the survey task area, and when the modal is opened it overlaps the example image of the currently selected choice. In contrast in PFE, the modal always opens below its button regardless of where the volunteer has scrolled the page to.

Examples using Snapshot Wisconsin:
<img width="500" alt="Screenshot 2023-08-03 at 3 01 21 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/cebc4bb7-5a24-4de6-b8f0-3c61d3b73c1d">
<img width="500" alt="Screenshot 2023-08-03 at 3 01 56 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/064eea98-2820-4bdf-b98e-6399c484cfb6">

As far as I understand, the "confused with" modal was designed this way to keep it in view while still being able to see the actual subject image. On a common desktop viewport size, if the “confused with” modal appeared lower on the screen and the volunteer needing to scroll down to it the subject image would be hidden at the top of the screen.

The volunteer also provided screenshots in their Talk post. From those screenshots it's obvious that they use a really large computer monitor. In their viewport, the subject image is always visible even with a very tall task area with lots of survey options:
![image](https://github.com/zooniverse/front-end-monorepo/assets/23665803/94d85402-f148-4159-baed-2beff0f60bce)

Also in FEM, the "confused with" modal jumps from above its button to below its button as the volunteer scrolls down the page. I think it was initially built that way to keep the modal in view. See example video:

https://github.com/zooniverse/front-end-monorepo/assets/23665803/33db34c3-2004-4f56-9c69-61cbeae00cdc

## Describe the solution you'd like

1. Should the "confused with" modal positioning be adjusted to match PFE's behavior? Should it always open below its button? 

2. Should it open above its button, but be draggable (like the field guide)?

## Additional context

Note that any update to this feature in FEM's classifier should be followed up by a post in the volunteer's Talk thread linked above.

**Comment by seanmiller26** [comment]
While I briefly thought about opening the modal on the left of the button, it's really beneficial to see all three images at once (subject image, example image, and confused with image). 

I think we try to match PFE's behavior and have it open below the button. That and eliminating the 'stay in view' jumping behavior.

**Comment by goplayoutside3** [comment]
That makes sense to me too - to match PFE's modal behavior. @mcbouslog do you agree? Also please let me know if you'd like this Issue assigned to you for sometime in the future.

I'm curious what you both think about the possibility of adding a "sticky" behavior to the subject viewer. For instance, when a subject image is taller than the image toolbar or the task area, both stick to the top of a volunteer's viewport when they scroll down the page. Would it be worth trying that out for a subject image too? The survey task area is packed with lots of options so it's likely to be a tall component in comparison to subject images for a lot of projects.

**Comment by mcbouslog** [comment]
Sounds good, adjusting the position of Drop to below the button with Grommet's `dropAlign` will be straightforward. I'm not sure about the jumping when there's space, that might be default behavior with the Grommet component.
