### ISSUE TITLE
Classifier shouldn't submit blank annotations

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#513]
**Package**
lib-classifier

**Feature or Issue Description**
If I press Done without answering a question, the classifier submits the classification with an empty annotations array. Panoptes responds with 400 Bad Request `Validation failed: Annotations can't be blank`. The classification queue tries to re-submit these bad requests on each subsequent press of the Done button.

The annotations array should contain a task annotation for the current task, even if the annotation value is empty. Bad classifications should be fixed (if possible), or removed from the classification queue, before re-submission.

**Comment by srallen** [comment]
The Done button should be doing what the Next button does, which adds the default annotation for that annotation type. It sounds like that was overlooked for the Done button.
