### ISSUE TITLE
MobX state tree error on submitting a classification

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#514]
**Package**
lib-classifier

**Feature or Issue Description**
Pressing Done generates this warning when classifying.
`[mobx-state-tree][error] You are trying to read or write to an object that is no longer part of a state tree. (Object type was 'SubjectResource'). Either detach nodes first, or don't use objects after removing / replacing them in the tree. Use setLivelynessChecking("error") to simplify debugging this error.`

**Comment by srallen** [comment]
Classifications don't appear to be reset correctly and the annotation from the previous classification is still in the store/being rendered in the task. I noticed while testing `projects/stephenserjeant/what-is-beauty/classify`

Maybe related to #513? I'm not sure yet.

**Comment by eatyourgreens** [comment]
I've noticed that my answers aren't cleared. I didn't realise it was the same bug. I don't think I've been able to reproduce this running the classifier as a standalone app, only while classifying in the project app.

**Comment by srallen** [comment]
Yes, I think it might be related because the MST error is telling us that it's trying to perform an action on a tree node after it's been removed. Basically, actions aren't firing the way we expect them to when the classifier is being used in the app-project.

**Comment by srallen** [comment]
I think adding tests to the classification store actions might help.

**Comment by eatyourgreens** [comment]
I think I started some basic classifier store tests in #504 so we can build on that.
