### ISSUE TITLE
Refactor `ClassificationQueue` to use async / await

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#525]
**Package**

lib-classifier

**Feature or Issue Description**

Following on from #517, we should refactor `packages/lib-classifier/src/store/utils/ClassificationQueue.js`'s `flushToBackend` method to use async / await.

**Comment by G4be34** [comment]
Is this still an issue?

**Comment by eatyourgreens** [comment]
Closed by #2567, a couple of years ago.
