### ISSUE TITLE
LightCurveViewer: no longer works with StrictMode + React 18 (local development)

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#5266]
## Development Issue

Package: `lib-classifier`
Follows: #3887

Following the React 18 upgrade in #3887, the LightCurveViewer no longer works _on local development._

- When a developer tries to view Planet Hunters TESS on lib-classifier, i.e. https://local.zooniverse.org:8080/?env=production&project=nora-dot-eisner%2Fplanet-hunters-tess&workflow=11235&demo=true , they'll see NO data points on the light curve viewer.
  <img width="848" alt="Screenshot 2023-08-31 at 22 46 57" src="https://github.com/zooniverse/front-end-monorepo/assets/13952701/e724f03e-8578-4e63-9926-e1f6e9a59f62">

Practical effects:
- **For users, no changes will be noted.** If you go to https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235 , you will be able to view the light curve data, make annotations, and submit classifications as normal.
- For developers, you'll need to remove the `<StrictMode>` component in `src/components/Classifier/Classifier.js` to allow the LCV to work correctly on local development.

### Replication

Tested on localhost with macOS + Chrome 116, on `lib-classifier`

- Go to the [Planet Hunters TESS project on local.](https://local.zooniverse.org:8080/?env=production&project=nora-dot-eisner%2Fplanet-hunters-tess&workflow=11235&demo=true)
  - Expectation: you should see a bunch of data points on the chart, creating a light curve.
  - Actual: the LCV renders with 0 data points. (Confirm with the [live page](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235) to ensure it's not a case of "we ran out of subjects")

### Dev Notes

**A note on the triggering conditions**

- The issue occurs very specifically with **React 18** + **Strict Mode** + Light Curve Viewer on **lib-classifier.**
- On React 17 (commit 94c01feafb5f7c69567b1c56165c8719df764a21), the Light Curve Viewer displays normally when viewing Planet Hunters TESS on local.
  - This is true _even with StrictMode added_
- On React 18 (aka on PR 3887), removing `<StrictMode>` from 'Classifier.js' will cause the LCV to work normally on lib-classifier.
- On React 18 with StrictMode (aka on PR 3887), I can view the Planet Hunters TESS project on `app-project`. i.e. the LCV will show data points when I boot up app-project and go to https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235?env=production

**A note on the LCV life cycle**

On React 18 _without StrictMode,_ I can monitor the lifecycle of the LCV when I view the [Planet Hunters TESS project on local.](https://local.zooniverse.org:8080/?env=production&project=nora-dot-eisner%2Fplanet-hunters-tess&workflow=11235&demo=true)

```
+++ componentDidMount()
+++ initChart
+++ drawChart
+++ componentDidUpdate
+++   dataChanged:  false
```

On React 18 _with StrictMode,_ this is what happens instead:

```
+++ componentDidMount()
+++ initChart
+++ drawChart
+++ componentWillUnmount
+++ componentDidMount()
+++ initChart
+++ drawChart
+++ componentDidUpdate
+++    dataChanged:  false
+++ componentDidUpdate
+++    dataChanged:  true
+++ clearChart
+++ drawChart
```

### Status

Significant impact, not urgent, but should be addressed. (File for long-term maintenance?) While the upgrade to React 18 doesn't break the LCV for users right now, it's an indicator that the LCV isn't future-proofed. Heavens knows what'll happen if we hit React 19.

Two options:
- Update the LCV's lifecycle to meet React 18's stricter standards.
- Replace the `LightCurveViewer` with the `ScatterPlotViewer`. (suggested by Jim) This should be doable in the JSONDataViewer.js file, I think?

**Comment by eatyourgreens** [comment]
With Strict Mode and React 18, I’m also noticing that this story creates two brushes for each click-and-drag. 
https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/subject-viewers-scatterplotviewer--x-range-selection

To run the storybook in strict mode, run `yarn storybook`.

**Comment by eatyourgreens** [comment]
Here's the link for [changes to Strict Mode in React 18](https://github.com/reactwg/react-18/discussions/19). Strict Mode now preserves component state across mounts, so I'm guessing that the light curve viewer breaks if it mounts **with the light curve already loaded.**

**Comment by eatyourgreens** [comment]
Here's a quick video of that x-range selection bug in strict mode. Each click-and-drag generates two selection brushes.


https://github.com/zooniverse/front-end-monorepo/assets/59547/053971a4-8ffb-4774-b6c6-1014e9049633

**Comment by eatyourgreens** [comment]
Turns out `initChart()` breaks if you run it twice, so my quick solution is to empty the SVG element when the viewer unmounts.
