### ISSUE TITLE
Publish packages to NPM 

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#528]
**Package** lib-grommet-theme, lib-react-components, lib-classifier, lib-panoptes-js

**Comment by rogerhutchings** [comment]
This isn't required by our current setup - we build the packages inside the base Docker image, and they're symlinked by lerna.

**Comment by srallen** [comment]
We should still do this so that the libraries, react components, classifier, etc are available to CFEs.

**Comment by rogerhutchings** [comment]
Yup, but we don't need it for TESS
