### ISSUE TITLE
Transcription Task: gray lines blending into subject background

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#5291]
## FEM 
Transcription Task

## Is your feature request related to a problem? Please describe.
On the Davy Notebooks Project, certain subjects have the same background color as the greyed-out lines, creating problems where people don't realize a page is complete and start re-transcribing things. The current workaround is to use the color inversion tool, which clearly shows the grey lines.

## Describe the solution you'd like
I think we need to consider a new color for completed lines that won't blend into certain paper colors (brighter?).

## Additional context
Grey lines blending in:
![Screenshot 2023-09-05 at 9 43 59 AM](https://github.com/zooniverse/front-end-monorepo/assets/25958358/67cda67a-93e9-49db-805a-c7b50680e968)

Same page, shown in inverted color:
![Screenshot 2023-09-05 at 9 44 05 AM](https://github.com/zooniverse/front-end-monorepo/assets/25958358/839c8e4e-4cc2-491b-b88c-35f981c35935)

**Comment by eatyourgreens** [comment]
Maybe detect the colour of the subject image and set a contrasting colour for completed lines?

**Comment by seanmiller26** [comment]
Great point about whiter paper. I had that same thought. Yes, I think for consistency we add the drop shadow to all lines. 

If we're proposing a change might I suggest slightly thicker lines as well? Here's an example with the existing pink transcription line on top

<img width="809" alt="Screen Shot 2023-09-05 at 1 34 40 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/89043489/0b754786-3dba-4df7-b2f4-fe3d21a943e5">

**Comment by snblickhan** [comment]
We can certainly try increasing the thickness and see what people think! I do think we need to make sure that the drop shadow isn't coupled with the increased thickness, though, in case the feedback is negative and we need to roll that back w/o losing the drop shadow, too.

If we increase the thickness, my worry is that some projects might struggle, especially if there's less vertical space between the lines of text (which is common). The DNP dataset are quite widely spaced, so I don't want to inadvertently use this as a metric for what to expect from all other datasets. That said, I think the example you've included here shouldn't(?) be an issue, but only one way to find out, I suppose!

**Comment by eatyourgreens** [comment]
There have been complaints this week that the line thickness has changed, and is now thinner. I'm not sure what would have changed in the projects, though. Bigger images, maybe?

[Transcription underlines have become too fine recently](https://www.zooniverse.org/talk/17/3059210) on Talk.

**Comment by snblickhan** [comment]
Oh that's an interesting point, re: image size increasing. If it's in demand, then definitely let's go with the increased thickness route :)

**Comment by eatyourgreens** [comment]
Noting here that there are a couple of widths that need adjusting in the code; the visible width and a wider, invisible line which is the actual click target.

Off the top of my head, I think Apple's recommendation for click/touch targets is 40px minimum. I thought we'd already built that size into the code but the scaling calculation might be wrong.

**Comment by snblickhan** [comment]
@seanmiller26 would it be possible to follow up on this in the next few weeks? Do you have the bandwidth to mock up a design update with the shadows we discussed above? And we'd then want to update the 'click target' as well, but not sure that needs design(?).

**Comment by seanmiller26** [comment]
All of my restyle suggestions are above. 

Some specifics: 
- Grey transcription line value = Light 4 CBCCCB
- I don't know where to see the current width of the lines, but I'd recommend trying 1.5x or 2x the stroke width as a first pass.
- Same with the current touch target values. The standard is 44px but since we sometimes deal with many lines close together, I'd try Jim's suggestion of 40px. 
- Drop shadow value = Dark 5 5C5C5C

**Comment by eatyourgreens** [comment]
One of the volunteers on Beyond Borders posted that [rotating the image fixes the problem](https://www.zooniverse.org/talk/17/3059210?comment=5044447&page=1) where lines are too small to click. That is totally a bug in our code.

**Comment by eatyourgreens** [comment]
Here's a video of the line thickness bug in Firefox on my laptop. The SVG image scale isn't being set correctly on the first render. Pressing the reset button forces the React component to recalculate the image scale, fixing the problem.


https://github.com/zooniverse/front-end-monorepo/assets/59547/ba111e8f-3c99-43d9-984d-b3b45f731dca

**Comment by seanmiller26** [comment]
I see that it changes the anchor sizing but not the line thickness. Do the anchors represent the touch target size?

**Comment by eatyourgreens** [comment]
I think so, but I don't actually remember how the code works for these lines.

**Comment by eatyourgreens** [comment]
Here's the drop shadow, from #5383. Darker grey lines too.

<img width="300" alt="Screenshot of completed lines with a drop shadow in the storybook" src="https://github.com/zooniverse/front-end-monorepo/assets/59547/e9d62647-d9db-4e9e-8ca3-87f5aa13c1e1">
<img width="300" alt="Screenshot of completed lines with a drop shadow in the dev classifier." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/7b5efb89-d13f-413d-92eb-130896642c0e">
