### ISSUE TITLE
Generalise graph2dRange feedback to the scatter plot viewer

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#5297]
`Graph2dRangeFeedback` here is hardcoded to use the TESS `LightCurveViewer`. It should be generalised so that feedback can also be displayed in the scatter plot viewer eg. for Black Hole Hunters. 
https://github.com/zooniverse/front-end-monorepo/blob/c5fac082f85d9d6a8f7725121316110cc4cb7ca5/packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js#L102-L108

**Comment by adammcmaster** [comment]
I think maybe this should have been closed when #5298 merged?

**Comment by eatyourgreens** [comment]
This should stay open until feedback is implemented in the scatter plot viewer. At the moment, it's only available in the light curve viewer, which is specific to PH-TESS subjects.

**Comment by eatyourgreens** [comment]
Yep. #5298 passes the feedback brushes down to the viewer, but theres no code in place to render them, which is why you aren't seeing any vertical bars for the simulated data.

**Comment by eatyourgreens** [comment]
`feedbackBrushes` are currently only available in the LCV, here:
https://github.com/zooniverse/front-end-monorepo/blob/a10466b3f36986c009412741670f6b531fae4ff7/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js#L41-L44

**Comment by eatyourgreens** [comment]
I think that this can be closed once #5857 merges, and that would mean that the old light curve viewer can be deprecated.

**Comment by eatyourgreens** [comment]
Closed by #5857.
