### ISSUE TITLE
Consolidate and refactor Notifications stores

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#5364]
## Package
_Choose from the list:_
- [x] app-content-pages
- [x] app-project
- [x] unknown

## Is your feature request related to a problem? Please describe.
Currently, a Notifications store is duplicated in app-content-pages [here](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-content-pages/src/shared/stores/User/UserPersonalization/Notifications/Notifications.js) and app-project [here](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/stores/User/UserPersonalization/Notifications/Notifications.js). Additionally, the stores include data fetching (not recommended by MobX). 

## Describe the solution you'd like
The notifications functionality - requesting unread notifications, requesting unread conversations, subscribing to sugar notification events - should be consolidated and refactored.

## Context
The Notifications store provides the unread count for the ZooHeader Notifications and Messages items, as well as subscribes to Sugar for Talk notifications.

**Comment by mcbouslog** [comment]
Per #5337

**Comment by goplayoutside3** [comment]
Noting that notifications data can exist in one app-root store/context in the future. I've got this on my radar!

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/front-end-monorepo/pull/5337#issuecomment-1723401910

It probably doesn't even need to be defined globally. 

```js
function Notifications(props) {
  const { data, isLoading } = useSWR(dataKey, dataFetcher)

return isLoading ?
  'loading' :
  <NotificationsCounter count={data} />
}
```

The SWR hook caches data by `dataKey`, so you can request it once and use it many times. It will also request again when the cache is stale, so counts automatically refresh without any extra code on your part. 

To see an example of the latter, open a FEM field guide for one of your test projects in one tab. In another tab, edit the field guide. When you return to the first tab, SWR should automatically refresh the stale field guide with your edits.
