### ISSUE TITLE
Storybook: Workflow Menu Modal story broken

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#5370]
## Package
_Choose from the list:_
- [ ] app-content-pages
- [x] app-project
- [ ] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug

When running app-project's storybook, the WorkflowMenuModal component's story file won't run with the following error:
<img width="1004" alt="Screenshot 2023-09-19 at 9 49 41 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/6155dc16-0b5d-4d4a-820c-60268514070c">

## To Reproduce
1. Run app-project storybook locally
2. Go to http://localhost:9001/?path=/story/project-app-screens-classify-workflow-menu-modal--choose-a-workflow

## Expected behavior

The component's story should load without an error.

**Comment by goplayoutside3** [comment]
@kieftrav and @eatyourgreens tagging ya'll just for a quick look to see if this error is related to https://github.com/zooniverse/front-end-monorepo/pull/5231. I haven't had a chance to try changing code, but wanted to see if ya'll might know the culprit based on that PR. Thanks!

**Comment by eatyourgreens** [comment]
Here's a public link to the broken story. 

https://zooniverse.github.io/front-end-monorepo/@zooniverse/fe-project/index.html?path=/story/project-app-screens-classify-workflow-menu-modal--choose-a-subject-set
