### ISSUE TITLE
Subject Set Selection: Choose a new workflow is broken

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#5385]
## Package
_Choose from the list:_
- [ ] app-content-pages
- [x] app-project
- [ ] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug

Once I've chosen a subject in the classify page of a project with subject selection enabled, I can't choose another workflow via the Workflow Menu Modal. The `project` and `owner` are undefined, meaning the links in the modal are incomplete.

## To Reproduce
1. Go to a subject set selection project such as [Deciphering Secrets](https://www.zooniverse.org/projects/profdrrogerlouismartinez-davila/deciphering-secrets-unlocking-the-manuscripts-of-medieval-spain)
2. Choose a workflow, subject set, and subject
3. Once the subject is loaded, click on the Classify link in the project header
4. The Workflow Menu opens, but the links are unusable because `project` and `owner` are undefined
 
## Screenshots
In Chrome desktop:

https://github.com/zooniverse/front-end-monorepo/assets/23665803/d0bcce13-b679-4e15-afa7-9501104120a8

## Expected behavior

`project` and `owner` should not be `undefined`. The Workflow Menu Modal should allow selection of a different workflow.

**Comment by eatyourgreens** [comment]
This has been coming up in Sentry too. Do you see `undefined/undefined` in the URL? It's a bug in the NextJS router.

**Comment by goplayoutside3** [comment]
Yes the url looks like this:
<img width="465" alt="Screenshot 2023-09-22 at 11 33 30 AM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/8ca0d8ec-b62b-4bad-a5fc-a7abd60e7646">

Do you know where the router should be pulling `owner` and `project` from? I was wondering if maybe they're being reset accidentally in the store, but will dig deeper if this sounds unfamiliar!

**Comment by eatyourgreens** [comment]
I think this is a bug we've run into before where NextJS isn't properly setting `query.project` and `query.owner` for dynamic routes.

I've definitely seen this randomly happen with the Next and Previous buttons. These two lines sometimes set the slug to `undefined/undefined`.
https://github.com/zooniverse/front-end-monorepo/blob/f9533be0eb2647b76eb13bff9b3ca4a61e18dda5/packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js#L53-L54

**Comment by eatyourgreens** [comment]
Getting the project slug from the project itself would be more robust, to be honest.

**Comment by goplayoutside3** [comment]
There's an infinite loop happening somewhere in the ClassifierWrapper when the Classify button is clicked to open the Workflow Menu Modal. I put a console log to look at the router in that component, and once the modal is open in the UI, the console logs errors and messages infinitely.

**Comment by goplayoutside3** [comment]
I think I found the culprit:

https://github.com/zooniverse/front-end-monorepo/blob/ad92aee3b5a75aee87aec1a4a258777dbd4faa0c/packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js#L87-L93

I think the `useEffect` is intended to update the subject id in the url when the Next and Previous buttons are used in the Subject Set Progress Banner, however it's resulting in an infinite render of ClassifierWrapper

**Comment by goplayoutside3** [comment]
I've got a PR with a fix incoming. I found that the infinite loop was occurring because the `subjectID` prop passed to ClassifyWrapper comes from the classifier props, not from the url. The comparison of `subjectID` to `classifierSubjectID` was incorrectly being used to determine whether to update the url.

**Comment by eatyourgreens** [comment]
That makes sense. The subject ID, that’s passed into the classifier as a prop, never changes once the classifier mounts and initialises. So it can’t be used to reflect the subject that’s currently being classified.
