### ISSUE TITLE
Next 13: build errors

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#5409]
## Package
_Choose from the list:_
- [x] app-content-pages
- [x] app-project

## Describe the bug
A couple of build errors since upgrading to Next 13:
- `eslint-config-next` errors during project builds.
>info  - Linting and checking validity of types ..error - ESLint: Failed to load parser './parser.js' declared in '.eslintrc » eslint-config-next/core-web-vitals » /Users/odonnell/zooniverse/front-end-monorepo/node_modules/eslint-config-next/index.js': Cannot find module 'next/dist/compiled/babel/eslint-parser' Require stack: - /Users/odonnell/zooniverse/front-end-monorepo/node_modules/eslint-config-next/parser.js - /Users/odonnell/zooniverse/front-end-monorepo/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

- [`modularizeImports`](https://nextjs.org/docs/architecture/nextjs-compiler#modularize-imports) is stable, not experimental, in Next 13.4.

## To Reproduce
Build the Next.js apps. Both errors are logged to the console.

**Comment by h3m-an** [comment]
hey, @eatyourgreens Could you please assign this task to me. I identified the bug in this.

**Comment by eatyourgreens** [comment]
@h3m-an thanks but this is fixed by #5411.
