### ISSUE TITLE
Styling bugs in `Finished for the day?` widget

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#542]
**Package**

app-project

There are two minor styling bugs in this widget:

1. The project image doesn't resize to match the height of the text content (note the bottom of the cat image).

    <img width="703" alt="Screenshot 2019-03-13 21 24 55" src="https://user-images.githubusercontent.com/2725841/54315759-f4916d00-45d6-11e9-9686-c46fcdfad3fb.png">

1. The buttons extend beyond the width of the container before hitting the narrow breakpoint.

    <img width="835" alt="Screenshot 2019-03-13 21 25 11" src="https://user-images.githubusercontent.com/2725841/54315742-ed6a5f00-45d6-11e9-9052-9ad6f13e86b8.png">

**Comment by wgranger** [comment]
I'm not able to replicate this bug. Perhaps a recent change solved the issue? However, I'm not seeing an image to the left of "Finished for the day" as shown in the images above.

**Comment by srallen** [comment]
That's the project background, so you might have to try a different project or add a background to the one you're using to debug.
