### ISSUE TITLE
Next 13: custom server errors with EADDRNOTAVAIL on startup

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#5428]
https://github.com/zooniverse/front-end-monorepo/blob/b4e87d445704e63a0579bef36166d39161612623/packages/app-content-pages/server/server.js#L62-L65

The custom server errors here on startup.

```
yarn workspace v1.22.19
yarn run v1.22.19
$ NODE_ENV=${NODE_ENV:-production} PANOPTES_ENV=${PANOPTES_ENV:-production} node server/server.js
{
  APP_ENV: 'production',
  PANOPTES_ENV: 'production',
  assetPrefix: undefined
}
Invariant: failed to start server worker Error: listen EADDRNOTAVAIL: address not available 13.107.226.40
    at Server.setupListenHandle [as _listen2] (node:net:1800:21)
    at listenInCluster (node:net:1865:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:2014:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:110:8) {
  code: 'EADDRNOTAVAIL',
  errno: -99,
  syscall: 'listen',
  address: '13.107.226.40'
}
```

Starting the app with [`next start`](https://nextjs.org/docs/pages/api-reference/next-cli#production) will fix this in the short term (#5427) but we lose:
- logging to `stdout` (requests) and `stderr` (errors.)
- custom cache headers on responses.
- HTTPS in local development.

**Comment by goplayoutside3** [comment]
I might be missing something, but I'm confused about why `set-cache-headers.js` is needed in our Next.js apps. This Issue https://github.com/zooniverse/front-end-monorepo/issues/1807 describes why custom headers are in that file, but that was for Next.js version 9.

When I run app-content-pages locally in either dev mode or production mode, there are Cache Control headers on img assets. Also, when I look at https://www.zooniverse.org/about/publications, which is a build of app-content-pages without `server.js`(?), there are Cache Control headers on img assets, too.

Am I looking in the wrong place for response headers on assets?

**Comment by eatyourgreens** [comment]
We want to cache JS files for 1 year. 
https://github.com/zooniverse/front-end-monorepo/blob/0d200947b1aa2f933c792c9a39b286ec7f53d416/packages/app-project/server/set-cache-headers.js#L11

This talk explains our caching strategies:
https://youtu.be/qVQjGwm_mmw?si=U9mHwMd05mLpjsPC

**Comment by eatyourgreens** [comment]
See this open security alert too. 
https://github.com/zooniverse/front-end-monorepo/security/dependabot/78

**Comment by eatyourgreens** [comment]
Here’s that caching bug:
https://github.com/vercel/next.js/issues/45301

**Comment by eatyourgreens** [comment]
When I look at the `_app.js` file served from https://zooniverse.org/about/team, it's cached for 1 year so that looks totally fine to me too, in production.
<img width="800" alt="Screenshot of the dev console network panel for the Zooniverse Team page, with the request for _app.js selected in order to show the response headers. Cache-Control maxage is set to 1 year." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/e389fb37-3173-4813-81a0-699f0f0ddc45">

Locally, `_app.js` is also served with a `maxage` of 1 year from http://localhost:3000/about/team, **even though we've turned off the custom server**, which is great (we're not paying to serve files when we don't need to) but unexpected that cache-busting is now handled by default.
<img width="1278" alt="Screenshot of the dev console network panel for the Zooniverse Team page on localhost, with the request for _app.js selected in order to show the response headers. Cache-Control maxage is set to 1 year." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/539ff5f0-dd26-47e8-939e-71c32de2c8e0">

**Comment by goplayoutside3** [comment]
The screenshots are helpful thank you! Good to know that cache-busting is now handled by default.

This makes me think we can remove `set-cache-header.js` from app-content-pages. Any reason not to do so?

**Comment by eatyourgreens** [comment]
I’m not seeing this error with #5521.
