### ISSUE TITLE
Classifier needs to respond to narrow screen widths

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#543]
**Package**

lib-classifier

<img width="764" alt="Screenshot 2019-03-13 21 30 39" src="https://user-images.githubusercontent.com/2725841/54315913-55b94080-45d7-11e9-8ed6-a42e98ae543d.png">

**Comment by wgranger** [comment]
It's a quick fix to get the row of `MetaTools` to wrap, but are we currently concerned with how the classifier looks on mobile? Currently, the tools/answers get hidden when the screen hits a width of 700px.

**Comment by srallen** [comment]
No, there's no specific mobile design. I think we should just have parity with current PFE behavior, which is having the subject and task area stack vertically and the metatools remain under the subject viewer.
