### ISSUE TITLE
Markdownz: Embedded video overflows its container and doesn't play

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#5440]
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ ] app-project
- [ ] lib-classifier
- [ ] lib-panoptes-js
- [x] lib-react-components
- [ ] unknown

## Describe the bug
Embedded video does not play in a markdown page.

https://github.com/zooniverse/front-end-monorepo/assets/59547/9c96c973-f2c0-4530-a1ed-3c696d19bbb2

## To Reproduce
Play the embedded video on this page:
https://frontend.preview.zooniverse.org/projects/goplayoutside3/fem-test-project/about/research

## Expected behavior
Embedded video should play, like the same embedded video here on PFE:
https://www.zooniverse.org/projects/goplayoutside3/fem-test-project/about/research

Tested with Firefox 118 on MacOS 11.7.10

**Comment by mvaibhav77** [comment]
@eatyourgreens, Works fine on my machine...

**Comment by eatyourgreens** [comment]
The bug triggers when the request for the video either times out, or returns Service Unavailable from our cloud provider. 

Throttling your connection might help to reproduce it, but it's intermittent and a bit random.
