### ISSUE TITLE
Enabling drawing tools' marks on different frames in Flipbook or Separate Frames Viewer

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#5493]
## Package
- [x] lib-classifier

## Context

[ADR 49](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-49.md) and [ADR 50](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-50.md) describe the intersection of Flipbook or Separate Frames subject viewers and drawing tools tasks. 

Drawing tools in FEM currently duplicate each drawn mark across all frames in a multi-frame subject viewed in Flipbook or Separate Frames because every mark is recorded as `frame: 0`. For parity with PFE's classification UX, we need to build the ability to draw different marks on different frames in the two subject viewers above. Whether marks are duplicated or not across frames is determined by lab config (see below).

## Code Implementation

To implement the drawing tools on Flipbook Viewer, refactoring of [InteractionLayer](https://github.com/zooniverse/front-end-monorepo/tree/master/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer)'s handling of current `frame` is needed. The InteractionLayer is displayed on top of the subject image, and it is aware that it should only show/draw/edit marks for the current `frame`. However, it pulls the current `frame` value from the [Subject Viewer Store](https://github.com/zooniverse/front-end-monorepo/blob/550176f616668c1d17e9c5b44e3dc9e64b4e367d/packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js#L15). Also, when a mark is drawn on any subject viewer in FEM, the store's current `frame` is recorded in the annotation.

⚠️ IMPORTANT: Even if a project wants to clone their drawn marks across all frames, the current `frame` should still be saved in the annotation. See note about aggregation below too.

### Flipbook:
`currentFrame` is used as as local state variable in [FlipbookViewer](https://github.com/zooniverse/front-end-monorepo/blob/550176f616668c1d17e9c5b44e3dc9e64b4e367d/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js#L31) for now, but we want this viewer to allow the drawing tools config explained above, so "current frame" needs to be handled in the store instead of as local state. MultiFrameViewer already does this, see links below.

### Separate Frames
When using the Separate Frames Viewer, all frames are visible at once. Therefore, current `frame` must be recorded per frame the volunteer CLICKS on. This is in contrast to using the Subject Viewer Store as the source of truth for current `frame`. 

### MultiFrameViewer
For an example of how MultiFrameViewer uses current `frame` for transcription projects, see its component:
https://github.com/zooniverse/front-end-monorepo/blob/550176f616668c1d17e9c5b44e3dc9e64b4e367d/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js#L123
And where the function is defined in the store:
https://github.com/zooniverse/front-end-monorepo/blob/550176f616668c1d17e9c5b44e3dc9e64b4e367d/packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js#L164

### How a Mark is Created

`rootStore.workflowSteps.activeStepTasks[0].activeTool.createMark` includes the current `frame` stored as `rootStore.subjectViewer.frame`. The store action `createMark(mark)` is in the drawing tools' [model](https://github.com/zooniverse/front-end-monorepo/blob/550176f616668c1d17e9c5b44e3dc9e64b4e367d/packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js#L70C23-L70C23) where `mark` includes: annotations, frame, id, toolIndex, and toolType. So ideally for example, when `Circle.createMark(mark)` action is called, the `frame` is stored accurately regardless of whether it's the MultiFrame Viewer, Flipbook Viewer, or Separate Frames Viewer.

## Desired Lab UX

The multi-frame option to enable or disable "clone markers" does not yet exist in the [lab-fem](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab-fem/components/fem-multi-image-subject-options-editor.jsx) directory of PFE. It needs to be added. Here's a link to its code in the [PFE lab file](https://github.com/zooniverse/Panoptes-Front-End/blob/34aaf1295d331990b2be4c6540ccb2e8d259871c/app/components/multi-image-subject-options-editor.jsx#L110-L115).

When "Clone markers in all frames" is checked/enabled in the lab:
- A drawn mark such as a circle should appear on every frame of the subject viewer
- The frame index where the volunteer added the mark should still be recorded in its annotation
- If a volunteer drags a mark to a new position, that new position should display in all frames

When "Clone markers in all frames" is unchecked/disabled in the lab:
- A drawn mark should appear only on the frame where it was initially drawn
- The frame index where the volunteer added the mark should be recorded in its annotation
- If a volunteer drags a mark to a new position, that new position should only apply to the dragged mark

## Additional Context

A helpful Slack thread: https://zooniverse.slack.com/archives/C06LHUC6R/p1683218895593149

To test this feature during development I recommend creating a test Zooniverse project with multi-frame subjects. You'll be able to toggle between subject viewers and multi-frame options in your lab.

### Aggregation
Aggregation needs to be considered during or after development of this FEM feature. As mentioned in the Slack thread linked above, this is the [extractor](https://github.com/zooniverse/aggregation-for-caesar/blob/master/panoptes_aggregation/extractors/shape_extractor.py) used by FEM. Potentially follow-up with Cliff(?) if anyone needs to be notified of changes to how `frame` is saved in each drawing annotation object.

**Comment by kieftrav** [comment]
In a discussion between myself, @goplayoutside3, and @lcjohnso we decided that when we **clone marks across frames** the `mark.frameIndex` will always be `0` instead of whichever frame the mark was drawn or edited. This logic extends to data pulled from Caesar such that all data uploaded to Caesar that has the "clone marks" enabled **must** set the `frameIndex` to 0. The purpose of enforcing this rule is to prevent unexpected behavior in the data aggregation and processing pipeline.
