### ISSUE TITLE
Typo in readme.me file

### ISSUE THREAD

**Issue by mrinmay7875** [zooniverse/front-end-monorepo#5510]
## Describe the bug
There is a typo in the Readme.md file. The typo is in the main readme file of the project.

## To Reproduce
1. Go to 'README.md' in the root of the project.
2. Scroll to the Docker section.
3. See in the last line the `development` spelling is incorrect.

## Screenshots

Here is a screenshot of the issue:

<img width="955" alt="image" src="https://github.com/zooniverse/front-end-monorepo/assets/33797909/5e7ed183-aae4-4c21-9c29-52a79751ef25">

This issue will be present in all devices and in all browsers since this is a typo.

**Comment by eatyourgreens** [comment]
Closed by #5511.
