### ISSUE TITLE
Build out `Recents` behaviour for anonymous users

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#558]
**Package**

app-project

**Feature or Issue Description**

Although PFE only shows recent subjects for logged-in users, [the Recents model](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/stores/Recents.js) would allow the new project app to have a Recents page for anonymous volunteers too.

cc #555

**Comment by eatyourgreens** [comment]
The store already exists for this, and is connected up to the classifier, so it should just be a case of building a view to render `recentsStore.recents`. https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/stores/Recents.js
