### ISSUE TITLE
Only animate numbers when in viewport

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#559]
**Package**

app-project

**Feature or Issue Description**

The project app uses a component called `AnimatedNumber` which ticks up from 0 to the intended value. This happens as soon as the client bundle is loaded; it should actually happen when they're in the viewport, or it's kind of pointless

**Comment by rogerhutchings** [comment]
cc #1102 which moves around this component a bit

**Comment by eatyourgreens** [comment]
This effect is cute when I first visit a project, but gets kind of irritating when I navigate around the project and it happens every time I enter a page. It's particularly distracting on the Classify page. Is it possible to set it so it only happens the first time that I enter a page during a session?

**Comment by rogerhutchings** [comment]
perfect candidate for session storage - we'll need #1071 merging first though

**Comment by eatyourgreens** [comment]
Cool. Session storage would help with getting the current user too.

**Comment by goplayoutside3** [comment]
Closed by https://github.com/zooniverse/front-end-monorepo/pull/5947
