### ISSUE TITLE
Is the current protocol / hostname be available as an environment variable?

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#569]
**Package**

app-project

https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/src/components/Head/HeadContainer.js#L49 - we need the current protocol (always HTTPS?) and hostname in order to generate a URL on the server. Is this available, maybe as an env var?

**Comment by adammcmaster** [comment]
There's no proxy between the app and the load balancer now, so those should be in the HTTP headers.
