### ISSUE TITLE
Classifier placeholder image persists behind subject image

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#5750]
## Package
lib-classifier

## Describe the bug

When a subject image loads, there's a placeholder [image](https://static.zooniverse.org/www.zooniverse.org/assets/fe-project-subject-placeholder-800x600.png) used to fill the space until the subject image is ready. This placeholder image somehow ends up as the subject viewer's background behind the subject image. 

## To Reproduce
1. Go to any FEM project's classify page
2. Use the image toolbar to zoom-out
3. You'll see a grey rectangle behind the subject image that does not fit to the viewer bounds.

## Screenshots

<img width="868" alt="Screenshot 2023-12-06 at 11 20 10 AM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/e8f62bfd-855e-4814-847e-6565a2d831b9">.

## Device information
Any

## Additional context
Llikely introduced here: https://github.com/zooniverse/front-end-monorepo/pull/5436

**Comment by eatyourgreens** [comment]
Changing the background style from `contain` to `cover` here will fix it.
https://github.com/zooniverse/front-end-monorepo/blob/07ec2ab8f438c7d8647d4ea0a433bd65e452b2ab/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js#L11-L16

<img width="800" alt="A Daily Minor planet with the subject background image styled to cover the whole subject viewer." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/89c6abab-ed79-4f02-ba33-5efb7ee0d07d">
