### ISSUE TITLE
Subject Set Selection: After choosing a subject set the link to project homepage is 404

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#5770]
## Package
_Choose from the list:_
- [x] app-project
- [ ] lib-classifier?

## To Reproduce
1. Go to a project that uses subject set selection such as [Deciphering Secrets](https://www.zooniverse.org/projects/profdrrogerlouismartinez-davila/deciphering-secrets-unlocking-the-manuscripts-of-medieval-spain)
2. Choose a subject set and subject to work on
3. From the classify page click on the project title in the Project Header 
4. It should navigate to the project home page, but instead goes to https://www.zooniverse.org/projects/undefined/undefined

## Screenshots
<img width="500" alt="Screenshot 2023-12-11 at 3 09 08 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/bc49ac35-913f-4a4c-93b6-62336ef12fd7">

## Additional context

Could be related to https://github.com/zooniverse/front-end-monorepo/issues/5385

**Comment by eatyourgreens** [comment]
Links to the project stats page are also broken, because the `query` object is empty after page hydration.
