### ISSUE TITLE
Back button in Task Area glitches with tooltip

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#5798]
## Package
_Choose from the list:_
- [x] lib-classifier

## Describe the bug

I noticed on Elephant ID that when hovering over the Back button in the Task Area, the tooltip appears glitchy and at 50% opacity. I can eventually click the Back button, but the UX is degraded.

## To Reproduce
1. Go to Elephant ID's [Classify](https://www.zooniverse.org/projects/aeuk/elephant-id/classify) page
2. Place a point on the subject
3. Click the Next button in the Task Area
4. Hover over the Back button

## Screenshots

https://github.com/zooniverse/front-end-monorepo/assets/23665803/d6c005a4-cbee-411e-b28b-d0e7bf107fcd

## Expected behavior

I think there's supposed to be a tooltip on hover 🤔 

## Additional context
Back Button: https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButton.js

**Comment by eatyourgreens** [comment]
That tooltip shouldn't appear at all. See [ADR 35: adding undo/redo to workflow steps](https://github.com/zooniverse/front-end-monorepo/blob/master/docs/arch/adr-35.md). It's worth checking if Elephant ID have explicitly turned off 'persist annotations' and if so, why.

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/front-end-monorepo/issues/2525
