### ISSUE TITLE
Team member account links are broken

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#5801]
## Package
_Choose from the list:_
- [ ] app-content-pages
- [x] app-project
- [ ] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
Links to individual team members, from project Team pages, use broken URLs that return 'not found'. 

## To Reproduce
Scroll down to the list of team members and click on the link to their Zooniverse user account. 

https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/about/team

## Expected behavior
Links are missing the URL base path, `/projects`. If that's added back, they should work.

**Comment by eatyourgreens** [comment]
I think that the problem is the base URL here. 
https://github.com/zooniverse/front-end-monorepo/blob/b84229dc583e82558dce3571d0896d1ec77bb0b5/packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.js#L66

**Comment by Saicbmm** [comment]
My hunch would be that the use profile hyperlink is pointing to a deleted profile or the user has deleted their account. If that is not the case, check and see if the link is valid.
