### ISSUE TITLE
Graph2dRangeFeedback Doesn't show correct answers

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/front-end-monorepo#5856]
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ ] app-project
- [x] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
I gather from #5298 that feedback used to show which annotations were incorrect and also used to show where the correct annotations should have been. Now it just seems to show the volunteer's annotations without indicating what the correct answer should have been.

## To Reproduce
1. Go to the BHH training workflow https://www.zooniverse.org/projects/cobalt-lensing/black-hole-hunters/classify/workflow/25860
2. When classifying a subject with a lensing event, either don't mark it or mark the wrong part of the light curve.
3. Submit the classification.
4. The feedback window will open with the failure message, but the subject will be displayed without the correct ranges being highlighted.

## Screenshots
![IMG_0427](https://github.com/zooniverse/front-end-monorepo/assets/428423/8fc4b0aa-e803-4859-a73e-7ba8bcf5fd3e)

## Expected behavior
The correct range (towards the left hand side in the above example) should be highlighted.

### Desktop (please complete the following information):
 - OS: [e.g. Windows 10]

### Smartphone (please complete the following information):
 - Device: [e.g. iPhone]
 - OS:
 - Browser:
 - Versio:

**Comment by eatyourgreens** [comment]
Feedback hasn't been implemented yet for the scatter plot viewer. Once that's done, that should fix this.

- https://github.com/zooniverse/front-end-monorepo/issues/5297

**Comment by eatyourgreens** [comment]
@adammcmaster I've got feedback working on a branch. I can open a PR.

<img width="500" alt="Green feedback for a successful detection in Black Hole Hunters." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/c285e8e8-08c9-4dde-802c-56981566da51">

**Comment by eatyourgreens** [comment]
The subject viewer is still interactive in the popup. You can delete or edit annotations. I’ve also fixed that in #5857.

**Comment by eatyourgreens** [comment]
AFAIK the popup opens after the classification is saved, so the editing bug shouldn’t affect classifications.
