### ISSUE TITLE
Broken login/registration link

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/front-end-monorepo#5869]
## Package
_Choose from the list:_
- [ ] app-content-pages
- [x] app-project
- [ ] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

(I assume this is lib-classifier but I'm not sure.

## Describe the bug
The "Sign in" and "Register" links that appear when a not-logged-in user does a few classifications result in a 404.

## To Reproduce
1. Go to https://www.zooniverse.org/projects/cobalt-lensing/black-hole-hunters/classify/workflow/25070 while not logged in
2. Do some classifications.
3. When the blue bar with sign in/register links appears, click either sign in or register.
4. You'll be sent to a 404 at eg this URL:https://www.zooniverse.org/projects/projects/cobalt-lensing/black-hole-hunters/classify/workflow/25070?register=true

### Desktop (please complete the following information):
 - OS: [e.g. Windows 10]

### Smartphone (please complete the following information):
 - Device: [e.g. iPhone]
 - OS:
 - Browser:
 - Versio:

**Comment by goplayoutside3** [comment]
I think this bug was caused by changes in https://github.com/zooniverse/front-end-monorepo/pull/5749. I'll see if I can find a quick fix!
