### ISSUE TITLE
Registration form can't be submitted on project home pages

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#5876]
## Package
_Choose from the list:_
- [ ] app-content-pages
- [x] app-project
- [ ] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
None of the checkboxes in the registration form can be checked. One of them is required, which means that the form itself can't be submitted. No one can register for a new account at the moment.

https://github.com/zooniverse/front-end-monorepo/assets/59547/a9bb7d2d-896f-477b-a3ea-8a0f949caf26

## To Reproduce
Register for a new account here: https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess

**Comment by eatyourgreens** [comment]
The registration form works from the team page, so this bug seems to be specific to project pages.
https://www.zooniverse.org/about/team

**Comment by eatyourgreens** [comment]
Could have been introduced by https://github.com/zooniverse/front-end-monorepo/pull/5871

**Comment by goplayoutside3** [comment]
This is specific to a project's home page, the checkboxes work when viewing a project's team page or a project's classify page. I'll investigate into why that is

**Comment by eatyourgreens** [comment]
`values.privacyAgreement` is set when I click the checkbox, but the rendered checkbox doesn't update, and isn't checked in the DOM. 🤔

**Comment by goplayoutside3** [comment]
It looks like on the home page, the form fields are somehow duplicated, where the following warnings log to the console. These warnings don't log when opening the register form on the project About Pages or a project's Classify page.

<img width="343" alt="Screenshot 2024-01-29 at 10 05 22 AM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/25130344-c944-4dc9-b5cf-00febe54b1a9">

**Comment by goplayoutside3** [comment]
Ah I think I see what's happening here. There's a `Media` component used in the project home page layout not used in other project page layouts. I think it's unintentionally causing a dupe render of the `<header>` components while looking for the viewport size. I'll write up a refactor.
