### ISSUE TITLE
SubjectId prop to CollectionsModalContainer is undefined

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#588]
**Package**

app-project

**Feature or Issue Description**

- This is firing off complaint a warning that `subjectId` is a required prop, but is undefined. Logging it while opening / closing the modal and general futzing around with the classifier shows that it's always undefined. Could it be left over from a previous iteration?

**Comment by eatyourgreens** [comment]
Yep. A quick look at the code shows it’s stored in component state now. https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/CollectionsModalContainer.js

**Comment by rogerhutchings** [comment]
Cool, that's what I thought - just wanted to check.
