### ISSUE TITLE
Workflow Assignment Modal: link URL is incorrect for next workflow

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/front-end-monorepo#5880]
## Package
_Choose from the list:_
- [x] app-project

## Describe the bug
Gravity Spy users report (Talk thread) that the URL used by the "Take me to the next workflow" button in the Workflow Assignment Modal is incorrect -- it does not include `/projects` at the beginning of the path.

Current Bad URL: https://www.zooniverse.org/zooniverse/gravity-spy/classify/workflow/1934
Target Good URL: https://www.zooniverse.org/projects/zooniverse/gravity-spy/classify/workflow/1934

## To Reproduce
1. Login as zootester (creds in Passbolt)
2. Navigate to Gravity Spy: https://www.zooniverse.org/projects/zooniverse/gravity-spy
3. Select Level 1 Workflow from homepage.
4. Because zootester is leveled up into Level 2, you should see the Workflow Assignment Modal pop-up -- note the incorrect URL for the "Take me to the next workflow" button.

## Screenshots
Screenshot of Workflow Assignment Modal:
<img width="1442" alt="Screenshot 2024-01-30 at 10 08 46 AM" src="https://github.com/zooniverse/front-end-monorepo/assets/2006101/849b05cb-d315-4dc9-aed7-3bf42777e303">

## Expected behavior
URL should include `/projects` so it is valid.

**Comment by eatyourgreens** [comment]
This means that the Next.js `Link` component, which adds the initial `/projects` to the URL, isn't being used correctly for those links. Those links need to use client-side links in order to preserve JS state in the browser (eg. any classification work in progress.)

The API for `Link` changed in Next.js 13, so that's probably the cause of this bug.

**Comment by eatyourgreens** [comment]
If it's helpful, I used `<Anchor as={Link} href={href}>` to fix this elsewhere in the project app, when I upgraded it to Next.js v13.
