### ISSUE TITLE
Missing UI - `Helpful` action

### ISSUE THREAD

**Issue by mbiesiad** [zooniverse/front-end-monorepo#5890]
## Package
- [x] unknown

## Describe the bug
Hi, case - user click on the `Helpful` action button (known/visible as `thumb up`) and can see lack of UI - information/warning message. Note - missing comma (,) and missing UI there.

## To Reproduce
As logged in user go to:
1. The project Talk section with comments ie.: https://www.zooniverse.org/projects/[name]/[name]/talk/[nr]/[nr]?comment=[nr]&page=1
2. Add your comment
3. Click `Helpful` button (known/visible as `thumb up`) for your own comment, see result.

## Screenshots
Screenshot - current result:
![bug](https://github.com/zooniverse/front-end-monorepo/assets/18367606/b48fd07f-61b4-4060-83fa-b2b9fa44d70d)

## Expected behavior
Add missing comma (after 'Hey') and use more user-friendly UI there.

### Desktop 
 - OS: Windows 
 - Browser: Chrome and Firefox at least

### Smartphone (please complete the following information):
NA

## Additional context
At this moment it looks like 'missing UI' there.

Best wishes,

**Comment by goplayoutside3** [comment]
Hi @mbiesiad. Could you describe what a "helpful UI" would be in this case? The "you can't upvote your own comment" message communicates to a signed-in user that they cannot add a +1 via the thumbs-up. They cannot upvote their own comment.

The Talk feature is part of the [PFE](https://github.com/zooniverse/Panoptes-Front-End) codebase, so if needed I'll transfer this Issue over there.

**Comment by mbiesiad** [comment]
Hi @goplayoutside3 sure, sorry. Please feel free to transfer this issue to the proper repo, if needed.

Short answer is - more uniform style. Everywhere there we can see other style with this kind of msgs than here.

I agree from minimalistic point of view - info msg is proper (content focused). But let's compare this with other example:
![image](https://github.com/zooniverse/front-end-monorepo/assets/18367606/c5fdef73-c91c-46fa-a685-9e3bded042ab)

Moreover, event if we don't want to be focused on UI - there is missing comma, as mentioned.

Best wishes,

**Comment by goplayoutside3** [comment]
Thank you for the clarification! As mentioned the Talk feature is part of the PFE codebase, so UI changes will be addressed as part of Talk's rebuild in the future.
