### ISSUE TITLE
Used `url` not `URL`

### ISSUE THREAD

**Issue by mbiesiad** [zooniverse/front-end-monorepo#5892]
## Package
- [x ] unknown

## Describe the bug
Hi. Please feel free to transfer this issue to the proper repo, if needed, ie.: [PFE](https://github.com/zooniverse/Panoptes-Front-End).
In mentioned place there is used `url` not proper one `URL`. Moreover, later there is used proper form (URL) - just one line below.

## To Reproduce
As logged in user go to the:
1. Your project/lab, link example: https://www.zooniverse.org/lab/[nr]
2. Take a look at places from screenshots - below

## Screenshots
![url](https://github.com/zooniverse/front-end-monorepo/assets/18367606/df907870-926b-47a6-8399-a02822290871)

## Expected behavior
Changed from `url` to `URL`. 

## Device information
NA

### Smartphone (please complete the following information):
NA

## Additional context
https://en.wikipedia.org/wiki/URL
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL
https://www.techtarget.com/searchnetworking/definition/URL

Best wishes,

**Comment by goplayoutside3** [comment]
Closing this Issue here for now - its code is in the PFE codebase and will be addressed while we rebuild the project builder interface.
