### ISSUE TITLE
Mismatched packages for Sentry and Storybook

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#5918]
## Describe the bug
Installed `@sentry` and `@storybook` packages have mismatched versions in the production release.
- `@sentry` is a mixture of 7.99 and 7.100.
- `@storybook` is a mixture of 7.6.12 and 7.6.15

<img width="800" alt="Screenshot of the output from `yarn outdated`, including listings for all @sentry and @storybook packages." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/51831dab-0bc1-4c11-aada-6830f3009f1f">

## To Reproduce
You can manage installed packages with either [`yarn outdated`](https://classic.yarnpkg.com/lang/en/docs/cli/outdated/) or [`yarn upgrade-interactive`](https://classic.yarnpkg.com/lang/en/docs/cli/upgrade-interactive/).

## Expected behavior
Sentry and Storybook both expect that all installed packages will be the same version. Sentry, in particular, expects all installed packages to use the same version of the Sentry SDK.

**Comment by goplayoutside3** [comment]
Sentry is now consistent, and I'm closing this in favor of tracking how to upgrade to Storybook v8: https://github.com/zooniverse/front-end-monorepo/issues/5970
