### ISSUE TITLE
Already seen/Finished subject banners

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#593]
**Package** lib-classifier

**Feature or Issue Description**
We need to add this UI element. The current PFE version causes a lot of confusion, but we still need to inform volunteers on the state of the subject to not waste their time.

We do have an updated design for this:
- Already seen banner: https://projects.invisionapp.com/d/main#/console/12923997/328618227/preview
- Finished banner: 
https://projects.invisionapp.com/d/main#/console/12923997/328618228/preview

These new banners include a 'why' button that shows a tooltip on hover and/or on click?

Also related to #204

**Comment by rogerhutchings** [comment]
![gif1](https://user-images.githubusercontent.com/2725841/55167728-6f2ac280-5169-11e9-89e5-70e01c44159a.gif)
