### ISSUE TITLE
Project announcement banner

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#594]
**Package** app-project

**Feature or Issue Description**
The project announcement banner/toast. This should be dismissible for the session. Current PFE iteration does not support that. Nor do we have a design for this.

**Comment by rogerhutchings** [comment]
cc @beckyrother

**Comment by beckyrother** [comment]
Something like the banners here @rogerhutchings ? https://projects.invisionapp.com/d/main#/console/12924056/344288110/preview I can add this to the classifier project if this is what you had in mind.

**Comment by rogerhutchings** [comment]
<img width="1368" alt="Screenshot 2019-09-19 12 59 57" src="https://user-images.githubusercontent.com/2725841/65242240-68a85280-dadd-11e9-8702-2aa332280caa.png">

**Comment by beckyrother** [comment]
This looks awesome @rogerhutchings!
