### ISSUE TITLE
Try _not_ transpiling libraries 👀

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#597]
**Package**

all

**Feature or Issue Description**

We have a bunch of libraries we're transpiling ourselves - we could try using https://github.com/wellcometrust/next-plugin-transpile-modules and skip that part...

**Comment by srallen** [comment]
We don't need to do this for the next app, but would for publishing to npm, perhaps we could have differing npm scripts for what is needed for the target consumer?

**Comment by rogerhutchings** [comment]
I'm not sure we need to, assuming:

- We're not adding these libraries to existing apps
- We using something like webpack in the consuming app

If so, then we compile in the consuming app, where we can use an env var anyway 🎉 

https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages

**Comment by srallen** [comment]
I think at least the react-components repo should be transpiled, published, and available to use for existing apps. I don't want to have to do any maintenance anymore on the previous versions... for header, footer, etc.

**Comment by rogerhutchings** [comment]
Closing - we've removed transpilation where we don't need it, and the remainder are published as transpiled.
