### ISSUE TITLE
Classify page daily classification counts don't update

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#5971]
## Package
_Choose from the list:_
- [x] app-project

## Describe the bug
When you submit a classification, your daily classification count doesn't change, on the Classify page.

## To Reproduce
1. Go to https://www.zooniverse.org/projects/fulsdavid/the-daily-minor-planet/classify/workflow/22354
2. Submit a classification
3. Scroll down to Your Stats and see that 'Classifications Today' hasn't changed.

## Screenshots
Here's a screenshot from Daily Minor Planet, with dev tools open to inspect the `AnimatedNumber` component. You can see that the `value` prop is 3, but the displayed count is 2.

<img width="800" alt="Screenshot of Daily Minor Planet in Firefox, with dev tools open to show that the value passed into the Stat component, for your daily classification count, is not being reflected on the page." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/92cf0f26-9cf6-4bff-b03a-175da0ccd492">

## Expected behavior
The classification count should increment, in the browser, when a classification is submitted for an unclassified subject.

### Desktop (please complete the following information):
 - OS: MacOS 14.3.1
 - Browser: Firefox 123.0.1

## Additional context
This bug seems to have been introduced by #5947.

**Comment by eatyourgreens** [comment]
Here are the Talk discussions:
- [Zooniverse Talk: Troubleshooting](https://www.zooniverse.org/talk/17/3293615).
- [Daily Minor Planet Talk](https://www.zooniverse.org/projects/fulsdavid/the-daily-minor-planet/talk/5539/3294325).

**Comment by eatyourgreens** [comment]
This wasn't fixed by #5974, but should be fixed by #6192. GitHub won't let me reopen it, even though I'm the original owner.

**Comment by goplayoutside3** [comment]
Gotcha, I'll re-open!
