### ISSUE TITLE
Workflow Assignment / Leveling Up: expect settings.workflow_id can be int or string 

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/front-end-monorepo#5972]
### Current Behavior
The Panoptes API allows `settings.workflow_id` from UserProjectPreferences, which is used for workflow assignment as part of the leveling up feature, to be written as a string or a integer type. While internal assignment of these values by the FE, Panoptes, and Caesar typically use the string -- and hence the type assumed by the FE was string for its current implementation -- project teams using the Python Client (via [ProjectPreferences.save_settings()](https://panoptes-python-client.readthedocs.io/en/latest/panoptes_client.html#panoptes_client.project_preferences.ProjectPreferences.save_settings) function) tend to assign integer values.

If a user has an integer type `settings.workflow_id` value, the FE throws an error (`Error: [mobx-state-tree] No matching type for union ({ workflow_id: (string | undefined?) } | undefined?)`) and the setting is ignored; the user is granted default workflow accessibility / as if they have no assigned workflow -- they cannot access higher workflows.

To reproduce:
- Login as zootester1 (user_id = )
- Visit https://frontend.preview.zooniverse.org/projects/lcjohnso/leveling-up-testbed, where zootester1 is assigned `workflow_id : 22843` (Level 3 on the project)
- Check console for error, confirm that user only has access to Level 1

### Desired Behavior
Either string or int are allowed types for `settings.workflow_id` value.

### Relevant Code
It appears settings.workflow_id is read from UserProjectPreferences here:
https://github.com/zooniverse/front-end-monorepo/blob/85bcd542e65fa06c7a8f5635ef56c854558286f3/packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.js#L37-L38

**Comment by eatyourgreens** [comment]
Roger created a `numberString` type for Panoptes IDs, so that would work here too. It doesn’t do type conversion, only validation, so you’d still need a snapshot preprocessor or an MST custom type to handle pure numbers. 

https://github.com/zooniverse/front-end-monorepo/blob/75c1373731d6ef379d47804c2383bcc676cda582/packages/app-project/stores/Project.js#L21

**Comment by eatyourgreens** [comment]
If the assigned workflow ID is a number, then the comparison with a string here will always be false and new workflows won’t be assigned. 

https://github.com/zooniverse/front-end-monorepo/blob/75c1373731d6ef379d47804c2383bcc676cda582/packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/WorkflowSelectButtons.js#L32

**Comment by eatyourgreens** [comment]
`FixedNumber` is an example of how to write a custom type. It’s used for drawing coordinates. 

https://github.com/zooniverse/front-end-monorepo/blob/75c1373731d6ef379d47804c2383bcc676cda582/packages/lib-classifier/src/plugins/drawingTools/types/FixedNumber.js#L3-L21

**Comment by eatyourgreens** [comment]
#5998 should fix this.
