### ISSUE TITLE
How to build the about pages?

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#6]
I'd like people to be able to edit the about pages without having to edit code, so I've been thinking about ways to do this. 

## Editing content

- **Markdown** - it's not code, but would still require people to make commits and such.
- **CMS** - I've been using [Grav](https://getgrav.org/) in my freelance work, which has been fairly painless to use.
- **Headless CMS** - I've experimented with [Contentful](https://www.contentful.com/) in the past, and there are open source options like [Cockpit](https://getcockpit.com/).

## Displaying content

- **Static site generator** - e.g. Jekyll, we'd need to configure it to be rebuilt on content edits
- **CMS**
- **React app** - requires an easy way of editing markdown, or using a headless CMS, but would be easiest to integrate with the rest of the site.

My preferred option would be a headless CMS and either Jekyll or a React app.

**Comment by srallen** [comment]
Just a couple questions that popped into my head when considering our options here:

- How will translations be handled?
- How would we handle the shared CSS from the zooniverse theme? Basically, I'd hate for us to have to maintain styled-components and grommet theme and some vanilla CSS (or SASS/Stylus) files in parallel.

**Comment by rogerhutchings** [comment]
# Translations

If we use a regular CMS, we'd need to pick one with localisation support, which would cut out the simpler ones. If we used a headless CMS, either it would need localisation support _or_ we can define our own field on the content type and store the language code there (and use it as a param in the content request).

# Styling

I don't want to maintain two sets of styling either, but it is an option (either for Jekyll, or a CMS theme). Alternatively, for a CMS, we could create a small wrapper app in React, modify the CMS theme to only output the content, request that in and let the React app handle styling. With the headless CMS option, we don't need that intermediate step, we simply request the content.

**Comment by srallen** [comment]
Just came across this React based static site generator: https://github.com/gatsbyjs/gatsby
