### ISSUE TITLE
Project-specific translations don't fallback to English when missing

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#6015]
## Package
_Choose from the list:_
- [ ] app-content-pages
- [x] app-project
- [x] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug

FEM’s codebase should display the English translations when another language's strings are missing for both project-specific translations and platform translations. Here are two cases where project-specific translation strings aren't complete in a Zooniverse project, and there's no English fallback displayed.

## To Reproduce

Go to [Daily Minor Planet](https://www.zooniverse.org/projects/fulsdavid/the-daily-minor-planet)'s classify page, use the language dropdown and switch to German. The project title is blank as well as the task area where project-specific translations should populate.

<img width="1269" alt="Screenshot 2024-04-03 at 11 14 41 AM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/06d4821c-15c0-496e-b856-13d44ef255c3">

______

Go to this [Snapshot Serengeti workflow](https://www.zooniverse.org/projects/fr/zooniverse/snapshot-serengeti/classify/workflow/4655) in French. There's no translations available in the task area, and no fallback to English.

<img width="1230" alt="Screenshot 2024-04-03 at 11 17 12 AM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/e3347b82-e6bc-4706-abdc-ef32d19ae810">

**Comment by eatyourgreens** [comment]
English is fetched as a fallback, but only used if the requested language doesn’t exist. 

These could merge the translation and the fallback, instead of returning one or the other. A translation is a flat dictionary, so merging two translations is simple. You don’t have to worry about nested objects. 

https://github.com/zooniverse/front-end-monorepo/blob/1b23585b46f38524551e793430138eb4e8835742/packages/app-project/src/helpers/fetchTranslations/fetchTranslations.js#L26-L28

**Comment by goplayoutside3** [comment]
That's the right behavior we want - backfilling keys with the fallback's string if there's no translation content for the currently selected language. However, if translations are missing when a project team enabled the language for project-specific translations, all of the keys exist as empty strings like this:
```
display_name: "Snapshot Serengeti",
tasks.T0.characteristics.BUILD.label: "",
tasks.T0.characteristics.BUILD.values.LANKY.label: "",
tasks.T0.characteristics.BUILD.values.LARGE.label: "",
tasks.T0.characteristics.BUILD.values.LOWSLUNG.label: "",
tasks.T0.characteristics.BUILD.values.SMALL.label: "",
tasks.T0.characteristics.BUILD.values.STOCKY.label: "",
tasks.T0.characteristics.COLOR.label: "",
tasks.T0.characteristics.COLOR.values.BLACK.label : "",
tasks.T0.characteristics.COLOR.values.BROWN.label:  ""
etc...
```

So using object spread to combine the two just overwrites `original` with `translation` for every key with an empty string.

**Comment by goplayoutside3** [comment]
I think I found a way to utilize [mergeWith](https://lodash.com/docs/4.17.15#mergeWith) for this. PR incoming...

**Comment by eatyourgreens** [comment]
Those empty strings are created by the translations editor. If you edit line 244 here, you can change the editor to use the original project language for empty fields. But then translators would have to select and delete that text before adding a translation. 

https://github.com/zooniverse/pandora/blob/8f92796ae6bc601a3a1f5bc4b839c8e92f01d475/src/ducks/resource.js#L243-L246
