### ISSUE TITLE
Update links in ZooFooter for redesigned pages

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#6025]
## Package
_Choose from the list:_
- lib-react-components

## Describe the solution you'd like

When the redesigned About Zooniverse pages and Get Involved pages are ready to be deployed, links in the ZooFooter should be revised to match the new pages. There's also a new section for Project discipline which can be added once the redesigned Projects landing page is deployed.

<img width="854" alt="Screenshot 2024-04-05 at 5 03 15 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/b8344e85-216d-49cd-a060-42cb6b30fbf4">

**Comment by goplayoutside3** [comment]
@seanmiller26 with impending launch of new FEM pages, are there any updates to the ZooFooter screenshot you'd like to make? For instance, I don't anticipate being able to implement the Projects disciplines column, but the rest works.

**Comment by seanmiller26** [comment]
Updated Figma link https://www.figma.com/design/6rXVi6arrGTmoM08x9tpex/UI-Kit?node-id=5-409&m=dev&t=MGdDZm4sLEz9aSXP-1
