### ISSUE TITLE
[RFC] Reorganizing MST structure in classifier stores

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#603]
**Package** lib-classifier

**Feature or Issue Description**
From comments in #585:

> I think I'd go for classifierStore.tasks.dataVisAnnotating. Similarly, I think workflow steps could be classifierStore.workflow.steps which would give the workflow store access to actions on the workflowStep store. At the moment, the structure's completely flat, and I'm thinking that loses us some of the advantages of the state tree.

**Comment by rogerhutchings** [comment]
Nesting `steps`  under `workflow` makes total sense to me.

I'm going to have a look around for more articles on designing a state object, but for now, redux's docs are quite good: https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape
