### ISSUE TITLE
Closed paths for freehand line tool are not saved to Panoptes

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/front-end-monorepo#6048]
## Describe the bug
When I use the freehand line drawing tool on FEM, for example on a [drawing test workflow](https://frontend.preview.zooniverse.org/projects/lcjohnso/lcj-test/classify/workflow/9812) on my LCJ Test project ([homepage](https://frontend.preview.zooniverse.org/projects/lcjohnso/lcj-test) / [lab link](https://www.zooniverse.org/lab/8749)), no coordinates are saved to the classification's annotation **for closed markings** when written / POSTed to Panoptes. Non-closed lines are saved as expected, but any annotation that closes (_either_ automatically while drawing or via the "close shape" button) is written with empty `pathX` and `pathY` values. 

Notes:
- Open (non-closed) lines behave fine in all / many circumstances I tested. In the case of multiple freehand line tools (i.e., toolIndex = 0 and 1), one non-closed line will be written out fine while a close shape will not be in the same classification.
- I tested on a workflow where machineLearnt reductions are not available on Caesar and loaded in. I have not tested the case when annotations are loaded in at the beginning of the classification.

## To Reproduce
1. Go to https://frontend.preview.zooniverse.org/projects/lcjohnso/lcj-test/classify/workflow/9812
2. Draw a closed shape.
3. Check POSTed annotation and/or Panoptes DB to see that `pathX` and `pathY` are empty for closed annotation.

## Expected behavior
I expect open and closed shapes drawn with the freehand line tool to be written to the classification annotation.

## Device information
Tested on Mac 13.6.5 via Chrome and Firefox (consistent behavior across browsers).

cc: @kieftrav @goplayoutside3

**Comment by kieftrav** [comment]
PR fixing also tested to make sure Caesar-connected data flowed through properly as well.
