### ISSUE TITLE
Hide previous marks persists to next subject, but will show 2nd mark

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/front-end-monorepo#6062]
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ X ] app-project
- [ ] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
When you are classifying on a drawing task you can select "Hide previous marks." After submitting a classification, the marks do not show on the next subject. However, you can still draw new marks. The 1st mark will be hidden, and subsequent marks will show. If you then press "show previous marks" you will see the 1st hidden mark has actually been recorded. See this video for more details.

https://github.com/zooniverse/front-end-monorepo/assets/89043489/d06d8818-2556-4c47-b852-14b91d9e991a

### Desktop (please complete the following information):
 - OS: [e.g. Windows 10]

### Smartphone (please complete the following information):
 - Device: [e.g. iPhone]
 - OS:
 - Browser:
 - Versio:

**Comment by eatyourgreens** [comment]
The bug here is in `task.hidingIndex`, which is persisted across subjects. So, if you hide two marks, say, then the first two marks will always be hidden for each new subject. 

The transcription task shares code with the drawing task, so this bug also affects transcription projects.

**Comment by eatyourgreens** [comment]
This bug was introduced in #1610, so it definitely affects transcription projects.

**Comment by eatyourgreens** [comment]
Here's a screen recording of the same bug on a transcription project. I hide 3 marks on the first subject, so my clicks are ignored for the first 3 lines of the next new subject.


https://github.com/zooniverse/front-end-monorepo/assets/59547/75f2f718-abc4-42cb-b944-41561d7ffe22
