### ISSUE TITLE
Dragging subject images ignores rotation transforms

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#6067]
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ ] app-project
- [x] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
Dragging a rotated subject image ignores the rotation transformation, leading to weird and unexpected UX eg. I drag right but the image moves up (its RHS in the rotated frame.)

Panning with the keyboard isn't affected, only dragging with a pointer (mouse, trackpad or finger.)

https://github.com/zooniverse/front-end-monorepo/assets/59547/701789b3-32e3-4bc8-ad99-9c86ecef56ae

## To Reproduce
Zoom an image, either in or out, rotate it, and drag the rotated image to move. 

## Expected behavior
Dragging should move the image in the frame of the subject viewer, not the rotated frame of the image eg. dragging right should move the rotated image to my right. 

## Device information
Tested in desktop Firefox and Chrome,  and mobile Safari on an iPhone XS. This seems to be a bug in the Zooniverse SVG code, not a browser bug. 

## Additional context
Dragging worked correctly when rotation was first introduced, for transcription projects.

**Comment by eatyourgreens** [comment]
After a bit of testing on a drawing workflow, on my phone, dragging to draw is not affected by this bug. Only dragging to move the image. 🤔

https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify/workflow/3370?env=staging

**Comment by goplayoutside3** [comment]
Related to https://github.com/zooniverse/front-end-monorepo/issues/2273

**Comment by eatyourgreens** [comment]
Both #2273 and this issue should be fixed in #6065.
