### ISSUE TITLE
Tutorial keyboard interaction

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#607]
**Package** lib-classifier

**Feature or Issue Description**
From comments in #552 

> When a tutorial pops up on zooniverse.org, I can change slides by pressing the cursor keys. When the tutorial pops up here, pressing the cursor keys does nothing and there's no indicator to show me where focus is.

Also note that Grommet's RadioButton does not behave the way we expect:

> RadioButtonGroup handles focus accessibly. RadioButton on it's own does not. We recommend RadioButtonGroup as the preferred means of handling radio button input. You can file an issue on RadioButton. However, I suspect it will not receive much attention from the grommet core team unless an example arises where RadioButtonGroup isn't sufficient.

RadioButton needs focus or we should not use it.

**Comment by eatyourgreens** [comment]
Does the tutorial receive focus when it opens? It should do, so that the content is announced in screenreaders. If it does, would it be difficult to add listeners that change the slides on keypress?

I think it receives focus because it can be closed by pressing Esc, but I could be wrong.
