### ISSUE TITLE
Add Instagram icon to the footer social media menu (site-wide)

### ISSUE THREAD

**Issue by apreleva** [zooniverse/front-end-monorepo#6107]
## Package
_Choose from the list:_
- [ ] app-content-pages

## Is your feature request related to a problem? Please describe.
Instagram icon is lacking in the footer social media menu of the zooniverse.org website, where Facebook and Twitter icons are present. That was brought to my attention by Nomad Purple (superuser). Sean Miller suggested I open this request.

## Describe the solution you'd like
Add the standard Instagram icon, leading to https://www.instagram.com/the.zooniverse 

## Additional context
N/A

<img width="774" alt="Screenshot 2024-05-28 at 16 35 25" src="https://github.com/zooniverse/front-end-monorepo/assets/144508133/d468c98b-ad50-4fd9-b684-83b4969c0036">

**Comment by goplayoutside3** [comment]
The screenshot above is of PFE's footer, so I'll transfer this issue over to that codebase: https://github.com/zooniverse/Panoptes-Front-End

PFE's footer is always dark gray.

FEM's footer already has an instagram logo and link. FEM's footer is white:
<img width="1350" alt="Screenshot 2024-05-28 at 2 16 06 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/a00973f7-9f42-4c21-83d7-e50df093fc63">
