### ISSUE TITLE
Two <main> elements

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#6142]
The app-root [HomePageContainer](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-root/src/components/HomePageContainer.js#L17) includes a `<main>` element as well as the lib-user [Layout](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-user/src/components/shared/Layout/Layout.js#L119) component. I think there should only  be one, and I'm not sure where we prefer to have it.
- we could refactor Layout with `<section>` and add a `<main>` element to the `/users` and `/groups` app-root pages
- we could refactor HomePageContainer with a `<div>`, but then Loader wouldn't have a `<main>` (unless we wrap it with one)
- we could wrap children in the RootLayout with `<main>` and remove elsewhere
- other?

**Comment by goplayoutside3** [comment]
Big picture:
- /about page.js files import a component from lib-content with `<main>` in AboutLayout
- /users page.js files import a component from lib-user with `<main>` in Layout
- /groups page.js files import a component from lib-user with `<main>` in Layout
- The home (/) page.js imports a component from lib-user or lib-content depending on whether there’s an auth user. When signed-out, `<main>` is in app-root’s HomePageContainer, but when signed-in, `<main>` is in both lib-user’s shared Layout and HomePageContainer.

I'm okay with removing `<main>` from app-root's HomePageContainer and putting it in DefaultHome in lib-content. That follows the pattern of all other pages in app-root. I'll open a PR to do so.

**Comment by goplayoutside3** [comment]
Oh but wait, the problem here is the Community component displayed in HomePageContainer regardless if a user is signed in or not 🤔

**Comment by goplayoutside3** [comment]
I decided to move the Community component around in #6149
