### ISSUE TITLE
Logged-in homepage styling adjustments

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/front-end-monorepo#6151]
## A short list of the most pressing styling changes taken from our Internal Feedback doc. 

Desktop:
1.  Links should underline on hover: Favorite / Collect / Comments / Messages
Dark Mode:
1.  The stroke around a user avatar should match the page background color
2. The stroke around the panels are inconsistent. They can all be #E2E5E9

Mobile:
1.  Decrease spacing between avatar and user display name to 30px
2.  Double check the Favorite / Collect / Comments / Messages icons are a consistent size >=24px. Increase both the touch target size and the spacing between them.
3.  Show the tabs for This Week / All Time stats.
4.  Remove teal header with Zooniverse logo.

**Comment by goplayoutside3** [comment]
When I address this Issue, I'll include added padding around the WelcomeModal so on "medium" screen sizes like an ipad, it won't touch the edges of your browser.

**Comment by goplayoutside3** [comment]
@seanmiller26 for this one:
> The stroke around the panels are inconsistent. They can all be #E2E5E9

Do you mean the stroke around all "content boxes"? For instance, all of the panels with rounded corners on a user's `/stats` page use the same component called ContentBox. They have a border color #5C5C5C. I could make sure the content boxes on a user's homepage have the same border + shadow. Would that work?

**Comment by seanmiller26** [comment]
@goplayoutside3 Yes, that would work. And they look fine in light mode, so here I am specifically looking at dark mode. Thanks!

**Comment by goplayoutside3** [comment]
Gotcha I'll double check everything in dark mode too. Second question is about:

> Remove teal header with Zooniverse logo.

The logged-in user homepage intentionally uses the same Layout component as all stats and groups pages because their layouts are all identical (for now). Removal of the user homepage's teal header on mobile will be a unique case where I'll need to duplicate the Layout component and modify it specifically for that one case. It's not at all difficult to do, but just double checking you're intentionally breaking the user homepage mobile layout away from the rest of the stats and groups page design?

**Comment by seanmiller26** [comment]
Thanks for checking. Yes, I do want to modify the layout for this one use-case. The header doesn't provide anything useful for the page. So I'm opting to remove it to gain more screen space for other, more useful elements. Plus it'll make the profile header and avatar pop.

**Comment by goplayoutside3** [comment]
Okay will do!

**Comment by goplayoutside3** [comment]
Sorry one more question before I open the PR. The Community section has border-radius on all corners of 16px (like the top of a user's home dashboard), but that clashes with the border-radius of 8px on all other content boxes (stats and groups pages). Like this:

<img width="1086" alt="Screenshot 2024-07-19 at 1 05 27 PM" src="https://github.com/user-attachments/assets/e30683dc-a91a-4e2b-afdc-247268d2400d">

Do you want me to change the border-radius of the Community section to match that of content box (8px)?

**Comment by seanmiller26** [comment]
Ah, yes I did notice that. Good catch. 

Let's unify and have it be 8px border. The only times it should be 16px are the tops of the homepage (profile header pic) and the stats pages (bar chart). Thanks.
