### ISSUE TITLE
Logged-out homepage - updated copy

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/front-end-monorepo#6155]
## Updated copy to include on the logged-out homepage

Figma file for reference:
https://www.figma.com/design/p6laHCEklj9YK79TC1F7NV/Homepages?node-id=0-1&t=VppQmBcav8TvVIPB-0
FEM Copy doc for reference:
https://docs.google.com/document/d/16LEB90_8ztDOW4QemBs1D_ksEZlooBe6fXsyMTln9B4/edit

#### Hero copy
<img width="600" alt="Screenshot 2024-07-02 at 2 52 43 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/89043489/3a1e708e-7dc7-4c9d-a1d1-b22fd6ad821f">

PEOPLE-POWERED RESEARCH
Join millions of people who help to advance real research, real science, and real knowledge.

#### What is the Zooniverse section
*New subtext copy: The wisdom of the crowd

The Zooniverse is the world's largest platform for people-powered research. We connect professional researchers with millions of volunteers worldwide. Facilitating real results from impractical, or otherwise impossible research. This has led to new discoveries, policy impacts, and research publications.

Our platform is driven by volunteers, like you. All ages and backgrounds are welcome to participate, no PhD required—just a sense of wonder and a few clicks. Many of the most interesting findings from Zooniverse projects have emerged from discussions between volunteers and researchers. Join us today to take part in cutting-edge research and make your own discoveries!

#### Real Researchers, Real Results section
*New subtext copy: Meet the researchers who've created projects on the Zooniverse

From classifying animals to discovering exoplanets to transcribing historical documents, and more, researchers across the disciplines have used the Project Builder to create engaging, accessible projects. Anyone can build a Zooniverse project. Simply upload your data, choose the tasks you want the volunteers to do, and join us in nurturing an inclusive and welcoming online community engaged in real research.

**Comment by seanmiller26** [comment]
@goplayoutside3  NEW mobile image(s) chosen. I'd like to match our 404 behavior of pulling random subject images. Uploaded here: https://github.com/zooniverse/Design-Resources/tree/main/Logged-out%20Homepage%20Images

<img width="600" alt="Screenshot 2024-07-12 at 1 16 42 PM" src="https://github.com/user-attachments/assets/624d24ae-960c-4f96-9131-de2dc310b779">

Figma file for reference: https://www.figma.com/design/p6laHCEklj9YK79TC1F7NV/Homepages?node-id=0-1&t=EVJ7Qb3IzpDovAzG-0

If pressed for time / too much effort, go ahead and choose any one of the images and we can revisit the random-pull at a later time.

**Comment by goplayoutside3** [comment]
@seanmiller26 In https://github.com/zooniverse/front-end-monorepo/pull/6166 I chose just the first image above for mobile for now. I'm worried some of the other images in the design resources folder make the gold text really difficult to read due to minimal contrast. If you'd like to, we could look at each image together with the teal + blur filter applied in the future.

**Comment by seanmiller26** [comment]
Even with the 40% 005D69 and blur overlay? Totally ok for now, though, until we can revisit.
