### ISSUE TITLE
Multiple button selections allowed for single-answer question

### ISSUE THREAD

**Issue by yshish** [zooniverse/front-end-monorepo#6178]
## Describe the bug
In camera trap project task (https://www.zooniverse.org/projects/abbsta/south-coast-threatened-fauna-recovery-project) there's a multiple button selection allowed for the species count while it is a single-answer question.

## To Reproduce
1. Go to https://www.zooniverse.org/projects/abbsta/south-coast-threatened-fauna-recovery-project and choose either of the available workflows to load a subject to classify.
2. Click on any species category to open it in the task (except the one called 'Nothing') and answer the question "HOW MANY INDIVIDUALS?" by selecting more than one answers (f.e. 1, 2, 3, 4). 
3. Then do the same for the following question "CAN YOU SEE YOUNG? ONLY ANSWER YES IF YOU CAN SEE BODY PARTS; I.E. A HEAD, TAIL OR A ARM STICKING OUT OF THE POUCH." by selecting both 'Yes' and 'No' answers at the same time.
4. Click on 'Identify'.
5. Open the same category again to see that all your multiple answers are highlighted (and so I guess they're to be recorded if you finish your classification by clicking 'DONE' - Haven't tried that as I am unable to figure out the results).

## Screenshot
![ysh_Screenshot_2024-07-20_22-18-59](https://github.com/user-attachments/assets/d49242f9-220c-4b2b-a1aa-e2d15c83e18f)

## Expected behavior
When answering How many individuals, I'm supposed to be allowed to select only one answer. The same goes for the YES/NO question.

### Desktop (please complete the following information):
 - OS: Ubuntu
 - Browser: Chromium
 - Version 126.0.6478.126 (Official Build) snap (64-bit)

## Additional context
It works fine in Panoptes so I believe this is a bug of the new front-end codebase.

**Comment by mcbouslog** [comment]
Thank you for reporting @yshish ! I can confirm the task data is configured unexpectedly based on the questions, i.e. questions that should not allow multiple answers do indeed allow multiple answers, due the underlying task data having `multiple: true` in the question configuration.
<img width="382" alt="survey_task_question" src="https://github.com/user-attachments/assets/c1b3381a-3eb4-4e6e-8544-128c38872465">

We'll have to update the workflow task data as expected (`multiple: false`) for any questions currently misconfigured.

**Comment by mcbouslog** [comment]
Related Talk post: https://frontend.preview.zooniverse.org/projects/abbsta/south-coast-threatened-fauna-recovery-project/talk/5163/3397400
