### ISSUE TITLE
DashboardLink in UserHome should be clickable anchors on mobile screens

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/front-end-monorepo#6181]
## Package
_Choose from the list:_
- [ ] lib-user

## Describe the bug

The icons below correspond to the links on desktop, but on mobile screens they don't link out to Favorites, Collections, etc
<img width="349" alt="Screenshot 2024-07-22 at 9 09 13 AM" src="https://github.com/user-attachments/assets/efcf2a06-2880-4c58-9484-f56f53cd8a24">

**Comment by seanmiller26** [comment]
Can we ensure the heights of the icons are the same? Widths are less important
