### ISSUE TITLE
Add placeholder for classifier while loading

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#619]
**Package**

lib-classifier

**Feature or Issue Description**

Rather than magically appear, we should have a placeholder element that roughly occupies the same area as the classifier.

**Comment by srallen** [comment]
Maybe https://github.com/buildo/react-placeholder?

**Comment by goplayoutside3** [comment]
Closing due to lack of designs. This would be a complication due to wide variety of subject image sizes and task area sizes. We can instead consider opening specific Issues for each of the classifier's main components with their own loader design.
