### ISSUE TITLE
Project Stats: Project Stats numbers (Classifications Today / Classifications Total) don't show on initial Next.js page fetch

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/front-end-monorepo#6190]
## Inconsistent UI Bug?

Package: `app-project` and/or `lib-react-components`
Confirmed as of commit: 
Also see: #5974 (previous fix for AnimatedNumbers), #5971 (similar issue)
Possibly related Talk issue: https://www.zooniverse.org/talk/17/3402644 ?

In certain cases _when the Next.JS server first fetches a page,_ it's possible for the Project Stats ("Classifications Today" and "Classifications Total" count on the Classify page) to not display accurate numbers, despite fetching the correct data.

Replicating this issue is a faff, but can be done on localhost:
- Tested using macOS + Chrome 126 _non-Incognito,_ targeting app-project, with a logged-in session saved. (i.e. when I open the target URL, I'm already logged in with an account that has already made 5+ classifications today.)
- Start a FRESH instance of the local dev server (`yarn dev`)
- Open a new window in Chrome.
- Open target URL: https://local.zooniverse.org:3000/projects/fulsdavid/the-daily-minor-planet/classify/workflow/22354?env=production (Daily Minor Planets)
  - A hydration warning should appear.
  - Scroll down to the Project Stats; it should display inconsistent numbers (see screenshot below)
- Refresh the page. Project stats should be normal.

_Screenshot: Project Stats show 0 Classifications Today and 0 Classifications Total, but the bar chart indicates otherwise._

<img width="401" alt="image" src="https://github.com/user-attachments/assets/89ca2865-d9ac-403f-b0ca-c42d8b248d14">

### Extended Testing

<details>
<summary>Asides from the issue seemingly stemming from the "initial Next.JS page fetch", additional testing shows that the Project Stats otherwise works fine.</summary>

- Tested with macOS + Chrome 126 on https://www.zooniverse.org/projects/fulsdavid/the-daily-minor-planet/classify/workflow/22354 and [local](https://local.zooniverse.org:3000/projects/fulsdavid/the-daily-minor-planet/classify/workflow/22354?env=production) (app-project, master)
- I'm able to load the FEM Classify page (while already logged in) and see the initial Classifications Today and Total counts.
While logged in, I can make classifications, and both the Classifications Today and Total counts update as expected. (About 5 classifications per test)
- I can log out, and the counts will reset to 0
- I can login to the same account, or to a different account, and the Classifications Today and Total counts update as expected.
</details>

### Dev Notes

Thoughts 1: I don't have enough expertise on the Next.JS infrastructure to understand why/how the fetch process would be a problem. Is it a hydration thing?

Even if it is, I can't tell if it's anything user-facing (i.e. if it affects the non-dev servers), and how I'd confirm/check that.

Thoughts 2: could it be possible that in certain scenarios, the animation of the `<AnimatedNumbers>` used in the project stats is interrupted, causing the numbers to "freeze" at 0 (for small counts) or appear to "lag" (for larger counts)?

I'm starting to think if it's worth removing **AnimatedNumbers** altogether, if it's a potential cause of problems.

Thoughts 3: this may issue or may not be related to the [Talk post that initiated this investigation](https://www.zooniverse.org/talk/17/3402644), since that volunteer said that despite refreshing their page, the lag still persisted.

> But since then it has started to fall behind the 'classifications today' counter, until it was lagging behind by 55 classifications. I tried refreshing the page, clearing my cache, waiting for an hour and refreshing again, none of which made any difference

But then again:

> Logging out of my account and back in again did seem to do something, though - the total classifications counter is now off by just two classifications. Better, but still not quite what I wanted.

### Status

~~Unknown priority.~~ Impact level unclear, but some volunteers are understandably upset when this occurs. Replicability/consistency of the issue is dubious since it relies on some Next.JS infrastructure shenanigans that I can only consistently replicate on my localhost.

[UPDATE (1 Aug):](https://github.com/zooniverse/front-end-monorepo/issues/6190#issuecomment-2264002520) now set to **low priority.**

**Comment by eatyourgreens** [comment]
If it helps, classification stats aren’t fetched server-side. They’re fetched in the browser, after you’ve been logged in.

**Comment by shaunanoordin** [comment]
## Update

I'm filing this investigation under low priority for now, as the original volunteer has [informed us](https://www.zooniverse.org/talk/17/3402644?comment=5588647) that they couldn't replicate the problem at the moment. I'll still keep this issue open until we know for sure what's been happening.

Also, of interest, the volunteer also added something else that may either be related to this issue, or is tangential to it:

> PS: I have come across the inconsistent UI problem as well, for what it's worth, although for me it usually manifests slightly differently: when I start a fresh session after booting my computer, both stats counters will initially be at 0, with the bar chart for the preceding days also incorrectly at 0. The problem mostly goes away after doing a few classifications and refreshing the page, although occasionally I need to open the classify page in a new tab for the bar chart to be displayed correctly. I have always assumed that this is connected to the fact that I normally stay logged into my zooniverse account.

**Comment by eatyourgreens** [comment]
It might also be worth noting that user project classification counts are cached in session storage, to prevent them being lost when you go to Talk. 

https://github.com/zooniverse/front-end-monorepo/issues/5134#issuecomment-1693125389

**Comment by eatyourgreens** [comment]
@shaunanoordin I can reproduce this bug on the Zooniverse site:

1. Open a Classify page in a tab and do some classifications:
https://www.zooniverse.org/projects/fulsdavid/the-daily-minor-planet/classify/workflow/22354
<img width="400" alt="Classification statistics for Daily Minor Planet: 4 today and 50 total." src="https://github.com/user-attachments/assets/16b4bd35-4cb4-4675-9f03-6a0b9ffd535a">

2. Open the same page in **a new tab**. Today's total is correct but total project classifications are now 0:
<img width="400" alt="Classification statistics for Daily Minor Planet: 4 today and 0 total."" src="https://github.com/user-attachments/assets/95b61002-6609-497c-bdb1-b96d5b1ef6ef">

**Comment by eatyourgreens** [comment]
I’m not 100% sure this is relevant, but each tab has its own, independent Panoptes session. See #4892 and https://github.com/zooniverse/panoptes-javascript-client/issues/207. 

So, in theory, the new tab should log you in, with your secure Panoptes cookie, then request your classification count from the API. I think there might be a bug in the code that makes that request, which is in the user store. TBH, making network requests from a MobX store isn’t a recommended pattern so that code probably needs to be replaced.

**Comment by eatyourgreens** [comment]
Here's the action that fetches your personal stats, when the React app first loads in the browser.

https://github.com/zooniverse/front-end-monorepo/blob/094daf5997cea823dc647b78af31808b9f8a75a9/packages/app-project/stores/User/UserPersonalization/UserPersonalization.js#L75-L83

**Comment by eatyourgreens** [comment]
I just refeshed my browser tab from one hour ago. Project stats have changed, but today's 4 classifications are missing from the overall total. The correct numbers should be; 4 classifications today, 50 classifications overall.

<img width="400" alt="Daily Minor Planet statistics: 4 classifications today, 46 classifications overall." src="https://github.com/user-attachments/assets/fc32c05d-aa13-4ead-b044-121ba3bc78e5">

**Comment by eatyourgreens** [comment]
I added console logs for the `counts` prop, and ran a production build of Daily Minor Planet on `local.zooniverse.org`. The `counts` prop updates as expected, so counts are being fetched properly from the API, but the `YourStats` component doesn't reflect changes to `counts.total`. `counts.today` does update when it changes.

<img width="600" alt="The stats component for Daily Minor Planet, with the browser dev console open. The stats component says 5 classifications today, 0 total. The console log says 5 classifications today, 50 total." src="https://github.com/user-attachments/assets/f8163104-09f1-48f2-9b9c-fd09f2188328">

**Comment by eatyourgreens** [comment]
Logging the props for the `Stat` component shows that the displayed value doesn't match the prop either.

<img width="600" alt="The stats component, showing 0 classifications today, with a dev console log that shows the Stat component value is 5." src="https://github.com/user-attachments/assets/2fe44ecd-f938-4d37-85b6-8986429dd56a">

**Comment by eatyourgreens** [comment]
The `AnimatedNumber` component is being passed a value of 51, but showing a value of 0. That's the same issue I saw in #5971. I find that the bug triggers if I load my classification counts offscreen, so the bug might be in the intersection observer that animates the number.


https://github.com/user-attachments/assets/6f4bcb2d-26eb-43e9-b4f7-30bdbaa2712c


https://github.com/user-attachments/assets/939436b8-8454-4c50-b933-a2f0c5872838

**Comment by eatyourgreens** [comment]
If I load my stats offscreen, `animated` is always false in the `AnimatedNumber` component, when the value first changes from 0 to 5.

<img width="500" alt="Console logs, including the internal state of the AnimatedNumber component, when stats load offscreen." src="https://github.com/user-attachments/assets/88883139-cc4c-48a7-8133-47755e604fc3">

When `animated` is false, `AnimatedNumber` shows 0, so maybe there's a bug here?
https://github.com/zooniverse/front-end-monorepo/blob/094daf5997cea823dc647b78af31808b9f8a75a9/packages/lib-react-components/src/AnimatedNumber/AnimatedNumber.js#L80

**Comment by eatyourgreens** [comment]
NB. that code also means that project stats are always rendered as 0 during SSR. Here are the Node console logs from that same page, running locally.

```sh
counts: { today: 0, total: 0 }
Stat: test-classify-your-stats-today-count Classifications today 0
{ animated: false, value: 0 }
Stat: test-classify-your-stats-total-count Classifications total 0
{ animated: false, value: 0 }
Stat: undefined Volunteers 6190
{ animated: false, value: 6190 }
Stat: undefined Classifications 810216
{ animated: false, value: 810216 }
Stat: undefined Subjects 71804
{ animated: false, value: 71804 }
Stat: undefined Completed subjects 28715
{ animated: false, value: 28715 }
```

**Comment by eatyourgreens** [comment]
Now that I know how to reliably reproduce this bug, here's a screenshot showing the `AnimatedNumber` component in production, with the `value` prop highlighted in the React fcomponent inspector. `value` is 51, but the displayed value is 0, which is pretty much the same issue as #5971.

To reproduce this bug:
1. Use a new tab, so that user preferences (including `activity_count`) aren't already cached in session storage and must be fetched from Panoptes.
2. Make sure the `YourStats` component is offscreen, so that it doesn't animate when stats load from the API.
3. Load the Classify page for a project that you've classified on today.
4. Scroll down to your stats. One will animate to its loaded value, but I find that one will stay stuck at 0 most of the time. Sometimes today's count is stuck at 0, sometimes the total count is stuck at 0.

<img width="800" alt="Daily Minor Planet in Firefox, with the React component inspector open to show that the value prop for AnimatedNumber doesn't match the displayed value." src="https://github.com/user-attachments/assets/2a67156a-3204-441c-9fc5-2cf09dc93f96">

**Comment by eatyourgreens** [comment]
I think I see the bug. The effect hook here captures the `animateValue` closure when `value` is 0. It doesn’t update when  `animatedValue` changes, so I think it’s always going to animate to 0, even though a new `animatedValue` closure is generated when `value` changes. The effect hook executes a stale reference to an older value of `animateValue`. 

The linter should really be warning about missing `useEffect` dependencies here. I’d also be careful about generating callback functions on every render, like you’re doing here, since it’s really easy to accidentally capture a stale variable scope inside a closure. If possible, move your callbacks outside the render function. 

https://github.com/zooniverse/front-end-monorepo/blob/094daf5997cea823dc647b78af31808b9f8a75a9/packages/lib-react-components/src/AnimatedNumber/AnimatedNumber.js#L65

**Comment by eatyourgreens** [comment]
I've opened #6192 to fix the `useEffect` hook, so that the animated value always uses the latest version of the `value` prop.

**Comment by eatyourgreens** [comment]
@shaunanoordin this isn't particularly exhaustive testing, but I'm seeing stats show up correctly in dev mode, with the changes in #6192. Screen recording from Firefox:


https://github.com/user-attachments/assets/bb1ddc1d-a850-43fc-8b19-78ac8808fa2a

**Comment by eatyourgreens** [comment]
Here’s an explanation of the bug. 
1. When the `AnimatedNumber` component mounts, `value` is 0 and `animated` is false. `useEffect` runs and creates an intersection observer which will animate the displayed number from 0 to 0.
2. `value` changes to your actual count but `useEffect` doesn’t run, so the intersection observer doesn’t change. It has captured the value of `value` when it was created, which is 0. 
3. When you scroll the number into view, it animates the displayed number to 0, then sets `animated` to true. 

So the component should always show 0, if it loads offscreen. There’s no story or test for the case where `value` is set asynchronously.

**Comment by eatyourgreens** [comment]
Here's a story that reproduces the bug. On the main branch, this story always shows 0.

```js
export const DeferredAnimation = () => {
  const [value, setValue] = useState(0)
  setTimeout(() => setValue(700000000), 2000)
  return (
    <Box pad={{ vertical: '120vh' }}>
      <AnimatedNumber duration={4000} value={value} />
    </Box>
  )
}
```

**Comment by eatyourgreens** [comment]
@shaunanoordin this might not be a low priority bug after all, given that volunteer classification counts are always displayed as 0 if they load from Zooniverse APIs. They display fine if they load from session storage, which is why refreshing the page fixes them.

**Comment by eatyourgreens** [comment]
For anyone who's made it this far, congratulations, and the title of this issue is wrong. **The bug has nothing to to do with Next.js**.

**Comment by eatyourgreens** [comment]
I've posted a link to Talk that reproduces this bug every time you click it:
https://www.zooniverse.org/talk/17/3402644?comment=5592887

**Comment by eatyourgreens** [comment]
Here's a quick screen recording in Chrome, where I click that link three times and get the wrong counts each time. Weirdly, the daily stats sometimes show up, sometimes show as 0. Total counts are always 0.


https://github.com/user-attachments/assets/65875a9e-7f50-4609-a368-6fb2cf0a797d
