### ISSUE TITLE
SubjectGroupComparison Annotation Bug

### ISSUE THREAD

**Issue by kieftrav** [zooniverse/front-end-monorepo#6224]
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ ] app-project
- [x] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
Research team started creating a group subject selection for FEM and realized that the tool wouldn't allow "selecting" or "annotating" individual subjects within the group viewer. Found that the bug is related to a previous PR that has a list of tasks that enable the Annotate Button in the Classifier, specifically noting that the subjectGroupComparison task does not pass that filter.

## To Reproduce
Load up the Classifer locally and visit Mike Wallamsley's test project ["Not Galaxy Zoo FEM"](https://local.zooniverse.org:8081/?project=mikewalmsley%2Fnot-galaxy-zoo-fem&env=production&workflow=27251). You cannot see the pencil icon indicating the "Annotate" action selecting one of the subjects in the subject group.

## Screenshots
See attached screenshot of both bug behavior and fixed behavior.

<img width="1275" alt="SubjectGroup-Annotate-Bug" src="https://github.com/user-attachments/assets/5a66d4ee-54c8-45df-aced-ee64e8eca51e">
![SubjectGroup-Annotate-Fix](https://github.com/user-attachments/assets/9b211ed8-a9a9-4fbb-9714-2b508e70b5f6)

**Comment by kieftrav** [comment]
Fixed with PR #6223

**Comment by goplayoutside3** [comment]
@kieftrav please close this Issue, thanks!
