### ISSUE TITLE
Fetch user roles

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#623]
**Package** app-project

**Feature or Issue Description**
We need to know if the authenticated user is a project owner, collab, expert, tester, etc. This is stored in a separate resource on Panoptes, so we need to request it and store it too. Then it can be passed along with the user to the classifier to use there _(ONLY NECESSARY FOR GOLD STANDARD CLASSIFICATIONS IF IMPLEMENTED see #1277 )_. 

Also, collections has its own collections roles too, but we can tackle that once we start building out those pages.

**Comment by srallen** [comment]
The classifier would only need to know user roles for the gold standard classification, which we may instead deprecate. There hasn't been a clear request or use case. Potentially a classification flagged as gold standard made by volunteers with the expert role could have down stream decision make effects with Caesar, but again, let's just do it when asked for. 

We still need to know the user roles for the project app to determine whether or not to load a private project or inactive workflows.

**Comment by srallen** [comment]
Projects are loaded server side. Authentication still only happens client side, therefore loading of the user roles will have to wait for client side authentication to finish unless we implement server side authentication. Projects have a boolean attribute for `private` which can be used to determine if the request and render should wait for client side authentication and the request for the user roles to finish.

The app now has an overall `appLoadingState` getter view: https://github.com/zooniverse/front-end-monorepo/blob/379b02980b6bbb0e09b0c43324664745caf50b66/packages/app-project/stores/Store.js#L26-L41

This could be enhanced with including the loading state of the user roles or maybe the user role loading state is looked up independently as needed. The user roles model should be added as a child node to `User`.

**Comment by eatyourgreens** [comment]
The classifier loads project roles now, in order to determine whether you're allowed to view inactive workflows.
https://github.com/zooniverse/front-end-monorepo/blob/1d3f19c83a8e543c3c02de2213fc59776b59ce89/packages/lib-classifier/src/hooks/useProjectRoles.js#L29-L34
