### ISSUE TITLE
New homepage is empty on load

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#6231]
## Package
_Choose from the list:_
- app-root?
## Describe the bug
The new home page loads as an empty page. 

https://github.com/user-attachments/assets/f65e1578-16d1-456e-a2c5-67951383dd57

## To Reproduce
I'm not sure. It happened randomly on my phone but the page consistently reloads blank. ~~If it helps, I was signed out.~~ It happens regardless of whether I’m logged in or not, and the page also loads empty in desktop Firefox.

**Comment by eatyourgreens** [comment]
The new page is running Next.js 13.5, which still had bugs in the app router. That might be the problem here. 

There's also an open redirect vulnerability in the 13.5 app router, published in April I think, which is fixed in 14.1.1.

**Comment by eatyourgreens** [comment]
The same issue happens in desktop Firefox. If it helps, the server is sending a 304 (Not Modified) response with an empty body and an invalid Cache-Control header. There's no value specified for `stale-while-revalidate`, which is a well-known bug in Next.js. They may have fixed that in recent versions.

<img width="800" alt="Screenshot of the Network panel in desktop Firefoxm showing a 304 response. Cache-Control is s-maxage=3600, stale-while-revalidate." src="https://github.com/user-attachments/assets/36759d93-bfb2-4324-9923-acc9f2773bc6">

**Comment by goplayoutside3** [comment]
This bug is caused by https://github.com/zooniverse/front-end-monorepo/pull/6221

**Comment by eatyourgreens** [comment]
@goplayoutside3 no sign of that bug now but one weird thing: `s-maxage` is set to one year ie. the page will be cached by shared caches, like FrontDoor, for one year.

<img width=800 alt="Screenshot of the new page with the dev console open to show the response headers. Cache-Control is set to s-maxage=31536000" src="https://github.com/user-attachments/assets/e55d2b45-fb69-402c-ae07-f54a4e99b115" >

**Comment by eatyourgreens** [comment]
One year cache TTL is the default set by Next.js. 🤷‍♂️ Something to watch out for once you have this running behind a CDN.

>Also the 1-year max age can easily shoot you in the foot if you don't manually purge cache on each deployment, which you most likely don't if you self-host Next.js.

https://focusreactive.com/configure-cdn-caching-for-self-hosted-next-js-websites/#nextjs-default-stale-while-revalidate-implementation

**Comment by goplayoutside3** [comment]
That's why I wanted to add 'revalidate' 🫤 I guess I could try `{ cache: 'no-store' }`, but then why fetch the blog posts serverside at all. I think we'll have to wait until app-root can be upgraded beyond the current Next.js 13 version.

**Comment by goplayoutside3** [comment]
@eatyourgreens I reimplemented revalidate for the Wordpress fetch. Please let me know if you see this bug reemerge at https://fe-root.preview.zooniverse.org.
