### ISSUE TITLE
Survey task: increase task area width to 540px for workflow with survey task

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/front-end-monorepo#6237]
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ ] app-project
- [x] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Is your feature request related to a problem? Please describe.
Allow more space for the task area and its components. In turn, this helps with #6210 when the task is a Survey.

## Describe the solution you'd like
Increase the task area to be 540px. Figme for reference https://www.figma.com/design/ASqNlLhicNRzEDhYDA2t8j/Survey?node-id=65-1006&m=dev&t=PxDxXDB67AH8V9Aa-1 
Specific margins and other annotations here:

<img width="600" alt="Screenshot 2024-08-28 at 1 59 58 PM" src="https://github.com/user-attachments/assets/802e75d4-0787-4487-98b8-c10a76c5f6fa">

**Comment by mcbouslog** [comment]
@seanmiller26 - for a workflow with multiple steps, should the increased task area width apply to steps without a survey task or only to a step with a survey task?

**Comment by seanmiller26** [comment]
Yes, we should keep the task area a consistent size, if possible.

**Comment by mcbouslog** [comment]
@seanmiller26 - currently the subject viewer and task area layout goes from horizontal to vertical at 768px (`small` breakpoint). Should the subject viewer and task area change from horizontal to vertical at a different breakpoint with these changes?

The Grommet ResponsiveContext `medium` breakpoint discussion could be applicable to this issue.

**Comment by seanmiller26** [comment]
Yes, this is something I'd like to explore with this task as a pathfinder for other task types. I think best to move forward with the initial styling in this issue. Then I can try it out on staging and I'll be able to make a more informed decision once I can play around with it.

**Comment by goplayoutside3** [comment]
@mcbouslog there was recent discussion about unexpected changes to task area styling when going back and forth between task types in this Issue: https://github.com/zooniverse/front-end-monorepo/issues/6271#issuecomment-2335148214

Not caused by any changes to the survey task code, but I want to link it here in case it's worth considering better management of task area styling in general.

**Comment by eatyourgreens** [comment]
Hi, I’ve moved that conversation from #6271 to #6275. It’s a bug in the single image viewer styling, when ‘limit subject height’ is enabled. The viewer is styled with `max-height`, so the browser is free to render it at any height smaller than that value.
