### ISSUE TITLE
Add support for the env query param to POST and PUT

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#624]
**Package** lib-panoptes-js

**Feature or Issue Description**
For SSR, we pass along the env query param to set which host to use for the client. POST and PUT still need to be updated to support this. Related to #612

**Comment by eatyourgreens** [comment]
More generally, we support query params on PUT and POST in the existing client so we should allow them in the new client too.
https://github.com/zooniverse/json-api-client/blob/6398c84b23c1a1379f2df48915051218c69f2972/src/make-http-request.coffee#L32-L33

**Comment by srallen** [comment]
Done in https://github.com/zooniverse/front-end-monorepo/pull/1082
