### ISSUE TITLE
Firefox Transcription Task 'page jumping' after viewing completed transcriptions

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/front-end-monorepo#6271]
## FEM
_Choose from the list:_
- [ ] app-content-pages
- [ ] app-project
- [x] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
When classifying on Transcription Task projects in FEM on Firefox, opening a completed (grey) annotation and closing it causes the page to 'reset' to the top of the page, even if the view was scrolled down to the bottom when the modal was opened. This does not happen when clicking into pink lines or when placing a new transcription, only when closing the grey 'view finished transcription' box. Note: this does not happen on Chrome, and shouldn't happen at all, as it's a bad experience for the user.

## To Reproduce
1. Open Firefox 
2. Go to https://www.zooniverse.org/projects/printmigrationnetwork/print/classify/workflow/20199/subject-set/111064/subject/84319114
3. Scroll down to bottom of the subject image (so that top of the image is not in viewport)
4. Click on a grey line to view finished transcription
5. Click on 'x' to close the view transcription box
6. See error (screen will jump to top of the classify page)

## Screenshots
Screen recording 1: grey box behavior only on Beyond Borders on Firefox 

https://github.com/user-attachments/assets/ce2fbc1f-5698-4a6b-a2e6-4fffe0ed8568

Screen recording 2: grey box behavior on PRINT on Firefox, also w/ proof that other uses of the Transcription Task don't cause this same kind of 'jump' 

https://github.com/user-attachments/assets/281e672f-ea86-47f0-97f2-74c177c21000

## Expected behavior
Closing a modal shouldn't change the page focus at all.

### Desktop (please complete the following information):
 - OS: MacOS Ventura 13.6.9
 - Browser: Firefox 
 - Version: 127.0.2

## Additional context
Originally reported on Talk: https://www.zooniverse.org/projects/mainehistory/beyond-borders-transcribing-historic-maine-land-documents/talk/4453/3428338?comment=5631500

**Comment by snblickhan** [comment]
FWIW: I tried to see whether this was specific to the Transcription Task, or if there were other weird Firefox-specific 'page jump' issues. Here's an example from Science Scribbler (note change in image size between marking + question task). NB I don't think this is related (it happens on Chrome, too), but wanted to share just in case, since it seems like an odd thing to happen (not sure why subject image size would change mid-classification):


https://github.com/user-attachments/assets/64440326-f251-480c-8d8d-e5c0120680e3

**Comment by eatyourgreens** [comment]
Poor focus management strikes again. This is also an accessibility issue, specifically WCAG 2.4.3, which is a level A requirement. 
https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html

Focus order must be predictable. In this case, focus should return to the grey line when the modal closes.

**Comment by eatyourgreens** [comment]
>FWIW: I tried to see whether this was specific to the Transcription Task, or if there were other weird Firefox-specific 'page jump' issues. Here's an example from Science Scribbler (note change in image size between marking + question task). NB I don't think this is related (it happens on Chrome, too), but wanted to share just in case, since it seems like an odd thing to happen (not sure why subject image size would change mid-classification):

This is caused by the viewer CSS changing when you move from one task to another (which is weird because the viewer styling is supposed to be independent of the task.) Watch how `grid-template-columns` changes here. In particular, the width of the first column changes from 90px (drawing task) to 75px (question task.)


https://github.com/user-attachments/assets/a38a4159-18d8-46e3-b032-a5514ec9799b

**Comment by eatyourgreens** [comment]
Sorry, something else I've bnoticed in that Science Scribbler video. On the question task, the pencil button is active, even though drawing is disabled.

**Comment by eatyourgreens** [comment]
#6272 fixes the focus management bug for transcription tasks in Firefox, where focus is jumping to the document body when the consensus popup closes.

You probably want to open a separate issue for the subject viewer changing size in Science Scribbler.

**Comment by eatyourgreens** [comment]
I moved all the Science Scribbler comments to #6275.
