### ISSUE TITLE
Users see a placeholder Profile Page

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/front-end-monorepo#6312]
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ ] app-project
- [ ] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
If you open the user's profile link directly from this Talk thread, (a PFE page) it opens properly. https://www.zooniverse.org/talk/2354/3435274?comment=5652467 

Opening in a new tab or copy+paste shows the issue: https://www.zooniverse.org/users/am.zooni 

<img width="600" alt="Screenshot 2024-09-17 at 5 37 44 PM" src="https://github.com/user-attachments/assets/825c334c-2097-44b0-b1de-5e8c4b8c77cc">

**Comment by goplayoutside3** [comment]
This might be an Issue for the [static](https://github.com/zooniverse/static) repo and should be investigated by @zwolf.

A browser request to a user's profile landing page such as https://www.zooniverse.org/users/goplayoutside3 should always --> proxy --> PFE.

**Comment by seanmiller26** [comment]
@goplayoutside3 It was found in the linked Talk thread!

**Comment by goplayoutside3** [comment]
> was it found by a volunteer trying to see their own profile page?

`am.zooni` clicked Profile in the ZooHeader on PFE or FEM and saw the above screenshot. It's a blank page in FEM's codebase.

**Comment by zwolf** [comment]
Fixed by https://github.com/zooniverse/static/pull/377
