### ISSUE TITLE
Design review of Project Statistics widget

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#632]
**Package**

app-project

**Feature or Issue Description**

@beckyrother provided the following design notes:

![Screenshot_3_29_19__11_48_AM](https://user-images.githubusercontent.com/2725841/55249500-1ed46300-5244-11e9-8e34-9b8449173733.png)

**To Dos**

- [x] Change animated number colour to #5c5c5c (fixed by e3dda56134fa48ea0677d7c552ee5d5a59139ad0)
- [x] Increase size of secondary labels

**Comment by rogerhutchings** [comment]
@beckyrother, the `font-size` for title, subtitle and lipsum text is all `14px`?

**Comment by beckyrother** [comment]
My mistake! Maybe the primary label is just too far away – should be 20px

**Comment by rogerhutchings** [comment]
Fixed by #635
