### ISSUE TITLE
Errors in project classification counts

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#6329]
## Describe the bug

The new user classification counts, published last night, don’t agree with the counts that were published on the old home page. Some volunteers are reporting differences of thousands of classifications, in total, for their new user stats. 

Here’s a couple of examples from my account. 

New user stats page stats (all time):
- Diagnosis London: 468
- Science Gossip: 313
- Snapshots at Sea: 108

Old home page stats:
- Diagnosis London: 253
- Science Gossip: 524
- Snapshots at Sea: 94

## To Reproduce
Logged in as a Zooniverse volunteer, go to More Stats and select All Time for the time range. Project classification counts are shown under Top Projects. Compare the new counts with the counts shown on https://pr-7177.pfe-preview.zooniverse.org/#projects. Differences show up for both Ouroboros and Panoptes projects, with older projects (pre-2019 maybe) more likely to show large differences from the `activity_count` stored on your project preferences.

## Expected behavior
Classification history shouldn't have changed during the move to a new stats API. Total classifications for a given project should match `user_project_preferences.preferences.activity_count` for that project.

## Additional context
This seems like a problem that should have been caught by spot checking some volunteer accounts prior to launch, or by snapshot testing against the old counts. Generate project classification snapshots for a few thousand sample accounts on the old API, generate the same snapshots with the new API then assert that the snapshots match. 

FWIW I use this technique in one of my current software projects to check that backend changes can be deployed to production without breaking research models in the production database. Before a release, the release branch is tested against snapshots generated on the main branch, using real data. It's a very useful technique.

**Comment by eatyourgreens** [comment]
The old home page uses `preferences.activity_count`, which ignores any classification where either:
- you had already classified that subject.
- the subject was retired.

If the ERAS count includes duplicates and retired subjects, that might explain the sudden increase in classification counts for PFE projects.
https://www.zooniverse.org/talk/2354/3435274?comment=5657245&page=7

**Comment by eatyourgreens** [comment]
The new code uses `preference.activity_count` here:
https://github.com/zooniverse/front-end-monorepo/blob/a4fba3d2143940998b746356961fa7243b419932/packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjects.js#L54-L61

but ERAS here:
https://github.com/zooniverse/front-end-monorepo/blob/a4fba3d2143940998b746356961fa7243b419932/packages/lib-user/src/components/shared/TopProjects/TopProjects.js#L115-L122

That leads to inconsistent and confusing UX in the new code, where the same project can show two different numbers for the same volunteer.

**Comment by eatyourgreens** [comment]
Aft4er chatting with @yshish and others, another difference we're seeing is that ERAS reports a different number of projects worked on.

For my account:
- Panoptes API: 148 projects.
- ERAS API: 155 projects.

For @yshish:
- Panoptes API: 89 projects.
- ERAS API: 93 projects.

The problem with having launched a new home page, and also changed how projects and classifications are counted, is that people are confused by the change in numbers, and consequently unsure whether they can trust the new stats.

**Comment by goplayoutside3** [comment]
All classification counts on public facing Zooniverse webpages are now using ERAS. I'm going to close this Issue because ERAS is the source of truth for all user stats and project stats regarding classification counts going forward.

Some of the descrepancies mentioned in this Issue have also been discussed at length on Talk, but in short:
- ERAS counts submitted classifications on retired subjects
- ERAS counts submitted classifications on already seen subjects
- General classification counts per user fetched from ERAS will include private projects, and if a project was a legacy Ouroboros project, its stats must have been migrated to ERAS. Not all legacy projects from Ouroboros were migrated to ERAS.
    - Given this behavior, you might see a total projects count on your personal stats page different than the total projects count previously seen on the old homepage.
