### ISSUE TITLE
Design review for task area

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#633]
**Package**

lib-classifier

**Feature or Issue Description**

@beckyrother provided the following design notes:

![Screenshot_3_29_19__11_46_AM-2](https://user-images.githubusercontent.com/2725841/55249748-b89c1000-5244-11e9-9155-2446f9c4f154.png)

**To Dos**

- [x] Adjust padding
- [x] Add colour for active tab (captured in #620)
- [x] Align task area and bottom of classifier (captured in #561)

**Comment by srallen** [comment]
The paragraph text is fixed in #645
