### ISSUE TITLE
Entire  Zooniverse web site blocked from search engines

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#6331]
## Describe the bug
Since launching the new home page, the `www.zooniverse.org` domain is blocked from appearing in search engines. 

<img width=400 alt="Search results for Eclipsing Binary Patrol. The Zooniverse entry is a message about being blocked from showing a result." src="https://github.com/user-attachments/assets/ee00319f-918a-4b5e-a111-09f77f305bf4">

## To Reproduce

https://www.zooniverse.org/robots.txt disallows indexing of all URLs on the Zooniverse domain. 

You can reproduce the problem by searching for Eclipsing Binary Patrol in DuckDuckGo. 
https://duckduckgo.com/?q=eclipsing+binary+patrol&t=iphone&ia=web

Google doesn't seem to be affected.
https://www.google.co.uk/search?q=eclipsing+binary+patrol

## Expected behavior
Search engines should be allowed to index Zooniverse, so that people can find new projects.

## Additional context 
- #6010 added a `robots.txt` file that blocks deploys from being indexed. 
- you can use Google Page Speed Insights to check SEO errors: https://pagespeed.web.dev/analysis/https-www-zooniverse-org/zek3cq1vmw

**Comment by eatyourgreens** [comment]
Google shows links to Zooniverse. Like DuckDuckGo, the description is blocked. 

<img width=400 alt="Galaxy Zoo linked from a Google search for 'galaxy zoo website.' The listing says that Google is blocked from showing information about the page." src="https://github.com/user-attachments/assets/06ffae21-7566-4365-b084-b1c2887f9a29">

**Comment by lcjohnso** [comment]
Adding `robots.txt` originated from wanting to prevent indexing of staging pages (see https://github.com/zooniverse/front-end-monorepo/pull/2541). Consistent with previous homepage behavior, the restriction should be removed for the main Zooniverse domain.

**Comment by eatyourgreens** [comment]
>Adding robots.txt originated from wanting to prevent indexing of staging pages (see https://github.com/zooniverse/front-end-monorepo/pull/2541). Consistent with previous homepage behavior, the restriction should be removed for the main Zooniverse domain.

The `robots.txt` files I added in #2541 don't actually work, as I didn't publish them to their respective domain roots. 😞

**Comment by eatyourgreens** [comment]
I've opened #6335 to publish `/robots.txt` for the standalone projects app.

**Comment by snblickhan** [comment]
A report from Justin Schell re: Mapping Prejudice (project ID: 3877).

Workflow 25524 is appearing in Google search results via an FEM link (frontend.preview), but MP is a PFE project. This has led to one case where someone found this link by searching "washtenaw Zooniverse" and inadvertently submitted FEM classifications to a PFE project, not realizing there was any difference. See screenshot below: 

<img width="738" alt="washtenawzooniverse" src="https://github.com/user-attachments/assets/19986e63-2d85-40d5-8c24-57fa2adbd196">

**Comment by eatyourgreens** [comment]
@snblickhan https://frontend.preview.zooniverse.org/robots.txt blocks search crawlers, but I think it didn’t exist prior to last week.

**Comment by eatyourgreens** [comment]
#6340 might remove `/robots.txt` from staging too.

**Comment by goplayoutside3** [comment]
@eatyourgreens do you have a suggestion on how to solve the scenarios you described? We do not want www.zooniverse.org/robots.txt, but we do want frontend.preview.zooniverse.org/robots.txt. How to make that happen?

**Comment by eatyourgreens** [comment]
Can you selectively add that file to the staging deploy, but not to the production deploy? I haven't thought about this for a long time, but I believe that staging and production use different Docker images.

**Comment by eatyourgreens** [comment]
A very quick search of the app router docs found the answer. 

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/robots

**Comment by goplayoutside3** [comment]
> the answer

I don't see any mention in the docs link about selective deployment. Unless you're considering using a `robots.js` file to look for certain env variables 🤔 

Was there a different question you're looking for the answer to?

**Comment by eatyourgreens** [comment]
I hacked something together very quickly in #6341. It seems to work.

**Comment by eatyourgreens** [comment]
For pages on `frontend.preview.zooniverse.org`, or `fe-root.preview.zooniverse.org`, that have already been indexed by Google, you might need to go into Google's search tools (as owners of those subdomains) and explicitly ask Google to remove them from the search index.

**Comment by eatyourgreens** [comment]
You can also add
```html
<meta name="robots" content="noindex nofollow">
```
to pages that you don't want to be indexed eg. staged projects.
https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag

**Comment by goplayoutside3** [comment]
Via discussion with @zwolf we decided to use the following strategy:
- fem apps all serve the restrictive version of /robots.txt
- host the permissive one in blob storage
- proxy explicit requests to [www.zooniverse.org/robots.txt](http://www.zooniverse.org/robots.txt) to the permissive version

See https://github.com/zooniverse/static/pull/380 and https://github.com/zooniverse/front-end-monorepo/pull/6340

**Comment by eatyourgreens** [comment]
Looks like static.zooniverse.org is already in the Google index, including some data CSVs. 

https://www.google.com/gasearch?q=site:static.zooniverse.org

**Comment by goplayoutside3** [comment]
Fixed by https://github.com/zooniverse/static/pull/380 and Google is re-crawling.
