### ISSUE TITLE
Unread notifications vanish on the app-root pages

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#6337]
## Package
- app-root

## Describe the bug
Unread notifications vanish when I go from Talk to the new home page, then reappear when I go back to Talk.

## To Reproduce
Here's a video where I've got 2 unread notifications in the top bar, but they don't appear on the home page.

https://github.com/user-attachments/assets/0f77a4c9-baa8-45a6-946f-3d0725446191

## Expected behavior
Unread notifications should be consistent across the various different React apps that make up the Zooniverse site.

**Comment by goplayoutside3** [comment]
@eatyourgreens is this true for all app-root pages? Or just the homepage at `/`?

**Comment by yshish** [comment]
It happens to me with unread messages. After counting 45 seconds, the unread messages do get loaded on the home page. @eatyourgreens have you tried waiting for so long? :)

**Comment by eatyourgreens** [comment]
@goplayoutside3 here's a longer video where I click around a few different pages, including Panoptes Front End and both Next.js apps. Notifications are missing across all the pages from the new app (`app-root`.) Might be related to #6336.

@yshish I haven't tried waiting to see if the notifications load eventually.


https://github.com/user-attachments/assets/fa8eff0d-0b24-4043-9c6c-0eb6f0b60e63

**Comment by yshish** [comment]
(Ah, just visited the home page again to see whether it happens for both notifications and messages to me and waited for longer than 2 minutes before the unread loaded. And yes, it happens for both.)

**Comment by eatyourgreens** [comment]
I just waited for 2 minutes on the home page but nothing changed, so maybe this is a different bug from #6336.

**Comment by eatyourgreens** [comment]
I can reproduce that by leaving the home page, going to Talk, and coming back to the home page. I can also force the home page to reload notifications, by going to another tab then back to the Zooniverse tab, which forces the API request to refresh. In that case, unread notifications generally show up.

**Comment by eatyourgreens** [comment]
OK, after a bit of playing around on the Zooniverse site, here's my workaround to make notifications appear instantly:
1. Go from Talk (or wherever) to the home page.
2. If the home page isn't showing your notifications, switch to another tab in your browser.
3. Switch straight back to the Zooniverse home page tab.
4. Notifications should be showing on the home page now.

Technical details: I think I implemented the notifications count with [SWR](https://swr.vercel.app/), which refreshes API data when either tab visibility or tab focus changes, so switching to a new tab and back can force it to perform a data fetch.

So many sites use SWR, or React Query, now that I use this trick on many web pages to force data to refresh.

**Comment by eatyourgreens** [comment]
This bug vanishes if you go into local storage and delete the `panoptes-user` object, so I think it's caused by stale notification counts cached in local storage.

**Comment by eatyourgreens** [comment]
D'oh! Notifications and messages don't wait for `auth.checkCurrent()` to resolve, so they are requesting personal data before you have finished logging in.
https://zooniverse.github.io/panoptes-javascript-client/#panoptes-javascript-client-auth-authcheckbearertoken

I somehow managed to forget my own documentation when I wrote those hooks.
