### ISSUE TITLE
Squirrel Mapper subjects aren't loading

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#6343]
## Package
- lib-classifier

## Describe the bug
Squirrel Mapper subjects aren't loading on workflow 20808. Instead, each subject gives an error in the browser console.

```
Subject 85443806 is not a valid subject.
```

## To Reproduce
1. Go to https://www.zooniverse.org/projects/bcosentino/squirrelmapper/classify/workflow/20808
2. Open the dev console to see the actual error.

## Expected behavior
The subjects are image subjects with multiple locations, so should load without problems.

## Additional context
Each subject has a `zooniverse_id` property, which isn't allowed by the `Subject` model.
https://github.com/zooniverse/front-end-monorepo/blob/a240e57ef3ad55041969414e7835a8f5f9fcbd76/packages/lib-classifier/src/store/subjects/Subject/Subject.js#L13-L26

**Comment by goplayoutside3** [comment]
Subjects in other workflows of this project, such as https://www.zooniverse.org/projects/bcosentino/squirrelmapper/classify/workflow/20578, also have a `zooniverse_id` property. It is not unique to subjects not loading in workflow 20808

**Comment by goplayoutside3** [comment]
Broken subjects are audio recordings instead of images, such as https://www.inaturalist.org/observations/51046966.

**Comment by eatyourgreens** [comment]
The one I checked only had images, but I didn’t note the subject ID.

**Comment by goplayoutside3** [comment]
> Oh wait, the classifier just stops displaying any subjects if there’s a single invalid subject anywhere in the queue. I only checked the first subject in the queue.

Yes, was just typing this. Even if the first subject served to you in the queue does have images in `locations`, a different subject in the queue that is missing `locations` because it's an audio recording will cause the error. The audio recordings were not intended to be subjects for this workflows as far was we know.

**Comment by eatyourgreens** [comment]
Is there a limit on the number of locations? I'm now seeing subjects load, without any errors, but the subject viewer doesn't render. Each subject has 11 jpeg images.

**Comment by goplayoutside3** [comment]
@eatyourgreens thanks we are aware of the 403 response. Zach is working on a fix as we speak.

**Comment by goplayoutside3** [comment]
Workflow 20808 is being deactivated for now and in communication with the researchers. The workflow is also 99% so we’re only seeing the busted, unretired/underclassified ones, which includes subjects that 403, or have more than 10 images. 

I plan to make a PR to remove the limit on 10 `locations`, but also handling of these specific iNat subjects may change a bit to avoid future problems in the automated process (exclude audio subjects, maybe trim those with 20 images, etc)

**Comment by goplayoutside3** [comment]
The fix for subject locations count is in place so I’m going to close this FEM Issue. All other busted subjects on the Squirrel Mapper deactivated workflow are unrelated to frontend code
