### ISSUE TITLE
Rebuild subject queue on login / logout

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#636]
**Package**

lib-classifier

**Feature or Issue Description**

We need to rebuild the subject queue when the user logs in or out, as it will contain states that are no longer accurate (e.g. `already_seen`)

**Comment by eatyourgreens** [comment]
One way to do this would be to key the classifier on user ID, so that it unmounts and remounts when the user changes.

**Comment by eatyourgreens** [comment]
I think that's currently handled by keying on workflow ID, so the key could be expanded to `workflow-${workflow.id}-user-${user.id}` when there's someone logged in.

**Comment by eatyourgreens** [comment]
Turns out the classifier is already set to unmount when the user changes.
https://github.com/zooniverse/front-end-monorepo/blob/2b776f73966ad53fd629feddbed7bf768efcd991/packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js#L81-L92
