### ISSUE TITLE
Home page recent projects are shown in reverse order

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#6407]
## Package
- app-root or lib-user. I'm not sure.

## Describe the bug
After doing some classifications today for Material Culture of Wills, then some classifications for Squirrel Mapper, the order of today’s projects on the home page is reversed:
1. Material Culture of Wills.
2. Squirrel Mapper.

## To Reproduce
Classify on more than one project, then look at your recent projects on the home page.

## Expected behavior
Projects should be listed with my most recent classification activity first.

## Additional context
I'm reasonably sure this bug was introduced by #6397.

**Comment by goplayoutside3** [comment]
See https://www.zooniverse.org/talk/2354/3435274?comment=5722201

Copying the Talk explanation for clarity:
We’re going to revert this change by the end of next week based on your input and the UI/UX decision that recent projects should display in the exact order in which classified.

The new stats service ERAS involves time aggregation, so the request for projects a person has classified on will never return a fine-grained response smaller than 24hrs. ERAS will return projects in the order of what was done in a current time bucket, and the smallest time bucket is one day. The unexpected behavior of seeing projects in an order different than recent subjects is more noticeable when you’ve classified on multiple projects in one day and also visit your homepage to look at the Continue Classifying section frequently.

**Comment by eatyourgreens** [comment]
Thanks for the explanation. By the way, updates to user project preferences (UPP) don’t accurately reflect recent classifications either, because PFE projects update your UPP when you visit a project. A finished or paused project can jump to the top of your recent activity list if you go back and look at it.

**Comment by goplayoutside3** [comment]
> updates to user project preferences (UPP) don’t accurately reflect recent classifications either

Agreed! But this is how the old PFE homepage worked, and it's what we'll have to fallback on while working on a strategy for the best recent projects UX.
