### ISSUE TITLE
Home page ERAS stats queries often run slow

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#6417]
## Package
- lib-user (I think.)

## Describe the bug
When I visit the home page, there's always a noticeable delay before classifications stats are displayed. Looking in the network panel, API requests to `eras.zooniverse.org` often run slow (taking > 1s to get a response and marked with tortoise icons in this screenshot.)

<img width=800 alt="The browser network panel in Firefox, showing network requests to eras.zooniverse.org. A number of requests take more than 1s, and are flaggeed with a tortoise icon." src="https://github.com/user-attachments/assets/1d684eea-285c-4b46-b9c2-11972267f96a">

## To Reproduce
Visit the home page and inspect requests to `eras.zooniverse.org` in browser dev tools.

There’s also a noticeable delay, and layout shift, while the numbers load. 

## Expected behavior
API requests to other Zooniverse services usually take ~70ms or so. 1s seems excessive for a small request.

**Comment by goplayoutside3** [comment]
@eatyourgreens could you elaborate why this Issue is opened on FEM instead of eras?

The code for fetching stats uses SWR in the code file below. Without more detail in this Issue, I'll have to close it without actionable solutions.

https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-user/src/hooks/useStats.js

**Comment by eatyourgreens** [comment]
Sorry, please do feel free to move it to ERAS. I can't reassign it to another repo.

In the frontend, maybe have a placeholder to mitigate the layout shift while slow requests resolve but you're right, this is an ERAS issue.

**Comment by eatyourgreens** [comment]
As a bit of astronomy trivia, 1.2s is roughly the delay you would expect from the server if ERAS were hosted on the Moon.

**Comment by goplayoutside3** [comment]
Agreed that a placeholder could mitigate the layout shift.
