### ISSUE TITLE
Guide volunteer to workflow selection/project selection for finished or already seen states on subjects

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#642]
**Package** lib-classifier

**Feature or Issue Description**
The already seen/finished banners have a tooltip with an explanation, we could maybe include a button to open up the project selection modal which could also include options to select other workflows too if the current project allows it. cc @beckyrother (we discussed this on slack)

**Comment by rogerhutchings** [comment]
Bumping from the milestone as it's a future enhancement

**Comment by goplayoutside3** [comment]
Closing because this is not planned/designed at the moment
