### ISSUE TITLE
Support light/dark theme for field guide

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#643]
**Package** lib-classifier

**Feature or Issue Description**
Add light/dark theme support.

**Comment by rogerhutchings** [comment]
cc #653

**Comment by mcbouslog** [comment]
It looks like for the FieldGuide.js component I should use `withThemeContext` from `lib-react-components`, similar to the recent changes to Tabs or the Next and Done buttons?

The `lib-react-components` Modal has some padding, so I think I should refactor to work with the theme similar to the PlainButton component?

Mentioning @rogerhutchings who worked on recent changes noted above.

**Comment by rogerhutchings** [comment]
Yeah, if you want to make changes to the theme just for this component, you can use `withThemeContext` and pass in the component as the first argument, and the custom theme object as the second. Were you able to inspect the theme object in this component and see if it's changing or not? If it's not immediately available, you can use the `withTheme` HOC from `styled-components`, which will pass in the `theme` as a prop

**Comment by mcbouslog** [comment]
The Modal is inserted as the 3rd child within `<body>`, after `<script src="main.js" />`, so it doesn't have ThemeProvider and maybe other relevant HOCs? So I can send the theme (reflecting light/dark toggle) to Modal as prop and works from there, will put up related PR shortly.

**Comment by eatyourgreens** [comment]
React Portals should pass props/context down via the react tree, not the DOM tree. That's why they were added to React, to solve these sorts of problems where a child of a component isn't its child in the DOM.

That said, I'd give the provider a try and see if that fixes this.

**Comment by mcbouslog** [comment]
I tried creating a [codepen](https://codesandbox.io/s/6jnn5ornkn?fontsize=14) in the Grommet.js file to demonstrate weirdness. I think there's a bug with Grommet theme?

I'm almost done implementing with passing the theme as a prop from the Container to Modal, not ideal, but I think ok until issue noted resolved.

**Comment by srallen** [comment]
I'm looking at the codepen (here's the popped out version that I think is a little easier to use with react dev tools: https://6jnn5ornkn.codesandbox.io/grommet), I see that the `LayerContainer` gets the theme with the customizations in the context:

![Screen Shot 2019-05-09 at 9 53 27 AM](https://user-images.githubusercontent.com/5016731/57463466-7a7d0d80-7240-11e9-98e7-9bfc532f24e2.png)

But the theme prop on the same component does not and also is not getting the `dark: true` setting, so it's just the original base theme being passed as the prop:

![Screen Shot 2019-05-09 at 9 53 44 AM](https://user-images.githubusercontent.com/5016731/57463497-87016600-7240-11e9-9b0a-d09a48739d4f.png)

This reminds me of some the styling issues we saw, before updating React, where the Grommet team said that the older issue was a bug in React's context itself. The theme is getting set in the `LayerContainer` here: https://github.com/grommet/grommet/blob/master/src/js/components/Layer/LayerContainer.js#L75

It's unclear to me if this is a Grommet bug or a React bug. Check out this site that a fellow user of Grommet put together:

https://grommet-dashboard.herokuapp.com/components?theme=black

You can switch between themes and the Layer looks I think as expected, but I see the same difference between the theme context vs theme prop on the LayerContainer.
