### ISSUE TITLE
Classify page skips heading levels

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#663]
**Package**
lib-classifier

**Feature or Issue Description**
![Screenshot showing the heading level hierarchy on the classify page](https://user-images.githubusercontent.com/59547/55725836-5f7f6980-5a06-11e9-9528-55e02dc0a05f.png)

The classify page section structure skips straight from H1 to H3.

**Comment by eatyourgreens** [comment]
The project home page skips from H1 to H4.
![Screenshot showing the heading hierarchy on the project home page.](https://user-images.githubusercontent.com/59547/55733312-842f0d80-5a15-11e9-836c-4046d5cb18dd.png)

**Comment by srallen** [comment]
@eatyourgreens Maybe we make `'Finished for the Day?` on the classify page an H2?

**Comment by eatyourgreens** [comment]
@srallen you could do. The other sections of the page would need appropriate levels too, unless they become subsections of Finished For The Day?

**Comment by eatyourgreens** [comment]
Page structure is linked to #671 too.
