### ISSUE TITLE
Design: Field Guide

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/front-end-monorepo#666]
- [x] Is it possible to drag the field guide around the screen? One of the main goals for moving this to a modal was to allow it to stay open while the user makes classifications. (interim solution in #697)

- [x] All modals should have a shadow to indicate that they are 'floating' above the main site content `box-shadow: 0px 10px 20px #00000030;`

- [x] Margins should be even at 30px between left and right sides. (This is my fault as the InVision did a bad job)

- [x] Decrease margin between the H2s and the paragraphs under them – both elements do not need margins.

- [ ] Thumbnail title: `line-height: 18px`

**Comment by eatyourgreens** [comment]
Anything that’s draggable with a mouse should also be moveable with the keyboard. 

Modals, by definition, block interaction with anything else while they’re open. I don’t know if our Modal component will allow you to classify while it’s open.

**Comment by beckyrother** [comment]
I recognize that this is different to our other modals; the reason to make this a modal rather than a sliding panel was to be able to classify at the same time rather than some volunteers keeping two browser windows open.

**Comment by eatyourgreens** [comment]
Grommet’s Layer component lets you turn off modal behaviour, so that’s good. I don’t know if Layers can be moved, though.

**Comment by eatyourgreens** [comment]
@beckyrother Grommet is opinionated about modals. If you want the classifier to be available while the guide is open, the Field Guide can’t be modal.

**Comment by beckyrother** [comment]
Is there another component that could be used instead?

**Comment by rogerhutchings** [comment]
Not in grommet

**Comment by eatyourgreens** [comment]
You can have floating layers that aren’t modal in Grommet, but I don’t know if they can be moved around.

**Comment by eatyourgreens** [comment]
I’m leaning towards the Field Guide being a separate thing that can be linked to from the classifier and Talk, per #662.

**Comment by beckyrother** [comment]
Is it possible to pop out the component into a separate window? This current modal is likely going to make classification worse if the modal covers up the subject image. 

In the future, what is a good way to communicate design intent like this? Since I'm not in the Oxford office to drop by and see progress and the Zoominar about this was so long ago, I'm not sure where best to have included this information.

**Comment by srallen** [comment]
@beckyrother I think we could look into opening in an actual pop up window. For the beta test with TESS and likely the launch, it will unfortunately have to be this initial modal implementation. What we could do is take advantage of some of the options we do have with Grommet's Layer component in the interim. Would having it at least open off to the side help? Like: https://storybook.grommet.io/?path=/story/layer--cornerlayer

We could also disable the modality, which would remove underlay preventing interaction with the classifier. 

As for design notes, maybe the comment mode in indesign? We use those as the reference for what to do, so that might be a good place to leave these kinds of notes.

**Comment by eatyourgreens** [comment]
I think staging work-in-progress, like we do with PFE, will also help, so that @beckyrother can comment on it before it's merged to master. This should have been caught while we were discussing the PR last week.

**Comment by srallen** [comment]
@beckyrother the title is rendering a paragraph tag. Do you want that to be the line-height for all paragraphs or just this one?

**Comment by beckyrother** [comment]
@srallen yes, the storybook component without the modality would be a bit better – as it stands now it's not useful to cover up the subject image with reference photos. 

I'll make sure to leave notes in InVision, but yes, please tag me (and continue to tag me if I've not answered) as soon as there's a staging branch ready so I can check it earlier on. 

That line-height should apply to all paragraph tags.

**Comment by srallen** [comment]
We've turned off the modality of the field guide and set its position right in #697
