### ISSUE TITLE
Add subject viewers etc to classifier exports

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#69]
**Package**

`lib-classifier`

**Feature or Issue Description**

via https://github.com/zooniverse/front-end-monorepo/pull/29#pullrequestreview-134123456

The classifier currently only exports the main classifier component. We talked about also exporting the various subject viewers that will exist as well; is there anything else that might be useful?

**Comment by srallen** [comment]
I think we've decided to move subject viewers into their own package instead.
