### ISSUE TITLE
Application metrics for monitoring app health and performance

### ISSUE THREAD

**Issue by camallen** [zooniverse/front-end-monorepo#691]
How will we gain metrics about how the node app is working internally? Looks like we could use new relic to help with this.
https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/install-nodejs-agent

**Comment by rogerhutchings** [comment]
cc #217

**Comment by rogerhutchings** [comment]
Cool, can you invite me to NR and I'll get this added in
