### ISSUE TITLE
Should we support `//` as a subject metadata filter?

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#693]
**Package** lib-classifier

**Feature or Issue Description**
This came up in #665:

> Also, the original implementation of the filters supports // as a filter, but I do not know of any project that uses this? I think we should drop support for it.

**Comment by rogerhutchings** [comment]
Let's support it. It costs us virtually nothing to do, and covers us in case someone follows the original implementation without knowing about us dropping it.
