### ISSUE TITLE
Error UI for classifier

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#70]
**Package**

`lib-classifier`

**Feature or Issue Description**

via https://github.com/zooniverse/front-end-monorepo/pull/29#pullrequestreview-134123456

The classifier needs a user interface for handling errors. Is there one designed? @beckyrother

**Comment by goplayoutside3** [comment]
Closing due to lack of detail. Can re-open if designs are funded/implemented.
