### ISSUE TITLE
Needs some help modal styles fixes

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#709]
**Package** lib-classifier

**Feature or Issue Description**
Why is the text so big?

<img width="742" alt="Screen Shot 2019-04-11 at 5 30 47 PM" src="https://user-images.githubusercontent.com/5016731/55974469-9ca26080-5c7f-11e9-807f-9dc67463f3c4.png">

**Comment by srallen** [comment]
Might be because of my sloppy setting of the string text via console.

**Comment by eatyourgreens** [comment]
Everything in the box is H2. Markdown error? The task help for Galaxy Zoo looks ok. https://fe-project.preview.zooniverse.org/projects/zookeeper/galaxy-zoo/classify

**Comment by srallen** [comment]
Yes I think that's it. I copied and pasted from the production workflow while putting this one together for testing on staging for semi-real content and I don't think the line breaks got in there correctly in the string.
