### ISSUE TITLE
Update dark theme colours on LCV

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#735]
**Package**

lib-classifier

**Feature or Issue Description**

Following #653, we need to update the dark theme colours for the LCV. @shaunanoordin came up with some themes in #400.

@beckyrother which do you want to use for the dark theme?

**Comment by beckyrother** [comment]
How would we feel about keeping the graph the same?

**Comment by rogerhutchings** [comment]
I'm not bothered either way :) If you'd rather do that, then please close this issue and we can reopen it later if needs be.

**Comment by beckyrother** [comment]
Looks like I'm not able to close this but if you're able to please go ahead.
