### ISSUE TITLE
Make project name, theme toggle sticky

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#738]
**Package**

app-project

**Feature or Issue Description**

Following #653, the project name and theme mode toggle are currently rendered at the top of the classify page; these should centre themselves in the viewport, and be made sticky

**Comment by srallen** [comment]
Given the space they take up on the mobile view (see screen shots in https://github.com/zooniverse/front-end-monorepo/issues/746#issuecomment-487744230 and in #790), they probably shouldn't render on the side once the ResponsiveContext becomes 'small'

Maybe the project display name moves above the subject viewer and the toggle for dark mode move below the subject metadata buttons?

**Comment by beckyrother** [comment]
Please also add the underline hover state to the theme toggle – should look and behave the same as the 'add to favourites' etc. (Sorry if this is not the right place to put this comment.)

**Comment by goplayoutside3** [comment]
These components are removed in favor of a them toggle in ZooHeader
