### ISSUE TITLE
Buttons in classifier Task Area need to be updated for dark mode

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#744]
**Package**

lib-classifier

**Comment by srallen** [comment]
Is this a dup of the one I opened for #759? I'm not sure since there's no additional description.

**Comment by rogerhutchings** [comment]
well, it would include the single / multiple choice workflow buttons as well, but we might as well sort those out when we actually need to

**Comment by srallen** [comment]
Ah, good point. Is it ok to rename this one to be about those since I opened #795 about the task nav and didn't realize this was already open?

**Comment by rogerhutchings** [comment]
Actually, we might as well close this and circle back to it when we need to 🎉
