### ISSUE TITLE
Design: Mobile issues

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/front-end-monorepo#746]
### Tutorial
- [x] add a 'get started' button on the last slide of the tutorial (also applies to the desktop version)
- [ ] the circles within the page indicators are not centered. this is because the circle is an even px width; increase the outside circle by 1px 
![IMG_4692](https://user-images.githubusercontent.com/1392130/56610134-6694a300-65d4-11e9-9283-9f407664799b.png)

---

### Interface
- [x] left align info, favourites, collections buttons to the left edge of the subject
- [x] adjust padding so it's even between buttons
- [x] Task/Tutorial tabs should be 40px tall
![IMG_4693](https://user-images.githubusercontent.com/1392130/56610004-1a496300-65d4-11e9-9346-e1432de8dc5e.png)

---

### Secondary modules
- [x] Stack 'Planet Finders Beta Statistics' and 'view more stats' buttons
       - Title left aligned, button right aligned
- [x] Add padding between 'keep track of progress' and the copy (currently lipsum)
- [x] Add padding between the content and bottom of the module
![IMG_4694](https://user-images.githubusercontent.com/1392130/56609932-fa19a400-65d3-11e9-83c1-6017d1f63ffd.png)

---

### Footer
- [x] Text should be two columns
![IMG_4695](https://user-images.githubusercontent.com/1392130/56609856-c179ca80-65d3-11e9-9556-115e035ed2ba.PNG)

**Comment by srallen** [comment]
@beckyrother did the footer not collapse correctly when dragging the window to be smaller? What if you refresh the page when at the smaller size? Or was this in the dev tools emulator? I'm asking because it renders ok in the storybook and emulators for me.

**Comment by beckyrother** [comment]
These are screenshots from my iPhone 6s

**Comment by srallen** [comment]
@beckyrother Thanks! I'll coordinate with you to test with an actual device because I'm not seeing all these issues with the emulator.

**Comment by srallen** [comment]
Footer fix in #786

**Comment by srallen** [comment]
A few notes from viewing on my iPhone SE:

- Grommet's Layer in modal form is still scrollable for the tutorial, field guide, and need some help. Is this intended?

<img src="https://user-images.githubusercontent.com/5016731/56926581-adccd900-6a97-11e9-974f-60c34e78ceed.PNG" width="200px" />
<img src="https://user-images.githubusercontent.com/5016731/56926588-b4f3e700-6a97-11e9-8f9a-4adf68ddd399.PNG" width="200px" />

- Headers on modals need fixing on need some help and field guide's item view:

<img src="https://user-images.githubusercontent.com/5016731/56926611-c6d58a00-6a97-11e9-8b2a-32dd23334d6c.PNG" width="200px" />
<img src="https://user-images.githubusercontent.com/5016731/56926618-cb01a780-6a97-11e9-81da-520a41201fc5.PNG" width="200px" />

- The dark mode button takes up a lot of space (keep in mind the SE is the smallest smart phone screen out in the market still) and also note the the project name is being cut off on the left side. @beckyrother do you still want it on the side here or to move somewhere else?
<img src="https://user-images.githubusercontent.com/5016731/56926650-db198700-6a97-11e9-8a95-30656af1977b.PNG" width="200px" />

Also, I tried upping the outer circle of the pagination icon for the tutorial by 1px, and that didn't fix the off-centeredness. I'm not sure what's going on here:
<img src="https://user-images.githubusercontent.com/5016731/56927035-b83ba280-6a98-11e9-8427-afb18ebcd2b6.PNG" width="300px" />

**Comment by srallen** [comment]
Extra gap between the subject meta buttons fixed in #779

**Comment by mcbouslog** [comment]
Reviewed on Android (Pixel 3, Chrome) and nothing that hasn't already been noted jumped out to me.

**Comment by srallen** [comment]
The modal still allowing scroll on mobile Safari is a CSS bug in mobile Safari. I have a tentative fix for the Grommet lib.

**Comment by srallen** [comment]
Closing and opening a separate issue for the final item
