### ISSUE TITLE
Get jenkins to work with the monorepo setup

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#75]
**Package** All

**Feature or Issue Description**
Standard travis setup doesn't work with a monorepo. Here's an example monorepo travis setup that might work: https://github.com/sagikazarmark/travis-monorepo-demo

**Comment by rogerhutchings** [comment]
We could also set up Jenkins to run the tests instead.

**Comment by rogerhutchings** [comment]
We've set up Travis for tests, and Jenkins now builds the docker images and deploys them.
