### ISSUE TITLE
Font size style regression

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#758]
It looks like without a specific prop of `size='medium'`, font sizes in text-based components are reverting to `18px`

**Comment by srallen** [comment]
Grommet is showing the default for Paragraph is `medium`: https://v2.grommet.io/paragraph

But doesn't show a default for Text (the docs just might not be right). Is this happening with Paragraph or Text? Or places where we're missing using either?

**Comment by rogerhutchings** [comment]
List items in the footer, for example, and content box headings etc are all rendering smaller (12px), weirdly. I can't remember which component they're using off-hand, but I wonder if a global default has been accidentally set

**Comment by srallen** [comment]
Was this fixed in #765?

**Comment by srallen** [comment]
As noted in #786, the 'small' sizes in the theme for text, paragraph, and headings should use a line-height of 14px. The footer section headings need to be updated to use 'small'.
