### ISSUE TITLE
Dark theme: Next, Done and Done & Talk dark theme styles

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#759]
**Package** lib-grommet-theme, lib-classifier

@rogerhutchings I'm assigning you since you've done the dark theme work most recently.

**Feature or Issue Description**
The dark theme styles mean switching to a outline border style for the task navigation and slight color changes:

<img width="396" alt="Screen Shot 2019-04-24 at 10 08 02 AM" src="https://user-images.githubusercontent.com/5016731/56670662-e2482b80-6678-11e9-941a-1018f9569d95.png">
<img width="397" alt="Screen Shot 2019-04-24 at 10 08 38 AM" src="https://user-images.githubusercontent.com/5016731/56670702-f2f8a180-6678-11e9-8c7a-bf689859e3c1.png">

How they appear in the new app:

<img width="387" alt="Screen Shot 2019-04-24 at 10 09 27 AM" src="https://user-images.githubusercontent.com/5016731/56670827-1e7b8c00-6679-11e9-9b03-aa304d5caf68.png">
<img width="389" alt="Screen Shot 2019-04-24 at 10 09 51 AM" src="https://user-images.githubusercontent.com/5016731/56670832-21767c80-6679-11e9-88a4-737cbcaa7cf2.png">

@beckyrother any changes here or should we replicate the current implementation?

**Comment by beckyrother** [comment]
Sorry which is which in those images?

**Comment by srallen** [comment]
@beckyrother first two is how it is in current PFE. The next two is how it is with the new app: https://fe-project.preview.zooniverse.org/projects/nora-dot-test/planet-finders-beta?env=staging (it's using grommet defaults I think)

**Comment by beckyrother** [comment]
Got it. Please continue to use the outline versions with the font size that's shown, they're more legible.
