### ISSUE TITLE
Add helper labels for image toolbar buttons

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#76]
**Package**

`lib-classifier`

**Feature or Issue Description**

Following on from https://github.com/zooniverse/front-end-monorepo/pull/74, the Invision designs have a hover state with a text label that needs to be added:

<img width="173" alt="screenshot 2018-07-11 14 57 13" src="https://user-images.githubusercontent.com/2725841/42576616-bb5d8942-851a-11e8-87ba-7917a1fa9b70.png">

I suggest adding a delay before showing the label, or it could get quite visually noisy.

**Comment by srallen** [comment]
Grommet v2 now has a tooltip in addition to our own tooltip in our component library.

**Comment by goplayoutside3** [comment]
Closing this one in favor of https://github.com/zooniverse/front-end-monorepo/issues/4483
