### ISSUE TITLE
Try enabling AMP support for pages

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#766]
https://nextjs.org/blog/next-8-1:

> AMP HTML is a stricter version of HTML that imposes a few restrictions to achieve more reliable performance and better scalability. Some HTML tags are replaced with AMP-specific HTML tags to provide a better experience than its corresponding HTML tag.

> AMP pages are automatically discovered by search engines which support it. These search engines generally implement an AMP Cache (e.g. Google and Bing). AMP Caches help the page to render faster from their search results.

**Comment by eatyourgreens** [comment]
The thing that might benefit most from AMP is Talk.

**Comment by rogerhutchings** [comment]
https://shkspr.mobi/blog/2019/05/a-report-from-the-amp-advisory-committee-meeting/
