### ISSUE TITLE
LCV: resizing lag

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#773]
**Package** lib-classifier

**Feature or Issue Description**
Originally from #695 

- [ ] When resizing the window, there's a slight lag when the data resizes to fit. Can there be an overlay with a loader to indicate that something is happening – I think this is used elsewhere in the site so if that component can be reused that would be ideal

**Comment by goplayoutside3** [comment]
LCV data doesn't resize anymore when the window is resized.
