### ISSUE TITLE
Feedback: List design and button label

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#774]
**Package** lib-classifier

**Feature or Issue Description**
Originally from #695 

- [ ] remove the bullet and add more details to the feedback (Note: We could remove the bullet, but the text is project supplied)
- [x] Maybe the 'close' button should say 'keep classifying' or 'show me another' to give more context into why this box has come up and what will happen when they close the module.

**Comment by eatyourgreens** [comment]
How much work would it be to remove the list completely and allow project owners to write a single feedback message that summarises all the rule outcomes for the current subject? In my mind, this requires string interpolation on the feedback message, to insert the number of successes and failures, but I'm probably overlooking some subtleties that would be required in a real project.

**Comment by srallen** [comment]
I'm not really sure how we go about redesign the bullet list of messaging because feedback messaging could be per subject and each subject could have an unknown about of messages (however many is in the metadata). Because of the free form nature of this, I don't think we could easily switch to an interpolated paragraph text. I'm going to close this for now and it can be reopened if we can think of a good redesign solution, but it may impact how feedback gets setup.

**Comment by eatyourgreens** [comment]
I was thinking the message string (from the workflow or from the subject) could be something like `You caught ${successes} transits and missed ${fails}. Some of these are really hard to spot.` where the number of successes and fails are interpolated by the feedback reducer. We'd need to invent an interpolation syntax that we can easily teach to project owners.

**Comment by srallen** [comment]
Ok, I think that would necessitate an update to how the configuration works in the lab first. We could add some custom syntax to support interpolation with the new Markdownz via remark. However, we should find out if custom X number of messaging is being used currently. If not, then transitioning to something like you've described will be easier.

**Comment by eatyourgreens** [comment]
In theory, generating a single feedback message from a reducer would be easy but @rogerhutchings is still really the expert on what can/can't be done with feedback at the moment so I'd defer to his opinion on this.

I'm not following why this would need Markdown. The reducer could generate a string, with the numbers interpolated, before it's passed to Markdownz for rendering.

At the moment, TESS just shows a very generic message for all feedback.
![A screenshot of feedback for a simulated transit in Planet Hunters Tess.](https://user-images.githubusercontent.com/59547/56680122-84d6cd80-66be-11e9-95e8-99015858cd61.png)
