### ISSUE TITLE
Setup new workflow on TESS project for new app

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#775]
This is just a placeholder issue for us to be aware that this needs to happen and done by the research team. No action needs to be taken by the devs. We've advised them that it'll be easier to switch over and do the redirect with a new project rather than new workflow.

**Comment by srallen** [comment]
Just noting here that the advice to use a separate project is because we've decided it'll be easiest and safest to ensure a smooth transition for the new setup and app deployment. Trying to setup a workflow in the existing project could have issues with determining how to correctly load the right workflow with the right app. The unfortunately consequence with this is Talk fragmentation, however, an organization could help alleviate this.

**Comment by srallen** [comment]
@trouille is looking into the issue of Talk fragmentation since this might be a big issue.

**Comment by srallen** [comment]
@trouille confirmed that the Talk comments are integral to the project, so we need to make an effort to do a change over to the new app on a new workflow within the existing project.

**Comment by srallen** [comment]
There will be a hard switch over for the new classifier code while the project is out of data.

- [ ] A new default workflow will be configured, distinct from the existing one used to derive old data. That new workflow will be configured for caesar / MAST pipeline. We really need to ensure we’ve got distinct data flows setup in place, and split on workflows is good here.

- [ ] Configure PFE client code to detect the classifier page load and force a full page reload to the SSR rebuild code once the config for https://github.com/zooniverse/Panoptes-Front-End/pull/5319/files is in place. Related issue: https://github.com/zooniverse/Panoptes-Front-End/issues/5320

- [ ] Configure nginx proxy redirect for the project's classify page URL so that the new next.js app is loaded.

Based on this setup, in theory there is no way that a user can access the new rebuild / LCV workflow in the old PFE code. We need to ensure that this is the case for launch.

**Comment by srallen** [comment]
The workflow will have a Panoptes retirement of 15 and Caesar will handle early retirement per comments here: https://github.com/zooniverse/caesar/issues/782#issuecomment-490953757

**Comment by rogerhutchings** [comment]
[ ] Deploy a production version of `packages/app-project` (#808)

**Comment by srallen** [comment]
Actually the retirement will be `never_retire` because of the training subjects and Caesar will handle all retirement conditions.

**Comment by srallen** [comment]
What the beta production workflow looks like so far just for documentation purposes. Note that the feedback is not its final configuration as we're waiting on the upload of the training set to configure this. The feedback config that is there is just for example purposes:
```
{
  "id": "11005",
  "display_name": "BETA workflow",
  "tasks": {
    "T1": {
      "help": "## Help...  /n----------------  /n  /n![Screenshot 2018-12-04 at 16.56.23.png](https://panoptes-uploads.zooniverse.org/production/project_attached_image/eb2a0532-9b02-4278-be07-12ddc0912c09.png)  /n  /nIf you see any transits, mark their locations by clicking on the figure to draw **boxes** around the **fainter points**. The boxes should be just wide enough to include all points of one transit as shown in the example above. Adjust the size and location of the box using your mouse.  /n  /nIf you don't see a transit, simply skip to the next lightcurve by pressing the '**Done**' button.  /n  /nHave a look at the ***Field Guide*** tab on the right for specific examples of what a transit lightcurve looks like!",
      "type": "dataVisAnnotation",
      "tools": [
        {
          "type": "graph2dRangeX",
          "label": "Transit?"
        }
      ],
      "feedback": {
        "rules": [
          {
            "id": "t11",
            "strategy": "graph2drange",
            "failureEnabled": true,
            "successEnabled": true,
            "defaultTolerance": "2",
            "hideSubjectViewer": false,
            "defaultFailureMessage": "Not quite, but don't worry, some of these are really hard to see!",
            "defaultSuccessMessage": "Awesome, you correctly marked the Transit!"
          }
        ],
        "enabled": true
      },
      "required": false,
      "instruction": "**Do you spot a transit?** If so, please mark it on the lightcurve to the left!  /n  /nIf you don't see any transits, continue by clicking Done or Done & Talk."
    }
  },
  "steps": [
    [
      "S1",
      {
        "taskKeys": [
          "T1"
        ]
      }
    ]
  ],
  "classifications_count": 0,
  "subjects_count": 0,
  "created_at": "2019-05-06T15:47:34.299Z",
  "updated_at": "2019-05-09T20:24:33.444Z",
  "finished_at": null,
  "first_task": "",
  "primary_language": "en",
  "version": "4.2",
  "content_language": "en",
  "prioritized": false,
  "grouped": false,
  "pairwise": false,
  "retirement": {
    "options": {
      "count": 15
    },
    "criteria": "never_retire"
  },
  "retired_set_member_subjects_count": 0,
  "href": "/workflows/11005",
  "active": true,
  "mobile_friendly": false,
  "aggregation": {},
  "configuration": {
    "subject_viewer": "lightcurve",
    "classifier_version": "2.0",
    "hide_classification_summaries": true
  },
  "public_gold_standard": false,
  "completeness": 0,
  "links": {
    "project": "9222",
    "subject_sets": [],
    "tutorial_subject": null,
    "published_version": null,
    "attached_images": {
      "href": "/workflows/11005/attached_images",
      "type": "attached_images",
      "ids": []
    },
    "classifications_export": {
      "href": "/workflows/11005/classifications_export",
      "type": "classifications_exports"
    }
  }
}
```

**Comment by srallen** [comment]
There will be an array of 13 feedback rules following an id convention starting from 11110 to 111112. Each will have the same setup:
``` js
{
  defaultFailureMessage: "A green column indicates that you've correctly marked a simulated planet 
    transit! A red column means you missed one, but don't be discouraged, some are very difficult, or 
    even impossible, to spot. This can happen when the planet is very small compared to its host star, 
    meaning that the transit is very shallow and easily lost in the varying brightness of the star. You're 
    doing great, keep going!",
  defaultSuccessMessage: "Awesome! The green column shows where you've correctly marked a 
    simulated planet transit! A red column means you missed one, but don't be discouraged, some are 
    very difficult, or even impossible, to spot. This can happen when the planet is very small compared 
    to its host star, meaning that the transit is very shallow and easily lost in the varying brightness of 
    the star. You're doing great, keep going!",
  defaultTolerance: "0.25",
  failureEnabled: true,
  hideSubjectViewer: false,
  id: "11110",
  strategy: "graph2drange",
  successEnabled: true
}
```

**Comment by srallen** [comment]
Setup to do list for production launch:

- Prior to launch
  - [ ] Decide on production launch date and notify and confirm with MAST
  - [ ] Write a blog post announcing the switch over and date of switch over
    - [ ] Add project announcement banner with link to blog post
  - [ ] Create new workflow on current project and configure modeled on beta project's (can be done before project goes private for setup)
    - [ ] Front end config: Set configuration object
    - [ ] Front end config: Set task and feedback rules
    - [ ] Front end config: Set retirement to never retire
    - [ ] Front end config: Set hide classification summaries
    - [ ] Front end config: Link tutorial, field guide (previous versions or new ones?)
      - [ ] Do either need content updates?
    - [ ] Caesar config: Extractors
    - [ ] Caesar config: Reducers
    - [ ] Caesar config: Effect to send to MAST
  - [ ] Subject sets
    - [ ] Upload new data
    - [ ] Designator config: set weights for subject sets (depends on new sets being uploaded and available)
- Day of launch
  - [ ] Set project to private
  - [ ] Set new workflow to default and active
  - [ ] Inactivate old workflow
  - [ ] Configure cloudfront CDN distribution is setup to use SSR rebuild code for the project's classify page URL so that the new next.js app is loaded.
  - [ ] Update route in PFE code to force refresh for project classify page
  - [ ] Internal team test
  - [ ] If all good, set project back to public and launch approved
- Two days after
  - [ ] Link up new data and announce it

**Comment by srallen** [comment]
feedback messages should now be: 

positive message = “Awesome! The green column shows where you’ve correctly marked a simulated planet transit! A red column means you missed one or drew a column slightly too large (try to only capture the transiting points in the columns that you draw), but don’t be discouraged, some are very difficult, or even impossible, to spot. This can happen when the planet is very small compared to its host star, meaning that the transit is very shallow and easily lost in the varying brightness of the star. You’re doing great, keep going!”

negative message = “A green column indicates that you’ve correctly marked a simulated planet transit! A red column means thst you missed one or that you drew a column slightly too large (try to only capture the transiting points in the columns that you draw), but don’t be discouraged, some are very difficult, or even impossible, to spot. This can happen when the planet is very small compared to its host star, meaning that the transit is very shallow and easily lost in the varying brightness of the star. You’re doing great, keep going!”

**Comment by srallen** [comment]
Designator uses a workflow configuration object, i.e. `planet_hunters_training_sets: ["76106"]` that contains an array of subject set ids to apply the custom designator configuration to.

**Comment by srallen** [comment]
I'm going to close this as all dev related work is now done.
