### ISSUE TITLE
Refactor Task Nav Buttons

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#782]
There is some refactoring required in the task area nav buttons (Back, Done, Done & Talk, Next):

- There is a bunch of checks for gold standard mode, demo mode etc, but we don't actually have the code for this, and currently no plans to build it, so it should really be removed.
- The nav buttons container is doing a bunch of checks and passing down props to the buttons, which it really doesn't need to do; responsibility for showing buttons and their behaviour should be devolved to the button components themselves (i.e. each button has a container connected to the store), which will make things easier to test and reason about.
- We may be able to share some common theme properties at the task nav level, rather than duplicating them within the buttons.

Follows on from #759, #781

**Comment by srallen** [comment]
> There is a bunch of checks for gold standard mode, demo mode etc, but we don't actually have the code for this, and currently no plans to build it, so it should really be removed.

Both gold standard mode and demo mode are used currently. The code for them didn't get moved over because I wasn't sure if it'd be a component state or an MST state somewhere. So there _should_ be plans for it, imo.

**Comment by rogerhutchings** [comment]
I mean they're not being used for TESS, which is our immediate concern, and there aren't currently any plans for moving projects supporting them to the new classifier. So yes, we should have a plan for it, but we don't need them right now.

**Comment by eatyourgreens** [comment]
Demo mode is used when giving talks, so could be used to demo the new classifier. It's not project-specific.

**Comment by rogerhutchings** [comment]
cc #1248
