### ISSUE TITLE
Auto-focus for task area

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#799]
**Package** lib-classifier

**Feature or Issue Description**
> Fieldsets aren't focusable elements in HTML, so I suspect this a line that was copied over from PFE even though it does nothing here. It can probably be removed.

The task-area should auto focus, but it shouldn't be done on the fieldsets.

**Comment by eatyourgreens** [comment]
The quick fix for this would be to give the fieldset a tabindex of 0.

That said, I'm not 100% sure if the task area should be focused for each new subject. It's very useful on transcription projects, but very confusing if you're using a screenreader to classify. In that case, you probably want to listen to the new subject before moving on to answering questions about it.

**Comment by goplayoutside3** [comment]
@eatyourgreens do you recommend implementing auto-focus? I noticed the task area is already auto-focuses for projects like Daily Minor Planet, but it does not auto-focus for TESS.
