### ISSUE TITLE
RFC: generic tests for subject viewer components

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#811]
**Package**
lib-classifier

**Feature or Issue Description**
Based on the subject viewer tests in #809 and #804, should we have a set of generic tests that all new subject viewers should pass, if only to guarantee that they will plug in to the classifier code without breaking anything? I'm thinking something similar to [PFE's generic task tests](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/generic.spec.js), which are expected to pass for all Task components.

**Comment by eatyourgreens** [comment]
Maybe also a generic viewer class that all viewers are expected to extend, even if all it does is define a common interface for communicating with the classifier.

**Comment by rogerhutchings** [comment]
:+1:

It might need to live in its own package, if we plan to move some of the subject viewers out to separate packages.

**Comment by srallen** [comment]
I think this is a good idea as this component would basically be defining the API we're expecting all subject viewers to work with. I agree it should be in a separate package eventually as we want independent subject viewers to work in contexts like the new transcription viewer/editor app that's going to be built.

**Comment by srallen** [comment]
I think now that the subject viewer store handles the loading state, we're now moving toward this generic API and tests for it. The specific container components for the viewers can contain any specific loading async requests as well as the connection to the store.
