### ISSUE TITLE
Graph2dRange feedback breaks with numeric values for rule x, width and tolerance

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#831]
**Package**
lib-classifier

**Feature or Issue Description**
Graph2dRange feedback breaks with numeric values for rule x, width and tolerance
See https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/store/feedback/strategies/datavis/graph2drange/reducer.js
**To Dos**

- [ ] create tests to catch bug
- [ ] add error logging
- [ ] check type, return or convert as needed

**Comment by eatyourgreens** [comment]
That code converts any string values in the rules to numbers here.
https://github.com/zooniverse/front-end-monorepo/blob/6a3c03cc41e491c33ef7cb4419db3f892b5390d2/packages/lib-classifier/src/store/feedback/strategies/datavis/graph2drange/reducer.js#L4-L6

It should work fine if `rule.x`, `rule.width` and `rule.tolerance` are numbers.

**Comment by eatyourgreens** [comment]
Which is not to say that shouldn't be backed up by tests anyway.
