### ISSUE TITLE
FeedbackViewer is untested in FeedbackModal

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#832]
These lines are untested in the feedback modal. It would be useful to have some mock rules in the tests, in order to debug problems with rendering the viewer.
https://github.com/zooniverse/front-end-monorepo/blob/6a3c03cc41e491c33ef7cb4419db3f892b5390d2/packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.js#L36-L40

**Comment by goplayoutside3** [comment]
Closing this because it can be wrapped into general conversion of enzyme spec files --> RTL specs
