### ISSUE TITLE
Add Acknowledgements page to `app-content-pages`

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#839]
Content / layout should be based on https://www.zooniverse.org/acknowledgements

**Comment by rogerhutchings** [comment]
Kamino cloned this issue to [zooniverse/front-end-monorepo](https://github.com/zooniverse/front-end-monorepo/issues/840)

**Comment by goplayoutside3** [comment]
Figma design: https://www.figma.com/file/zN9InDg8CTk2vnWp406moK/About-Pages

**Comment by seanmiller26** [comment]
This standalone page has been merged into the Resources page. See the Figma design for details

**Comment by goplayoutside3** [comment]
Thanks! I'll close this Issue in favor of the Resources page.
