### ISSUE TITLE
Add Resources page to `app-content-pages`

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#840]
Content / layout should be based on https://www.zooniverse.org/about/resources

**Comment by rogerhutchings** [comment]
Kamino cloned this issue to [zooniverse/front-end-monorepo](https://github.com/zooniverse/front-end-monorepo/issues/841)

**Comment by goplayoutside3** [comment]
Figma design: https://www.figma.com/file/zN9InDg8CTk2vnWp406moK/About-Pages
