### ISSUE TITLE
Add Contact url and section to `app-content-pages`

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#841]
Content / layout should be based on https://www.zooniverse.org/contact

**Comment by goplayoutside3** [comment]
Figma design: https://www.figma.com/file/zN9InDg8CTk2vnWp406moK/About-Pages

**Comment by seanmiller26** [comment]
I will note that there no longer is a dedicated Contact page as it has been merged into the main About page, HOWEVER, there should still be a direct URL, if possible, to accommodate the various links throughout the rest of the site.

See the Figma design above

**Comment by goplayoutside3** [comment]
Thanks! I'll update the title of this Issue
