### ISSUE TITLE
What should the lorem ipsum text in the stats box be?

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#845]
<img width="771" alt="Screenshot 2019-05-17 16 40 47" src="https://user-images.githubusercontent.com/2725841/57939583-8c0a8900-78c2-11e9-8aa8-93fb40d691ca.png">

(Also, the line height here looks really cramped)

**Comment by beckyrother** [comment]
Every classification counts! Join [project name]’s community of volunteers to complete this project and help researchers learn more about our world. Click “view more stats” to see even more details.

@mrniaboc does this sound ok?

**Comment by beckyrother** [comment]
Agreed, that should be font-size: 14px; line-height: 22px;

**Comment by mrniaboc** [comment]
I think that's close. Suggest slight changes:

Every click counts! Join [project name]’s community to complete this
project and help researchers produce important results. Click “view more
stats” to see even more details.

**Comment by beckyrother** [comment]
I like that. @rogerhutchings this is good to go ☝️
