### ISSUE TITLE
Classifier: render more than one task at a time

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#85]
**Package**
`lib-classifier`

**Feature or Issue Description**
PFE currently has the Combo Task to work around only being able to render one task component in the classifier's task area.

The new classifier should support rendering more than one task at a time, where each task is responsible for updating its own annotation.

**To Dos**

- [ ] Pass an array of tasks to the task area.
- [ ] Allow more than one annotation to be updated at a time.

**Comment by rogerhutchings** [comment]
Note: https://github.com/zooniverse/front-end-monorepo/pull/84 currently only renders one task at a time

**Comment by srallen** [comment]
I think this is done.

**Comment by eatyourgreens** [comment]
It was implemented in the new classifier, so never got implemented in PFE.
