### ISSUE TITLE
Dark theme missing for signed out stats placeholder

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#853]
**Package** app-project

**Feature or Issue Description**
The placeholder for the stats module does not have dark theme styling:

<img width="776" alt="Screen Shot 2019-05-20 at 2 33 52 PM" src="https://user-images.githubusercontent.com/5016731/58047012-94560480-7b0c-11e9-8f6a-14cbf497143c.png">

**Comment by seanmiller26** [comment]
@delilah let me know if any styling questions come up. 

Can we change the wording to be: 

Sign in to track your own stats!
