### ISSUE TITLE
Consolidate linter rules across all packages

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#859]
**Package**
all

**Feature or Issue Description**
Following on from #837, let's consolidate our linter configs across packages. At the moment, each package defines its own linter and rules.

**Comment by rogerhutchings** [comment]
we could also consolidate the linter packages - standard has [a node api](https://github.com/standard/standard#is-there-a-nodejs-api), so standardx almost certainly does too

**Comment by srallen** [comment]
This is done.
