### ISSUE TITLE
Update stats widget on classification

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#860]
From #821:

> Set up an observer on the classification store to watch for submitted classifications and increment the counters. This will be stored in the `sessionCount` volatile, and will need to be added to the daily count, the total count, and the weekly stats used for the chart.

cc #38

**Comment by eatyourgreens** [comment]
I've already hooked up the Done button to update classification counts on classification complete. It had to be done with a callback, because the classification store is in the classifier but the stats counts are in the project app. The classifier component should have an `onCompleteClassification` prop that increments the counters.

**Comment by eatyourgreens** [comment]
My bad, this function is supposed to call `yourStats.increment()` as well as `recents.add()`.
https://github.com/zooniverse/front-end-monorepo/blob/59c3ec128b2ba4752c58853e4dccbb2f0f17eff8/packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js#L43-L49

**Comment by srallen** [comment]
Instead of a callback, we could move stores that need to talk to each other into their own library as we discussed in #406. I'd like to continue to take advantage of the observable paradigm rather than move toward callbacks.

**Comment by eatyourgreens** [comment]
@srallen can that be done without creating a strong coupling between the classifier and the project app? The app shouldn't really need to know what's going on inside any third-party components it imports, and I think the classifier counts as a third-party import here.

My thinking with callback props was that we have a public interface between the classifier and anything that uses it.

**Comment by eatyourgreens** [comment]
I'm taking another look at this and my total count goes up when I classify, but not my daily count. I think I missed something when I set up the incrementing counters.

**Comment by eatyourgreens** [comment]
I guess we haven't implemented daily counts yet. https://github.com/zooniverse/front-end-monorepo/blob/27e41f3b5a7bd5458672a671efff30f750b5562a/packages/app-project/stores/YourStats.js#L115-L117

**Comment by srallen** [comment]
Could this discussion be moved to an open issue or does this need to be reopened?

**Comment by eatyourgreens** [comment]
>Isn't the daily count coming from the stats API?
Yes, but we add one to the stored value in the project app each time you press Done in the classifier.
