### ISSUE TITLE
Field guide images overflow container

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#873]
Images in the field guide are being chopped off on the right:

<img width="1350" alt="Screenshot 2019-05-23 16 20 22" src="https://user-images.githubusercontent.com/2725841/58264973-b9e64680-7d76-11e9-9e6e-a6f374950288.png">

This may be due to the fact that the `Media` component defaults to `object-fit: cover`, rather than `object-fit: contain`

**Comment by eatyourgreens** [comment]
There's invalid `alt` and `src` attributes on a div in that screenshot too. The browser will ignore those.

**Comment by srallen** [comment]
I don't recall exactly the reasoning why cover is the default. Maybe because it's default for the underlying Grommet Image component. Not sure. We could switch it easily... but we should double check the impact anywhere else Media might be used.

**Comment by srallen** [comment]
I think #883 also closes this.
