### ISSUE TITLE
Feedback storing task ID and empty array to classification metadata

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/front-end-monorepo#874]
**Package**
lib-classifier

**Feature or Issue Description**
Feedback is storing task ID and an empty array to classification metadata even if feedback is not relevant to the classification.

![Screen Shot 2019-05-23 at 11 40 22 AM](https://user-images.githubusercontent.com/12118751/58270717-14b87780-7d50-11e9-998c-d637af3d6627.png)

In the FeedbackStore [`createClassificationObserver`](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/store/FeedbackStore.js#L42) is updating feedback regardless of if feedback is active or not. Which then [sets a task rule to an empty array](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/store/FeedbackStore.js#L115).

Possible solution - adding a check for `self.isActive` before (or within) the `onAction` in the `createClassificationObserver`.

Even with solution ^, `metadata.feedback = {}` is always in metadata due to the [Classification model](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/store/Classification.js#L7). Is that ok or something to also fix?

Also, I want to triple-check how this may affect the TESS-MAST pipeline (@zwolf).

**Comment by mcbouslog** [comment]
Mentioning @eatyourgreens, @srallen

**Comment by srallen** [comment]
I don't think this has any affect on the Caesar pipeline. The pipeline is using subject metadata to determine decisions on reducer types to use, not classification metadata.

**Comment by srallen** [comment]
> adding a check for self.isActive before (or within) the onAction in the createClassificationObserver.

This seems reasonable to me since `feedback: { T1: [] }` does sort of make it look like feedback was meant to be shown and something wrong happened. I'm fine with `feedback: {}` in the metadata as a default value.

**Comment by eatyourgreens** [comment]
Why is this an issue? Is it breaking something? There's a solution listed but I can't see the problem that's being solved.

**Comment by srallen** [comment]
I think there was a concern yesterday that it might cause one, but I don't believe it is breaking anything. However, I would be for making the suggested update so that an empty array isn't added if feedback wasn't actually shown.

**Comment by eatyourgreens** [comment]
Looking back at the code, feedback should only be added to the classification if it's active and has rules (I think.) It might need an additional check that `rules` isn't empty.
https://github.com/zooniverse/front-end-monorepo/blob/7e84fbf6fb87bbd54c4ad10572dcc6906a79b6d7/packages/lib-classifier/src/store/ClassificationStore.js#L147-L150

**Comment by zwolf** [comment]
The affect this has on Caesar is that it allows the PluckFieldExtractor to be successful, plucking `[]` from `{ 'feedback': 'T1': [] }`. This causes an extra extract to be created for every non-training subject that doesn't have feedback. One each for every classification on every workflow with feedback set up.

This is already considerable thanks to TESS, and will grow with more projects adding feedback. It's not critical, but our extracts table has already crested 100 million rows, and threatens to become even more unwieldy, so we should be conscious about optimization.

**Comment by amyrebecca** [comment]
To add to what @zwolf said above, the fix that @srallen suggested on 5/23 of `feedback: {}` instead of `feedback: { T1: [] }` would solve our problems in Caesar.

**Comment by eatyourgreens** [comment]
Closed by #1095 but please re-open if it continues to happen.
