### ISSUE TITLE
Handle translated strings in Contentful data

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#877]
At the moment, we only use the `en-US` translation of content strings requested from Contentful. When we add a language picker, we'll need to add a way to get the correct translation from the store, as other translations are included in the response.

cc #876

**Comment by goplayoutside3** [comment]
Closing this with the decision to not translate data from Contentful. All other copy in the Zooniverse /about pages will use Lokalise like the rest of the website.
