### ISSUE TITLE
Visiting a project creates a new, empty Favourites collection

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#879]
**Package**
app-project

**Feature or Issue Description**
Visiting a project for the first time creates a new, empty favourites collection for that project. PFE, on the other hand, doesn't create the favourites collection until you favourite something for the first time.

I think this is a minor change of behaviour, but it might be annoying to volunteers who make heavy use of collections.

**Comment by eatyourgreens** [comment]
@ErikOstlund is this a duplicate of an issue that you’ve opened?

**Comment by ErikOstlund** [comment]
Yes. Here is the issue I created:
https://github.com/zooniverse/front-end-monorepo/issues/2473

**Comment by eatyourgreens** [comment]
Closing this as a duplicate.
