### ISSUE TITLE
Figure out why tests are slow to exit for panoptes.js

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#88]
**Package** lib-panoptes-js

**Feature or Issue Description**
The tests are slow to exit. Issue might be caused by `superagent-mock`

**Comment by srallen** [comment]
@rogerhutchings If it work similarly enough for the tests, then I'm fine with the swap out.

**Comment by srallen** [comment]
I had thought that a promise wasn't being returned correctly somewhere, but the issue indicates it's a bug in the library itself that hasn't been addressed.

**Comment by rogerhutchings** [comment]
I was able to replicate it even with the tests whittled down to a single spec with `.only`
