### ISSUE TITLE
Standardize buttons

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#887]
Our designs specify to use a lightened border as the hover state for buttons. However, we're applying this inconsistently, and there are buttons with resizing borders still around. This needs to be set in the theme, and the existing buttons checked for compliance

**Comment by srallen** [comment]
We could better standardize the buttons by leveraging the newer theme API for buttons from Grommet: https://v2.grommet.io/button
https://v2.grommet.io/button#theme

See the description of default, primary, and secondary.
