### ISSUE TITLE
Footer tweaks to bring it in line with new design

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#89]
**Package**

`zoo-react-components`

The footer needs some tweaks in order to match the design in https://projects.invisionapp.com/d/main#/console/12923997/270495242/preview. Sorry if there's a good reason for any of these!

- [ ] Font still renders as Work Sans, rather than Karla
- [ ] Spacing between top border and content needs increasing
- [ ] Spacing between sides and content needs increasing
- [ ] There are still BEM class names left in
- [ ] It should stick to the bottom
- [ ] Links in the bottom bar should be uppercase, letter-spaced and teal
- [ ] Link sections in the upper section should wrap a bit more cleverly
- [ ] Social media buttons need to respond to screen size
- [ ] Think about how to style anchors that are set in the props
- [ ] Update `react-components` documentation

This is probably a good opportunity to do some work on the grommet theme - spacing, for example, is done in tens of pixels, so we could set the base font size to 10px, set the `spacing` variables in the grommet theme to multiples of rems, and use those variables in the grommet props.

ref #73

**Comment by srallen** [comment]
Yep, We purposely punted some of the footer work, because really it was grommet theme work as you say. @mcbouslog Could you add the rest of the to dos we were discussing in the PR here?

**Comment by mcbouslog** [comment]
I think all the open items mentioned in PR #73 were included in Roger's original comment or I've subsequently added.

**Comment by srallen** [comment]
There are many ways to sticky a footer in CSS (css-tricks as always has a nice guide: https://css-tricks.com/couple-takes-sticky-footer/) including ways using flex or grid, so I'm inclined to make this the responsibility of the consuming app.

**Comment by rogerhutchings** [comment]
fixed by #435
