### ISSUE TITLE
Design: use correct top bar

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/front-end-monorepo#899]
The black bar at the top of [this page](https://fe-project.zooniverse.org/projects/trouille/planet-hunters-tess-beta/classify?register=true&login=true) uses the incorrect fonts, spacing, and sizing. Please use the same one that's on the current site.

incorrect:
![image](https://user-images.githubusercontent.com/1392130/58816498-46063280-85ef-11e9-90df-390cf1ae7262.png)

correct:
![image](https://user-images.githubusercontent.com/1392130/58816526-51595e00-85ef-11e9-9d63-5cc440cba04c.png)

**Comment by rogerhutchings** [comment]
There's also some issues with styled components (missing `className` props) in the header

**Comment by rogerhutchings** [comment]
Removing from the Project app milestone as it applies to all apps

**Comment by goplayoutside3** [comment]
@seanmiller26 I randomly came across this documented issue. Just wondering - do you have a preference between the UI styling for PFE top nav bar versus the FEM one? If we want to keep the currently styled FEM top nav bar, I'll close, otherwise I'll address this issue with a PR.

**Comment by goplayoutside3** [comment]
@seanmiller26 I think Becky means she wanted the FEM black nav bar (with sign-in register links, etc) to match the same height and padding as PFE's black nav bar. FEM's nav bar has looked like her screenshot for years though, and therefore different from PFE for years.

I prefer the current FEM padding in the nav bar compared to PFE's, but wanted to double check with you!

**Comment by seanmiller26** [comment]
I see, that wasn't entirely clear. I also like the FEM nav bar and don't mind the difference as we continue to move all pages to the new frontend.
