### ISSUE TITLE
Task model chokes when `required` is a string

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#902]
While investigating #900, @eatyourgreens found that some tasks have `{ required: 'true' }` or `{ required: '' }`, rather than a boolean, which causes the model to choke as it's expecting a boolean.

MST does have preprocessing, so we could coerce that value to a boolean, but not at the version we're on, so we'd need to:

- [ ] bump the MST version (currently 3.14.0)
- [ ] fix existing code / tests - loads of tests broke after a quick test
- [ ] add `preProcessSnaphot` to the Tasks models (where they use `required`)

**Comment by rogerhutchings** [comment]
An alternative idea would be to do the type coercion in the panoptes client, but that wouldn't work for an immediate fix since the classifier only uses the main `get` method, not the resource-specific helpers, and I don't think this should be globally applied

**Comment by rogerhutchings** [comment]
cc #924

**Comment by eatyourgreens** [comment]
The underlying bug in the project builder, which caused this, was fixed a while ago. `required` should be a Boolean now, except for very old workflows.

**Comment by goplayoutside3** [comment]
The Task model now looks like this: `required: types.maybe(types.union(types.string, types.boolean))`
