### ISSUE TITLE
Color theme setting not respected

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#903]
**Package** app-project

**Feature or Issue Description**
From Talk (https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk/2110/855185?comment=1682277):

> I’ve noticed a little problem with the new interface: The Dark Theme switches back to the Light Theme everytime I reload the page

**Comment by srallen** [comment]
We have more reports of the theme setting not working:

https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk/2108/1020600?comment=1698046

**Comment by srallen** [comment]
Still isn't fixed. In production, now we definitely have only one cookie being set, but it still switches back to light mode upon reload.

**Comment by eatyourgreens** [comment]
![Screenshot showing the page using the light theme even when the mode cookie is set to 'dark'](https://user-images.githubusercontent.com/59547/60021774-7db24880-968a-11e9-8099-d501256471f2.png)
![Screenshot showing that mode is sent correctly with the initial page request.](https://user-images.githubusercontent.com/59547/60021832-99b5ea00-968a-11e9-9c11-86eac0994e7c.png)

`mode=dark` is sent correctly with the initial page request, but the returned page has the light theme, so I'm getting the impression that the cookie is ignored by NextJS when it renders the HTML.

**Comment by eatyourgreens** [comment]
Fixed by actually passing the mode cookie from client to server in our Cloudfront setup.
