### ISSUE TITLE
Subject advance can throw TypeError

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#904]
**Package** lib-classifier

**Feature or Issue Description**
If the subject queue happens to only have a single subject in it, this line throws a TypeError:

https://github.com/zooniverse/front-end-monorepo/blob/dffe6a7bdccbe3ee333d400c0033ce9f496e1052/packages/lib-classifier/src/store/SubjectStore.js#L53

Because `value` is undefined. Discovered while testing the Done & Talk fix on staging projects with very few subjects.

**Comment by eatyourgreens** [comment]
My test project (ID 908) only has 1 or 2 subjects so can be used to reproduce this error.

**Comment by eatyourgreens** [comment]
We could add a test where `advance()` is called while the mock queue only has one subject.

**Comment by srallen** [comment]
My test project 1233 also only has 2 subjects and this is where I was seeing this happen.

**Comment by eatyourgreens** [comment]
1233 seems to be working when I try it with #909. My test project is broken by #902 so just doesn't render at all.
