### ISSUE TITLE
Add fallback for `Grid` in classifier

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#92]
**Package**

`lib-classifier`

**Feature or Issue Description**

Depending on the outcome of #87, we may need to add a fallback for the use of CSS Grids (e.g. [in layouts](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js#L16))

Raised in #81, [comment](https://github.com/zooniverse/front-end-monorepo/pull/81/files#r203421199)

- [Handy article on the topic](https://www.smashingmagazine.com/2017/11/css-grid-supporting-browsers-without-grid/)

**Comment by srallen** [comment]
Closing since the result of #87 is that we'll drop IE 11 support for the rewrite.
