### ISSUE TITLE
Integrate local storage with color theme setting

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#951]
**Package** app-project

**Feature or Issue Description**
PFE currently uses local storage to store the user's color theme pick. We should check for this too and have it take precedence over the cookie and set the cookie to be the same so we have consistent behavior across projects between the old and new apps.

**Comment by rogerhutchings** [comment]
...or store the PFE color theme in a cookie

**Comment by eatyourgreens** [comment]
Cookies shouldn't be relied on for client-side storage. I'd say use local storage to persist data in the client, and use a cookie when you want to sync that state with the server.
